### ISSUE TITLE
Verwendung von eigenen JavaScript Bibliotheken im swissbib Modul

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#100]
Mir ist aufgefallen,dass wir eine recht grosse Anzahl an eigenen jQuery / JavaScript Bibliotheken / Dateien verwenden

Einen Teil habe ich bereits auskommentiert, weil ich denke, dass diese einfach aus den alten Modulen kopiert wurden und nun nicht mehr benötigt werden.

Ziel:
- wirklich nur die Bibliotheken benutzen die wir wirklich verwenden  
- Verständnis darüber, warum diese Bibliotheken verwendet werden

A. noch aktivierte - Klärung für was sie benutzt werden und warum
-
lib/handlebars.js
-> wird unter anderem in swissbib/AdvancedSearch.js verwendet
Frage: was machen wir hier anders als VF2?

jquery/plugin/jquery-migrate-1.2.1.js
-> bei uns noch benötigt?

jquery/plugin/jquery.spritely.js
-> wird in swissbibHoldings.js (zum Nachladen u.a. der Holdings) 
Frage: hat VuFind hier keine eigene Lösung? 

jquery/plugin/jquery.cookie.js
-> gibt folgenden Fehler wenn nicht vorhanden
Error: TypeError: jQuery.cookie is not a function
Source File: https://develop.swissbib.ch/Record/166053546?expandlib=Z01#holding-institution-NEBIS-Z01
Line: 373

jquery/plugin/loadmask/jquery.loadmask.js
meist die Methode object.mask
wird von verschiedene swissbib jQuery Dateien verwedet
(z.B. AdvancedSearch.js)

B. bereits deaktivierte
-

Frage: werden sie noch noch benötigt?

- jquery/plugin/jquery.validate.min.js
- jquery/plugin/jquery.form.min.js
- jquery/plugin/jquery.validate.min.js  ??
- jquery/plugin/jquery.hoverintent.js ??
- jquery/plugin/loadmask/jquery.loadmask.js ?? 
- jquery/plugin/jquery.form.min.js ??
- swissbib-jq-plugins/hint.js ??
- swissbib-jq-plugins/menunav.js ??
- swissbib-jq-plugins/info.js ??
- swissbib-jq-plugins/info.rollover.js ??
- swissbib-jq-plugins/toggler.js ??
- swissbib-jq-plugins/checker.js ??
- swissbib-jq-plugins/dropdown.js ??
- swissbib-jq-plugins/tabbed.js ??
- swissbib-jq-plugins/enhancedsearch.js ??
//scheint durch eine andere library ersetzt worden zu sein (welche)
- swissbib-jq-plugins/extended.ui.autocomplete.js

C. swissbib.js
-
Dies war in der alten Lösung die init-Datei für die meisten Java-Script Aktionen. So wie ich das sehe,
wird der Grosstel des Codes heute nicht mehr verwendet. Allerdings wird der Namespace swissbib, der in dieser Datei definiert ist, von anderen noch aktiven Libraries oder Codedateien noch verwendet.(z.B. AdvancedSearch.js). Diese starke Abhängigkeit muss untersucht werden.
- braucht man den Code in swissbib.js nicht mehr, kann der namespace auch anderer Stelle definiert werden
- falls doch teilweise, sollte der Coide zumindest entschlackt werden.

**Comment by maechler** [comment]
lib/handlebars.js
--> Wir haben die erweiterte Suche mehr oder weniger VuFind nachgebaut. Ich sehe bis jetzt keinen Grund, warum wir nicht mit der VuFind erweiterten Suche arbeiten könnten.

jquery/plugin/jquery-migrate-1.2.1.js
--> Wird gebraucht für die Migration von jQuery Versionen unter 1.9.*. Habe ich gelöscht, da auf keiner Seite eine deprecated Warnung erschien.

jquery/plugin/jquery.spritely.js
--> Habe ich gelöscht und den Laden-Spinner bei den Holdings mit einem Font Awesome Icon ersetzt. So macht das VuFind seit Bootstrap.

jquery/plugin/jquery.cookie.js
--> noch in Gebrauch.

jquery/plugin/loadmask/jquery.loadmask.js
--> noch in Gebrauch.

Ich habe alle unnötigen jQuery Plugins entfernt. Zusätzlich habe ich die nicht benötigten swissbib Dateien entfernt und die Datei swissbib.js stark refactored. 

Nächste Schritte:
1) Die Javascript-Datei jquery.ui.js könnte meiner Ansicht nach entfernt werden, wenn wir den Tab-Mechanismus von Jusbib in der erweiterten Suche umbauen. Das sollte eine kleine Sache sein, ich konnte es aber nicht machen, da mir die Jusbib config.ini fehlt und ich keine Rechtsklassifikationen konfiguriert habe.
2) Ich denke wir sollten ein Issue machen, bei dem es darum geht die erweiterte Suche zu untersuchen und näher zurück an VuFind zu bringen.

**Comment by maechler** [comment]
Nächste Schritte:
1) Die Javascript-Datei jquery.ui.js könnte meiner Ansicht nach entfernt werden, wenn wir den Tab-Mechanismus von Jusbib in der erweiterten Suche umbauen. Das sollte eine kleine Sache sein, ich konnte es aber nicht machen, da mir die Jusbib config.ini fehlt und ich keine Rechtsklassifikationen konfiguriert habe.

--> erledigt

2) Ich denke wir sollten ein Issue machen, bei dem es darum geht die erweiterte Suche zu untersuchen und näher zurück an VuFind zu bringen.

--> erledigt https://github.com/swissbib/vufind/issues/296

3) [Optional] Weiteres Refactoring der swissbib eigenen Javascript Dateien. Wir könnten sicherlich auch noch auf jquery.cookie und jquery.loadmask verzichten mit entsprechenden Anpassungen.

--> Noch offen, wird bei Bedarf durchgeführt.
