### ISSUE TITLE
MyResearch/Favorites

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#103]
Problem
---
Die Seite "Favoriten / Zu den Favoriten hinzufügen" (MyResearch/Favorites) hat zwei Probleme:
* Der Suchschlitz ist viel zu klein und liegt ungleichmässig in der Box
* Der Text "Favoriten" wird mehrfach aufgerufen.

Beispiel
---
https://test.swissbib.ch/MyResearch/Favorites

Task
---
* Suchschlitz gleichmässig in Box setzen, verlängern und für alle Viewports brauchbar machen
* Template analysieren, doppelten Aufruf entfernen (oder zusätzliche Funktionalität der Favoritenliste einbinden

**Comment by saschahepp** [comment]
@oschihin habe einen Branch erstellt: https://github.com/swissbib/vufind/compare/rdgoingpublic...swissbib:feature/%23103_3498.67_MyResearch_favorites?expand=1
