### ISSUE TITLE
Icon-Grösse in Vollanzeige variabel

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#107]
Problem
-----------
Die Grösse von Stellvertreter-Icons in der Trefferliste variiert, auch bei demselben Icon. Dies führt z.B. beim Durchklicken von Trefferlisten zu einem unruhigen Verlauf. Beispiele:
/Record/256352623
/Record/170214303
Damit zusammenhängend das Problem: Vorschaubilder via externalService (bzw. amazon & Co.) werden z.T. sehr klein dargestellt.
Sämtliche Beispiele z.B. beim Durchklicken der Vollanzeigen einer Trefferliste mit 'Meier'

Lösung
---
1. Mechanismen zur Anzeige von Vorschaubildern und Icons verstehen und verbessern
2. Ein ruhiges und optimiertes Erscheinungsbild in der Vollanzeige und der  Trefferliste erreichen

**Comment by witzigs** [comment]
@nicokarrer 
Hallo Nicolas
Ich habe an einer Stelle noch einen unerwünschten grauen Balken. Ansonsten sieht das gut aus!

Ich bin eingeloggt und auf der Favoriten-Seite (MyResearch/Favorites). Wenn ich dann das "Konto IDS Basel Bern" aufklappe, habe ich unten einen grauen Balken. Das Problem tritt nur auf, wenn mehrere Favoriten gespeichert sind.

**Comment by nicokarrer** [comment]
@witzigs 

Hallo Silvia

Theoretisch sollte mein letzter Commit das Problem lösen. Da ich keine Konto-Informationen habe wenn ich eingeloggt bin, habe ich es versucht über die Facetten nachzuvollziehen.

Kannst Du das bitte prüfen? Danke
