### ISSUE TITLE
CSS für Vorschaubilder problematisch (sprengt Listendarstellung)

### ISSUE THREAD

**Issue by ToVie** [swissbib/vufind#108]
## Problem
Die aktuelle Umsetzung der Vorschaubilder führt dazu, dass bei grossen Vorschaubildern die Trefferlistendarstellung verschoben wird. Das Resultat: Die Liste ist zu breit und der Container mit den Facetten wird zu weit nach rechts verschoben (je nach Fenstergrösse aus dem sichtbaren Bereich)

Das Problem besteht soweit ich das sehe bei Firefox und Internet Explorer nicht aber bei Safari und Google Chrome. Allerdings hilft das nicht wirklich ... Die Lösung wäre wohl für FF und IE eine CSS-Alternative zu definieren ...

## Beispiele
* etwas zusammengedrückt: https://test.swissbib.ch/Search/Results?type=AllFields&sort=publishDateSort+asc&limit=100&filter[]=publishDate%3A%22[1913+TO+1918]%22&filter[]=format%3A%22XM020500%22
* extrem: https://test.swissbib.ch/Search/Results?lookfor=Fig%C3%BCrliches+Zeichnen&type=AllFields&limit=20&sort=relevance
* auch extrem: []/Search/Results?lookfor=plan+kirche+trogen&type=AllFields

## Task
Eine Lösung besteht darin die max-width der CSS-Klasse "recordcover" des img-Elements anstelle von Prozentwerten mit Pixelwerten zu steuern (z.B. 110px). Allerdings ist offen, ob das noch weitere Auswirkungen auf das responsive-Design hat ...
* Dringend: Korrektur

## Bemerkungen
* Issue #241 hier integriert

**Comment by ToVie** [comment]
Das Problem besteht soweit ich das sehe bei Firefox und Internet Explorer nicht aber bei Safari und Google Chrome. Allerdings hilft das nicht wirklich... 
Die Lösung wäre wohl für FF und IE eine CSS-Alternative zu definieren...

**Comment by adchsnowflake** [comment]
@oschihin 
Kann ich nicht nachvollziehen: Unter dem Beispiellink sehe ich keine Trefferliste, welche sich zur Trefferliste einer beispielhaften Suchanfrage wie zB. "Virus" darstellt. Kann das Problem der Darstellung evtl. anhand eines aktuellen Beispiellinks und/oder eines Printscreens so beschrieben werden, dass wir das nachvollziehen können?

**Comment by ToVie** [comment]
@adchsnowflake 
Salut Adrian
schön von Dir zu lesen. Wenn Du das zweite Bsp. (https://test.swissbib.ch/Search/Results?lookfor=Fig%C3%BCrliches+Zeichnen&type=AllFields&limit=20&sort=relevance) in Firefox (37.0.2) öffnest, dann siehst Du das Problem.

Beste Grüsse
Tobias

**Comment by adchsnowflake** [comment]
@ToVie 
Hoi Tobias
Schön auch von dir zu lesen! Wie geht es dir in Bern? Alles paletti?
Jetzt! Jetzt unter Firefox sehe ich das Problem auch :D! Alles klar.

Liebe Grüsse --- Adrian

![bildschirmfoto 2015-04-28 um 16 01 52](https://cloud.githubusercontent.com/assets/3326996/7371264/ecfdbeae-edbf-11e4-99c7-e2f7ec278189.png)
