### ISSUE TITLE
uneinheitliche Facettengenerierung swissbib test green / jusbib 

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#111]
jusbib generiert Facetten bei der Autorensuche. Dies im Gegensatz zu test.swissbib.ch

Auch wenn das grundsätzlich ein Ziel sein sollte, werden in den Kategorien der generierten Facetten keine numerischen Angaben geliefert
Beispiel:
http://sb-vf20.swissbib.unibas.ch/justestrd/Author/Home?author=Giliker%2C+Paula

Frage(n)
- warum uneinheitliche Generierung?
- warum keine numerischen Angaben?

Verhalten fiel mir nach dem Update auf letzten Stand development auf. Keine Ahnung ob vorher ebenso.

**Comment by witzigs** [comment]
@guenterh 
Kann dieses Issue geschlossen werden? Ist, da wir den Author-Router nicht mehr verwenden nicht mehr relevant.
