### ISSUE TITLE
Überarbeitung Design (Funktionen?) Vollanzeige

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#114]
@oschihin @witzigs 
Aktuell ist die Darstellung der Vollanzeige in meinen Augen so nicht brauchbar

Was für mich auf den ersten Blick auffällt:
Netzwerke werden kleiner dargestellt als untergeordnete Institutionen. So kann man das nicht in die Produktion übergeben.

Frage:
wie sieht der letzte Designvorschlag von snowflake aus? War das so auf dem Papier? 

Mein Vorschlag:
Wir setzen uns zusammen und besprechen,
- welche Änderungen müssen minimal gemacht werden (oder könnt Ihr mit dem aktuellen Zustand leben)?
- welche sonstigen Anpassungen sind in diesem Bereich hängig? (Bestellung etc)
- was können/wollen/müssen wir machen und was können wir hier snowflake übergeben? Mindestens Designanpassungen möchte ich snowflake geben 
Wir sollten hier möglichst bald zu einer Verständigung kommen

Danke für Feedback

Günter
![screenshot vollanzeige](https://cloud.githubusercontent.com/assets/1825990/5343000/dd8afc9c-7f02-11e4-8cf9-8cd54a71af8a.png)

**Comment by oschihin** [comment]
# sollte im Zug von #278 gelöst werden. Später hier schliessen
