### ISSUE TITLE
Suchschlitz zu kurz

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#117]
Problem
---
Nach dem letzten Merge mit dem VuFind Core ist in swissbib Basel Bern (theme sbvfrdmulti) der Suchschlitz wieder zu kurz. Zudem unterscheidet sich die Länge in den beiden Tabs.

Task
---
1. Anhand untenstehender Diskussion nachvollziehen (war bereits einmal gelöst, siehe verlinktes Issue).
2. Problem lösen (natürlich ;-) 
3. Kurze Erklärung (per Mail z.B.) warum es auftrat: Hat es z.B. mit der LESS-Kompilierung zu tun? Wie lässt sich das vermeiden?

**Comment by oschihin** [comment]
@witzigs ist das nicht gelöst?

**Comment by witzigs** [comment]
@oschihin 
Ja, scheint gelöst zu sein. Hoffen wir, dass es so bleibt!
