### ISSUE TITLE
Slider für Erscheinungsjahr fehlt

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#118]
## Problem
In der Trefferliste und der Erweiterten Suche fehlt seit einem Merge mit dem Code von VuFind-Master der Slider für die Facette Erscheinungsjahr.

## Beispiele
* https://test.swissbib.ch/Search/Results?lookfor=xml&type=AllFields Slider in Facette "Erscheinungsjahr" fehlt
* http://devbabe.swissbib.ch/Summon/Search?lookfor=xml&type=AllFields Slider in Facette "Erscheinungsjahr" fehlt auch im Tab "Artikel & mehr"
* https://test.swissbib.ch/Search/Advanced Unten bei Erscheinungsjahr
* http://sb-vf20.swissbib.unibas.ch/vf2coredemo/Search/Results?lookfor=meier&type=AllFields&limit=20&sort=relevance im Core ist der Slider vorhanden

## Task
* Analyse, wieso unterschiedliche Elemente generiert werden (siehe Kommentare unten)
* Wiederherstellung des Sliders in den fehlerhaften Beispielen oben

**Comment by guenterh** [comment]
Mit 
https://github.com/swissbib/vufind/issues/66
wurde von snowflake (Markus) der JavaScript Code des facet slider entfernt
https://gist.github.com/guenterh/f59bbe17ae913ffbfb56#file-sbvfrd_recommend_sidefacets-phtml-L126

Kommentar: Der VF2 JS code wirft Fehler

Lokal habe ich den für den slider angepassten code laufen lassen
(vgl. 
https://gist.github.com/guenterh/f59bbe17ae913ffbfb56#file-sbvfrd_recommend_sidefacets-phtml-L126)
Ich konnte keinen direkten JavaScript Fehler feststellen. Allerdings werden im Unterschied zu VF2 bestimmte HTML Elemente nicht generiert (vgl. screenshots nachstehend). Mir ist nicht klar, warum diese Elemente nicht erstellt werden, obwohl der code aus meiner Sicht identisch ist.
(CSS Anpassungen duch swissbib/snowflake ?)

task: zusammen mit snowflake sollte analysiert werden, warum unterschiedliche Elemente generiert werden. (Problembereich CSS / Javascript)

**Comment by guenterh** [comment]
![facets slider sbvfrd](https://cloud.githubusercontent.com/assets/1825990/5979231/29a2d4de-a8a6-11e4-847a-c0e86e42cdcb.png)
![facets-slider vf2core](https://cloud.githubusercontent.com/assets/1825990/5979232/29a55a06-a8a6-11e4-94af-9d3b4aba9928.png)

**Comment by guenterh** [comment]
Elemente slider sbvfrd
(gewisse Elemente werden nicht generiert)


![facets slider sbvfrd](https://cloud.githubusercontent.com/assets/1825990/5979256/627b6c94-a8a6-11e4-8107-e4267fdcae12.png)

**Comment by oschihin** [comment]
Siehe auch #176

**Comment by maechler** [comment]
@guenterh 
Das unterschiedliche Markup kam daher, dass wir jQuery UI eingebunden haben. jQuery UI überschrieb die Slider Methode, wie sie im bootstrap3 theme von einer Bootstrap-Erweiterung definiert wurde.
Ich habe jQuery UI neu zusammengestellt und das Slider Widget heraus konfiguriert, damit wird jetzt wieder die Slider Methode von VuFind verwendet um den Slider zu initialisieren.
Zudem wurden die Slider Handles falsch initialisert da VuFind Änderungen an der Struktur der rangeFacets gemacht hat. Im Commit sind das die Änderungen in der SideFacets.phtml Datei.
