### ISSUE TITLE
Merklistenzugang doppelt

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#120]
Der Zugang/Menüpunkt zu den Merklisten (und entsprechenden Funktionen) ist doppelt vorhanden. M.E. könnte man ihn oben weglassen.
![merklistenzugang-doppelt_10-12-2014](https://cloud.githubusercontent.com/assets/5259782/5376751/620d6eb4-807a-11e4-82ff-d234563d5051.jpg)

**Comment by witzigs** [comment]
@guenterh 
Ich habe den doppelten Merklistenzugang mit Bearbeitung von #213 entfernt und schliesse das Issue daher.
