### ISSUE TITLE
Auf Merkliste speichern / neue Merkliste erstellen: mouse over und Design Popup-Fenster

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#121]
Klick auf das Merklisten-Icon eines Titels in der Trefferliste, um ihn in eine Merkliste zu speichern. 
~~1. Fälschlicherweise wird beim mouse over "zu den Favoriten" angezeigt, statt "auf Merkliste speichern".~~ 
2. Ich wähle keine bereits vorhandene ML, sondern klicke auf "neue ML erstellen". Beim nun erscheinenden Fenster ~~stimmt der Titel nicht (wieder "zu den Favoriten") und~~ ist das Design verzerrt (vgl. Screenshot)
![neue merkliste_10-12-2014](https://cloud.githubusercontent.com/assets/5259782/5376862/9144edaa-807b-11e4-9a2c-8cf0732060ce.jpg)
3. Titel zu Merkliste hinzufügen: Der Titel des Werks und "zu den Favoriten hinzufügen" in derselben Schriftgrösse, ohne Abgrenzung. Unschön. Zudem sollte es heissen: Zur Merkliste hinzufügen.
![zu merkliste hinzufugen_15-12-2014](https://cloud.githubusercontent.com/assets/5259782/5439252/a66d583c-847e-11e4-82dd-bb822fb4663c.jpg)

**Comment by oschihin** [comment]
Abschluss
---
* Die Übersetzungen sind soweit ich sehe nun korrekt
* Eine bessere Kennzeichnung des Titels (oben Punkt 3) ist eigentlich trivial. Wir haben in der bisherigen View das entsprechende Template selbst gepflegt, nun kommt ein Standardtemplate von VuFind zum Zug (themes/bootstrap3/templates/record/save.phtml::Z10). Dort könnte man wie bisher das Titelelement in "Gänsefüsschen" einfassen. Aber:
 * Für diese minimale Änderung das Template selbst zu pflegen halte ich für nicht sinnvoll
 * habe einen Pull-Request bei VuFind gestellt (https://github.com/vufind-org/vufind/pull/274), mal schauen, was sie damit machen.

Hier geschlossen.
