### ISSUE TITLE
Verfügbarkeitsanzeige bei Exemplarstatus 41

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#123]
Bei Archivexemplaren mit Exemplarstatus 41 (nicht ausleihbar) bitte gelegentlich den aktuellen Anzeigetext "nicht verfügbar" ändern zu „Archivexemplar, keine Ausleihe“ (wie im OPAC). 
![verfugbarkeitsanzeige-archivexemplare_10-12-2014](https://cloud.githubusercontent.com/assets/5259782/5377428/3ee7cfee-8082-11e4-9661-15e36cb13056.jpg)

**Comment by oschihin** [comment]
@witzigs wurde gelöst
