### ISSUE TITLE
Mouse-over-Anzeige bei besitzenden Bibliotheken in der Trefferliste?

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#124]
Neu ist ein Klick auf "Bibliotheken" nötig, um in der Trefferliste die besitzenden Bibliotheken angezeigt zu bekommen. Könnte man das nicht wie gehabt als Mouse-over anbieten?
![mouse-over-bibliotheken_10-12-2014](https://cloud.githubusercontent.com/assets/5259782/5378048/ba63ba3e-8087-11e4-96a3-42c57f196b24.jpg)

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Mouse-over-Anzeige bei besitzenden Bibliotheken in der Trefferliste? #124 (12/2014-wishful)](https://trello.com/c/CyBVxDPK/102-mouse-over-anzeige-bei-besitzenden-bibliotheken-in-der-trefferliste-124-12-2014-wishful)
