### ISSUE TITLE
Design Formatbezeichnung 

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#125]
Mehr eine Beobachtung, nähme mich wunder, was die Design-Leute dazu sagen: Schriftteile oder Schaltflächen, die im dunkleren Orange gehalten sind, sind in der Oberfläche eigentlich durchgängig klickbar - ausser im Fall der Formatbezeichnungen (Buch, Artikel etc.). Gibt es zwingende Gründe, warum die orange sein müssen? 
![formatbezeichnung design_10-12-2014](https://cloud.githubusercontent.com/assets/5259782/5378160/8d022174-8088-11e4-9eb9-9236297c73e5.jpg)

**Comment by witzigs** [comment]
gelöst, siehe #251
