### ISSUE TITLE
Interpunktion in Anzeige

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#128]
Problem
---
Schon lange offen, Interpunktionszeichen v.a. in der Vollanzeige fehlen. Bspw. in der Kollation (300 S., Ill.), ev. weitere
Lösung
---
In View-Templates einbauen

**Comment by witzigs** [comment]
@oschihin 
Ich sehe nicht, wie ich das auf der Oberfläche für alle Fälle korrekt lösen könnte. Nicht hinter jeden Inhalt von 300 $a oder $b gehört ein Punkt und wenn ich trotzdem einen setze, sieht das für viele Fälle ziemlich seltsam aus (also nicht besser als es jetzt ist).
Hinzu kommt, dass ab RDA diese beschreibenden Angaben nicht mehr abgekürzt werden. Es bräuchte dann also eine andere Lösung für RDA-Daten.
Erklärst du mir bei Gelegenheit mal, weshalb diese Angaben bei der Datenverarbeitung wegfallen müssen?

**Comment by ToVie** [comment]
@witzigs und @oschihin: vielleicht kann ich das noch erklären - beim Export aus CBS läuft ein Skript mit, das ISBD-Interpunktion so konsequent als möglich zu entfernen versucht. Dabei schiesst es bei Punkten am Feldende immer dann übers Ziel hinaus, wenn der Punkt einer Abkürzung mit dem Punkt am Feld/Zonenende zusammenfällt.
@oschihin Mehr Infos dazu hat sicher Tonny. Vielleicht kann man den Mechanismus ja noch etwas verbessern.

**Comment by guenterh** [comment]
Muss in den Daten angepasst werden. Kann im GUI nicht gelöst werden.
