### ISSUE TITLE
Darstellung der Seite 0 Treffer

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#131]
Problem
---
Die Seite nach einer 0-Treffer-Abfrage ist noch nicht designt (die Suchvorschläge sind auch suboptimal, dies aber ein anderes Thema).
* Vorschläge werden zweimal dargestellt
* Hintergrundfarbe ist blau
* Links zu grösseren Katalogen fehlen

Lösung
---
orientiert am produktiven theme für die Links. Ansonsten Design und Darstellung

**Comment by guenterh** [comment]
mit dem Schliessen des Did You mean threads (s #115 ) (s. auch die Kommentare dort) sind die Grundlagen für die Weiterbearbeitung dieses threads gelegt

**Comment by guenterh** [comment]
@witzigs 
Hallo Silvia,

ich habe einen neuen branch angelegt (feature/improvedSpelling)
in dem ich mal erste Schritte für eine Verbesserung angelegt habe. Dieser branch ist so noch nicht nutzbar.

Der Grund warum wir nur so wenige (collation) Vorschläge beim spelling erhalten:
VuFind baut Listen auf, in denen die Terme als key benutzt werden. Da die von uns verwendete Methode des direct spellings als key mehrfach collation zurückliefert (möglicherweise ist dies bei der VF Methode nicht so) werden mehrfache Vorschläge immer wieder überschrieben.

Dies zu überschreiben ist mit den Defaultmitteln nicht so ohne weiteres möglich, da das Modul VuFindSearch ein wenig speziell aufgebaut ist. Ich habe jedoch einen Weg gefunden (der neue Branch)

Ich habe ein kleines Dokument mit bis jetzt (sehr wenigen) Beipielabfragen für das spellchecking
https://github.com/swissbib/vufind/blob/feature/improvedSpelling/sbDocumentation/searchcomponent/spelling.examples.txt

Ist folgendes möglich:
a) Du "spielst" ein wenig mit dem spellchecker und dokumentierst, welche Vorschläge für bestimmte queries gemacht werden.
b) bitte versuche auf folgende Aspekte zu achten (Dinge die mich interessieren würden)
- Bekommt man gleiche Ergebnisse wenn man Abfragen  mit den Parametern
spellcheck.q
und 
q

oder nur 
spellcheck.q
absetzt

- welchen Einfluss hat der Parameter  spellcheck.dictionary?
Im Moment haben wir zwei solcher dictionaries definiert
-- default (author(
-- basicSpell (title)


Wir könnten uns dann abstimmen: Was findest Du heraus, das kann ich dann besser in der Appikation umsetzen. Dadurch würde ich einiges an Zeit sparen.

Wäre super - vielen Dank!

Günter

**Comment by witzigs** [comment]
@guenterh 

Hallo Günter

Zwei Punkte zu den spelling suggestions, wenn man eine erweiterte Suche absetzt:
* Bei einer Suche mit einem Wort werden suggestions generiert. Jedoch stürzt der Aufbau der Seite ab. 
Beispiel: http://devbabe.swissbib.ch/Search/Results?sort=relevance&join=AND&bool0[]=AND&lookfor0[]=yerk&type0[]=AllFields&limit=20&daterange[]=publishDate&publishDatefrom=&publishDateto=

* Bei einer Suche mit mehr als einem Wort werden keine suggestions generiert.
Beispiel: http://devbabe.swissbib.ch/Search/Results?sort=relevance&join=AND&bool0[]=AND&lookfor0[]=new+yerk&type0[]=AllFields&lookfor0[]=&type0[]=AllFields&lookfor0[]=&type0[]=AllFields&limit=20&daterange[]=publishDate&publishDatefrom=&publishDateto= 

Liebe Grüsse
Silvia

**Comment by guenterh** [comment]
@maechler 
Hallo Markus
noch zu unserem Gespräch Recommendations und Spellings als ersten zu verbessernden Anwendungsfall:
Wir haben den branch https://github.com/swissbib/vufind/tree/feature/improvedSpelling
Dort habe ich mal, wie so oft, begonnen, die im Gespräch erwähnten Probleme, Aufbereitung der suggestions durch VuFind anzugehen. Leider ist es dann wieder liegengeblieben.
Ich habe noch ein paar zusätzliche Beipiele, wie die Vorschläge von SOLR generiert werden, in dieser
https://github.com/swissbib/vufind/blob/feature/improvedSpelling/sbDocumentation/searchcomponent/spelling.examples.txt
Datei abgelegt.

Neben Anpassungen in VuFind kann man sicherlich noch die Art und Weise, wie in SOLR spellcheckings generiert werden, anpassen. Eine Quelle kann
http://proquest.tech.safaribooksonline.de/book/operating-systems-and-server-administration/apache/9781617291029/chapter-10dot-query-suggestions/ch10lev1sec1_html
sein (nur innerhalb des Uni-Netzes)

Günter

**Comment by guenterh** [comment]
Obsolet
