### ISSUE TITLE
Navigieren in Trefferliste

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#136]
Man müsste gezielter in der Trefferliste navigieren können, mindestens so wie in der aktuellen Oberfläche.
![blattern-trefferliste_15-12-2014](https://cloud.githubusercontent.com/assets/5259782/5434286/7bae1b82-8450-11e4-9144-f868ae9b5435.jpg)
Jetzige Oberfläche:
![blattern-trefferliste-alt_15-12-2014](https://cloud.githubusercontent.com/assets/5259782/5434285/75f3ac7a-8450-11e4-9567-475476d281d7.jpg)

**Comment by witzigs** [comment]
Hier ist im Moment keine andere Lösung möglich - es wurde schon diverses ausprobiert.
