### ISSUE TITLE
Exportfunktion auf Ebene Trefferliste fehlt

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#138]
Auf Ebene Trefferliste kann man nicht exportieren/speichern:
![trefferliste-weiterverarbeitung_15-12-2014](https://cloud.githubusercontent.com/assets/5259782/5434592/aec0b6bc-8453-11e4-9574-e35bcfaf58e8.jpg)
Bisher angeboten:
![trefferliste-weiterverarbeitung-alt_15-12-2014](https://cloud.githubusercontent.com/assets/5259782/5434626/0a0bf59a-8454-11e4-9d6d-5adfe7992052.jpg)

**Comment by witzigs** [comment]
siehe #232
