### ISSUE TITLE
Icons Trefferliste und Vollanzeige

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#139]
Trefferliste:
Das schwarze Plus-Icon oben rechts bei der Trefferliste ist offenbar das Icon für "Suchanfrage speichern". Das müsste erkenntlicher sein (Tooltip heisst jetzt missverständlich "speichern"). 
Ev. könnte man das Icon auch gleich links neben den Titel "Suchergebnisse" nehmen?
Zum Design dieses Icons: finde ich nicht sehr gelungen, zu ähnlich wie das Kreuz für "auf Merkliste speichern". Wäre gut, wenn man fürs Speichern von Suchanfragen ein anderes Icon hätte.
Das Lupen-Icon links neben dem Titel "Suchergebnisse" finde ich hingegen an dieser Stelle überflüssig bis verwirrlich.
![icon-suchanfrage-speichern_15-12-2014](https://cloud.githubusercontent.com/assets/5259782/5434823/307f9946-8456-11e4-87f5-f945bbc0098d.jpg)

Vollanzeige:
Das Pluszeichen für "auf die Merkliste" entspricht nicht dem für diese Funktion verwendeten Icon beim einzelnen Treffer in der Trefferliste. 
![icons-weiterverarbeitung_15-12-2014](https://cloud.githubusercontent.com/assets/5259782/5435030/a8e37ca4-8456-11e4-91b3-ba3f2ba0987a.jpg)
![auf merkliste_15-12-2014](https://cloud.githubusercontent.com/assets/5259782/5434989/907ba4b6-8456-11e4-8a9d-0598001915ca.jpg)
Für "Zitieren" fänd ich sowas wie Anführungszeichen besser, aber man wird sich wohl daran gewöhnen...

**Comment by chantalw** [comment]
Danke für die Änderungen. 
An das jetzige neue Icon für "zu Merkliste hinzufügen" kann und wird man sich gewöhnen, denke ich. Es ist jetzt auch überall gleich. 
Icon "Zitieren": fa-pencil fände ich keine schlechte Idee. 
Mit dem Icon für "Exportieren/Speichern" habe ich noch etwas Mühe. Vielleicht wäre fa-folder oder fa-file oder fa-share noch was? oder fa-arrow-circle-down (wie oft für Download verwendet)? oder fa-save?
Etwas störend finde ich auch noch, dass die Icons in der Trefferliste dunkelgrau sind und die Icons bei der Vollanzeige tiefschwarz:
![05-01-2015_icons-trefferliste](https://cloud.githubusercontent.com/assets/5259782/5613970/fb1d28d0-94eb-11e4-99e4-b93146c43f9c.jpg)
![05-01-2015_icons-vollanzeige](https://cloud.githubusercontent.com/assets/5259782/5613969/fb1c90f0-94eb-11e4-9f2e-1f281bd3fed3.jpg)
Und noch ein Input zu den Tooltips: Sie beginnen jetzt alle mit Grossbuchstaben, ausser "per E-Mail versenden". Ich würde da konsequent sein, entweder überall mit Grossbuchstaben beginnen, oder dann "zu Merkliste hinzufügen" auch klein beginnen, ebenso "zitieren", "exportieren" etc.

**Comment by witzigs** [comment]
Ich habe für Zitieren fa-pencil gesetzt und für Exportieren fa-share. 
Den Tooltip für E-Mail versenden habe ich neu gross geschrieben und die Einfärbung der Icons in der Vollanzeige ist ebenfalls angepasst.
