### ISSUE TITLE
Titelvollanzeige: Pfadangabe oben

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#141]
- Bei Reiterwechsel macht der Pfad nicht mit bzw. nur beim ersten Wechsel. D.h. wenn ich vom Reiter Exemplare in den Reiter Beschreibung wechsle, wechselt der Pfad auf Beschreibung, wenn ich dann wieder in den Reiter Exemplare oder in den Reiter Felder wechsle, bleibt im Pfad Beschreibung.
- Frage: Braucht es dieses dritte Pfadelement (Reiterangabe) überhaupt?
![titelvollanzeige-pfadangabe_15-12-2014](https://cloud.githubusercontent.com/assets/5259782/5435996/9435f1a0-8461-11e4-8ad4-7b04992f3e6e.jpg)
- Vorschlag: Beim ersten Pfadelement (zurzeit bezeichnet mit "Suche") folgende Bezeichnung verwenden: "Ihre Suche: xy", so ähnlich wie in der aktuellen Oberfläche das Element im Screenshot. 
Allenfalls wäre auch "Suchergebnisse" oder "Trefferliste" besser als einfach "Suche".
![ihre suche-alt_15-12-2014](https://cloud.githubusercontent.com/assets/5259782/5436078/5dfa0a4e-8462-11e4-933b-f325b9be6029.jpg)

**Comment by witzigs** [comment]
Ist gelöst, wohl Zusammenhang mit #179.
