### ISSUE TITLE
Trefferliste aus Titelvollanzeige heraus ("Facette" Autor)

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#142]
Nach Klick auf die "Facette" Autor in einer Titelvollanzeige wird die neue Trefferliste nicht korrekt angezeigt (bei Klick auf "Facette" Thema funktionierts):
![titelvollanzeige-autor_15-12-2014](https://cloud.githubusercontent.com/assets/5259782/5436249/458a895a-8464-11e4-9a28-98c4a62db4c8.jpg)

Generiert man aus dieser Trefferliste eine Titelvollanzeige, kann man dort nicht blättern zwischen den Titelvollanzeigen:
![titelvollanzeige aus autorenliste_15-12-2014](https://cloud.githubusercontent.com/assets/5259782/5436253/4c869b54-8464-11e4-8b22-4671057dd77b.jpg)

Noch ein paar weitere Beobachtungen hierzu:
Pfadangabe: Gibt mir keine sinnvolle Navigationsmöglichkeit. Nach Klick auf "Verfasser/Beitragende" komme ich zu dieser Ansicht - was soll diese dem Nutzer bieten? Nicht selbsterklärend.
![08-01-2015_gefundene verfasser](https://cloud.githubusercontent.com/assets/5259782/5661204/491250c6-9729-11e4-99d2-5218fd748b59.jpg)
Zudem wird hier - obwohl ich angemeldet bin - nicht meine Einstellung der Anzahl Treffer pro Seite übernommen:
![08-01-2015_trefferliste-nach-verfasser](https://cloud.githubusercontent.com/assets/5259782/5661162/ccc1f60c-9728-11e4-8dd6-bf1382782f4f.jpg)

**Comment by chantalw** [comment]
Fallbeispiel dazu:
Einfach Suche nach john steinbeck - Trefferliste sieht OK aus
Eingrenzen mit Facette "Verfasser/Beitragende: John Steinbeck (1902-1968) oder "Verfasser/Beitragende: John Steinbeck" - Trefferliste sieht OK aus
Nach Eingrenzen mit einer der Verfasser-Facetten: Klick auf Titelvollanzeige - sieht normal aus
In Titelvollanzeige: Klick auf "Verfasser/Beitragende: Steinbeck, John"
![15-01-2015_titelvollanzeige-autorenfacette](https://cloud.githubusercontent.com/assets/5259782/5756292/0bbdfa88-9cae-11e4-9e62-ba18817f5008.jpg)
Danach erscheint die Trefferliste mit dem verzogenen Design und ausserdem einem Balken mit Wikipedia-Infos zu John Steinbeck, worin Begriffe verlinkt sind (bei Klick darauf wird in swissbib BB nach diesem Begriff gesucht).
![15-01-2015_wikipedia-infos](https://cloud.githubusercontent.com/assets/5259782/5756348/b967c24a-9cae-11e4-9e86-ba4e5f392b38.jpg)
 
Frage: Ist der Info-Balken ein neues Feature, über dessen Einführung man diskutieren könnte/sollte (falls es in Ordnung und konsequent angezeigt würde)?

**Comment by witzigs** [comment]
siehe auch #32

**Comment by guenterh** [comment]
@witzigs @oschihin 

Hallo Silvia

habe mir kurz vor dem Mittag die Möglichkeiten zur Erstellung von Autrorenfacetten angesehen (Überführung der Autorensuche in die allegemeine Suche)

Mit dem jetzigen Stand der Implementierung scheint die Umstellung relativ einfach möglich zu sein.
Eine spezielle Autorensuche mit 
https://test.swissbib.ch/Author/Home?author=Kevenh%C3%B6rster%2C+Paul
lässt sich einfach nach 
https://test.swissbib.ch/Search/Results?lookfor=Kevenh%C3%B6rster%2C+Paul&type=Author
umstellen. Die Treffermenge ist gleich uns sonst kann ich keine Nachteile erkennen (ok, z.B. der pager auf der Vollanzeige funktioniert auch in diesem Kontext nicht)

Vorschlag:
Ist es für Euch ok, wenn ich einen branch erstelle, in dem die Autorensuche auf die 2. Variante umgestellt wird und Ihr Euch die Änderungen dann gründlicher ansehen könnt?

Günter



https://test.swissbib.ch/Search/Results?lookfor=Kevenh%C3%B6rster%2C+Paul&type=Author

**Comment by witzigs** [comment]
Hallo Günter

Danke für die Infos. Ein branch zum Testen wäre gut.

Liebe Grüsse
Silvia

--
UNIVERSITÄT BASEL
Universitätsbibliothek
Silvia Witzig
IT / Verbundkoordination
Schönbeinstrasse 18-20
4056 Basel, Schweiz
Tel. +41 (0)61 267 29 44
Tel. +41 (0)61 267 30 95
E-Mail silvia.witzig@unibas.ch
URL http://www.ub.unibas.ch/bibliotheksnetz
________________________________
Von: Guenter Hipler [notifications@github.com]
Gesendet: Mittwoch, 21. Januar 2015 14:44
An: swissbib/vufind
Cc: Silvia Witzig
Betreff: Re: [vufind] Trefferliste aus Titelvollanzeige heraus ("Facette" Autor) (#142)


@witzigs<https://github.com/witzigs> @oschihin<https://github.com/oschihin>

Hallo Silvia

habe mir kurz vor dem Mittag die Möglichkeiten zur Erstellung von Autrorenfacetten angesehen (Überführung der Autorensuche in die allegemeine Suche)

Mit dem jetzigen Stand der Implementierung scheint die Umstellung relativ einfach möglich zu sein.
Eine spezielle Autorensuche mit
https://test.swissbib.ch/Author/Home?author=Kevenh%C3%B6rster%2C+Paul
lässt sich einfach nach
https://test.swissbib.ch/Search/Results?lookfor=Kevenh%C3%B6rster%2C+Paul&type=Author
umstellen. Die Treffermenge ist gleich uns sonst kann ich keine Nachteile erkennen (ok, z.B. der pager auf der Vollanzeige funktioniert auch in diesem Kontext nicht)

Vorschlag:
Ist es für Euch ok, wenn ich einen branch erstelle, in dem die Autorensuche auf die 2. Variante umgestellt wird und Ihr Euch die Änderungen dann gründlicher ansehen könnt?

Günter

https://test.swissbib.ch/Search/Results?lookfor=Kevenh%C3%B6rster%2C+Paul&type=Author

**Comment by oschihin** [comment]
@witzigs @guenterh ist das nicht erledigt durch das Umgehen des Author-Routers? Kann man hier schliessen?

**Comment by guenterh** [comment]
wie Oliver schreibt: ist mit dem Ausschluss des Autor-controllers nicht mehr relevant.

@oschihin 
sollte man für Jusbib aber nochmals anschauen. Habe ich längere Zeit nicht mehr aktualisiert
