### ISSUE TITLE
Export Titelvollanzeige: Erscheinungsjahr fehlt

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#144]
Export aus einer Titelvollanzeige nach Zotero (auch EndNoteWeb) ohne Erscheinungsjahr
![export-en-titelvollanzeige_15-12-2014](https://cloud.githubusercontent.com/assets/5259782/5436395/fa12ec40-8465-11e4-8881-7c3ffde4ce89.jpg)
![export-titelvollanzeige-zotero_15-12-2014](https://cloud.githubusercontent.com/assets/5259782/5436475/f307d194-8466-11e4-896e-ea93ccdc2598.jpg)
Wünschbar wäre auch der Export von Seitenzahl und ev. GND-Schlagworten

**Comment by chantalw** [comment]
Noch nicht ok. Zum Vergleich derselbe Titel nach Zotero importiert.
Per Klick auf "Exportieren nach EndNote": Hinzugekommen ist das "2. Auflage", Datum immer noch "s", ISBN ist da.
![22-01-2015_zotero-import-endnote](https://cloud.githubusercontent.com/assets/5259782/5855427/826706c2-a238-11e4-9e07-91708a0fabe7.jpg)
Per Klick auf "Exportieren nach BibTex": Auch hier "2. Auflage", Datum fehlt immer noch, ISBN fehlt ebenfalls.
![22-01-2015_zotero-import-bibtex](https://cloud.githubusercontent.com/assets/5259782/5855436/8ebc3f1e-a238-11e4-96d6-c2acc325c9aa.jpg)

**Comment by oschihin** [comment]
Ist noch nicht auf devbabe, wurde erst gestern abend commited

Am 22.01.2015 um 13:16 schrieb chantalw:
> Noch nicht ok. Zum Vergleich derselbe Titel nach Zotero importiert.
> Per Klick auf "Exportieren nach EndNote": Hinzugekommen ist das "2.
> Auflage", Datum immer noch "s", ISBN ist da.
> 22-01-2015_zotero-import-endnote
> <https://cloud.githubusercontent.com/assets/5259782/5855427/826706c2-a238-11e4-9e07-91708a0fabe7.jpg>
> Per Klick auf "Exportieren nach BibTex": Auch hier "2. Auflage", Datum
> fehlt immer noch, ISBN fehlt ebenfalls.
> 22-01-2015_zotero-import-bibtex
> <https://cloud.githubusercontent.com/assets/5259782/5855436/8ebc3f1e-a238-11e4-96d6-c2acc325c9aa.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swissbib/vufind/issues/144#issuecomment-71012132>.
>

-- 
UNIVERSITÄT BASEL
Universitätsbibliothek
Oliver Schihin
Projekt swissbib
Schönbeinstrasse 18-20
4056 Basel, Schweiz
Tel.: +41 61 267 13 07
Fax: +41 61 267 31 03
E-Mail oliver.schihin@unibas.ch
URL http://www.swissbib.org/

**Comment by chantalw** [comment]
Das Erscheinungsjahr wird nun korrekt nach Zotero exportiert. Bei EndNote Web ist es noch nicht ok, aber ich schliesse hier und mache einen neuen Issue zu EndNote Web.
