### ISSUE TITLE
Startseite Suchschlitz

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#147]
1. "Suche innerhalb von" über der Tab-Auswahl: m.E. eher weglassen
2. Wie bisher "Erweiterte Suche" statt nur "Erweitert", das Icon (Lupe mit Pluszeichen) sagt mir nichts, wird das verbreitet verwendet für die Erweiterte Suche? Könnte man sonst auch weglassen...
![startseite-suchschlitz_15-12-2014](https://cloud.githubusercontent.com/assets/5259782/5438832/69a2efbe-847b-11e4-94c5-d4316d3af21e.jpg)

**Comment by witzigs** [comment]
Punkt 2 ist mit 889daaf3d4239086736f6f53018b66ff70c1c3f0 gelöst.
