### ISSUE TITLE
Druckfunktion für Trefferliste und Titelvollanzeige fehlt

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#148]

**Comment by witzigs** [comment]
@chantalw 
Ich hatte den Eindruck wir hätten das schon mal diskutiert/festgehalten, kann es aber im Moment nicht finden. Deshalb nochmals hier: Wir werden auf der Oberfläche keine Druckfunktion (sowie jetzt vorhanden) anbieten, da dies zusätzlich zur Druckfunktion des Browsers nicht notwendig ist.
Die Druckausgaben von Trefferliste, Vollanzeige und Merkliste wurden von Snowflake überarbeitet und sind in Ordnung.
