### ISSUE TITLE
Druckausgabe Trefferliste

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#151]
Folgende Anpassungen sind notwendig:
* Coverbilder nicht drucken
* Keine Umrahmung der Labels
* Pagination nicht drucken
* Namen der besitzenden Bibliotheken drucken
* Ausgeführte Suche und Anzahl Treffer drucken (zuoberst auf der ersten Seite)
* swissbib-ID drucken

**Comment by oschihin** [comment]
@drummer23 
Basierend auf test.swissbib.ch (21.01.2015)
## Firefox
* Labels fehlen
* Namen der besitzenden Bibliotheken fehlen
* Text "Ihre Suche" seltsam in der Mitte eingerückt
