### ISSUE TITLE
Druckausgabe Vollanzeige

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#152]
Folgende Anpassungen sind notwendig:
* Coverbilder nicht drucken
* Keine Umrahmung der Labels
* zusätzlich Systemnummer drucken mit dem Label "ID"

Bei Druck im Tab Exemplare:
* Identische Ausgabe, egal ob Exemplare einer Bibliothek augeklappt oder nicht
* Name der Bibliothek, Standort und Signatur drucken
* Favorit hinzufügen/löschen nicht drucken

Bei Druck im Tab Reihe/Bände:
* Suchschlitz nicht drucken
* Symbole nicht drucken

**Comment by oschihin** [comment]
@drummer23 
## Chrome on Windows
* Labels vorhanden, jedoch umrandet
* Standort und Signatur fehlen, auch wenn Tab angewählt und Bibliothek geöffnet
