### ISSUE TITLE
Anzeigetext "Kurzausleihe" bei Exemplarstatus 52

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#153]
Bei Exemplaren mit Exemplarstatus 52 müsste auch in sbBB „Kurzausleihe (1 Tag)“ angezeigt werden. 
Ein Beispiel http://baselbern.swissbib.ch/Record/27123881X im Anhang.

![ex-status-52_18-12-2014](https://cloud.githubusercontent.com/assets/5259782/5485320/e69103c4-8699-11e4-9e41-8df9373198ec.jpg)
![ex-status52_opac_18-12-2014](https://cloud.githubusercontent.com/assets/5259782/5485319/e690fc80-8699-11e4-8ad2-74c6822bb853.jpg)

**Comment by chantalw** [comment]
@oschihin @witzigs Wie seht ihr die Möglichkeiten zur Umsetzung hier? Kommt das mit der neuen Oberfläche? Von der FBB kam eine Nachfrage: "Leider klappt das mit der Anzeige unserer Kurzausleihen (Status 52) in Swissbib immer noch nicht. Für uns ist es sehr wichtig, dass die Benutzenden den Status „Kurzausleihe“ sehen können, da es sich bei diesen Büchern um vielgebrauchte Schulungsunterlagen in Mehrfachexemplaren handelt." (Mail Fränzi Eberle an pal am 13.3.2015)

**Comment by oschihin** [comment]
@witzigs Falls bereits gelöst, bitte schliessen
