### ISSUE TITLE
Titelvollanzeige bei Zeitschriften

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#154]
Ich schaff's einfach nicht, mir ein ZS-Detailfenster im neuen Design anzeigen zu lassen. Der Ladevorgang kommt zu keinem Ende, auch bei Titeln mit wenigen Exemplaren...
Ein Wunsch wäre, dass im ZS-Detailfenster die Blättermöglichkeit nicht nur oben rechts sondern auch unten rechts angezeigt würde (vgl. Screenshot).
By the way ist mir noch aufgefallen, dass rechts bei "Verknüpfte Einträge" der Anzeigetext noch nicht bereinigt ist (vgl. Screenshot).
![vollanzeige-zs_18-12-2014](https://cloud.githubusercontent.com/assets/5259782/5485700/fd8fe84c-869e-11e4-8c49-4511e7fadc8a.jpg)
![zs-detailfenster-blattern_18-12-2014](https://cloud.githubusercontent.com/assets/5259782/5485701/fd90f32c-869e-11e4-8f53-86f79770368f.jpg)

**Comment by chantalw** [comment]
Danke - das kommt ja sicher noch besser? ;-)
![12-01-2015_detailfenster-zs](https://cloud.githubusercontent.com/assets/5259782/5705594/bfa703a4-9a7a-11e4-8f46-b01b0c92ccdc.jpg)

**Comment by witzigs** [comment]
Ergänzend zum Design-Problem:
Es werden alle Exemplarsätze und nicht nur die Exemplarsätze der gewählten Bibliothek im Fenster angezeigt.

**Comment by oschihin** [comment]
hier wird geschlossen, da das meiste gelöst und der Issue ist unübersichtlich. Für weitere Probleme und Wünsche bzgl. Design und Funktionalitäten bitte neue Issues
