### ISSUE TITLE
iPhone (4S): Anmeldefunktion schlecht sichtbar

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#155]
Es bestehen Bedenken, ob das doch sehr kleine Menü-Icon oben rechts wahrgenommen wird. Sollten die wichtige Funktion "Anmelden" oder "Konto" auf der Startseite nicht auf Anhieb ersichtlich sein und nicht erst nach dem Drücken auf das Menü?

![iphone-anmelden_18-12-2014](https://cloud.githubusercontent.com/assets/5259782/5486173/0bfe6e58-86a4-11e4-8d50-63aaf022d8cb.jpg)

**Comment by witzigs** [comment]
Hier ist eine andere Lösung kaum möglich. Wir gehen auch davon aus, dass das Menü-Icon gesehen wird.
