### ISSUE TITLE
Informationen zur Anmeldung bei Anmeldung anzeigen oder verlinken

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#157]
In der aktuellen Oberfläche gibt es auf der Anmeldeseite Links zu Infos oder Aktionen, die mit der Anmeldung zusammenhängen:
![anmelden-alt_18-12-2014](https://cloud.githubusercontent.com/assets/5259782/5486612/c915c690-86a8-11e4-9692-235dec22a866.jpg)
In der RD-Oberfläche kommt einfach das Fenster zum Anmelden:
![anmelden-neu_18-12-2014](https://cloud.githubusercontent.com/assets/5259782/5486626/ef17fb56-86a8-11e4-97ab-fe2971d6fc9b.jpg)
Wäre es möglich, die Infos hier http://devbabe.swissbib.ch/HelpPage/myswissbib irgendwo im Kontext der Anmeldung anzuzeigen oder mindestens zu verlinken (also im Anmeldefenster einen Link "Informationen zum Benutzerkonto"  oder so ähnlich zu platzieren?
![anmeldeinformationen_18-12-2014](https://cloud.githubusercontent.com/assets/5259782/5486644/236227ec-86a9-11e4-8d0c-2d95f91d59d1.jpg)

**Comment by witzigs** [comment]
@chantalw 
Ein Link ist hier gut möglich. Auf weiteren Text würde ich verzichten, da das Popup-Fenster für die Anmeldung damit ziemlich überladen wäre.
Ich habe provisorisch einen Link auf die angegebene Hilfeseite eingefügt. Bezeichnung und Link sind aber nach Überarbeitung der Hilfeseiten nochmals anzupassen.

**Comment by guenterh** [comment]
@witzigs 
Ist das nicht mit der Entscheidung, keine Popupdialoge mehr zu benutzen, obsolet?

Günter

**Comment by witzigs** [comment]
Ist nicht obsolet, aber erledigt.
