### ISSUE TITLE
Tabletformate: Anzeige Benutzerprofil überprüfen

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#160]
Wenn man ein Android-Tablet im Querformat benutzt, wird das Benutzerprofil nicht richtig angezeigt:
Die Tabelle ist ganz schmal auf der linken Seite, zwei Drittel des Bildschirms rechts sind einfach weiss. 
 
![android-screenshot_2014-12-18-14-32-53](https://cloud.githubusercontent.com/assets/5259782/5488842/787711c4-86c3-11e4-80c0-64e3a1bd972c.png)

**Comment by chantalw** [comment]
Dasselbe gilt für iPad (Safari):
![ipad_profilansicht](https://cloud.githubusercontent.com/assets/5259782/5661779/f227b358-972f-11e4-8519-85ef007150ae.jpg)

**Comment by witzigs** [comment]
Ich kann dieses Problem nicht mehr nachvollziehen. Die Anzeige sieht auf allen Viewports in Ordnung aus.
