### ISSUE TITLE
iPhone (4S): "Wischen" geht nicht?

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#161]
Ist es richtig, dass für alle Aufrufe zusätzlicher Anzeigen/Funktionen (z.B. mit dem kleinen weissen Pfei im orangen Eck zum Aufrufen der Facetten) mit dem Finger getippt werden muss? Die "Wischbewegung" klappt bei mir jedenfalls nicht. 
![wischen_18-12-2014](https://cloud.githubusercontent.com/assets/5259782/5489572/d1e0a840-86ca-11e4-898c-12d208165327.jpg)

**Comment by witzigs** [comment]
Ja, der Button ist zum tippen/klicken gedacht.
