### ISSUE TITLE
Android-Tablet: Dropdown-Menüs nicht erkennbar

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#164]
Auf einem Android-Tablet sehen die Dropdowns aus wie Suchschlitze. Es ist nicht erkennbar, dass es sich um ein Dropdown handelt. Bei antippen des Felds öffnet sich das Auswahlmenü normal unten am Bildschirm.

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Android-Tablet: Dropdown-Menüs nicht erkennbar #164 (12/2014-useful)](https://trello.com/c/E76HiHxN/100-android-tablet-dropdown-menus-nicht-erkennbar-164-12-2014-useful)
