### ISSUE TITLE
fehlendes template nach letztem merge mit VF2 core?

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#165]
ist mir im log auf sb-vf1 aufgefallen (BASEDIR/log/error.log)
0T14:13:42+01:00 CRIT (2): Zend\View\Renderer\PhpRenderer::render: Unable to render template "record/not-found"; resolver could not resolve to a file

**Comment by oschihin** [comment]
Hinweis
---
Das Verhalten lässt sich leicht nachvollziehen mit dem Aufruf eines nicht-existierenden Record. Erste Analyse:
* Der Template-Aufruf ist hier fix codiert: https://github.com/swissbib/vufind/blob/development/module/Swissbib/src/Swissbib/Controller/RecordController.php#L22
* Dies entspricht offenbar nicht dem Ablauf von VuFind
 * Es gibt einen eigenen Controller: https://github.com/swissbib/vufind/blob/development/module/VuFind/src/VuFind/Controller/MissingrecordController.php
 * Dargestellt wird wahrscheinlich ein (sehr einfaches) Template: https://github.com/swissbib/vufind/tree/development/themes/bootstrap3/templates/missingrecord

Ich habe versucht, dieses Template anzusprechen, blicke aber bei den verschiedenen Controllern nicht durch. Ziel sollte sein:
* Nutzung des Standardmechanismus
* Falls nötig, eigenes Template pflegen, aber gemäss VuFind-Ablauf

**Comment by guenterh** [comment]
see https://github.com/swissbib/vufind/commit/1bc5fbef0bcc5a5544f5deddb6c4a368a39e2c65
a simple forward solves the problem

VF2 core flashmessages output is really basic 
If we want more we have to overwrite it
