### ISSUE TITLE
Überarbeitung login Dialog Shibboleth Responsive Design

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#166]
Der Shibboleth login Dialog 
(s. themes/sbvfrdsingle/templates/Auth/Shibboleth/login.phtml)
muss für responsive design ge-rendered werden

Folgetask von https://github.com/swissbib/vufind/issues/90

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Überarbeitung login Dialog Shibboleth Responsive Design #166 (01/2015-useful)](https://trello.com/c/55FbfQeQ/99-uberarbeitung-login-dialog-shibboleth-responsive-design-166-01-2015-useful)
