### ISSUE TITLE
"hängende" Anmeldung

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#167]
Im Internet Explorer (9) bleibt die Anmeldung (nach Klick auf Anmelden oben rechts) "hängen" (Rädchen dreht unendlich):
![08-01-2015_ie9_anmeldung](https://cloud.githubusercontent.com/assets/5259782/5661955/7643fe74-9732-11e4-983a-dc9049362ae6.jpg)
Wenn man das hängende Anmeldefenster einfach wegklickt, ist man angemeldet.

Dasselbe passiert im Firefox, wenn man in nicht angemeldetem Zustand aus einer Titelvollanzeige auf das Icon "per E-Mail versenden" klickt, das Anmeldefenster erscheint und man sich anmelden will:
![05-01-2015_anmelden-e-mail-versand](https://cloud.githubusercontent.com/assets/5259782/5610835/cff786c4-94bd-11e4-8260-f5d899821cad.jpg)
Ansonsten scheint die Anmeldung im Firefox (und auch in Safari) zu funktionieren.

Im IE9 klappt die Anmeldung seltsamerweise problemlos, wenn man sich nach Klick auf "zu Merkliste hinzufügen" anmeldet, oder via "Merklisten" oder "Einstellungen" im Menü ganz unten am Bildschirm.
![08-01-2015_ie9-anmeldung-myswissbib](https://cloud.githubusercontent.com/assets/5259782/5661993/03f98720-9733-11e4-87d9-e959aa22c944.jpg)

**Comment by chantalw** [comment]
Noch eine Frage zum Anmeldefenster: Wenn ich in unangemeldetem Zustand in einer Trefferliste bei einem Titel auf "zu Merkliste hinzufügen" klicke, dann kommt nicht - wie nach Klick z.B. auf "E-Mail-Versand" oder bei "zu Merkliste hinzufügen" aus der Titelvollanzeige - das kleine Anmeldefenster, sondern der Anmeldebildschirm:
![05-01-2015_anmeldung-ohne-fenster](https://cloud.githubusercontent.com/assets/5259782/5611025/deaf0a54-94c0-11e4-9d3d-aad88668835c.jpg)
Warum? Und warum kann man das kleine Anmeldefenster nicht mehr wie in der aktuellen Oberfläche auf dem Bildschirm herumschieben? Wegen RD? Wäre auf dem Desktoprechner trotzdem praktisch...

**Comment by guenterh** [comment]
mit diesem
892e0ceee82e900a7da03b15903f5113b9aa368b
commit behoben

**Comment by witzigs** [comment]
@guenterh 
Ich öffne dieses Issue wieder, da die Anmeldung auf IE8 und IE9 weiterhin hängt.

**Comment by chantalw** [comment]
@guenterh @witzigs 
Ich schliesse hier wieder, das funktioniert ja jetzt.
