### ISSUE TITLE
Ansicht Reiter "Reihe/Bände"

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#168]
Der Hierarchiebaum sollte standardmässig aufgeklappt sein, wie in der aktuellen Version. Das sehr kleine Dreieck zum Aufklappen ist ungünstig (v.a. auf den Touchscreens ist das kleine Dreieck schwierig zu treffen mit dem Finger), das Plus/Minus-Symbol wie in Windows scheint einleuchtender (in der aktuellen Version).
![05-01-2015_reihe-bande-1](https://cloud.githubusercontent.com/assets/5259782/5611199/b123acb8-94c3-11e4-81c7-52760896d322.jpg)
![05-01-2015_reihe-bande-2](https://cloud.githubusercontent.com/assets/5259782/5611202/b63db932-94c3-11e4-8c9b-9eb3bf7094bc.jpg)
![05-01-2015_reihe-bande-3](https://cloud.githubusercontent.com/assets/5259782/5611204/b9084754-94c3-11e4-958c-f2358b888392.jpg)

**Comment by chantalw** [comment]
In manchen Fällen (vermutlich bei den Titeln mit Format Buch) funktioniert das automatische Aufklappen des Hierarchiebaums nach Klick entweder auf "Kontext anzeigen" aus der Trefferliste oder auf den Reiter "Reihe/Bände" aus der Vollanzeige.
Z.B. hier: 
http://devbabe.swissbib.ch/Record/3199375/HierarchyTree?hierarchy=25860431X#tabnav
http://devbabe.swissbib.ch/Record/280964188/HierarchyTree?hierarchy=316655147#tabnav
http://devbabe.swissbib.ch/Record/266395333/HierarchyTree#tabnav
http://devbabe.swissbib.ch/Record/115437126/HierarchyTree#tabnav

Bei diesen Beispielen funktioniert es aber NICHT (Format Periodikum):
http://devbabe.swissbib.ch/Record/298845881/HierarchyTree#tabnav
http://devbabe.swissbib.ch/Record/262663813/HierarchyTree#tabnav
http://devbabe.swissbib.ch/Record/264185668/HierarchyTree#tabnav
http://devbabe.swissbib.ch/Record/261792679/HierarchyTree#tabnav
http://devbabe.swissbib.ch/Record/296886742/HierarchyTree#tabnav

**Comment by oschihin** [comment]
siehe auch #224
