### ISSUE TITLE
Holdinganzeige bei ZS oder Artikel lädt nicht (Reiter Exemplare)

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#169]
Bsp.
http://devbabe.swissbib.ch/Record/118702629?expandlib=C001#holding-institution-IDSBB-C001 
http://devbabe.swissbib.ch/Record/125725361
http://devbabe.swissbib.ch/Record/267265417
http://devbabe.swissbib.ch/Record/298811138
http://devbabe.swissbib.ch/Record/260539066

**Comment by ToVie** [comment]
Die Beispiele basieren auf unterschiedlichen Daten. Grundsätzlich sehe ich zwei Typen solche mit "korrektem" 852 und solche mit generischem 852.

Generisches 852 meint, dass swissbib ein 852 erstellt und mit einem entsprechenden Code - für IDSBB ist dies C001 - ergänzt:
* http://devbabe.swissbib.ch/Record/298811138
* http://devbabe.swissbib.ch/Record/118702629?expandlib=C001#holding-institution-IDSBB-C001 

Korrektes 852 meint - offensichtlich ist alles in Ordnung, mindestens aus der Sicht von swissbib. Dies betrifft die Sätze:
* http://baselbern.swissbib.ch/Record/125725361
* http://baselbern.swissbib.ch/Record/267265417
* http://baselbern.swissbib.ch/Record/260539066

Ich nehme an, dass sich zwischen sbvf2 und vufind etwas bei der Auswertung von Holdings geändert haben muss, da ja beide Fälle fehlschlagen. Dies betrifft aber nur die Konfiguration mit Aleph-Treiber.

**Comment by oschihin** [comment]
@witzigs hatte das eigentlich gelöst (da213936beaf4c919264c173f85207381586c192), aber devbabe ist auf einem alten Codestand, soweit ich sehe

**Comment by witzigs** [comment]
Nach Aktualisierung von devbabe funktioniert die Holding-Anzeige bei allen Beispielen.
