### ISSUE TITLE
Checkboxen bei Facette (Tab2)

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#171]
Problem
---
Die Checkboxen der drei ersten Facetteneinträge im Tab "Artikel & mehr" sind im Design aus dem Bereich gerutscht. Beispiel:
http://devbabe.swissbib.ch/Summon/Search?lookfor=meier&type=AllFields

Lösung
---
* Die Checkboxen müssen wieder auf einer Linie mit den folgenden Facettenboxen stehen

**Comment by chantalw** [comment]
@oschihin Was ist hier meine Aufgabe?

**Comment by billyjones** [comment]
Die Checkboxen der drei ersten Facetteneinträge im Tab "Artikel & mehr" sind wieder in ihrem Bereich.
Gelöst mit 3675bced9869b37207036521eb1943b10de6fe80
