### ISSUE TITLE
Erweiterte Suche - Verfeinern nach Erscheinungsjahr

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#172]
Anstelle des Feldes unterhalb der Eingabefelder "von - bis" sollte wohl der Slider sein? Oder was bedeutet das Feld? Entfernen, wenn bedeutungslos.
![05-01-2015_erscheinungsjahr](https://cloud.githubusercontent.com/assets/5259782/5614782/dba4d864-94f4-11e4-8c1c-d3fb7bdce5f1.jpg)

**Comment by witzigs** [comment]
Ja, da sollte der Slider sein. Siehe #118.
