### ISSUE TITLE
Suche verfeinern: gängigste Sprachen und zusammengefasste Formate

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#173]
Bitte wie in der aktuellen Oberfläche die vier gängigsten Sprachen und die zusammengefassten Formate zuoberst anzeigen
![05-01-2015_sprachen-formate](https://cloud.githubusercontent.com/assets/5259782/5614905/f581a0cc-94f5-11e4-9039-44519e6ad5b0.jpg)
![05-01-2015_sprachen-formate_alt](https://cloud.githubusercontent.com/assets/5259782/5614906/f5829fcc-94f5-11e4-9ead-c0e1465ba001.jpg)

**Comment by billyjones** [comment]
@chantalw 
gelöst mit commit
0c73af656cdeb9acf5b266d2e9b40ee9e7774192
und
92259aa352bb903536e16ab75c134eb1ede5380d

Viele Grüsse,
Biljana
