### ISSUE TITLE
"Kontext anzeigen" umbenennen?

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#174]
Die neue Funktion ist gut (wenn sie funktioniert, vgl. #168), die Bezeichnung "Kontext anzeigen" aber vielleicht nicht ideal. Wie wäre es konsequenterweise mit "Reihe/Bände" wie beim Reiter in der Vollanzeige? Den Reiter in "Kontext" umbenennen scheint mir weniger günstig.
![05-01-2015_kontext](https://cloud.githubusercontent.com/assets/5259782/5615049/afa272b4-94f7-11e4-8fb4-abc24aa5997d.jpg)

**Comment by oschihin** [comment]
@chantalw @witzigs @guenterh 
Die Hierarchien bzw. Reihe / Bände sollten bald besser daherkommen (siehe #224). Die Umbenennung ist natürlich kein Problem und sicher nötig für einheitliche Beschriftung. Ich frage mich aber, ob wir diese Funktion wirklich in der Trefferliste anbieten sollten, oder ob es nicht eher die Trefferliste überfrachtet. Bei VuFind ist das gedacht für die Anzeige des Kontext von Archivressourcen. Ob wir wirklich Bandaufnahmen hervorheben wollen? Mein Votum also: Die Funktion einfach aus der Trefferliste entfernen. Was meint ihr?

**Comment by chantalw** [comment]
@oschihin @witzigs @guenterh 
Von mir aus braucht es "Kontext anzeigen" nicht unbedingt in der Trefferliste. Ich werde aber noch die Meinung der AG dazu erfragen.

**Comment by chantalw** [comment]
@oschihin @witzigs @guenterh 
Die AG ist mehrheitlich der Ansicht, dass man "Kontext anzeigen" aus der Trefferliste entfernen könnte. Einziger Vorbehalt: meine Bemerkung oben zur Bestellmöglichkeit von Reihenbänden auf Smartphones.
