### ISSUE TITLE
Trefferliste Design: Favoriten-Herz auf gleicher Linie mit "Bibliothek"

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#175]
Das Herz wird unterhalb von "Bibliotheken" angeführt, sobald unter den besitzenden Bibliotheken mind. eine ist, die ich als Favorit definiert habe. Vorschlag: Das Herz auf dieselbe Linie mit "Bibliotheken" verschieben (vgl. Screenshot).
Ausserdem: bei "zu Merkliste hinzufügen" auf der zweiten Zeile unbedingt den Einzug einhalten, sieht so sehr unschön aus
![05-01-2015_favoriten-herz](https://cloud.githubusercontent.com/assets/5259782/5615204/45b04e88-94f9-11e4-87fd-40af4cd70bee.jpg)

**Comment by witzigs** [comment]
Mit d7e0ea87d09e7fc8284bd340615f89032c7df82d wird das Herz statt des Instituts-Icon angezeigt, sobald eine Favoritenbibliothek den Treffer im Bestand hat.
