### ISSUE TITLE
Facette Erscheinungsjahr: Defaulteinstellung fehlt

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#176]
## Problem
Beim Eingrenzen nach Erscheinungsdatum gibt es in der aktuellen Oberfläche die Voreinstellung "von ... bis ...". Im neuen responsive Design fehlt dies, man muss das „-bis heute“ manuell eingeben. Dies bedeutet zusätzlicher Aufwand für die Benutzer und Risiko, dass Treffer verfehlt werden (User gibt tendendziell -2015 ein, doch tatsächlich wird es bald schon einige Literatur mit Erscheinungsjahr 2016 geben > User verliert also das Aktuellste und hat erst noch mehr Arbeit.)

### Neue Oberfläche
![05-01-2015_facette-jahr](https://cloud.githubusercontent.com/assets/5259782/5615777/ba81be86-94fe-11e4-9021-691487d9d956.jpg)

### Bisherige Oberfläche
![05-01-2015_facette-jahr_alt](https://cloud.githubusercontent.com/assets/5259782/5615776/ba7fb5a0-94fe-11e4-9161-0825129e0a50.jpg)

## Task
* Standardwerte erscheinen in beiden Boxen der Oberfläche
 * Werte: 1450 - 2016
 * Konfiguration via config.ini ermöglichen

**Comment by adchsnowflake** [comment]
@oschihin 
Würde es sich hier evtl. anbieten, den Wert für "bis" automatisch auf das aktuelle Jahr zu setzen?
Damit würde die Konfiguration für "bis" entfallen und müsste nicht jedes Jahr neu definiert werden.

**Comment by maechler** [comment]
Habe ich implementiert und getestet in diesem Feature: https://github.com/swissbib/vufind/commits/feature/%23176_range_facets

Ich dachte ich überlasse es euch, ob ihr das noch in den Livegang reinnehmen wollt oder nicht. Man sollte den Branch ohne Konflikte mergen können. Auf die Konfiguration in der config.ini habe ich verzichtet, da VuFind den Minimalwert direkt im Template setzt und ich nicht denke, dass dieser Wert oft ändert.

**Comment by guenterh** [comment]
durch Markus erledigt
