### ISSUE TITLE
Record Driver: Problem mit Thumbnailanzeige

### ISSUE THREAD

**Issue by ToVie** [swissbib/vufind#178]
Beschreibung
---
Es besteht bei der Anzeige von Thumbnails ein Problem, das mit der Jahreszahl zusammenzuhängen scheint. Ich habe es v.a. bei der Quelle Posters (CCSA) festgestellt, die über die Funktion "getThumbnail_856_1()" eingebunden wird.

Es wird keine Vorschau angezeigt, wenn die Jahreszahl in __260 $c__* vollständig ist aber von eckigen Klammern eingeschlossen wird. Das Phänomen tritt sowohl bei sbvf2 als auch bei swissbib/vufind auf.
Offensichtlich wird in diesem Fall die Funktionen "getThumbnail_856_1()" und   "getThumbnail_956_1()" in  "getThumbnail($size = 'small')" gar nicht mehr ausgeführt. An der fehlenden ISBN kann das aber nicht liegen, da diese bei allen geprüften per Definition fehlen muss (Bilder und Poster).

Beispiele
---
 "getThumbnail_856_1()"  in swissbib/vufind: https://test.swissbib.ch/Record/071655786
 "getThumbnail_856_1()"  in swissbib/sbvf2: https://www.swissbib.ch/Record/071655786
 "getThumbnail_956_1()"  in swissbib/vufind: https://test.swissbib.ch/Record/125862458
 "getThumbnail_956_1()"  in swissbib/sbvf2: https://www.swissbib.ch/Record/125862458

swissbib/sbvf2: https://www.swissbib.ch/Search/Results?lookfor=stop+aids+sida&type=AllFields&sort=publishDateSort+asc&limit=100&page=5&filter[]=union%3A%22CCSA%22
swissbib/vufind: https://test.swissbib.ch/Search/Results?lookfor=stop+aids+sida&type=AllFields&sort=publishDateSort+asc&limit=100&page=5&filter[]=union%3A%22CCSA%22

___
__*__ Leider kann mann das nur in der Feldansicht verifizieren, da die Jahreszahl für die Anzeige aus Feld 008 stammt.

**Comment by oschihin** [comment]
@ToVie sieht für mich gut aus, auf sbvf2 zieh ich das ev. nach, wenn du die Lösung auf test.swissbib gut findest. Der Letzte schliesse hier

**Comment by ToVie** [comment]
Scheint mir in Ordnung allerdings bin ich drauf gekommen, wo das Problem bei #108 liegt
