### ISSUE TITLE
Tab Reihe/Bände

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#179]
Die Probleme treten lokal auf, auf devbabe ist alles ok. D.h. Zusammenhang mit letztem Merge von VF core?

1. Wenn bei der Vollanzeige als erster Tab Reihe/Bände aufgerufen wird (aus Trefferliste über Kontext anzeigen oder bei Anwählen eines Bandes über den Baum), können die Inhalte der anderen Tabs nicht aufgerufen werden.

2. Die Bände im Hierarchy Tree werden anders sortiert, Beispiel: http://devbabe.swissbib.ch/Record/092753469/HierarchyTree?hierarchy=092753469#tabnav

**Comment by guenterh** [comment]
@witzigs 
Das Problem tritt ebenfalls auf, wenn man im Hierarchietab zwischen den einzelnen items wechselt und nach einem Wechsel (der geänderte Kontext wird in der Vollansicht angezeigt) den Tab wechseln möchte.
Ich schaue es mir an

**Comment by guenterh** [comment]
Das Problem:
Beim rendering des content für den Hierarchiebaum werden ungültige links für den Wechsel der Tabs generiert
http://localhost/vfrd/Record/019353766//AjaxTab
anstelle von
http://localhost/vfrd/Record/019353766/AjaxTab
erzeugt eine HTTP 404 response

Muss noch schauen wo und warum das hineingekommen ist.

**Comment by guenterh** [comment]
sollte nach Berücksichtigung dieses mails

*********
Hi Chris
with
https://github.com/swissbib/vufind/commit/48f38e09a0ffa2405b88e418d6895f980d6bb178
you introduced a method to build the query for an AjaxRequest
if(urlroot[0].substring(-1) != '/') {
 urlroot[0] += '/';
 }

This doesn't work because produces double slashes in the context of hierarchies.
Could you replace
urlroot[0].substring(-1)
with
either
urlroot[urlroot.length -1];
or
urlroot.slice(-1);
Thanks! I think not worth a pull request.
Günter 

*****

in VF2 core behoben sein

**Comment by guenterh** [comment]
mit 
https://github.com/swissbib/vufind/commit/bd4f967a17e003a3c841faf97a63018efedebd53
behoben
auf test.swissbib.ch getestet

**Comment by guenterh** [comment]
@witzigs 
Hallo Silvia,
ich eröffne den issue wieder. Werde mir den Kontext mit ein klein wenig Ruge ansehen und dann wohl einen formalen PullRequest absetzen - auch wenn es nur wenige Zeilen Code sind. Dann ist die Chance grösser, dass die Funktion eine bessere Qualität erhält.

Grüsse, Günter

**Comment by guenterh** [comment]
Das Probem der Tabs ohne Inhalt sollte mit diesem
892e0ceee82e900a7da03b15903f5113b9aa368b
commit behoben sein.
Nach merge mit letztem Stand VF2
5f3126a88d525ef5980605797519781f6260b74c
lokal für grün und orange sowie auf test.swissbib.ch getestet. Keine Fehler mehr aufgefallen

Bemerkung:
Ich bin mit Implementierung (wie es jetzt vom VF2 core gemacht wurde) nicht sehr glücklich.

  if(urlroot == "null/") {
    return true;
  }

Die condition macht keinen Sinn. (ist in meinem Augen falsch).
Wenn ich auf null prüfe (kein match beim vorhergehenen regex), müsste die Abfrage sein
if(urlroot == null)
oder
if(urlroot === null)

null ist ein eigenständiges Objekt in JavaScript.
Chris Halberg hat dies wohl so gemacht (machen müssen), weil er implicit vorher Strings verknüpft.

Ok, das ist jetzt so. Ich gehe jedoch davon aus, dass ein match eigentlich immer stattfinden müsste.

Für die falsche Sortierreihenfolge bei den Bänden siehe den eigenständigen issue
https://github.com/swissbib/vufind/issues/184
