### ISSUE TITLE
Keine Treffer in Tab 1: Anzeigetext vervollständigen

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#180]
Aktuell wird bei 0 Treffern in Tab 1 dieser Text angezeigt:
![08-01-2015_keine-treffer-alt](https://cloud.githubusercontent.com/assets/5259782/5659810/c6e7ec60-9718-11e4-97db-603545646d05.jpg)
Auf der neuen Oberfläche müsste dies noch ergänzt werden. Den neuen (VUFind?) Hinweis auf die Wildcard-Möglichkeit finde ich nicht schlecht, den könnte man auch belassen. Wichtig ist aber der Hinweis/Link, um die gleiche Suche in Tab 2 abzusetzen. Diesen müsste man im Vergleich zur aktuellen Oberfläche möglichst noch besser hervortreten lassen (ev. fett, grössere Schrift o.ä.).
Zudem wirkt der leere graue Balken auf der rechten Seite hier etwas komisch.
![08-01-2015_keine-treffer-tab1](https://cloud.githubusercontent.com/assets/5259782/5659815/de9e67ee-9718-11e4-9e7f-e46040c27652.jpg)

**Comment by guenterh** [comment]
Anstatt Textänderung sollten wir die Funktionalität verbessern 
(s. https://github.com/swissbib/vufind/issues/115)

Ich versuche mich, so rasch wie möglich, darum zu kümmern. 
Muss mir dazu auch noch die aktuellen Anpassungen im branch 
https://github.com/vufind-org/vufind/tree/spell-recommend
von VF2 core ansehen. Es macht keinen Sinn, unsere Erweiterungen zu implementieren ohne auf die Entwicklung in VF2 core zu achten.

**Comment by chantalw** [comment]
Auch Tab 2 beachten:
![15-01-2015_tab2-otreffer](https://cloud.githubusercontent.com/assets/5259782/5755315/57ad0a52-9ca3-11e4-877e-60b8491eeeb1.jpg)

**Comment by guenterh** [comment]
@chantalw @witzigs 

Hallo Chantal und Silvia
- Mit c7e7f2174fa231644665b2f0c29f98c8e9a038fc habe ich die Suggestions bei 0 Treffern (für Suchen in unserem eigenen Index) so angepasst, dass 'nie mehr' Vorschläge kommen sollten, die wiederum zu 0 Treffern führen. Dieses Verhalten ist im aktuellen Zustand schon geradezu peinlich...

- Neu sollte es nun auch einfacher sein, den content (Hinweise) zu 0 Treffern leichter anzupassen. Bisher wurden die HTML Strukturen von VuFind fix in einem ViewHelper codiert, was in meinen Augen sehr unschön ist. 
https://github.com/swissbib/vufind/blob/development/themes/sbvfrd/templates/search/spellingSuggestions.phtml

- die Summon Suggestions beeinflusse ich nicht. So wie ich das gesehen habe, sind die Ergebnisse zumindest so weit brauchbar, dass keine Vorschläge mit 0 Treffern geliefert werden. Das ist schon mal ok. Im oben genannten template werden die targets für unseren INdex und Summon (bzw. andere von VF2 gelieferten targets unterschieden). Das sollte keine Konflikte geben.

- die Funktion ist auf jeden Fall weiter verbesserungswürdig. Sowohl auf der Seite der Suchmaschine (solrconfig.xml) als auch auf Seite der Applikation (wie steuert man die Funktionalität an bzw. wertet die Ergebnisse aus). Hier könnten wir gemeinsam daran arbeiten.
Silvia: wir können uns dazu mal zusammensetzen?

Günter

**Comment by mschwendener** [comment]
Null Treffer Basel Bern, beide Tabs: 
"Siehe auch
Hilfe und FAQ" 

FAQ im Moment nicht verlinkt, könnte auf http://baselbern.swissbib.ch/HelpPage/Faq linken.
 
(Und der Link hinter "Hilfe" vielleicht direkt auf http://baselbern.swissbib.ch/HelpPage/Search anstatt http://baselbern.swissbib.ch/HelpPage.) 

Und super wäre natürlich, wenn der Suchstring bei "Suche wiederholen in" mitgegeben würde.
