### ISSUE TITLE
iPad (Safari), Titelvollanzeige: nach Klick auf Export-Icon Designfehler

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#181]
Wenn ich aufs Icon "exportieren" klicke, fallen die anzuwählenden Exportformate aus dem Bildschirm (Hochformat, Querformat):
![titelvollanzeige-exportieren](https://cloud.githubusercontent.com/assets/5259782/5660424/4bcaae66-9720-11e4-9c77-c8e3d140226e.gif)
![tva-export-quer](https://cloud.githubusercontent.com/assets/5259782/5660425/4bcc09c8-9720-11e4-863b-1d15ee93817b.gif)

**Comment by witzigs** [comment]
Hier geschlossen da der gleiche Fehler in Issue #245 erfasst ist.
