### ISSUE TITLE
Trefferliste: Funktion "exportieren" nicht OK

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#182]
iPad (Safari): Wenn ich in einer Trefferliste auf das Icon "exportieren" klicke, erscheint links ein störender Balken, ansonsten passiert nichts:
![ipad_trefferliste-balken](https://cloud.githubusercontent.com/assets/5259782/5660587/2e85db12-9722-11e4-804f-ee18a2d827e9.jpg)
Desktop-PC: Nach Klick aufs Export-Icon für Endnote oder BibTex kommt eine Errormeldung:
![12-01-2015 _tab2-export-bibtex](https://cloud.githubusercontent.com/assets/5259782/5705420/81772768-9a79-11e4-9569-d511a469cc75.jpg)
![12-01-2015_tab2-nach-export-bibtex](https://cloud.githubusercontent.com/assets/5259782/5705421/8183f006-9a79-11e4-9cbe-6655f70d11c7.jpg)

**Comment by oschihin** [comment]
## Probleme
1. In solr (Tab 1) wird nur der jeweils erste Satz exportiert
2. In summon (Tab 2) wird offenbar versucht, solr zu laden, was in obiger Fehlermeldung endet.

**Comment by witzigs** [comment]
Design-Problem ist behoben, da in Viewport xs uns sm auf Ebene Trefferliste kein Export angeboten wird. Siehe #245

**Comment by witzigs** [comment]
Exporte aus Trefferliste nach BibTex und EndNote funktionieren, siehe #232
