### ISSUE TITLE
iPad (Safari): Kein Aufklappmenü nach Touch auf das orange Dreieck

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#183]
![ipad_kein aufklappmenu](https://cloud.githubusercontent.com/assets/5259782/5661693/efe6409c-972e-11e4-8c9b-cea06840c131.jpg)

![ipad_keine facetten](https://cloud.githubusercontent.com/assets/5259782/5661413/b173c634-972b-11e4-8a44-3e09666ca9bb.jpg)

**Comment by witzigs** [comment]
Bei mir funktioniert das Öffnen des Menüs grundsätzlich. Ich habe aber beim Testen auch bemerkt, dass manchmal mehr als ein Versuch notwendig ist.
