### ISSUE TITLE
Sortierung Bände in Hierarchy Tree

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#184]
## Problem
Die Bände im Hierarchy-Tree (Reihe / Bände) werden falsch und anders als in der aktuellen Oberfläche sortiert.

## Beispiele
* http://devbabe.swissbib.ch/Record/092753469/HierarchyTree?hierarchy=092753469#tabnav
* http://devbabe.swissbib.ch/Record/270167994

## Hinweis
* Sortierfunktion: \VuFind\Hierarchy\TreeDataSource\Solr::sortNodes
* in der bisherigen Lösung (sbvf2) wurde anders sortiert, dieselbe Funktion in der alten View: https://github.com/swissbib/sbvf2/blob/master/module/VuFind/src/VuFind/Hierarchy/TreeDataSource/Solr.php#L206

**Comment by oschihin** [comment]
Ich werde mir das anschauen, da ich letztes Mal schon Einiges daran gemacht habe. Auf jeden Fall müssen wir https://github.com/vufind-org/vufind/pull/251 im Auge behalten. Da wird das Cache-Format umgestellt, und sonst wahrscheinlich noch viel Zeugs

**Comment by oschihin** [comment]
Lösung mit 078b903c7bd9caad31915f1c124eba6bb38d8c9a

**Comment by guenterh** [comment]
@witzigs 
Hallo Silivia
ich habe die Sortfunktion von Biljana ersetzt. Kannst Du Dir die Sortierung bitte nochmals ansehen?
(test.swissbib.ch)
Ausprobiert habe ich die zwei Beipiele oben und Aufnahmen mit der Suche
Handbuch der Orientalistik

Die Anpassung habe ich noch nicht commited. Wenn ich von Dir ein positives feedback erhalte passiert dies (so dass Du dies auch nach devbabe übertragen kannst)

Danke und Grüsse

Günter

**Comment by witzigs** [comment]
Hallo Günter

Ich habe mir einige Beispiele angesehen - die Sortierung sieht überall gut aus.

Liebe Grüsse
Silvia


________________________________
Von: Guenter Hipler [notifications@github.com]
Gesendet: Freitag, 20. März 2015 14:31
An: swissbib/vufind
Cc: Silvia Witzig
Betreff: Re: [vufind] Sortierung Bände in Hierarchy Tree (#184)


@witzigs<https://github.com/witzigs>
Hallo Silivia
ich habe die Sortfunktion von Biljana ersetzt. Kannst Du Dir die Sortierung bitte nochmals ansehen?
(test.swissbib.ch)
Ausprobiert habe ich die zwei Beipiele oben und Aufnahmen mit der Suche
Handbuch der Orientalistik

Die Anpassung habe ich noch nicht commited. Wenn ich von Dir ein positives feedback erhalte passiert dies (so dass Du dies auch nach devbabe übertragen kannst)

Danke und Grüsse

Günter

**Comment by guenterh** [comment]
Danke! - Anpassung ist commitet

Günter

**Comment by guenterh** [comment]
mit https://github.com/swissbib/vufind/commit/552536001fdf4347d488704aa5b632af8c4016e7 abgeschlossen
