### ISSUE TITLE
Einblendetext Tab 2

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#185]
Der Einblendetext in Tab 2 ist da, allerdings erscheint er auch innerhalb des Uninetzes...
Vom Layout her bitte noch den Titel "Zugangseinschränkungen" fett hervorheben (wie oben "Andere Suchmöglichkeiten")
![12-01-2015_tab-2-einblendetext](https://cloud.githubusercontent.com/assets/5259782/5700216/f5566062-9a39-11e4-8c89-b516959098b9.jpg)

**Comment by oschihin** [comment]
siehe #63 (und für die Facette #171) bitte Issues nur einmal und mit nur einem Thema erfassen, hier sind drei unterschiedliche Bugs bzw. Design-Themen genannt
