### ISSUE TITLE
Merkliste bearbeiten/erstellen (Design)

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#186]
Beim Bearbeiten einer Merkliste wird das Design verzerrt (auf Desktop-PC ok). 
iPad Quer- und Hochformat:
![ipad_merkliste-bearbeiten](https://cloud.githubusercontent.com/assets/5259782/5700258/690b2672-9a3b-11e4-9754-2ac8fc34692a.jpg)
![ipad_ml-bearbeiten-hochformat](https://cloud.githubusercontent.com/assets/5259782/5700259/690e138c-9a3b-11e4-850c-1ea2e03234ef.jpg)

**Comment by witzigs** [comment]
Die genannten Punkte treten bei "Merkliste erstellen" und "Merkliste bearbeiten" auf.
xs: Buttons werden abgeschnitten (vgl. #235)
sm und md (Seiten-Ansicht) sowie sm, md und lg (Lightbox): Text "Zugangseinschränkungen" überschneidet sich mit Buttons und Labels

**Comment by witzigs** [comment]
tritt aktuell nicht mehr auf
