### ISSUE TITLE
iPad (Safari): Tab 2 Facetten (Design)

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#187]
Verzerrtes Design, die Quadrate zum Anhaken fehlen:
![ipad_tab-2-verfeinern](https://cloud.githubusercontent.com/assets/5259782/5700338/a955cc22-9a3c-11e4-8424-ab82b28627f2.jpg)

**Comment by witzigs** [comment]
Sollte durch Lösen von #171 und #126 gelöst werden.
