### ISSUE TITLE
Tablets/Smartphones: kleines x zum bequemen Löschen von Text im Suchschlitz

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#189]
Wünschbar für Tablet/Smartphone-Nutzung: ein kleines „x“, mit dem ich Sucheingaben bequem löschen kann im Suchschlitz

**Comment by chantalw** [comment]
@witzigs Falls das mit nicht viel Aufwand umzusetzen wäre würde ich dem aus Sicht der mobilen Geräte doch ein bisschen mehr Nachdruck als "wishful" verleihen wollen... Aber wenn aufwändig, dann steht es hinten an, ist schon klar.

**Comment by chantalw** [comment]
Gilt nicht nur für Suchschlitz, sondern eigentlich für alle Eingabefelder.

**Comment by maechler** [comment]
Wird im Rahmen dieses Issues implementiert: #376
