### ISSUE TITLE
Titelvollanzeige (Firefox): Exemplarinfos einzelner Bibliotheken lassen sich nicht zuklappen

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#191]
Im Firefox: Wurden die Exemplarinfos einer Bibliothek einmal aufgeklappt, kann man sie mit Klick auf den Bibliotheksnamen nicht mehr schliessen wie in der aktuellen Oberfläche. Dasselbe mit den "Oberüberschriften" Region Basel, Region Bern oder Favoriten. Ist das absichtlich so? 
Bsp. http://devbabe.swissbib.ch/Record/268228388 
http://devbabe.swissbib.ch/Record/316997676 oder beliebige weitere
![12-01-2015_exemplarinfos-schliessen](https://cloud.githubusercontent.com/assets/5259782/5701814/0b7f8050-9a51-11e4-8a63-5b6654c406e7.jpg)

**Comment by oschihin** [comment]
sollte mit #278 gelöst werden
