### ISSUE TITLE
Tab 2 Titelvollanzeige: Volltextlinks prominenter

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#192]
Die Verlinkung der Zeitschrift bzw. Anzeige weiterer Artikel daraus kann zwar bei Recherchen u.U. durchaus nützlich sein. Es scheint mir jetzt aber für die User deutlich weniger klar zu sein, welcher Link zum Volltext dieses Artikels führt. In der aktuellen Oberfläche ist die Zeitschrift nicht verlinkt und die Volltextlinks im Tab Beschreibung sind prominenter dargestellt.
Vorschlag: Wäre es möglich, die Links zum Volltext (get it, SFX) oben bei der bibliographischen Info anzuzeigen (wie auch in Tab 1) und die (Zusatz)Info zur Zeitschrift unten im Reiter Beschreibung?
![12-01-2015_tab-2-volltextlinks](https://cloud.githubusercontent.com/assets/5259782/5701951/6d19e402-9a53-11e4-9951-3314cd86530c.jpg)
![12-01-2015_tab-2-volltextlinks-alt](https://cloud.githubusercontent.com/assets/5259782/5701952/6d1c8108-9a53-11e4-9399-22451ee6a224.jpg)

**Comment by witzigs** [comment]
Anpassung mit 0e09b9fbf4a2ddb5657a46a61c8bc45452240d33
