### ISSUE TITLE
Vollanzeige: grauer Facettenbalken wenn keine Facetten vorhanden

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#193]
Wenn keine Facetten zur Auswahl stehen ist der graue Balken trotzdem da und irritiert:
![12-01-2015_facettenbalken](https://cloud.githubusercontent.com/assets/5259782/5702195/dfdfe7c2-9a56-11e4-91aa-efffc3cd824b.jpg)
Ist in der aktuellen Oberfläche unauffälliger:
![12-01-2015_facettenbalken-alt](https://cloud.githubusercontent.com/assets/5259782/5702220/42fa19e0-9a57-11e4-920a-9e6ab21eee1a.jpg)

**Comment by oschihin** [comment]
@chantalw @witzigs ich finde keine Beispiele mehr in summon, da wir offenbar auch die Suche nach Zeitschriftentiteln anbieten (siehe das Mini-Problem dazu in #254)

**Comment by witzigs** [comment]
Beispiel: http://devbabe.swissbib.ch/Record/277767687
