### ISSUE TITLE
Breadcrumb-Pfad in Trefferliste und Titelvollanzeige

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#194]
Die Breadcrumb-Navigation scheint unlogisch und unpraktisch. 
In der Trefferliste ist das Angezeigte zwar einleuchtend: Suche: Suchbegriff
Aber dort ist es ja nur eine Information, keine Navigationsmöglichkeit. 
![12-01-2015_trefferliste-breadcrumb](https://cloud.githubusercontent.com/assets/5259782/5704417/61283f0e-9a71-11e4-99ae-13c0b83a8c17.jpg)
Beim Breadcrumb-Pfad, wie er in der Titelvollanzeige angezeigt wird, fehlt hingegen die hier wichtige Information zur abgesetzten Suchanfrage. Stattdessen steht der Titel des Werks, den man ja sowieso in der Vollanzeige vor sich sieht. Darauf klicken bringt nichts.
![12-01-2015_titelvollanzeige-breadcrumb](https://cloud.githubusercontent.com/assets/5259782/5704445/c93aa186-9a71-11e4-9480-51d700ce2160.jpg)
Das letzte Pfadelement (Reiterangabe) ist m.E. nicht nötig, man sieht ja die Reiter vor sich und kann dort vom einen zum anderen wechseln. Wichtiger wäre, dass das erste Pfadelement (zurzeit einfach bezeichnet mit "Suche") auch in der Titelvollanzeige die Info zu den verwendeten Suchbegriffen enthalten würde: "Ihre Suche: xy", so ähnlich wie in der aktuellen Oberfläche das Element im Screenshot. 
![12-01-2015_ihre-suche-alt](https://cloud.githubusercontent.com/assets/5259782/5704602/6df5bc78-9a73-11e4-9d53-b88aad7d51cb.jpg)
Noch eine Gestaltungs-Idee aus den Tests: Nur die verwendeten Suchbegriffe im Breadcrumb-Pfad fett darstellen, den Pfad sonst nicht fett:
![breadcrumb_09-02-2015](https://cloud.githubusercontent.com/assets/5259782/6108666/4d0ee666-b075-11e4-8f84-c1c9027a6a63.jpg)

Wenn das nicht möglich ist, könnte man anstelle von "Suche" besser "Trefferliste" oder "Suchergebnisse" oder "meine Suche" verwenden.

**Comment by witzigs** [comment]
Eine Änderung bei den Breadcrumbs ist schwierig: Die angezeigten Breadcrumbs werden in den einzelnen Templates aufgebaut. Davon betroffen sind auch einige Templates, die wir direkt aus VuFind verwenden. Wir müssten diese Templates nur für diese Anpassungen bei uns führen, worauf ich verzichten möchte.

**Comment by chantalw** [comment]
@witzigs: Könnte ev. eine Änderung in die erwünschte Richtung bei VUFind angeregt werden?
