### ISSUE TITLE
Merkliste: Funktionsicons?

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#195]
Warum kommen bei den Merklistenfunktionen (E-Mail, Löschen, Export, Drucken) nicht die sonst verwendeten Icons (siehe Screenshots) zur Anwendung?
![12-01-2015_ml-funktionen](https://cloud.githubusercontent.com/assets/5259782/5705175/7c552afc-9a77-11e4-9e52-1686a1c22812.jpg)
![12-01-2015_funktionsicons](https://cloud.githubusercontent.com/assets/5259782/5705265/4abb2a0e-9a78-11e4-8467-36909e96908b.jpg)
![12-01-2015_icon-loschenjpg](https://cloud.githubusercontent.com/assets/5259782/5705264/4ab94360-9a78-11e4-87b6-9a6a804248fb.jpg)

**Comment by oschihin** [comment]
Es handelt sich um ein Template aus dem Core, das wir vorderhand nicht anpassen wollen.
