### ISSUE TITLE
Titelvollanzeige: DOI verlinken?

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#196]
Wäre es möglich, wo ein DOI vorhanden ist, diesen zu verlinken?
![12-01-2015_vollanzeige-doi](https://cloud.githubusercontent.com/assets/5259782/5705830/57178dac-9a7c-11e4-8018-7930b254de2d.jpg)

**Comment by oschihin** [comment]
@chantalw 
Das ist einfach. Aber dann haben wir Volltextlinks an zwei Orten. Ist das sinnvoll?

**Comment by chantalw** [comment]
Was spricht dagegen? Der Benutzer hat zwei Möglichkeiten, zum Volltext zu gelangen, und kann den wählen, der für ihn sinnvoller ist.
