### ISSUE TITLE
Anzeige Ausleihen

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#198]
Bei der Anzeige der ausgeliehenen Medien ist mit dem Verzicht auf die Tabelle einiges an Übersichtlichkeit verloren gegangen (auch bei den Reservationen, dort dünkt es mich aber weniger schlimm, weil man in der Regel weniger hat). Ich sehe aber, dass diese Ansicht auf den kleineren Bildschirmen von Vorteil ist. 
Vielleicht würde es schon etwas bringen, wenn der Buchtitel besser hervortreten würde?
![12-01-2015_ausleihen](https://cloud.githubusercontent.com/assets/5259782/5706301/e3bec768-9a7f-11e4-8147-66d94c4e4a08.jpg)
![12-01-2015_ausleihen-alt](https://cloud.githubusercontent.com/assets/5259782/5706300/e3b9c6e6-9a7f-11e4-98f0-da1813480e7a.jpg)

**Comment by witzigs** [comment]
@chantalw 
Ich schliesse hier - die Kontoseiten sind von der AG aus ja soweit ok.
