### ISSUE TITLE
RSS-Feed funktioniert nicht immer

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#202]
Desktop-PC in Citrix, Firefox, RSS-Feed in Outlook abonnieren:
Einfache Suchabfragen in Tab 1: RSS abonnieren funktioniert in der Regel, es wird bei verschiedenen Testsuchanfragen jeweils eine unterschiedliche Anzahl Treffer aus der Trefferliste im Feed angezeigt (die ersten 50, 55, 118 etc. in der Trefferliste).
Mit Facetten (z.B. Verfasser) eingeschränkte Suchen in Tab 1: Das Abonnieren scheint zu funktionieren, aber es werden im Feed keine Treffer aus der Trefferliste angezeigt.
In Tab 2 passiert nichts nach Klick auf das RSS-Symbol

**Comment by chantalw** [comment]
In Chrome kommt nach Klick aufs RSS-Icon nur XML-Text:
![12-02-2015_rss-chrome](https://cloud.githubusercontent.com/assets/5259782/6168826/ec74952a-b2c8-11e4-829e-9101127395db.jpg)

**Comment by oschihin** [comment]
Du musst wahrscheinlich einen Feed-Reader installieren. RSS ist ein 
XML-Format, das du "nackt" siehst ohne entsprechendes Programm.

Am 12.02.2015 um 15:09 schrieb chantalw:
> In Chrome kommt nach Klick aufs RSS-Icon nur XML-Text:
> 12-02-2015_rss-chrome
> <https://cloud.githubusercontent.com/assets/5259782/6168826/ec74952a-b2c8-11e4-829e-9101127395db.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swissbib/vufind/issues/202#issuecomment-74075891>.
>

-- 
UNIVERSITÄT BASEL
Universitätsbibliothek
Oliver Schihin
Projekt swissbib
Schönbeinstrasse 18-20
4056 Basel, Schweiz
Tel.: +41 61 267 13 07
Fax: +41 61 267 31 03
E-Mail oliver.schihin@unibas.ch
URL http://www.swissbib.org/

**Comment by chantalw** [comment]
Ah ja, sorry... Ich werde das mal zu Hause testen, kann hier (Citrix) grad keinen Reader installieren.

**Comment by witzigs** [comment]
@chantalw 
Ich kann die Probleme, die du für Tab 1 geschildert hast nicht (mehr) nachvollziehen.
Der RSS-Feed in Tab 2 funktioniert nun auch, vgl. #250.
In Chrome kann der RSS-Feed mit einem entsprechenden Reader ebenfalls abonniert werden.
Ich schliesse daher dieses Issue, bitte ein neues eröffnen, falls du etwas neues feststellst.

**Comment by ToVie** [comment]
Ich kann das weiterhin bestens nachvollziehen. Wenn es Euch recht ist, würde ich den Issue wieder öffnen und als Frage labeln - und zwar: Kann man das Verhalten eines Browsers in diesem Bereich (mit vertretbarem Aufwand) beeinflussen oder nicht?

**Comment by edelm** [comment]
Bei mir (xubuntu, firefox) stimmt die Anzahl Treffer im RSS und in der Trefferliste auf der Webseite immer überein. Getestet mit und ohne Facetten, und in beiden Tabs (Solr und Summon).

Chromium/Chrome hat by Design kein GUI für RSS. Es gibt jedoch ein offizielles Plugin dafür.

Siehe dazu auch:
https://bugs.chromium.org/p/chromium/issues/detail?id=84
https://chrome.google.com/webstore/detail/rss-subscription-extensio/nlbjncdgjeocebhnmkbbbdekmmmcbfjd
