### ISSUE TITLE
Mailversand Trefferliste: "Kopie an Absender" fehlt

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#203]
Versenden einer Titelvollanzeige: Es erscheint dieses Fenster
![15-01-2015_fenster-versenden-titelvollanzeige](https://cloud.githubusercontent.com/assets/5259782/5756970/38fbbf50-9cb6-11e4-9856-1b2b8ff78152.jpg)
Die Auswahlmöglichkeit "Kopie an Absender" ist gut und wichtig. Anzeigetext: verständlicher wäre "Kopie an Absender schicken"
Versenden einer Trefferliste: Hier fehlt im Versandfenster die Auswahlmöglichkeit "Kopie an Absender". Bitte noch ergänzen. 
![15-01-2015_fenster-versenden-trefferliste](https://cloud.githubusercontent.com/assets/5259782/5756971/38fd8b3c-9cb6-11e4-9691-ecf9f2506e6a.jpg)

**Comment by witzigs** [comment]
Die Funktion "Kopie an Absender" ist in VuFind bei unserer Konfiguration (manuelle Eingabe der An und Von Mail-Adresse) nicht vorgesehen. Es handelte sich um einen Fehler im template für den Mailversand einer Titelvollanzeige (record/email).

Grundsätzlich kann VuFind so konfiguriert werden (config [Mail]), dass die E-Mail Adresse des eingeloggten Benutzers verwendet wird und das Feld Von nicht angezeigt wird, möglich. Mit dieser Konfiguration würde dann auch die Funktion "Kopie an Absender" eingesetzt. Wir werden aber zur Zeit die Konfiguration für swissbib nicht ändern.

Das Senden an mehrere Adressen gleichzeitig ist in VuFind im Moment nicht vorgesehen. Eine Entwicklung wäre möglich. Antwort von Demian auf die entsprechende Frage: 

"VuFind is not currently designed to accept more than one email address at a time – this is in part a security feature to reduce the ability of spammers to abuse VuFind’s email mechanism.
 
However, it would certainly be possible to change this, and it might make sense to add a new configuration setting that allows multiple “to” addresses, perhaps with a limit on the recipient count to maintain some of the security of the “one-at-a-time” approach while offering a bit more flexibility.
 
Adding this feature would require some modifications to the theme (to make the email form validation smarter) and the controllers (to adjust server-side validation and to allow multi-recipient emails to be sent correctly) but I don’t think it would be a huge amount of work."
