### ISSUE TITLE
Merklisten: Mailversand

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#204]
1. Das Versenden einer ganzen Merkliste per Mail funktioniert, man muss vorher "alle auswählen" anhaken. Beim Versandfenster fehlt aber die Auswahlmöglichkeit "Kopie an Absender" (vgl. unten 3.1)
2. Versenden eines einzelnen Titels in einer Merkliste (aus Titelvollanzeige) funktioniert.
3. Versenden ausgewählter Titel aus Merklisten funktioniert ebenfalls, allerdings: 

3.1 fehlt beim Versandfenster die Auswahlmöglichkeit "Kopie an Absender"
![15-01-2015_versenden ausgewahlter titel aus ml](https://cloud.githubusercontent.com/assets/5259782/5757255/e86f942c-9cb9-11e4-9487-689fe26b01ff.jpg)

3.2. stimmt bei der Anzeige für den Empfänger das Design nicht
![15-01-2015_ansicht ausgewahlte versendete titel](https://cloud.githubusercontent.com/assets/5259782/5757196/0f88abb2-9cb9-11e4-836c-3e7ac97a7747.jpg)

**Comment by witzigs** [comment]
neues Issue erstellt für das Design der Liste, die aus dem Mail geöffnet wird: #231
