### ISSUE TITLE
Mailversand: Mailtext wenn "Kopie an Absender" gewählt wurde

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#205]
Wenn man beim Versenden einer Titelvollanzeige per Mail den Haken bei "Kopie an Absender" setzt (vgl. Screenshot), bekommt man als Absender in der Mailkopie den Text: "Diese Mail wurde verschickt von: Absenderadresse (die eigene)". Für den Absender wäre aber die logischere (wichtigere) Information: "Diese Mail wurde verschickt an: Empfängeradresse". 
![15-01-2015_fenster-versenden-titelvollanzeige](https://cloud.githubusercontent.com/assets/5259782/5757394/1f7a0f0a-9cbb-11e4-8627-30ee5ac9e9ad.jpg)

**Comment by witzigs** [comment]
Kopie an Absender ist mit der aktuellen Konfiguration nicht vorgesehen. Die Checkbox wird entfernt, siehe auch #203
