### ISSUE TITLE
Englische Version: nicht alle Übersetzungen da/angezeigt?

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#207]
In der englischen Oberflächenversion ist noch das Meiste deutsch. Übersetzungen noch nicht drin?
Sehe gerade, dass das auch in der aktuellen Oberfläche mangelhaft ist...
![15-01-2015_english-alt](https://cloud.githubusercontent.com/assets/5259782/5759163/fd6fea04-9ccb-11e4-86e6-538623220b31.jpg)

**Comment by witzigs** [comment]
In der neuen Oberfläche ist das ein bug, siehe #91

**Comment by oschihin** [comment]
s.o., andernorts erfasst
