### ISSUE TITLE
My swissbib-Einstellungen werden verzögert wirksam

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#208]
Was ich für mein Konto eingestellt habe (Sprache, Anzahl Treffer pro Seite, Sortierungskriterium) wird "mit einem Klick Verzögerung" wirksam: 
Wenn ich mich ganz zu Beginn oder mitten aus einer Recherchesitzung anmelde, werden die Einstellungen nicht unmittelbar, aber doch nach der ersten Aktion (Suchanfrage, Tabwechsel, Wechsel in die erweiterte Suche, Wechsel auf Titelvollanzeige oder zurück auf Trefferliste etc.) wirksam.

**Comment by guenterh** [comment]
issue ist mit der Entscheidung von Basel / Bern, keine Popupdialoge bei der Anmeldung zu verwenden, obsolet
