### ISSUE TITLE
My swissbib-Einstellungen bei Sprachwechsel

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#209]
Wenn ich in angemeldetem Zustand in eine Oberflächensprache wechsle, die nicht meinen Einstellungen entspricht:
1. wird diese Sprache automatisch als meine neue Einstellung übernommen (was ich nicht erwarte/wünsche)
2. das eingestellte Sortierungskriterium (z.B. neuestes Jahr zuerst) wird in den folgenden Suchen nicht mehr wirksam (sondern Relevanzsortierung)
3. Nach Abmeldung bleiben gewisse in meinem Konto eingestellte Kriterien wirksam (Sortierung, Anzahl Treffer pro Seite - Sprache wechselt interessanterweise auf Deutsch), wenn man im gleichen Tab weiterrecherchiert. Erst nach Tabwechsel werden wieder die Standardeinstellungen wirksam.
4. Nach erneuter Anmeldung wechselt die Sprache gemäss meinen Einstellungen, die anderen Einstellungen (Anzahl Treffer, Sortierungskriterium) werden aber nicht mehr wirksam bzw. erst nach Tabwechsel.

**Comment by guenterh** [comment]
s. https://github.com/swissbib/vufind/releases/tag/26-beta-5
