### ISSUE TITLE
My swissbib-Einstellungen und Suchhistorie

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#210]
Wie in #209 beschrieben, werden meine Einstellungen bezüglich Anzahl Treffer und Sortierungskriterium nach der Anmeldung nicht wirksam, sondern erst nach einem Tabwechsel. Nachdem ich nach Tab 2 und wieder zurück nach Tab 1 gewechselt habe, sind sie (manchmal) wirksam. Wenn ich jetzt eine Suchanfrage aus der Suchhistorie reproduziere, bleibt das eingestellte Sortierungskriterium erhalten, die eingestellte Anzahl Treffer fällt aber auf 20 zurück.

**Comment by guenterh** [comment]
s. https://github.com/swissbib/vufind/releases/tag/26-beta-5
