### ISSUE TITLE
My swissbib-Einstellungen und erweiterte Suche

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#211]
Insgesamt erscheint die Funktionsweise der Einstellungen unberechenbar (vgl. #208, #209, #210). Wenn die im Konto eingestellten Kriterien in einer Trefferliste nach einer einfachen Suche gerade mal wirksam sind, fällt zumindest das Sortierungskriterium nach einer Suchanfrage in der erweiterten Suche wieder auf Relevanz zurück.

**Comment by guenterh** [comment]
s. https://github.com/swissbib/vufind/releases/tag/26-beta-5
