### ISSUE TITLE
Kontomenü

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#213]
Vorschläge zur Verbesserung der Ansicht "Kontomenü" (von oben nach unten):
1. "My swissbib" anstatt "Konto" (wie im Grundmenü am unteren Bildschirmrand)
2. In diesem Auswahlmenü ist "Merklisten" überflüssig, da diese unten einen eigenen Bereich haben (vgl. #120)
3. Konto IDS BB: Was im Moment "Voreinstellungen" heisst und etwas abgesetzt unterhalb angeführt ist (Adresse ändern, PW ändern) gehört inhaltlich zu "Konto IDS BB" und sollte unter diesem Menü zur Auswahl stehen. 
Auswahlmöglichkeiten "Konto IDS BB" bitte möglichst in dieser Reihenfolge:
Profil, Adresse ändern, Passwort ändern, Ausleihen, Reservationen, Kopienbestellungen, Gebühren, Buchungen. Wobei man nach Klick auf "Konto" wie bisher direkt in die Ansicht "Ausleihen" geleitet werden sollte (vgl. #156)
Zudem ein Erweiterungsvorschlag unter #206
4. Im Menü "Merklisten" sollte beim ersten Punkt statt erneut "Merklisten" z.B. "Alle Merklisten" oder noch besser "Alle gemerkten Titel" stehen.
![19-01-2015_kontomenu](https://cloud.githubusercontent.com/assets/5259782/5799086/8158e564-9fce-11e4-9b28-03e7f73a8a2a.jpg)

**Comment by witzigs** [comment]
Änderungswünsche mit 79ad779acabd4a2d496b757b191a7592ca21a1c4 umgesetzt.

**Comment by chantalw** [comment]
Vielen Dank, das sieht jetzt viel besser aus!
