### ISSUE TITLE
Anmeldeseite statt Anmeldefenster

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#217]
Beim Anwählen der folgenden Aktionen wird anstelle des Anmeldefensters die Anmeldung als Seite angezeigt:
*In der Exemplaranzeige bei Anmelden
*In der Trefferliste bei Suche speichern und bei Zu Merkliste hinzufügen (aber nicht bei E-Mail senden)
*In der Suchhistorie bei Suche speichern
*In der Suchhistorie und Erweiterten Suche beim Punkt Einstellungen im Menü
*Im Footer bei Merklisten und bei Einstellungen

In der Vollanzeige bei Zu Merkliste hinzufügen und bei E-Mail senden kommt korrekt das Anmeldefenster.

**Comment by guenterh** [comment]
@witzigs @oschihin 

Hallo Silvia und Oliver,

ich habe mir zwei der fünf Punkte angesehen (Exemplaranzeige, Einstellungen in der erweiterten Suche)
Bevor wir etwas machen, sollten wir nochmals darüber diskutieren:
- warum sollen in Orange die Anmeldialoge nun als PopUp erscheinen? Was ist der Mehrwert davon?
Bisher haben wir diese Popupdialoge nicht - was sind die Negativpunkte an der jetzigen Lösung und was gewinnen wir mit den Popups?
- bei einer View mit Shibboleth (einschliesslich Guest account und embeded wayf) ist die Implementierung genau anders herum : Die Anmeldedialoge müssen alle auf einer eigenen page erscheinen. (zumindest für den aktuellen Stand - andere Lösungen müssen erst noch evaluiert und, wenn möglich, implementiert werden). Das heisst: Zumindest für unsere Betaphase werden wir in swissbib green keine Popups haben.
- Grösse der Zahl auf dem Preisschild für die Implementierung, alle Dialoge einheitlich als Popups aufbauen zu können.

Warum erscheinen bei den zwei Punkten die Popups nicht:

- Exemplaranzeige:
Die HTML Struktur zur Anzeige wird dynamisch nachgeladen und die DOM Struktur in die page eingefügt.
Das bedeutet: Der aktuelle event handler zur Anzeige der sog. Lightbox funktionieren nicht:
Datei: themes/boostrap3/js/common.js
  /*
  $('#loginOptions a.modal-link').click(function() {
    return Lightbox.get('MyResearch','UserLogin');
  });
wird der event handler auf diese Weise implementiert feuert er nicht bei dynamischen Elementen:
Alternative:
sog. delegators oder on Methode:
vgl. z.B. http://api.jquery.com/on/
Die erste Variante (von VuFind realisert) ist noch die alte JQuery Art. Möchten wir uns auf VF abstützen, müssten wir mit der Liste erstmal anfangen zu diskutieren. Ich kann vom Schiff auch nicht abschätzen, was denn Nebeneffekte einer Anpassung wären (die Lightbox wird in vielen KOntexten eingesetzt) Ein schneller Weg wäre das nicht.

Variante: sbvfrd/templates/Holdings/holding-actions.phtml
<ul class="holdingActions <?=$listClass?>">

	<script language="JavaScript1.5">

		  $('a.modal-link').on('click', function (e) {
			return Lightbox.get('MyResearch','UserLogin');
		  });

	</script>

   <?php foreach($actions as $key => $action): ?>

		<li id="loginOptions">
			<a  class="modal-link" href="<?=$action['href']?>" <?php if(isset($action['target'])): ?>target="<?=$action['target']?>"<?php endif; ?> title="<?=$this->escapeHtml($action['label'])?>">
				<span><?=$this->escapeHtml($action['label'])?></span>
			</a>
		</li>

   <?php endforeach; ?>

</ul>

Auf diese Weise würde der eventhandler auch it dynamschen code umgehen können. Noch besser wäre hier der Einsatz eines Delegators.

Nachteil: das machen wir nur für Basel / Bern - nicht für green und jusbib.

Wollen wir das?

- Einstellungen in der erweiterten Suche:
Das lässt sich leicht lösen:

            <a class="list-group-item modal-link" href="<?=$this->url('myresearch-settings')?>" title="<?=$this->transEsc('My_Search_Settings')?>"><?=$this->transEsc('My_Search_Settings')?></a>

in themes/sbvfrdmulti/templates/search/advanced/sidebar.phtml
löst das Problem. Hier mag das noch gehen, da es ein eigenes template für basel / Bern gibt.
Bei den von mir nicht angeschauten Punkten wird man entweder eigene templates / view oder eine zusätzliche Konfiguration einführen müssen.

Obwohl ich kein Fürsprechen von immer mehr Konfigurationen bin, wäre das für mich ein möglicher Weg. Bei allen Optionen liesse sich durch Einstellungen festlegen, welche Klassen gesetzt werden. Das sollten wir aber zusammen mit VF2 lösen - und das braucht Zeit. Sicher nicht jetzt. Ich möchte mich nicht festlegen, ob das bis April ginge.

Soviel mal für unsere Diskussion

Günter

**Comment by witzigs** [comment]
nicht mehr relevant, siehe #268
