### ISSUE TITLE
Accessibility issues in swissbib Responsive

### ISSUE THREAD

**Issue by abigger** [swissbib/vufind#218]
Mit meinen Tools zur Analyse einer Webseite auf Zugänglichkeit habe ich ein paar formale Probleme festgestellt, die sich vermutlich leicht beheben liessen:
* Das Textfeld bei er Sucheingabe hat kein Label
* Dasselbe trifft für praktisch alle Textfelder bei der erweiterten Suche zu
* Das Logo Powered by Universität Basel hat keinen ALT-Text
* Im Bereich "Modal" ganz am Ende hat es ein leeres Title-Tag (\<h4\>)
* Trefferanzeige: Hier hat es ein leeres \<label\> vor jedem Treffer in der Liste
* Trefferanzeige: Bei den Thumbnails fehlt jeweils der ALT-Text (das konnte das aktuelle swissbib besser ...)

**Comment by oschihin** [comment]
## Lösungen
* URZ-Logo: 2437cb8981b390c248b9cbf8e8dbbcd62a53f124

**Comment by drummer23** [comment]
-h4 tag habe ich drin gelassen, da er aus vufind template kommt und wir nicht abschätzen können, ob hier noch was kommt. (generiert zurzeit beim entfernen bereits einen javascript error)

-leeres label tag habe ich bereits ins Issue #236 entfernt

**Comment by oschihin** [comment]
@drummer23 
ok, gemergt
