### ISSUE TITLE
Accessibility issues in swissbib traditionell

### ISSUE THREAD

**Issue by abigger** [swissbib/vufind#219]
Hier noch ein paar Accessibility issues im traditionellen swissbib, falls das interessiert:
* Das Bild "Powered by ..." hat keinen ALT-Text
* In der erweiterten Suche fehlen reihenweise Labels bei den Feldern
* In der Trefferliste hat swissbib Basel Bern oben ein leeres \<h1\> - in swissbib grün steht dort die Treffermenge
* In der Vollanzeige fehlt der ALT-Text beim Thumbnail, beim Icon für die Merkliste und beim QR-Code beim Exemplar
* Was ich nicht wirklich checken kann, aber vermute: Das Häklein bei der Availability ist vermutlich für einen Blinden nicht sichtbar (es wird ja per CSS eingesteuert).

**Comment by oschihin** [comment]
@abigger beim alten passen wir nichts mehr an, ich schliesse hier.
