### ISSUE TITLE
Titelvollanzeige (IE): Exemplarinfos einzelner Bibliotheken lassen sich nicht aufklappen

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#220]
Reiter Exemplare: Im Internet Explorer (9) lässt sich die Exemplaranzeige nicht aufklappen.

**Comment by witzigs** [comment]
Gilt auch für IE8. 
Mit IE11 funktionierts.

**Comment by guenterh** [comment]
Das ist etwas trickiger als ich ursprünglich dachte und ich habe noch keine Lösung...

In meinem IE8 bekomme ich keinen Syntax - Fehler. So wie der Aufklappmechanismus im Moment implementiert ist, scheint er von IE8, ohne dass ein Fehler geworfen wird, nicht unterstützt zu werden. Ich muss erstmal sehen, wie die Aufklappmechanismen funktionieren. Evtl. ein Task für snowflake.

**Comment by guenterh** [comment]
@witzigs @chantalw 
Hallo Silvia, Hallo Chantal

habe es nochmals ausprobiert und die JavaScript Dateiein mit ctrl-R  zuerst neu geladen.
Danach konnte ich mir die Exemplare einzelner Bibliotheken auch im IE8 anzeigen lassen
Beispiel:
https://test.swissbib.ch/Record/29123979X

Könnt Ihr das bitte verifizieren?

Viele Grüsse

Günter

**Comment by chantalw** [comment]
@guenterh Das klappt bei mir leider nicht, weder im IE8 noch im IE9.

**Comment by guenterh** [comment]
@chantalw 
Hmh, hast Du die von mir angegebene Ressource auf test.swissbib.ch aufgerufen?
Siehst Du im Browser irgendwo einen Hinweis auf einen JavScript Fehler?

Ansonsten schaue ich mir das mal gemeinsam mit Silvia an.

Viele Grüsse

Günter

**Comment by chantalw** [comment]
@guenterh Ja ich habe deine Beispielressource aufgerufen. Es passiert einfach nichts, wenn ich auf die Bibliotheksnamen in der Liste klicke bzw. im IE8 wird unten rechts am Bildschirmrand in der Leiste die Meldung "Fehler auf der Seite" angezeigt. Beim Drüberfahren über "Zu den Favoriten hinzufügen" kommt in der Leiste unten rechts die Meldung "javascript:void (0)". 
Wenn ich "zu Favoriten hinzufügen" klicke dann funktioniert das erst mal, nach einer Weile rumklicken auf der Seite stürzt sie aber im IE8 regelmässig ab und ich habe einen weissen Bildschirm, bis ich die Seite wieder neu lade.

**Comment by guenterh** [comment]
@chantalw 
Ok, das ist schon mal mehr. Wenn du auf Bibliotheksnamen clickst und rechts unten die Fehlermeldung siehst  - kannst Du dann auf diese Meldung clicken so dass ein Fenster aufgeht. In diesem Fenster sollte dann ein Hinweis sein, an welcher Stelle ein Fehler auftritt. Kannst Du das mal ausprobieren?

Danke und Grüsse

Günter

**Comment by chantalw** [comment]
Aha: 'console' is undefined / Holdings.js / Code: 0 / URI: https://test.swissbib.ch/themes/sbvfrd/js/swissbib/Holdings.js?_=1422550066

**Comment by guenterh** [comment]
@chantalw 
Super! das werde ich morgen ändern - die Hoffnung ist gross, dass es dann besser geht. Scheint, dass die alten Browser, das Objekt console nicht unterstützen. 
Danke Chantal und vorerst mal eine gute Nacht - wenn Du nicht noch sonst etwas vor Mitternacht finden solltest. Danach nehmen die Basler aus Bern nichts mehr entgegen...

Günter

**Comment by chantalw** [comment]
@guenterh ok gute nacht!

**Comment by guenterh** [comment]
@chantalw @witzigs 
Hallo Chantal und Silvia,

könnt Ihr die Exemplaranzeige im IE8 / IE9 auf test.swissbib.ch nochmals ausprobieren. Bitte vorher mit ctrl-R die Dateiein neu laden.

Danke und Grüsse, Günter

**Comment by chantalw** [comment]
@guenterh Im IE9 lassen sich die Exemplarinfos so nun aufklappen (IE8 hab ich im Moment nicht zur Verfügung). Allerdings lassen sich die Infos nicht wieder zuklappen, aber das ist ja auch im Firefox so und vielleicht Absicht? Vgl.  #191

**Comment by guenterh** [comment]
@chantalw @witzigs 
Guten Morgen Chantal - hattest ja eine nicht allzulange Nacht....
Danke für die Info und schön dass das Aufklappen im IE9 nun funktioniert. Ich gehe davon aus, dass dies im IE8 nun auch ok ist - bei mir, auf einem alten WinXP mit IE8 habe ich den Fehler auch nicht. Allerdings habe ich hier gestern noch spezielle Browsereinstellungen zum Debugging gesetzt, so dass bei mir der Fehler schon gestern nicht mehr auftrat.

Zum Zuklappen: ja aktuell ist es so, dass ein Zuklappen nicht implementiert ist. Wir müssen schauen, ob wir das in der ersten Version umsetzen.

Fazit: Ich nehme aus den Skripten (die zum swissbib code gehören), das console Objekt heraus und schliesse diesen issue. Bitte melden wenn erneut Probleme mit alten IEs auftreten.

Grüsse, Günter
