### ISSUE TITLE
Auswahl Anzahl angezeigte Treffer in Trefferliste

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#221]
Ist in der aktuellen Oberfläche auch so, darum einfach "wishful":
In der Trefferliste werden mir 5 bis 100 Treffer pro Seite zur Auswahl angeboten: 
![27-01-2015_einstellung-trefferzahl_trefferliste](https://cloud.githubusercontent.com/assets/5259782/5917162/2ad7d9a0-a61a-11e4-8b49-0b40ac303b56.jpg)
Bei den my swissbib-Einstellungen habe ich 10 bis 100 Treffer pro Seite zur Auswahl:
![27-01-2015_einstellungen-trefferzahl_myswissbib](https://cloud.githubusercontent.com/assets/5259782/5917169/451353f8-a61a-11e4-93f4-be1da6a663fc.jpg)
Kann/sollte das nicht einheitlich sein?

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Auswahl Anzahl angezeigte Treffer in Trefferliste #221 (01/2015-wishful)](https://trello.com/c/XyPCp8kX/96-auswahl-anzahl-angezeigte-treffer-in-trefferliste-221-01-2015-wishful)
