### ISSUE TITLE
Facettenaus-/abwahl analog aktuelle Oberfläche

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#222]
In der aktuellen Oberfläche verschwinden ausgewählte Facetteneigenschaften aus den Auswahlmöglichkeiten der Facette und werden oberhalb angezeigt, wo man sie wieder abwählen kann:
![29-01-2015_facettenauswahl-alt](https://cloud.githubusercontent.com/assets/5259782/5956621/eddcff7a-a7af-11e4-876a-86ac66280160.jpg)

In der neuen Oberfläche bleiben die gewählten Facetteneigenschaften unter den Auswahlmöglichkeiten der Facette und erscheinen mit orangem Hintergrund und OK-Häkchen. Oberhalb werden sie ebenfalls angezeigt bzw. zur Abwahl angeboten:
![29-01-2015_facettenauswahl](https://cloud.githubusercontent.com/assets/5259782/5956646/3e739e1c-a7b0-11e4-9d1b-8a5b6197c00d.jpg)

Sitzung AG swissbib BB 27.1.2015: Die Lösung in der aktuellen Oberfläche wird bevorzugt. Wenn möglich sollten die ausgewählten Facetteneigenschaften auch in der neuen Oberfläche aus den Auswahlmöglichkeiten der Facette verschwinden und nur oberhalb zur Abwahl angeboten werden.

**Comment by witzigs** [comment]
@chantalw 
Mit c90f3bcd3a90955b9cfebfa4aa5e195497bb7054 wurde in VuFind die Möglichkeit des Abwählens einer Facetteneigenschaft durch das Anklicken in der Facette ermöglicht. Ich habe dies mit a150ea0b180779ae08731ed0884a7f2f348863dd für swissbib übernommen.
Ich denke, dass damit das grösste Problem (wirkungsloses Klicken auf die Facette mit Häkchen) gelöst ist und schliesse das Issue daher.
