### ISSUE TITLE
Link Bibliotheksinfo: neues Icon/Bezeichnung und möglichst neue Platzierung

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#223]
Der Link „Bibliotheksinfo“ fehlt in der neuen Oberfläche noch. Die AG schlägt vor, ihn im Reiter Exemplare direkt beim Bibliotheksnamen zu platzieren. Zudem soll er hinter ein „kleines i“-Icon oder „Info“ gelegt werden statt wie bisher hinter das „www“-Icon. 
Bisher:
![29-01-2015_link-bibinfo-alt](https://cloud.githubusercontent.com/assets/5259782/5957482/6d11048a-a7ba-11e4-9a60-3b74c4f9d019.jpg)
Neu gewünscht:
![29-01-2015_link-bibinfo](https://cloud.githubusercontent.com/assets/5259782/5957486/77116bc8-a7ba-11e4-87b4-3222573a8322.jpg)

**Comment by witzigs** [comment]
@chantalw 
Inzwischen weiss ich mehr: Die Bibliotheksinfo muss weiterhin unten beim Exemplar stehen. Grund dafür sind zusammengeführte Zweigstellen, d.h. mehrere Aleph-Librarycodes, die als eine Zweigstelle in swissbib geführt werden. Damit bei diesen zur korrekten Bibliotheksinfo verlinkt werden kann, muss der Link bei den Exemplarangaben stehen.
Ein i-Icon mit Link zur Bibliotheksinfo habe ich mit 3aa6176dcdbed18b9722ccd9b90afdd03bf764fa ergänzt.
