### ISSUE TITLE
Anpassungen JsTree

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#224]
@oschihin @witzigs 

Hallo Silvia und Oliver,

ich habe die Anpassungen gemacht, damit unsere JsTree Klassen mit denen von VF2 core wieder kompatibel sind.
https://github.com/swissbib/vufind/commit/d4104bdda368358e89a8d3698ed0a5501ba92d2e
Lokal wurde bei mir der Baum nun ohne XML Validierungsfehler aufgebaut. Die sourcen sind noch nicht nach test.swissbib.ch verteilt.

Nicht angeschaut habe ich mir evtl. Unterschiede in der Implementierung in von uns überschriebenen Methoden im Vergleich zu VF2 (ich gehe davon aus, dass sich hier Dinge geändert haben). Abgemacht ist, dass Ihr Euch das ansehen werdet

Günter

**Comment by guenterh** [comment]
@oschihin 
Der neue Jstree code ist nun auch für Jusbib Test RD verteilt
http://sb-vf20.swissbib.unibas.ch/justestrd/

Die bestehende Funktionalität scheint auch mit den Jusbib Bäumen zurecht zu kommen. Allerdings sollte man das genauer ansehen.

Günter

**Comment by oschihin** [comment]
## Probleme und offene Fragen
* Darstellung zur aktuellen View ist nicht identisch, es werden nur flache Bäume aufgebaut. Siehe z.B. http://baselbern.swissbib.ch/Record/260877379/ für mehrstufige Hierarchie, derselbe Satz in neuer View zeigt für die zweite Hierarchie nur eine flache Struktur
 * könnte mit 'collections' zusammenhängen
