### ISSUE TITLE
Syntax - Fehler in swissbib template

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#225]
Hallo Silvia,

mit diesem commit
https://github.com/swissbib/vufind/commit/3458f28bd003d878152a9814733a476173d0ec79
habe ich einen kleinen Syntaxfehler herausgenommen, der die Anzeige der Vollansicht verhinderte.
Erstaunlicherweise habe ich das erst beim Deployment von Jusbib gesehen und nicht schon lokal. Scheinbar ist mein Aufriuf nicht über diese Codestelle 'gelaufen'

Ich habe den booleschen Ausdruck mal so geändert, dass es nun keinen Fehler mehr gibt. Allerdings weiss ich nicht, ob meine Änderung jetzt das macht was Du wolltest. Deswegen bitte ich Dich, dies nochmals anzusehen.

Vielen Dank!

Günter

**Comment by witzigs** [comment]
@guenterh 
Danke für die Korrektur, das macht so was es sollte.
