### ISSUE TITLE
Alternativen für Wiki-Mashup

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#226]
Damit Facetten bei der Autorensuche angezeigt werden, verzichten wir (vorerst ?) auf den von VuFind gelieferten Autorencontroller und benutzen die allgemeine Suche mit dem type - Parameter.

Diese Entscheidung liefert uns Facetten, 'raubt' uns zur gleichen Zeit aber auch den Wiki-Mashup in der Resultatliste. Wir sollten nach Möglichkeiten suchen, Mashups mit Wiki-content in Zukunft erstellen zu können.

Beachte bei Lösungen auch:
https://github.com/swissbib/vufind/issues/96

**Comment by guenterh** [comment]
s. auch
https://github.com/swissbib/vufind/issues/113

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Alternativen für Wiki-Mashup #226 (02/2015-useful)](https://trello.com/c/iLQ8SYhO/95-alternativen-fur-wiki-mashup-226-02-2015-useful)

**Comment by sonjakupfi** [comment]
Wird mit Linked gelöst
