### ISSUE TITLE
Titelvollanzeige: Export nach / Import in Zotero

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#227]
Stand am 2.2.2015 (devbabe-Version vom 22.1.) bezüglich Export aus einer Titelvollanzeige nach Zotero: 

Exportieren/importieren durch Anwählen von BibTex oder EndNote als Exportfomat funktioniert grundsätzlich, die grundlegenden Daten werden korrekt nach Zotero übernommen. Die Funktionsweise entspricht dem Stand der aktuellen Oberfläche. 

Allerdings gibt es (auch in der aktuellen Oberfläche) Unterschiede, je nachdem welchen Export man wählt:

Via BibTex: Die Zusammenfassung (Feld 520) fehlt im Vergleich zu Export als EndNote:
![02-02-2015_zotero-bibtex2](https://cloud.githubusercontent.com/assets/5259782/6002127/e71e3282-aaf0-11e4-805e-9257bb454a04.jpg)
![02-02-2015_zotero-en2](https://cloud.githubusercontent.com/assets/5259782/6002128/e71f0d74-aaf0-11e4-8faa-040beb449398.jpg)

Via EndNote: Der Reihentitel (490) und die Fussnotenanmerkungen (500/504) fehlen im Vergleich zu Export als BibTex:
![02-02-2015_zotero-en](https://cloud.githubusercontent.com/assets/5259782/6002057/2c326f6a-aaf0-11e4-9092-e6936f365d0d.jpg)
![02-02-2015_zotero-bibtex](https://cloud.githubusercontent.com/assets/5259782/6002056/2c30f28e-aaf0-11e4-8846-0cc471759768.jpg)

Am besten fänden wir, wenn Zotero bei Klick auf "Exportieren" auch explizit als Exportmöglichkeit genannt würde, sonst bleibt das immer erklärungsbedürftig. Optimalerweise würde dadurch dann ein Datensatz mit allfälligem Reihentitel und den 500er Feldern nach Zotero exportiert.

**Comment by oschihin** [comment]
@chantalw 
Ein spezifisches Angebot für Zotero ist ebenso überflüssig wie für Citavi. Zotero blendet in der Adresszeile ein Icon ein (analog zum Picker). Dieses entnimmt die Daten dann der COINs-Ausgabe (im Quelltext übrigens sichtbar unter class="Z3988").

**Comment by oschihin** [comment]
## Exportformate
Die Exportformate sehen korrekt aus. Ich tippe eher auf fehlerhafte Importmechanismen auf Seiten von Zotero. Für die Exporte würde ich Fehlermeldungen und Diskussionen empfehlen, die sich auf Probleme in den exportierten Daten beziehen, nicht auf Screenshots und Importe über mehrere Ecken hinweg. Das ist nur aufwendig rekonstruierbar. Also, wenn etwas fehlt oder falsch ist, bitte im Exportformat prüfen, welches Feld bzw. Tag benutzt oder korrigiert werden müsste. Der nächste Schritt ist natürlich: Wenn unsere Daten korrekt rauskommen, kann man sich bei den Anbietern melden, welche Importmechanismen anpassen können.

### Endnote (.enw)
* Doku (schwer zu finden): http://wiki.cns.iu.edu/pages/viewpage.action?pageId=1933370
* Bemerkungen:
 * Reihentitel wird korrekt in '%B' ausgegeben
 * Abstract / Summary bzw. Feld 520 wird in '%X' ausgegeben
 * Ein weiterer Tag für allgemeine Notizen (bzw. Feld 500) ist offenbar nicht vorgesehen. Falls ich da was übersehe, kann man das nachführen. Grundsätzlich übernehmen wir hier aber die Exportdefinitionen von VF core
Beispiel ID: 329732315
```
%0 Buch
%A Kotler, Philip
%E Armstrong, Gary
%I Pearson Education
%D 2014
%C Boston
%G eng
%@ 978-0-13-308404-7
%T Principles of marketing
%U http://aleph.unisg.ch/hsgscan/hm00387663.pdf
%U http://opac.nebis.ch:80/F?func=service&doc_library=EBI01&local_base=EBI01&doc_number=009753879&line_number=0001&func_code=DB_RECORDS&service_type=MEDIA
%U http://opac.nebis.ch/objects/pdf03/z01_978-0-273-78699-3_01.pdf
%U http://www.ub.unibas.ch/tox/IDSBB/006102807/PDF
%7 15th ed
```

### bibtex
* Doku: http://en.wikipedia.org/wiki/BibTeX#Field_types
* Bemerkungen
 * Feld 500 wird in 'notes' ausgegeben, es gibt offenbar kein Feld für 520 (Abstract)
 * Reihe wird korrekt in 'series' ausgegeben (s.u.=
Beispiel: ID 279530056
```
@book{
VuFind-279530056,
title = {Current results on health and physical activity},
series = {Series Club of Cologne},
editor = {Hollmann, Wildor},
address = {Schorndorf},
publisher = {Hofmann},
year = {2001},
url = {http://www.ub.unibas.ch/tox/HBZ/HT013127680/PDF and http://www.ub.unibas.ch/tox/HBZ/HT013127680/PDF},
crossref = {http://localhost/vfrd/Record/279530056},
isbn = {3-7780-6002-3},
}
```
