### ISSUE TITLE
Direktimport in Citavi aus Titelvollanzeige (Firefox): Import Verlag/Verlagsort nicht korrekt

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#228]
Der Citavi Picker wird in der Leiste unten angezeigt, der Import nach Citavi per Klick darauf funktioniert (Direktimport). 
Allerdings erscheint in Citavi der Verlag im Feld "Verlagsort" und der Verlags-/Erscheinungsort fehlt. 

In der aktuellen Oberfläche werden die Infos zu Verlag und Verlagsort in die richtigen Citavi-Felder importiert.

**Comment by oschihin** [comment]
@chantalw : Welches Exportformat wird vom Citavi-Picker ausgelesen? Das wäre eine nützliche Information zur Behebung des Problems. Ich nehme an, COINs / Z3988? Siehe zu dem ganzen Komplex auch https://github.com/swissbib/sbvf2/issues/550

**Comment by chantalw** [comment]
@oschihin : Ja COinS gemäss http://service.citavi.com/KB/a538/23081-coins-daten-sind-unvollstaendig.aspx?trans=1&forcetrans=true Diese Seite ist vielleicht auch noch hilfreich: http://www.citavi.com/sub/manual4/de/picker_introduction.html

**Comment by oschihin** [comment]
@chantalw @witzigs 
Tatsächlich war was schief in der OpenURL-Erstellung, das sollte nun gefixt sein (siehe Commit). Mit zotero funktioniert es jedenfalls, Citavi habe ich nicht, aber die Mechanismen sind analog. Ich schliesse deshalb hier.
