### ISSUE TITLE
Titelvollanzeige: Export nach EndNote funktioniert nicht

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#229]
Titelvollanzeige: Mit Klick auf "Exportieren nach EndNote" geht bei mir im Moment gar nichts (EndNote X7).

**Comment by oschihin** [comment]
@chantalw 
Ich kann das nicht nachvollziehen. Der Export funktioniert auf Seiten VuFind. Ich kenne mich nicht aus mit Einstellungen auf Seiten Endnote.

**Comment by chantalw** [comment]
Der Export nach EndNote (Desktop-Version) funktioniert nun bei meinen Tests korrekt, ich schliesse darum hier mal.
