### ISSUE TITLE
Export nach EndNote in der Trefferliste

### ISSUE THREAD

**Issue by billyjones** [swissbib/vufind#232]
# Problem:
Export nach EndNote in der Trefferliste liefert nur einen Eintrag obwohl es in der Liste viele Einträge gibt. Dazu scheint der exportiere Eintrag nicht in der Trefferliste vorhanden zu sein, also in der Exportdatei ist irgendwelcher Eintrag (weiss  nicht woher dieser kommt).

**Comment by oschihin** [comment]
## Hinweis
Mit diesem Commit wurde ein Problem gelöst, das ähnlich klingt. Sollte man sich mal anschauen:
https://github.com/vufind-org/vufind/commit/239de388026cc6ba112d8ac1b8cdf9b8718936d8

**Comment by guenterh** [comment]
@witzigs @biljana-r  

Hallo Silvia
https://github.com/swissbib/vufind/commit/943890e8da225f141fc6a37cc6a801927b7326c7 sollte den issue https://github.com/swissbib/vufind/issues/232 sowohl für Solr als auch Summon lösen.

Könntest Du den commit mal auf devbabe verteilen (oder bei Dir lokal ansehen) und mir ein feedback geben?

Nach dem Abholen der sourcen solltest Du den cache löschen (auch im Browser) da ich auch JavaScript angepasst habe.

Was nach meiner Ansicht möglicherweise noch nicht ok ist:
In der Trefferliste wird auch Endnote Web angeboten. Wollen wir diese Option im BulExport anbieten? Auf www.swissbib.ch bieten wir auf der Trefferliste EndNote Web nicht an.
Müssen wir die Liste der Exportmöglichkeiten auf der Trefferliste konfigurieren können?
Ich weiss aktuell nicht, ob VuFind für die Vollanzeige eine Konfiguration anbietet.

Generell erhält man bei EndNote Web auch auf der Vollanzeige im Moment noch einen Fehler (damit kenne ich mich jedoch nicht aus)

Günter

**Comment by witzigs** [comment]
Mit c576e94b3f13284deed0ceaae58a040ae4f5f9c7 wurde die Auswahl der Exportformate auf BibTex und EndNote eingeschränkt, da Exporte mit diesen Formaten in Tab 1 und 2 funktionieren.

Als Memo: In der Merkliste funktioniert der Export mehrerer Titel auch nach EndNote Web und RefWorks.
