### ISSUE TITLE
"Ähnliche Einträge"

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#233]
# Problem
Durch den letzten Update von VF core ist ein zusätzlicher Tab aktiviert worden, "Ähnliche Einträge". Das hängt zusammen mit dem schönen neuen Feature "Similar item carousel" (siehe der PR https://github.com/vufind-org/vufind/pull/252). In swissbib funktioniert der Tab aber nicht, es wird nichts dargestellt.

# Lösung
* Tab deaktivieren (wahrscheinlich durch Überscheiben in der module.config.php
* oder natürlich noch besser, konfigurieren und einsetzen.

**Comment by guenterh** [comment]
@oschihin 
ich schau mir das an - für mich ist das Ziel dass wir es einsetzen.
Günter

**Comment by guenterh** [comment]
@oschihin @witzigs @chantalw 

Hallo zusammen
auf test.swissbib.ch kann man sich die Funktionalität nun anschauen. Achtung: Die Anzeige ist nach click auf den tab immer noch leicht verzögert, das Laden der items braucht ein wenig Zeit.

Hintergrund:
In unserer solrconfig Datei fehlte ein von VuFind neu eingeführter spezieller request handler mit dem Namen morelikethis. Dieser wird für die Anzeige verwendet.
Ich habe den VF Handler nun 1:1 für unsere solrconfig Dateien (master / slave) verwendet (418a6f078a2e2bd07e7b20c3dae1e59c541ae833) und die slave Datei nach sb-s7 kopiert. Deswegen kann man sich die Funktionalität auf test.swissbib.ch ansehen (Hinweis: Die config Datei im Deployment Prozess für test.swissbib.ch habe ich nicht angepasst)

an Oliver: kannst Du Dir mal die Feldnamen in dem handler ansehen. Ich vermute wir haben bei uns andere Namen.

Man sollte die Funktion noch ein wenig verschönern (und wenn möglich die Geschwindigkeit erhöhen), ich möchte sie aber übernehmen. Solche visuellen Sachen machen immer etwas her.

Günter

**Comment by chantalw** [comment]
@guenterh Sieht gut aus - worauf basiert die "Ähnlichkeit" der Einträge?

**Comment by oschihin** [comment]
@chantalw 
Die Ähnlichkeit der Einträge basiert auf den in der solrconfig-Datei definierten Indexfelder und entsprechenden Relevanzwerten. Der Link dazu s.o. Wir müssen hier sicher noch nachjustieren, Günter hat mal die Definition von VuFind-Core reinkopiert, das stimmt nicht 1:1 mit unserem Schema überein (wie oben beschrieben). Aber gemäss der aktuellen Definition sind sicher Titel, Thema und Autor wichtig.

**Comment by ToVie** [comment]
Voll cool :+1:
