### ISSUE TITLE
Titelvollanzeige Tab 1: Platzierung Volltextlink

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#234]
Da fällt mir grad auf: warum kann eigentlich nicht der Text in der Standort-Spalte "Volltext nur im Uninetz zugänglich" mit dem Link aus Spalte 1 "Zum Bestand" hinterlegt sein?
![05-02-2015_e-book-volltextlink](https://cloud.githubusercontent.com/assets/5259782/6061206/02bc6cd2-ad46-11e4-8cd2-17504e59da90.jpg)
Zweite Zufallsbeobachtung bei diesem Titel: Beim Volltextlink oben fehlt Uni Bern
![05-02-2015_volltextlink-alt](https://cloud.githubusercontent.com/assets/5259782/6061272/8974ab04-ad46-11e4-8a72-a11739a808f7.jpg)

**Comment by witzigs** [comment]
Der Volltextlink für Bern fiel wegen einer falschen Konfiguration weg - ist behoben.

**Comment by witzigs** [comment]
@chantalw 
Für mich hat es hier schon genug Links zum Volltext und ich halte einen zusätzlichen Link unter Standort nicht für notwendig (sondern unter Umständen sogar eher für verwirrend). Zudem gibts den Link "Zum Bestand" immer, unter Standort gibts nicht zwingend einen Text. Z.B. die Daten aus retroseals, bei denen unter Standort nur der Info-Link steht.
