### ISSUE TITLE
Design (Viewport xs): Checkbox Filtereinstellungen

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#235]
Noch so ein Design-Problem (wurde soweit ich sehe noch nicht erfasst): 
Auf dem iPhone 4S rutscht auch die Checkbox für "behalte die Filtereinstellungen" aus dem Bildschirm:
![design-starseite](https://cloud.githubusercontent.com/assets/5259782/6062465/55ef43ca-ad50-11e4-8a13-4ee297abe3ef.PNG)

**Comment by guenterh** [comment]
Dieser Effekt tritt bei Android ebenso auf

**Comment by oschihin** [comment]
Im Core wurde ein ähnliches Problem gefixt, siehe:
* https://vufind.org/jira/browse/VUFIND-1119
* https://github.com/vufind-org/vufind/commit/facd512d5eee9284462359c1920fc1955755ca8c

**Comment by chantalw** [comment]
@witzigs : scheint nun ok zu sein, ich schliesse den Issue.
