### ISSUE TITLE
Design (Trefferliste und Vollanzeige): Zeilenabstände

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#236]
@witzigs @oschihin Ich weiss nicht, ob ihr das schon auf der Design-Agenda habt, allenfalls bitte verlinken. 
Die Zeilenabstände in der Trefferliste und Vollanzeige erscheinen einfach viel zu gross, die Titel nehmen so m.E. zuviel Raum ein. Könnte das Design nicht etwas kompakter werden, den Platz effizienter nutzen?
Auf dem iPhone sieht man gerade mal 2 Titel einer Trefferliste gleichzeitig auf dem Bildschirm:
![trefferliste](https://cloud.githubusercontent.com/assets/5259782/6063149/6a5e32ee-ad55-11e4-9bb8-91ebdc4de42b.PNG)
In der Vollanzeige nehmen die bibliographischen Angaben den ganzen Bildschirm ein: 
![vollanzeige](https://cloud.githubusercontent.com/assets/5259782/6063150/6a5fe9b8-ad55-11e4-84b3-2f36d3272da7.PNG)

**Comment by adchsnowflake** [comment]
@oschihin 
Betrifft dieser Wunsch bloss das Smartphone oder das Smartphone & das Tablet?
Gibt es konkrete Angaben zu Zeilenhöhe usw. oder erfolgt die Umsetzung nach "bestem Wissen und Gewissen" unsererseits?

**Comment by oschihin** [comment]
@adchsnowflake 
* Betrifft den kleinsten Viewport, also Smartphone
* Umsetzung in vollstem Vertrauen auf euch
Es scheint sich um einen <br> zu handeln. Ev. ist dieser auf grösseren Viewports nötig
