### ISSUE TITLE
switchAAI-Anmeldung direkt auf "Anmelden an Bibliothekssystem"

### ISSUE THREAD

**Issue by ToVie** [swissbib/vufind#240]
Problem
-----------
Sobald ich mich mit einem "jungfräulichen" switchAAI-Account bei swissbib anmelde gelange ich von der Startseite bei Klick auf "My swissbib" auf die Seite "Anmelden an Bibliothekssystem"
![anmelden](https://cloud.githubusercontent.com/assets/3183064/6075372/2dc4d19a-add1-11e4-8f5a-fade5965c841.png)
Diese Seite gibt mir relativ wenig Informationen, was ich denn nun machen soll ;)...
Ich nehme an, dass es sich zum aktuellen Zeitpunkt weiterhin um eine ungewünschte Konfiguration handelt...

Lösung
---------
In swissbib-spezifischer config wieder deaktivieren.

Bemerkung
---------------
In jedem Fall sollte mehr Information zum Sinn dieser Anmeldung bereitgestellt werden. Vor allem über den Nutzen dieser grossartigen Funktion für die Benutzer!

**Comment by guenterh** [comment]
Hat einen gewissen Zusammenhang mit https://github.com/swissbib/vufind/issues/157

**Comment by guenterh** [comment]
s. auch https://github.com/swissbib/vufind/issues/166

**Comment by oschihin** [comment]
@guenterh @ToVie 
Gelöst. Wir haben den Driver 'NoILS' konfiguriert und als Standardseite für 'MyResearch' > Settings. Der Aufruf von Profile (d.h. die Angaben des Benutzerkontos) führt zur entsprechenden Anmeldeseite.
