### ISSUE TITLE
Darstellung von images (icons) im Responsive Design

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#241]
@witzigs @oschihin 

bin gerade wegen etwas Anderem durch Zufall darüber gestolpert.
https://test.swissbib.ch/Search/Results?lookfor=Fig%C3%BCrliches+Zeichnen&type=AllFields&limit=20&sort=relevance
versus
https://www.swissbib.ch/Search/Results?lookfor=Fig%C3%BCrliches+Zeichnen&type=AllFields&limit=20&sort=relevance

Es handelt sich um die Werke der Dame aus Zürich, zu denen nicht passende Covers gewählt wurden.
Scheinbar ist das von Ihr gelieferte cover (was bei der Dame auch nicht anders zu erwarten ist) grösser im Format als die üblichen 'small - size', die wir in der Liste verwenden, aber auch die Vollanzeige zerreist es. Bzw. sie hat nur grosse icons.
So responsive müssen wir nun auch wieder nicht sein.

Dies hat auch einen inhaltlich Bezug zu den unterschiedlich dargestellten icons, welche von Snowflake geliefert worden sind (Dagmar). Was auch immer die Gründe sind, warum sie unterschiedlich dargestellt werden.

Wir sollten das in einem Design-Task fixen.

**Comment by oschihin** [comment]
siehe dazu auch #107 
Dieser Issue ist an snowflake vergeben und sollte nächste oder übernächste Woche angegangen werden

**Comment by oschihin** [comment]
Issue in #108 integriert, hier geschlossen
