### ISSUE TITLE
Mobile Geräte: Facettenmenü verschwindet nach dem Setzen/Entfernen von Facetten

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#242]
Gilt für beide Tabs und bei Phones für Hoch- und Querformat, bei Tablets für Hochformat:
Ich fänds praktischer, wenn das Menü nicht nach Tipp auf ein Filterkriterium gleich verschwinden würde, um der neuen Trefferliste "Platz zu machen". Vielleicht will man ja mehrere Facetten gleichzeitig anwählen. Das sollte m.E. irgendwie möglich sein.

**Comment by witzigs** [comment]
Das sofortige durchführen der angepassten Suche (und damit verbunden das Ausblenden des Menüs) entspricht dem Standardverhalten der Oberfläche und wird nicht angepasst.
