### ISSUE TITLE
Weiterverarbeitungsfunktionen auf mobilen Geräten

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#243]
Die hinter den kleinen Icons oben rechts liegenden Weiterverarbeitungsfunktionen werden aktuell nicht alle auf allen Bildschirmgrössen angeboten. Da die Icons nicht viel Platz brauchen, wäre ich dafür, möglichst alle Funktionen, die Sinn machen, auch auf den kleinen Bildschirmen in Quer- und Hochformat anzubieten. Z.B. Mailversand, was im Moment noch fehlt. Wenn welche weggelassen werden müssen, würde ich auf den Phones am ehesten auf Druckfunktion oder Exportfunktion verzichten, das braucht man m.E. auf diesen Geräten weniger (bin zwar nicht sicher, die Exportfunktion kann für Nutzende doch auch auf Phones Sinn machen).

**Comment by witzigs** [comment]
@chantalw: Ich habe dies mit d26cc7311f8f152d27d21367e30b9b2fa7042e01 angepasst und schliesse das Issue.
Der einzige Unterschied ist jetzt noch, dass die Exportfunktion aus der Trefferliste in den Viewports xs und sm nicht angezeigt wird. Grund ist, dass wir dort nur Endnote und Bibtex als Export-Formate anbieten können und diese Formate auf mobilen Geräten wohl kaum genutzt werden (können).
Falls diesbezüglich Benutzerwünsche gemeldet werden, lässt sich das aber auch später noch ändern.
