### ISSUE TITLE
QR-Code Popup

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#244]
Die Titelangaben, die im Popup unterhalb des QR-Codes eingeblendet werden, sind nicht lesbar:
![bildschirmfoto am 2015-02-10 um 11 34 00](https://cloud.githubusercontent.com/assets/9479686/6125649/ca32a580-b118-11e4-83dd-753a1d2565d4.png)

**Comment by chantalw** [comment]
Lustigerweise poppt der QR-Code nicht immer am selben Ort auf... Lesbarkeit und Abgrenzung von der Oberfläche waren in der aktuellen Version sicher besser gelöst.
![09-02-2015_qr-code](https://cloud.githubusercontent.com/assets/5259782/6168225/a2fe2258-b2c3-11e4-8146-1d51a33965bd.jpg)
![09-02-2015_qr-code-alt](https://cloud.githubusercontent.com/assets/5259782/6168226/a30151b2-b2c3-11e4-9d73-b9f269cb84ac.jpg)

**Comment by oschihin** [comment]
Erledigt sich, da QR-Codes aus der Exemplaranzeige verschwinden werden. Unklarer Nutzen. Schliesse später hier
