### ISSUE TITLE
Design (Viewport xs/sm): Dropdown Exportieren

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#245]
iPhone 4S, Hoch- und Querformat: 
![exportieren-hochformat](https://cloud.githubusercontent.com/assets/5259782/6168355/f31011d8-b2c4-11e4-8cb5-4f19881bae4f.PNG)
![exportieren-querformat](https://cloud.githubusercontent.com/assets/5259782/6168354/f30e0f64-b2c4-11e4-814b-f7999cab0fa5.PNG)

**Comment by witzigs** [comment]
Das Dropdown-Menü für den Export ist in den Viewports xs und sm sowohl in der Trefferliste als auch der Vollanzeige nicht korrekt positioniert:
* Trefferliste (xs): Das Dropdown nimmt mehr als die gesamte Breite des Bildschirms ein.
* Trefferliste (sm): Das Dropdown öffnet sich links über "Suchergebnisse".
* Vollanzeige (xs und sm): Das Dropdown ist rechts, geht aber über den Bildschirm hinaus (siehe Screenshots)

**Comment by witzigs** [comment]
@edelm 
Das hier ist noch immer aktuell. In der Vollanzeige wird das Export-Menü in den kleinen Viewports abgeschnitten.
