### ISSUE TITLE
Versionsangaben in Beschreibungstab anzeigen

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#249]
MARC-Feld 562 $c (http://www.loc.gov/marc/bibliographic/bd562.html) soll angezeigt werden. Offenbar verwendet in Aufnahmen von HelveticArchives.

Bsp.:
- https://test.swissbib.ch/Record/cha477725
- https://test.swissbib.ch/Record/cha480073
- https://test.swissbib.ch/Record/cha478531
- https://test.swissbib.ch/Record/cha478538

**Comment by oschihin** [comment]
@ToVie : Hast du oder deine Crew noch eine Idee, wie man das Label nennen könnte (in allen vier Sprachen). Momentan leider noch nicht auf dem Server, wir haben ein deployment-Problem

**Comment by ToVie** [comment]
Ich würde "zusätzliche Information" sagen - nicht besonders schön aber treffend...
- "informations complémentaires"
- "additional information"
- "informazioni aggiuntive"

**Comment by oschihin** [comment]
Wäre etwas wie "Angaben zur Version" nicht präziser?

Am 06.03.2015 um 09:13 schrieb ToVie:
> Ich würde "zusätzliche Information" sagen - nicht besonders schön aber
> treffend...
>
>   * "informations complémentaires"
>   * "additional information"
>   * "informazioni aggiuntive"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swissbib/vufind/issues/249#issuecomment-77521748>.
>

-- 
UNIVERSITÄT BASEL
Universitätsbibliothek
Oliver Schihin
Projekt swissbib
Schönbeinstrasse 18-20
4056 Basel, Schweiz
Tel.: +41 61 267 13 07
Fax: +41 61 267 31 03
E-Mail oliver.schihin@unibas.ch
URL http://www.swissbib.org/

**Comment by ToVie** [comment]
Ja, das geht auch.

**Comment by ToVie** [comment]
Super, merci!
