### ISSUE TITLE
Leerer Tab "Beschreibung" in summon-Vollanzeige

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#252]
## Problem
Bei summon-Aufnahmen, welche keine entsprechenden Metadaten zur Anzeige im Reiter "Beschreibung" enthalten, wird dieser Reiter trotzdem einfach leer angezeigt.

## Beispiel
http://devbabe.swissbib.ch/SummonRecord/FETCH-oup_oro_10_1093_acref_9780199545155_013_105083

## Lösung
Zwei Möglichkeiten:
* Entweder **immer** die Links in diesem Tab anzeigen, damit ist immer was drin
* oder den Tab ausblenden, wenn keine Inhalte vorkommen

@witzigs : Kannst du dir das mal anschauen und überlegen, welche Lösung du vorziehst?

**Comment by witzigs** [comment]
Die Suche nach Zeitschriftentitel ist nun im Tab Beschreibung, daher ist in den meisten Fällen etwas vorhanden. Eine Lösung für das Ausblenden, wenn der Tab leer ist, habe ich nicht gefunden.
