### ISSUE TITLE
Autocomplete : Probleme

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#253]
## Problem

Die Autosuggest-Funktionalität ist in der aktuellen Oberfläche schwer benützbar. Z.B.
- Der Eintrag unter dem Mauszeiger wird übernommen, ohne das er angewählt wurde
- Die Liste enthält Vorschläge mit der Zeichenfolge "irgendwo" im Titel. 
## Lösungen
- [x] Die Funktionalität muss deaktivierbar sein
- [x] Die JS-Library muss besser in den Griff bekommen werden
- [ ] Die Vorschläge müssen eventuell verbessert werden, Zeichenfolgen am Anfang des Titels (oder anderer Kategorien) sollten zuoberst kommen.
## Hinweise
- VuFind arbeitet offenbar an einer besseren Lösung: https://github.com/vufind-org/vufind/pull/459

**Comment by adchsnowflake** [comment]
@oschihin 
Wo wird Autosuggest eingesetzt? Auf zB. devbabe.swissbib.ch oder test.swissbib.ch habe ich kein Autosuggest für den Suchschlitz:  Ist das im Moment deaktiviert?

**Comment by oschihin** [comment]
@adchsnowflake siehe commit oben

**Comment by adchsnowflake** [comment]
@oschihin 
Ah. Wunderbar, alles klar, also deaktiviert ;). Danke.

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Autocomplete : Probleme #253 (02/2015-)](https://trello.com/c/uUIO0Gzd/93-autocomplete-probleme-253-02-2015)

**Comment by sonjakupfi** [comment]
Wir in einer neueren Form wieder erfasst.
