### ISSUE TITLE
Zeitschriftenbände / Details anzeigen (Design)

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#257]
## Beschreibung
Dieser Issue sammelt Anforderungen und Wünsche an das Design der Bestellung von Zeitschriftenbänden:
* Paging / Blättern nicht nur oben rechts, sondern auch unten rechts anzeigen

## Beispiele
* http://devbabe.swissbib.ch/Record/270219390

## Hinweise
* Verwandte Issues: #256, #154

**Comment by witzigs** [comment]
Paging / Blättern sollte nicht angezeigt werden, wenn ein Filter aktiv ist und deshalb nur eine Anzahl Exemplare angezeigt wird, die auf einer Seite Platz hat.

**Comment by adchsnowflake** [comment]
@oschihin 
Um was geht es hier? Was ist zu tun? Unter dem Beispiellink sehe ich kein Paging.

**Comment by oschihin** [comment]
@adchsnowflake Das Paging befindet sich im Popup der Zeitschriftenbände. Dieses erreichst du, wenn du im Tab "Exemplare" z.B. bei Uni Basel - Hauptbibliothek auf den Link "Details anzeigen" gehst.
