### ISSUE TITLE
Sitemap konfigurieren und erstellen

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#258]
## Thema

VuFind bietet die Möglichkeit, Sitemaps für Suchmaschinen (google, bing, etc.) zu erstellen. Diese Funktionalität sollten wir konfigurieren, unseren Bedürfnissen anpassen und auf produktiven Hosts laufen lassen.
## Hinweise
- Konfigurationsdatei in /config/vufind/sitemap.ini
- Skript /util/sitemap.php
- für swissbib wichtig: Die Bibliotheksliste (unter https://test.swissbib.ch/Libraries)
- Mehrsprachigkeit berücksichtigen
- Verwandte Issues: #130, #239, #12 
- Info von google: https://support.google.com/webmasters/answer/156184?hl=de

**Comment by edelm** [comment]
Hier ist ein guter Artikel über Sitemaps und robots.txt: http://www.advancedhtml.co.uk/robots-sitemaps.htm

Zusammengefasst ist robots.txt um URL fürs SEO explizit zu *exkludieren*, und Sitemap um wichtige URLs explizit zu *inkludieren* (inkl Einstellungen für Relevanz-Gewichtung und Besuchs-Intervalle).

Wir können hier im Issue mal zusammentragen, welche URLs für SEO von Swissbib/Vufind wichtig sind, um dann daraus die Sitemap dafür abzuleiten.

**Comment by oschihin** [comment]
@edelm 
Hier einige Gedanken, was auszuschliessen oder anderseits hoch zu gewichten ist. Notiert sind hier nur Inhalte von grün, Summon in orange ist schon ausgeschlossen:
### ausschliessen oder tief gewichten
* /Search/ : d.h. Trefferlisten. Kommt in Suchmaschinen häufig vor, finde ich aber eigentlich ein Ressourcenfresser
* /MyResearch/ : hier gibt's nichts zu indexieren
* /Help/ : Hilfeseiten, die Inhalte kommen von VF Core. Muss nicht indexiert sein
* /Record/[ID]/Details : ausschliessen
* /Record/[ID]/Similar : ausschliessen
* /Record/[ID]/Hierarchy : ausschliessen
* /Record/[ID]/Save : ausschliessen
* /Record/[ID]/Export : ausschliessen
* /Record/[ID]/Email : ausschliessen
* /Record/[ID]/Cite : ausschliessen

### hoch gewichten
* /Record/
 * /Record/[ID]/Holdings
 * /Record/[ID]/Description
* /Libraries/
* /HelpPage/ : Hier sind v.a. Projektinfos drin, die auch in einer Suchmaschine interessant sein können (keine blosse Suchhilfe)
Falls wir den Crawlerzugriff so optimieren können, können wir bei den erlaubten bzw. hoch gewichteten Inhalten auch die Inhalte selbst optimieren (Stichworte schema.org, RDFa)

**Comment by edelm** [comment]
Die austzuschliessenden URLs sind im robots.txt integriert. Jedoch jeweils ohne das "/Record/[ID]", da robots.txt keine Wildcards erlaubt.

Die hoch zu gewichtenden URLs sind im Moment noch nicht in einem sitemap-File. In einem sitemap-File müssen immer komplette URLs (mit der Domain und Protokoll) angegeben werden. Dies ist schwierig umzusetzen, da wir teilweise mehrere Domain und Protokolle nutzen (basel|bern|baselbern.swissbib.ch, http|https). Ebenfalls ist es unklar, ob wir /holdings und /Description für jeden Record überhaupt angeben können (die Liste der URLs ist meist auf 50k Einträge begrenzt).

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sitemap konfigurieren und erstellen #258 (03/2015)](https://trello.com/c/VNKlmuFJ/92-sitemap-konfigurieren-und-erstellen-258-03-2015)

**Comment by liowalter** [comment]
I think this is quite important for the indexing by google and would rather reopen it. 
Examples : 

- springer https://link.springer.com/sitemap-index.xml
- tribune de geneve http://www.tdg.ch/sitemap/sitemap0.xml.gz

Vufind documentation https://vufind.org/wiki/administration:search_engine_optimization

On top of that the protocol [ResourceSync](http://www.openarchives.org/rs) is based on sitemaps.

**Comment by gagarine** [comment]
It's a no brainer: if you are not on google... you are not on the web. This should be issue number 1. Only  a public founded project can afford to not be indexed. Unbelievable.

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [258](https://trello.com/c/jBr8PWg6/132-258)

**Comment by liowalter** [comment]
Seit langem erledigt : https://www.swissbib.ch/sitemapIndex.xml
