### ISSUE TITLE
Statistik

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#259]
## Thema
Statistikmodul von VuFind implementieren, um regelmässige Auswertungen über die Verwendung des Dienstes generieren zu können.

**Comment by maechler** [comment]
Es gibt im Grunde 3 verschiedene Arten um in VuFind Statistiken über die Nutzung zu sammeln:

## VuFind Statistics Modul
- Beispielkonfiguration: https://github.com/swissbib/vufind/commit/34b4a8e12908793c3e90be3d48a531b0464dd472
  - Admin-Panel: yourhost.ch/admin
- Komplett in VuFind integriert
- Speicherziele konfigurierbar: Solr, File, Datenbank
- Auswertungen zu Trefferliste und Vollanzeige
  - Total Suchen, 0 Treffer Suchen, Total Record Views, Top Suchbegriffe, Top Records, Browser, Anzahl Tags, Anzahl Favoriten
- Erweiterbar (Search und Record Service überschreiben)

## Google Analytics
- Google Analytics Standard z.B. Geo-Location, Benutzerfluss, Geräteinformation, Referer, ...
- Custom Variables ohne VuFind Unterstützung

## Piwik
- Open Source Software
- Funktionen für Auswertungen zu Trefferliste und Vollanzeige
  - Suchbegriff, Anzahl Resultate, Facetten, Suchtyp, Target, Sortierung, Limit, Format, Author, Titel, Institution
- Piwik Standard z.B. Geo-Location, Benutzerfluss, Geräteinformation, Referer, ...
- Custom Variables mit VuFind Unterstützung

## Fazit
Piwik ist wohl die beste Wahl. VuFind hat bereits integrierte Unterstützung um z.B. Facetten bei der Suche zu tracken. Piwik ist Open Source und kann selber gehostet werden im Gegensatz zu Google Analytics. Piwik liefert viele Zusatzinformation wie Geo-Location oder Geräteinformationen (Desktop, Smartphone, Bildschirmgrösse). Im Gegensatz zum VuFind Modul wird jede Seite getracked z.B. auch MyResearch. Es können zusätzlich beliebige Werte als "Custom Variables" getracked werden.

**Comment by witzigs** [comment]
Piwik ist eingerichtet, ich sammle hier Wünsche für Custom Variables, die durch die Standard-Implementierung von VuFind nicht erfüllt werden:

* Facetten-Typ: Bei der Standard-Implementierung (Variable FacetTypes) werden in Piwik gewählte Facettenkombinationen als ein Wert (z.B.: Union adv_search_year Language) aufgeführt. Ziel wäre, dass jeder gewählte Facettentyp einmal gezählt wird, unabhängig von der Kombination.

*Reiter in der Vollanzeige: Wie oft wird welcher Reiter in der Vollanzeige angewählt?

**Comment by guenterh** [comment]
@witzigs 
Was hälst Du davon, den issue mit Bezug auf den ersten Teil (Analyse welches Statistiktool und Implementierung) an dieser Stelle zu schliessen und Deine Fragen vom 1. Oktober unter einem neuen issue zu erfassen? Dort würde es dann um Erweiterung/Verbesserung/Nutzungsformen gehen.

Ich habe gerade nachgesehen: Wir erhalten seit 4.1. (neuer release) für alle drei domains (swissbib.ch / baselbern / jusbib) Statistiken

**Comment by witzigs** [comment]
neues Issue für Erweiterungen #401
