### ISSUE TITLE
"Ihre Suchbegriffe" wieder anzeigen

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#261]
## Problem
In der aktuellen Oberfläche wird das Element "Ihre Suchbegriffe" nicht mehr dargestellt. Es enthält markierte Terme aus den indexierten Volltexte (Inhaltsverzeichnis, Abstract). Dargestellt wird es im template 'core.phtm'

## Hinweis
Das ganze funktioniert schlecht, siehe dazu Issue https://github.com/swissbib/searchconf/issues/8

**Comment by guenterh** [comment]
Highlighting erscheint nun wieder wie im bisherigen swissbib. 
Verbesserung der Funktionalität als solche (s.o) nach dem Livegang
Beipspielsuchen:
Die einheimischen  älteren  Menschen  in  Limburg
oder
Die  Einwanderung  von  Italienern  nach  Belgien
