### ISSUE TITLE
Reiterbeschrifungen in Vollanzeige

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#262]
## Problem

Bei Titeln mit vielen Reitern (Beispiel: https://test.swissbib.ch/Record/281804230) bricht die Zeile unschön um.
## Möglichkeiten
- Kürzung der Texte, z.B. beim (ausserhalb von Bibliothekarenkreisen) kaum genutzten Reiter "Felder" (Ein Buchstabe oder Symbol würde es auch tun)
- Anzeige eines Symbols, das in kleinen Viewports ausschliesslich angezeigt würde

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Reiterbeschrifungen in Vollanzeige #262 (03/2015-wishful)](https://trello.com/c/Oy8Ol4o7/90-reiterbeschrifungen-in-vollanzeige-262-03-2015-wishful)
