### ISSUE TITLE
Übersetzung location (Tab 40)

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#263]
Die Übersetzung der location codes funktioniert nicht. Siehe Holdings.php, getLocationLabel(array $item)

Location codes sollten für IDSBB-Exemplare und -Holdings durch die in den location-Sprachdateien vorgegebenen Werte aus Tab 40 übersetzt werden.
Im Moment wird bei Items der Inhalt von location_expanded angezeigt, bei Holdings wird kein Standort angezeigt.

Beispiel: http://devbabe.swissbib.ch/Record/076136957

**Comment by guenterh** [comment]
@witzigs 
Hallo Silvia
Du musst mir mal zeigen von was Du redest. Im MOment wird mir z.B. bei http://devbabe.swissbib.ch/Record/264048768
bei Location der Text im attachement angezeigt. VonRoll Speicher E7 kommt aus idsbb-de.ini
Ist das nicht das was Du möchtest?

Viele Grüsse, Günter

![location beispiel](https://cloud.githubusercontent.com/assets/1825990/6755731/88a601f4-cf25-11e4-8373-656a7d1e4962.png)

**Comment by guenterh** [comment]
@witzigs - wo ist das Beispiel.....? 
Viele Grüsse, Günter

**Comment by witzigs** [comment]
@guenterh 
Beispiel: http://devbabe.swissbib.ch/Record/076136957
(oder auch oben im ersten Kommentar... )
Liebe Grüsse
Silvia

**Comment by guenterh** [comment]
@witzigs 
Hallo Silvia, ich denke dass die Übersetzungen für locations sollten nun erscheinen  - bitte mal kurz ausprobieren.
Zu den englischen Übersetzungen: bitte mal sämtliche caches löschen (auch languages/data/cache)
Bei mir erscheinen die Übersetzungen nun auch in Englisch

Danke und Grüsse, Günter

**Comment by guenterh** [comment]
@witzigs 
Hallo Silvia, was ist hier der Stand? Günter

**Comment by witzigs** [comment]
@guenterh 
Das ist erledigt und in Ordnung - ich schliesse hier.
