### ISSUE TITLE
Merklisten löschen geht nicht

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#266]
## Problem
Wollte im Testkonto bei den Merklisten ein bisschen aufräumen - Merklisten lassen sich aber nicht löschen. Nach Klick auf "Merkliste löschen" erscheint unterhalb ein feines Design-Element (vgl. Screenshot), sonst passiert nichts.
![2015-03-20_merkliste-loschen](https://cloud.githubusercontent.com/assets/5259782/6754085/a544c22e-cf1a-11e4-83e1-4bf4dd85d2e4.jpg)

## Task
Designanpasungen, damit das Löschen von Merklisten funktioniert (siehe Kommentare unten)

**Comment by guenterh** [comment]
@chantalw @witzigs 
Hallo Chantal
das von Dir erwähnte feine Design Element ist die Popup - box, welche nicht deutlich genug auf der Oberfläche erscheint. Ein Click auf diese Liste löscht das Element.

Ich werde mal schauen, ob der Grund im VF2 Core oder nur bei uns im swissbib zu suchen ist.

Günter

**Comment by guenterh** [comment]
Im VF2core funktioniert das Element (s. attachement)
@witzigs : http://sb-vf20.swissbib.unibas.ch/vf2coredemo/ ist wieder auf dem letzten Core Stand (falls Du Dir dort etwas ansehen möchtest)
Die Ursache des Problems liegt im Design

![merkliste loeschen](https://cloud.githubusercontent.com/assets/1825990/6755065/e4043e4e-cf20-11e4-81bb-a3af11d452fd.png)

**Comment by oschihin** [comment]
30262cc52e67668e084f9f2dda9c7f4010d6bf0f
