### ISSUE TITLE
fehlender FRBR back button

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#267]
## Problem
Anders als in www.swissbib.ch bieten wir im neuen Responsive Design in der FRBR-Ergebnisliste für BenutzerInnen keinen "back-button" an, mit dessen Hilfe auf die allgemeine Ergebnisliste zurückgesprungen werden kann.

* bisher: https://www.swissbib.ch/Search/Results?lookfor=115526226&type=FRBR 
* neu: https://test.swissbib.ch/Search/Results?lookfor=115526226&type=FRBR

Zur Ergebnisliste können BenutzerInnen nur mit Hilfe des allgemeinen Browser History Buttons gelangen. Das ist ausgesprochen schlecht und muss im Rahmen der letzten Design/Implementierungsphase noch geändert werden.

## Task
* Baue eine Navigation mit Breadcrumb auf (wie in der Vollanzeige)

**Comment by adchsnowflake** [comment]
Problem wird ersichtlich, wenn:
i) Der Beispiellink "bisher" angeklickt wird
ii) Auf dessen Trefferliste auf den erste Treffer ("Bravo!") geklickt wird:
Hier kann der Benutzer anhand einer Schaltfläche [< Back to results] zur Trefferliste zurückspringen.
Dies Schaltfläche fehlt in der neuen Umgebung (Beispiellink "neu" und Ablauf analog) und muss implementiert werden.

**Comment by oschihin** [comment]
@saschahepp 
Vorhin kurz angesprochen, hier noch die Beschreibung eines Problems, das weiterhin besteht und die Abnahme noch blockiert.

## Problem
1. Von Trefferliste auf "Weitere Ausgaben"
2. In dieser Liste auf eine Vollanzeige
3. In der Vollanzeige auf "Weitere Ausgaben"
4. Nun ist man wieder auf der Liste der "Weiteren Ausgaben" (type=FRBR). Geht man hier im Breadcrumb auf Suche, wird eine leere Suche ausgelöst und der ganze Bestand ausgegeben.

## Task
* Wenn möglich, die ursprüngliche Suche ausgeben
* Falls absehbar zu kompliziert, andere Lösungen überlegen und rückfragen

**Comment by saschahepp** [comment]
@oschihin wenn ich das so umbaue, dann kann die Einzel-Ansicht des Records nicht mehr gecached werden, da sich der Link im Breadcrumb und auch die URL je nach Suche laufend ändert. Wenn das ok ist, kann ich das noch einbauen (vergleiche hierzu die URL der Ergebnisliste: ?lookfor=115526226&type=FRBR&name=bravo&limit=20&sort=publishDateSort+desc dies müsste man überall mit anhängen)

**Comment by oschihin** [comment]
@saschahepp 
1541f321fa380a62f097390a20164d65067e60be
gemergt, hier geschlossen.
