### ISSUE TITLE
kein popup im Anmeldedialog

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#268]
aktuell wird bei einigen anmeldepflichtigen Funktionen der popup - Dialog aufgerufen (z.B. Mail in der Suchliste) . 
In anderen Fällen wiederum nicht. (z.B. Mail in der Vollanzeige)

Für shibboleth soll dies auf gar keinen Fall passieren (kein Anmedledialog im Popupmodus), Basel/Bern hat sich noch nicht entschieden.

Ziel: 
a) klare Analyse warum sich die Applikation so verhält 
b) Richtigstellen des Verhaltens

**Comment by witzigs** [comment]
Basel/Bern hat sich ebenfalls entschieden: kein Anmeldedialog mit Popups
Grund dafür ist, dass Einstellungen und Favoritenfacette bei einer Anmeldung über den Popup-Dialog erst nach einem weiteren Klick (oder reload der Seite) aktiv werden. Mit der Anmeldung über die Seite statt über den Popup-Dialog kann dies verhindert werden.

**Comment by guenterh** [comment]
@witzigs 
Liebe Silvia,
habe die Sachen committed
https://github.com/swissbib/vufind/commit/b473e37e5bbac362665351c6359b4a1902711842
Orange (Solr) und green habe ich eigentlich überall mal ausprobiert - sollte funktonieren
Mit dieser Einstellung kann man das Verhalten steuern
https://github.com/swissbib/vufind/blob/rdgoingpublic/local/config/vufind/config_base.ini#L73
Nimmst Du die Konfiguration weg, sollte wieder der popupdialog erscheinen - wenn nicht VuFind zwischendurch wieder andere Klassen setzt und mit event-Handlern versieht....

Summon habe ich eigentlich auf die Schnelle auch mal ausprobiert. Hier wäre ich froh, wenn Du auch nochmals hineinschauen könntest.

Grüsse, Günter

**Comment by witzigs** [comment]
@guenterh 
Ich bin bei Summon auf ein Problem gestossen: Wenn ich aus der Vollanzeige einen Titel als Mail versenden will, gibts eine Fehlermeldung, da nach einem solr-Record gesucht wird.
Beispiel: 
Nachricht: Record Solr:FETCH-LOGICAL-g911-839b766c8cc66ed8d53fb6cb6be2b3dbfd205b4cd2ff8ed5a23728dbe758ec733 does not exist. 

Liebe Grüsse
Silvia
