### ISSUE TITLE
update resources.swissbib.ch

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#269]
Der service hinter
https://resources.swissbib.ch
sollte aktualisiert werden. Nicht zwingend für going public aber sinnvoll.

Die bereits von mir im Februar begonnene Aktualiserung ist zur Zeit im repository 
git@sb-util.swissbib.unibas.ch:~/git/resources.swissbib.ch
abrufbar.

Wenn abgeschlossen, wandert das repository nach github.com/swissbib

**Comment by guenterh** [comment]
@edelm 
Hallo Matthias,
wie vor der pause besprochen. 
Unter https://github.com/swissbib/resources.swissbib.ch habe ich ein neues Rpository erstellt.
Das Repository enthält die beiden Module Resources und Resources.org. Letzteres ist der aktuelle produktive Code, der unter sb-vf15 und sb-19 zur Bereitstellung der icons benutzt wird.
Dieser Code dient nur zum Vergleich für die Neuentwicklung / Update und sollte nach Fertigstellung gelöscht werden.

Modul Resources dient für die eigentliche Implementierung.

## Ziele
* [ ] update der aktuell produktiven Umgebung mit dem im Original-VuFind Repository eingesetzten code  
* [ ] Integration von https://github.com/swissbib/vufind/issues/293

Du brauchst noch ein File local/config/resources/config.ini

Günter

**Comment by guenterh** [comment]
Schön fände ich noch, wie mündlich besprochen, wenn wir anhand dieser Implementierung die Probleme der aktuellen VuFind Architektur, wie ich sie in meiner Präsentation in Konstanz ansprechen werde, diskutieren könnten.

**Comment by guenterh** [comment]
@edelm 
Hallo Matthias,

hoffe Du konntest Dich am Nachmittag ein wenig erholen.
Ich habe heute versucht, das Repository resources.swissbib.ch mit den neuesten Sourcen des VuFind Moduls soweit zusammenzustellen, dass es einigermassen lauffähig ist.
(Bis jetzt kann ich ein image not available laden)
Ich habe eine ganze Reihe von Typen aus dem VuFind Modul kopiert (mehr als in der alten Verson). Dadurch sind wir aber näher an der aktuellen Codebasis von VuFind.

Mein Ziel wäre nun:
Die bestehende Implementierung soweit zu finalisieren, dass sie:
* produktiv einsetzbar ist
* die fehlende icon - Lade Funktion übernimmt, wenn keine images gefunden werden

Ich denke, bei diesem Projekt lässt sich einiges über die internen Zusammenhänge lernen. Deswegen möchte ich auch nicht vorpreschen und warte bis Du wieder 'auf dem Damm' bist.

Der grundsätzliche Nachteil, dass ich Code kopiert habe, kann aber auch zum Vorteil werden. Dann lässt sich leichter überlegen, was wir als Komponente wie aulagern könnten. Aber das ist bereits der nächste Schritt und hier warte ich auf jeden Fall auf Dich!

Viele Grüsse

Günter

**Comment by guenterh** [comment]
@oschihin @witzigs @edelm 

Betrifft diese beiden issues
https://github.com/swissbib/vufind/issues/293
https://github.com/swissbib/vufind/issues/269


Zur Zeit gibt an zwei Orten Implementierungen, die für die Erstellung von icons oder images in der Resultlist und/oder Vollanzeige zuständig sind

a) resources.swissbib.ch ausschliesslich für images aktuell bezogen in erster Linie von Amazon und in zweiter Linie von Google
b) Bereich Recorddriver/Holdings mit Regeln für die Erstellung von icons. Die Details dieser Implementirung kenne ich nicht, sie wurden von snowflake in Absprache mit swissbib erstellt.
Matthias ist zur Zeit dabei, sich die Details anzusehen und besser zu verstehen.

Nach unserer kurzen Diskussion im gestrigen daily zu diesem Thema - was wir aktuell benötigen ist eine Abstimmung darüber:
- Wie soll das definierte Ergebnis des use-cases "image und icon Erstellung" im Endergebnis aussehen?
- Wann werden icons nach den "swissbib Regeln" erstellt, wann sollen images von den definierten services bezogen werden? Sind die Regeln zur Erstellung der icons irgendwo festgehalten oder nur im code zu finden? Wenn letzeres, wo genau, dies um den Aufwand von Matthias in Grenzen zu halten.
- soll es eine Reihenfolge des Ablaufs geben? Zuerst icon - Erstellung, dann der Versuch des Bezugs von images durch definierte services?
- gibt es bereits aktuell (??) (oder soll es in Zukunft) Abhängigkeiten zwischen diesen beiden Implementierungen zum Beipiel in folgender Form geben: icon-Mechanismus benutzt den image-Mechanismus zur Anfrage, ob image vorhanden. Wenn nein, wird dieses oder jenes icon erstellt. Zur Zeit würde ich das als schlechte Lösung einstufen. 

Die Ziellösung können wir hier gemeinsam in diesem issue erarbeiten. Mittel können u.a. mündliche Beschreibungen oder auch sog. Pseudocode sein.

Vielen Dank! Günter

**Comment by oschihin** [comment]
@guenterh @edelm @witzigs 
## Ziel
* Der bisherige Stand muss erhalten und optimiert werden:
 * Anzeige von Bildern aus dem Cover Generator (amazon, google, hier passieren übrigens auch Erweiterungen im Core, siehe https://github.com/vufind-org/vufind/pull/507)
 * Anzeige der Bilder aus eigens definierten Diensten (e-manuscripta, e-rara, e-codices, usw.). 
   * Die Implementierung ist, wie in VF core auch, hier: \Swissbib\RecordDriver\SolrMarc::getThumbnail
    * Eine etwas veraltete Doku ist hier: http://www.swissbib.org/wiki/index.php?title=Thumbnail_locations
 * Anzeige von Format-Icons, wenn kein Coverbild angezeigt werden kann
 * Das hässliche No-Image-available muss endlich weg (#293)
* Ob der Aufruf des Cover Generators in einem View-Helper (wie jetzt) passiert, oder ob sich das vereinfachen lässt, weiss ich nicht.

Ansonsten: KeepItSimple

**Comment by guenterh** [comment]
@oschihin @edelm @witzigs 
s. auch https://github.com/swissbib/vufind/issues/293#issuecomment-142230243

Im Sinne von KeepItSimple but not simplistic
## Background
* Thema unserer bisherigen Diskussion sind unterschiedliche Wege, die festlegen, mit welchem Verfahren icon Repräsentationen generiert werden. Welche Wege wir bisher gelegt haben, findet man hier: https://github.com/swissbib/vufind/blob/core2swissbib/module/Swissbib/src/Swissbib/RecordDriver/SolrMarc.php#L672
* Wir bauen nicht nur Wege sondern auch Wegkreuzungen. An dieser Kreuzung muss man sich für eine Richtung entscheiden: Imagegenerierung mit definierten providern, icons aufgrund von 956 oder 856 Informationen, Erara oder EManuscripta. Ist die Entscheidung mal gefallen, steigen wir auf den Berg und erreichen eine Bergspitze und keine zweite mehr. Das heisst, grundsätzlich gibt es images eines service oder icons.
* Das Schöne oder Schlimme an der Softwarentwicklung (kommt auf den Standpunkt an) ist, dass man häufig noch ein zusätzliches Butterbrot einpacken kann, um damit vielleicht doch noch die zweite Bergspitze zu erreichen. In diesem Fall ist das zusätzliche Butterbrot die Formatinformation, welche im Covergenerator ausgewertet werden kann um das definierte icon (im binären Format) an den Browser zu schicken.
* Normalerweise würde ich mich gegen die Verdoppelung von solchen Sachen wehren. Ich habe mir jedoch den Code angesehen und die Vermengung hält sich in Grenzen.

Deshalb 
## mein Lösungsvorschlag
* Mit https://github.com/swissbib/vufind/commit/cf0a4db778017139475d980a664310a8487afbc5 füge ich die Formatinformation in die URL ein, falls vorhanden. Das ist vertretbar, auch weil sie sich an dieser Stelle leicht ermitteln lässt. Was ich jedoch nicht mache: Falls die Information vorhanden ist, beziehe ich mich default-mässig auf das erste Format in der Liste. Dinge wie most specific icon oder so etwas bleiben aussen vor - im Sinne von KeepItSimple. 
* Auswerten und Umsetzen lässt sich diese Information recht einfach - was mir bisher nicht bewusst war. Vgl. https://github.com/swissbib/vufind/blob/core2swissbib/module/Swissbib/src/Swissbib/View/Helper/Record.php#L411 Dies auch, weil wir sowhl im Original VuFind Cover-Generator als auch im (aktualisierten) resources.swissbib.ch (falls wir ihn denn noch verwenden werden) Zugriff auf die Konfigurationsinfrastruktur haben.
* ich denke wir brauchen aber noch eine Person mit künstlerischen Ambitionen in unseren Reihen, die ein verschönertes image erstellt, anstelle des bisherigen noImageAvailable. Zum Beipiel für den Fall, dass wir kein Bild von den definierten services erhalten und keine Formatinformation vorliegt. Dies wäre in meinen Augen sowieso keine schlechte Lösung, die supertollen icons unserer künstlerischen Direktorin Dagmar haben mich noch nie üebrzeugt.

## weiteres Vorgehen
* ich denke, wir können mit dieser Lösung leben. Falls Einsprüche da sind, bitte melden.
* Mit Matthias habe ich heute abgemacht, dass wir uns Montagnachmittag zusammensetzen und gemeinsam entscheiden, ob wir resources.swissbib.ch weiterleben lassen wollen oder auf die Original VuFind Lösung zurückgehen. In beiden Fällen müssen wir noch Arbeit hineinstecken und beides hat seine Vor- und Nachteile. Das Leben ist schein eine furchtbare Sache.
* Ich hoffe, für Matthias ist es nun besser möglich, die issues zum Abschluss zu bringen.

Allen ein schönes WE
Günter

**Comment by oschihin** [comment]
@guenterh @edelm @witzigs 
Wir haben 13'753 Aufnahmen ohne Formatangben (http://search.swissbib.ch/solr/sb-biblio/select?q=-format%3A*&wt=json&indent=true). Dies sind 13'000 zuviel, aber bei 21 Millionen vorerst verschmerzbar. Zum letzten Punkt deshalb:
* entweder in diesen Fällen gar nichts anzeigen
* oder ein Fallback-Format-Icon (z.B. Buch = XK020000) verwenden

Ich würde ein Redesign hier nicht vermischen

**Comment by edelm** [comment]
2642c2800aa331ed1e403ca0604bb86a1d82abb3 erweitert den CoverController/Loader vom swissbib/vufind Projekt dahingehend, dass nun ein MediaTypeIcon angezeigt wird, wenn die Cover-Services kein Cover zur Verfügung stellen können. Sollte vom FormatCode kein MediaType ermittelt werden können (via mediatypesiconsfiles.ini), wird trotzdem ein not-available-Cover angezeigt.

An der Stelle des bisherigen swissbib/resources.swissbib.ch Projektes zum erhalten der Covers/Icons, soll in Zukunft das swissbib/vufind Projekt verwendet werden. Entweder über die lokale Instanz mit "externalResourcesServer=." oder wie bisher mit "externalResourcesServer=https://resources.swissbib.ch", jedoch mit vollständigem swissbib-vufind Projekt auf der Adresse, statt des reduzierten resources-Projektes.

Zusätzlich während des Implementierens Aufgefallen ist noch: Für XK020053 gibt es kein Icon. Für XK020000 gibt es keinen Eintrag in der mediatypesicons.ini,

**Comment by oschihin** [comment]
@edelm 
Zwei Hinweise:
* Die Format-Icons werden basierend auf den spezifischen Formaten generiert. Das sind die Codes in Feld 898 $a. Du verwendest einen Formatcode aus $b. Ein Formatfeld in einem swissbib-Datensatz schaut so aus, es gibt also drei (!) Formatcodes
```
898 |a BK020000  |b XK020000  |c XK020000
```
 * $a: spezifisch: Für erweiterte Suche, Icon-Anzeige und Label
 * $b: generisch: Zusammenzug verschiedener Codes für einfachen Formatfilter (Facette)
 * $c: hierarchische Formatangabe: z.Z. unbgebraucht, in Entwicklung
* In der neuen config (local/config/vufind/mediatypesiconsfiles.ini) stehen spezifische Codes, mit Ausnahme von XK020000
* Wahrscheinlich ist diese neue Konfiguration überflüssig. Das Mapping zwischen Name und image-Pfad findet in themes/sbvfrd/less/media_icons.less statt

**Comment by guenterh** [comment]
@oschihin @edelm 
Hallo zusammen,
nur ein kleiner Hinweis aus dem Off - die zusätzliche Mapping Datei ist nicht unnötig. Was wir bisher haben ist eine reine less (css) Datei. Images werden durch CSS-Anweisungen am Ende der Kette durch den Browser geladen. Bei der Covererstellung suchen wir jedoch konkret nach einem image, welches im src-Attribut des img - tags geladen wird. Da hilft uns die CSS Zusammenstellung wenig. Was wir brauchen ist ein konkretes Mapping code-x->image-y in einer ini Datei. Das hat auch etwas mit meinem Bild der Wegkreuzung zu tun. Wenn ich auf dem Weg zum image auf Basis der isbn-Nummer bin, bin ich am Weg der CSS Generierung vorbeigelaufen. 
Viele Grüsse, Günter

**Comment by guenterh** [comment]
erledigt mit R1.7.5
