### ISSUE TITLE
jusbib: erweiterte Suche 

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#271]
## Problem
Die erweiterte Suche von Jusbib hat zuviele Einträge unter "Suche verfeinern" (siehe Screenshot).
![jusbib_erweiterte_suche](https://cloud.githubusercontent.com/assets/1825990/6852661/422e8b18-d3e6-11e4-8d0f-720a7a429de1.png)

## Erste Analyse
Es handelt sich (leider) nicht einfach um ein Designproblem. Offenbar sind im klassischen Design Konfigurationen aktiv, die das verhindern. Hier müssen ev. Templates nachgezogen werden und die Einstellungen geklärt werden.

Folgende Einstellungen in config_base.ini:
```ini
displayCatTreeElement = false
adv_search_useTabs = false
adv_search_activeTabId = tab-2
classificationTrees[]   = navDrsys_Gen
classificationTrees[]   = navDrsys_D
classificationTrees[]   = navDrsys_F
```

Diese sind z.B. wirksam in diesen alten Templates:
* themes/swissbib/templates/search/advanced/solr-tabs.phtml
* themes/swissbib/templates/search/advanced.phtml
bzw. auch im SearchController:
* Swissbib/src/Swissbib/Controller/SearchController.php

## Task
* Klärung, wie die Konfigurationen die Templates beeinflussen
* Nachbau in der neuen Responsive-View

**Comment by maechler** [comment]
In der alten Lösung wurde das sehr pragmatisch direkt im Template hart codiert. Ich habe das kurz nachgebaut: https://github.com/swissbib/vufind/commit/54300f4be6d1e526f2d4e1e55b5c0194063e7734

Man könnte es natürlich noch in eine Konfiguration auslagern und so auch für alle Themes zugänglich machen. (Im Moment ist es im sbvrd Theme im Template) Ich sehe im Moment aber keinen grossen Nutzen, ausser dass man nicht ins Template muss um es zu ändern. Was meint ihr?

Zu den Konfigurationen:
```
displayCatTreeElement = false
adv_search_useTabs = false
adv_search_activeTabId = tab-2
````
Diese Konfiguration wurde benötigt um innerhalb der erweiterten Suche den Bereich "Suche verfeinern" in mehrere Tabs zu gliedern. Im ersten Tab wären die jetzigen Einstellungen und im zweiten Tab der Klassifikationsbaum. adv_search_activeTabId kann gebraucht werden um den default-mässig aktiven Tab zu konfigurieren. So wie ich das sehe funktioniert aber der ganze Mechanismus seit dem Redesign nicht mehr. Ich glaube das wurde gemacht Entweder sollte man das zurückbauen (config.ini und SearchController) oder im Redesign wieder implementieren.

```
classificationTrees[]   = navDrsys_Gen
classificationTrees[]   = navDrsys_D
classificationTrees[]   = navDrsys_F
```

Diese Konfiguration steuert welche Facetten überhaupt als Baum angezeigt werden sollen und wird noch benötigt.
