### ISSUE TITLE
jusbib: Übersetzung von zwei Klassifikationen noch nicht gemacht

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#272]
![jusbib_erweiterte_suche](https://cloud.githubusercontent.com/assets/1825990/6852690/74e2da96-d3e6-11e4-9cd2-03cb28ff47f9.png)

**Comment by ToVie** [comment]
Hi Günter

die gehören nicht übersetzt sondern ausgeblendet, da sie lediglich zum Aufbau des Baumes benötigt werden.
Im alten jusbib gibt es dafür einen Parameter in der vufind.ini, wenn mich mich nicht täusche...

Beste Grüsse
Tobias

**Comment by guenterh** [comment]
@ToVie Danke für den Hinweis!
@oschihin : Kümmerst Du Dich darum? Auf http://sb-vf20.swissbib.unibas.ch/justestrd/ ist der letzte Stand verteilt.

Grüsse, Günter

**Comment by oschihin** [comment]
@ToVie @guenterh siehe #271 , ich schliesse hier
