### ISSUE TITLE
jusbib: Gestaltung home

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#273]
* die home seite von jusbib hat enthält noch den Kasten "Stöbern im Format" - ich denke das sollte heraus
* Footer muss ausgegliedert werden
* Home-Elemente sind auch noch von Grün
* Ev. müssen Hilfeseiten überarbeitet werden
* ~~~das theme von jusbib ist im responsive design vom theme sbvfrdmulti abgeleitet gwesen. In der produktiven Umgebung von swissbib single. Ich habe das in
https://github.com/swissbib/vufind/commit/0ea6b042330af7555a1ba7c4e2b53618a7d012d6
zurückgesetzt.~~~

![jusbib_gestaltung_home](https://cloud.githubusercontent.com/assets/1825990/6852779/182e81a0-d3e7-11e4-8d88-f079f84d8f16.png)

**Comment by oschihin** [comment]
@guenterh : die Umstellung macht Sinn. Es gibt Ideen für zwei Tabs, aber das kann man dann später anschauen
