### ISSUE TITLE
Ausleihen : Zweigstellencode unübersetzt

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#276]
## Problem
Auf der Übersicht der Ausleihen ist der Code hinter dem Label "Bibliothek" nicht übersetzt. (Siehe Screenshot)

![bildschirmfoto vom 2015-03-31 18 23 27](https://cloud.githubusercontent.com/assets/2760220/6923628/2c789e3a-d7d3-11e4-8516-71a188dc363b.png)

**Comment by witzigs** [comment]
Die Übersetzung funktioniert, wenn die Zweigstellen existieren - B423 und B431 sind Berner FH-Bibliotheken, die seit Januar im NEBIS sind.

**Comment by oschihin** [comment]
sorry ;-)

Am 01.04.2015 um 08:32 schrieb Silvia Witzig:
> Closed #276 <https://github.com/swissbib/vufind/issues/276>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swissbib/vufind/issues/276#event-270323396>.
>

-- 
UNIVERSITÄT BASEL
Universitätsbibliothek
Oliver Schihin
Projekt swissbib
Schönbeinstrasse 18-20
4056 Basel, Schweiz
Tel.: +41 61 267 13 07
Fax: +41 61 267 31 03
E-Mail oliver.schihin@unibas.ch
URL http://www.swissbib.org/
