### ISSUE TITLE
rero Favoritenbibliotheken erhalten keinen Bestand zugeordnet

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#281]
@oschihin 
Hallo Oliver
wähle ich 
EPFL Lausanne - Collège de Management de la Technologie
als Favoritenbibliothel aus, erhalte ich auch bei einer Anzeige des kompletten swissbib Bestandes keine Facette für diese Bibliothek.

Ich habe im Kopf, dass Du in diesen Tagen erwähntest, unsere Zusammenstellung der rero-Bibliotheken in libadmin sei nicht mehr aktuell. Hängt das damit zusammen?

Merci, Günter

**Comment by guenterh** [comment]
getestet auf testvf.swissbib.ch (Stand letzter commit)

**Comment by oschihin** [comment]
Schliesse hier, nicht weil gelöst, sondern weil in Arbeit bei Manu
