### ISSUE TITLE
Erweiterte Suche : Verfeinern

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#282]
## Problem
Die drei Listen unter "Suche verfeinern" sind zu schmal für alle Texte.

## Task
Redesign:
* Die zwei ersten Listen sollen je 50% der Breite erhalten
* Die dritte Liste soll darunter angeordnet werden
* Die Anordnung der darunter stehenden Elemente "Treffer pro Seite" und "Erscheinungsjahr" je nach Möglichkeit

## Hinweise
* siehe auch #145

**Comment by adchsnowflake** [comment]
@oschihin 
Du schreibst:
a) "Die dritte Liste soll darunter angeordnet werden": Welche Breite soll diese Liste (Library network) einnehmen?
b) "Die Anordnung der darunter stehenden Elemente (...)": Was hast du vor dem geistigen Auge?

Um diese Anpassung möglichst deinen Wünschen entsprechend vornehmen zu können, müssen wir etwas mehr Details zu deinen Vorstellungen betreffend der Darstellung haben. Ich könnte mir zB. vorstellen, dass wir Die Selectbox aus a) eine "Zeile" runter nehmen und über die Breite von 50% laufen lassen. Die Elemente aus b) dann auf der selben Höhe wie die Box aus a) daneben abbilden.
Was sind deine Vorstellungen?

**Comment by oschihin** [comment]
@adchsnowflake Ich kann mir das gut so vorstellen wie von dir geschildert:
1. Boxen "Sprache" / "Format" auf einer Zeile je ca. 50%
2. Box "Bibliotheksverbund" bzw. "Bibliothek" (bei swissbib Basel Bern) darunter 50%
3. Weitere Einschränkungsmöglichkeiten daneben
Vorausgesetzt, die Informationen passen hinein. Aber davon gehe ich aktuell aus
