### ISSUE TITLE
Footer : Einträge werden nicht übersetzt

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#284]
## Problem
Im Footer werden die Einträge bei einem Sprachenwechsel nicht übersetzt (z.B. Favoriten, Merklisten, Einstellungen).

**Comment by guenterh** [comment]
@witzigs @oschihin 

Hallo Silvia
mit https://github.com/swissbib/vufind/commit/239ed9863e7de2982a0718bad1e64ce675a246cf
habe ich einen 'schnellen' patch für das Problem erstellt. Im Template habe ich kurz das Problem beschrieben.
Bei mir erscheinen nun die Übersezungen im Footer (auch die breadcrumbs werden korrekt übersetzt)
Kannst Du dir das mal ansehen und mir Feedback geben, ob dadurch auch bei Dir (und devbabe) die fehlenden Übersetzungen verschwinden?
Abhängig von Deinem Ergebnis schreibe ich der Liste.

Viele Grüsse

Günter

**Comment by witzigs** [comment]
@guenterh 

Hallo Günter
Stand damit bei mir lokal und auf devbabe: 
*Breadcrumbs werden nicht übersetzt
*Im Footer werden die Menüpunkte übersetzt, die Titel (my swissbib, Suchoptionen, Information) jedoch nicht

**Comment by guenterh** [comment]
@witzigs 
bitte branch
https://github.com/swissbib/vufind/tree/feature/fixTranslations
testen, Günter

**Comment by witzigs** [comment]
Dieses Übersetzungsproblem ist gelöst - alle Einträge im Footer werden übersetzt.
