### ISSUE TITLE
"No image available" statt Formaticons oder Covers

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#293]
Bei einigen Treffern wird statt der neuen Formaticons noch immer das alte "No image available"-Ersatzbild angzeigt.
Beispiel: http://devbabe.swissbib.ch/Record/27286191X

**Comment by guenterh** [comment]
@witzigs Hallo Silvia: kannst Du mir mal erklären, nach welchen Regeln diese icons angezeigt werden sollen? Genauer gefragt: Wann gibt es Formaticons und wann nicht? - Danke! Günter

**Comment by witzigs** [comment]
Dieses Problem tritt weiterhin auf. 
In gewissen Fällen wird nach einem Reload der Seite oder nachdem man aus der Trefferliste auf die Vollansicht gesprungen ist, ein Coverbild angezeigt. Der umgekehrte Fall tritt ebenfalls auf: auf der Trefferliste hat es ein Coverbild, in der Vollansicht nicht mehr.
Beispiele: 
http://baselbern.swissbib.ch/Record/273514466
http://baselbern.swissbib.ch/Record/ssj0000091438

In anderen Fällen wird nur das "No image available"-Icon angezeigt. 
Beispiele:
http://baselbern.swissbib.ch/Record/ssj0001092706
http://baselbern.swissbib.ch/Record/300371594

@guenterh 
Kannst du dir das mal ansehen?

Zur deiner Frage oben:
Formaticons sollten angezeigt werden, sobald kein Coverbild zur Verfügung steht. Das "No image available"-Icon sollte in keinem Fall mehr angezeigt werden.

**Comment by guenterh** [comment]
@witzigs 
Danke für die zusätzlichen Infos!
Das Problem ist sinnvoll im Rahmen des Updates der Komponente resources.swissbib.ch zu lösen.
Diesen task habe ich vor einiger Zeit mal begonnen, bin jedoch nicht zum Abschluss gekommen.

Ich kann nicht versprechen, dass ich das bereits mit dem Wechsel auf 2.5 umsetze. Komme sonst einfach nicht zu sonstigen sehr wichtigen tasks.

Evtl kann ich das in meinen Vortrag in Konstanz als Beipiel mit einbeziehen (und damit auch die Implementierung bei uns verbinden). Es geht hierbei um Modularisierung von Funktionen.

Viele Grüsse
Günter

**Comment by edelm** [comment]
Habe mal Test gemacht mit CoverServiceProvidern Amazon, Google  und OpenLibrary. Cache gelöscht, leere Suche, erste 100 Treffer angesehen. OpenLibrary gibt 6 Covers, Google 60 Covers und Amazon zuerst 11, dann bei wiederholenden PageReloads 18, 23 etc... Nur bei Amazon erhöht sich die Anzahl covers bei Reloads.
Meine Folgerung daraus: Google scheint mit Abstand der beste CoverServiceProvider zu sein.

**Comment by guenterh** [comment]
erledigt mit R1.7.5
