### ISSUE TITLE
Anpassungen an den Facetten - Übersetzungen

### ISSUE THREAD

**Issue by ToVie** [swissbib/vufind#3]
Story
--- 
In swissbib können für spezifische Anwendungszwecke jeweils eigene Sprachdateien in Unterverzeichnissen erstellt werden. So z.B. für Bibliotheksnamen. vufind bringt diese Funktionalität nicht mit und schreibt alles in eine unhandliche Sprachdatei. Die Vorteile der modularen swissbib-Lösung sind evident:
    - durch die Gliederung der Sprachdateien in verschiedenen Unterverzeichnissen werden die jeweiligen Sprachdateien besser wartbar (z.B. für Sprachcodes, Bibliothekscodes, Formatcodes)
    - Das Zend-Framework bietet hierfür bereits Mechanismen out-of-the-box, die vufind aber nicht nutzt.

Akzeptanzkriterien
---
1. Der bereits bestehende Translate-Mechanismus von swissbib ist per Pull-request im Core verankert und in swissbib RD verfügbar.
2. Dazu werden die bislang verfügbaren Unterordner in local/languages eingebunden

**Comment by guenterh** [comment]
für unsere Zwecke behoben
