### ISSUE TITLE
 Trefferliste verliert die Sortierung, wenn mit dem Pager der Vollanzeige über die Menge der pro Seite angezeigten Treffer hinausgeblättert wird

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#301]
[Übernahme von swissbib/sbvf2#538]
Besteht auch in der neuen Oberfläche
## Problembeschreibung

Trefferliste verliert die Sortierung, wenn mit dem Pager der Vollanzeige über die Menge der pro Seite angezeigten Treffer hinausgeblättert wird.
## Replikation
1. Suche nach "mannschaftssport" (228 Treffer)
2. Die Trefferliste steht auf "Sortierung: Relevanz" und "Treffermenge: 20"
3. Ändere "Sortierung" von "Relevanz" nach "Neuestes zuerst"
4. Gehe zu Treffer 19 auf der Trefferliste und springe zu Vollanzeige
5. Blättere auf der Vollanzeige von 19 bis 21 und drücke den Button "zurück zur Trefferliste"
6. Kontrolle: die Sortierung der Trefferliste ist nicht mehr "neuestes zuerst" sondern "Relevanz"
## Gemeldet von

Der Bug wurde von einem swissbib-Nutzer über die Feedback-Funktion gemeldet:
Ticket Nr. 182

**Comment by guenterh** [comment]
Ein ähnlicher Effekt (pager läuft über die Länge der Suchliste in der Vollanzeige hinaus) scheint bei folgender Abfrage aufzutreten

In Solr:
http://sb-s16.swissbib.unibas.ch:8080/solr/sb-biblio/select?facet.field=e_institution_str_mv&facet.field=navSub_orange&facet.field=navAuthor_orange&facet.field=format&facet.field=language&facet.field=navSubform&facet.field=institution&facet.field=publishDate&qt=edismax&ps=2&hl=true&json.nl=arrarr&bf=recip%28abs%28ms%28NOW/DAY,freshness%29%29,3.16e-10,100,100%29&fl=*,score&hl.fragsize=250&start=0&q.op=AND&sort=score+desc&rows=20&hl.simple.pre={{{{START_HILITE}}}}&facet.limit=100&q=phil+zs&hl.simple.post={{{{END_HILITE}}}}&spellcheck=false&qf=title_short^1000+title_alt^200+title_sub^200+title_old^200+title_new^200+author^750+author_additional^100+author_additional_dsv11_txt_mv^100+title_additional_dsv11_txt_mv^100+series^200+topic^500+addfields_txt_mv^50+publplace_txt_mv^25+publplace_dsv11_txt_mv^25+fulltext+callnumber^1000+ctrlnum^1000+publishDate+isbn+variant_isbn_isn_mv+issn+localcode+id&pf=title_short^1000&facet.mincount=1&hl.fl=fulltext&facet=true&wt=XML&facet.sort=count


in VuFind:
http://baselbern.swissbib.ch/Search/Results?lookfor=phil+zs&type=AllFields&limit=20&sort=relevance

hängen die beiden Effekte zusammen?

**Comment by witzigs** [comment]
Der oben beschriebene Effekt tritt auch bei folgender Abfrage auf:
http://baselbern.swissbib.ch/Search/Results?lookfor=Ost-West-Konflikt&type=Subject&page=2&filter[]=navSub_orange%3A%22Sowjetunion%22&filter[]=navSub_orange%3A%22Vorgeschichte%22

Anzahl Treffer: 22, mit paging in der Vollanzeige kommt man auf 29 Treffer, die nicht auf der ursprünglichen Trefferliste auftauchen, die aber für die Abfrage relevant sind.

**Comment by mschwendener** [comment]
Weitere Ungereimtheit: 
- Eingabe *Zolli Basel*
- 41 Treffer
- Anzahl Treffer pro Seite auf 40 umstellen -> 2 Seiten
- Am Schluss der 1. Seite auf den Titel klicken (= Treffer 40 von 41)
- Mit dem kleinen Pfeil zur nächsten Aufnahme springen
=> Springt auf 25 von 41 (anstatt 41 von 41)

Wenn ich mich durchklicke, bis ich wieder auf Treffer 40 bin, spickt er mich anschliessend wieder auf Treffer 25 anstatt Treffer 41 anzuzeigen. 

-----

Verhalten bei *basel botanik*
- Treffer pro Seite auf 100 umstellen -> 610 Treffer = 7 Seiten
- Schluss der Seiten, inkl. Seite 6, verhält sich wie erwartet
- ganz am Schluss dann aber das Verhalten wie in den andern Meldungen beschrieben: kann mich von Treffer 600 durchklicken zu 611 etc., obwohl nur 610 Treffer
=> Sehe dann in den Treffern aber nur noch *basel*, nicht mehr *botanik*

**Comment by edelm** [comment]
Das "über die Trefferanzahl hinausblättern" konnte ich nicht mehr nachvollziehen. Das Verlieren des Sortierungskriteriums konnte ich immer noch nachvollziehen.

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sortierung Trefferliste/Detailanzeige #301 (05/2015-bug)](https://trello.com/c/9j9LeXkN/85-sortierung-trefferliste-detailanzeige-301-05-2015-bug)

**Comment by witzigs** [comment]
Beide Punkte lassen sich produktiv nicht mehr nachvollziehen.
