### ISSUE TITLE
DOI-Suche funktioniert nicht

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#302]
[Übernahme von swissbib/sbvf2#366]

In der erweiterten Suche, DOI
10.1093/acprof:oso/9780199230938.001.0001

keine Treffer.
Hat wahrscheinlich mit Punkten und Schrägstrichen zu tun.

**Comment by witzigs** [comment]
Das Problem ist nicht die Suche nach DOI sondern die in der DOI enthaltenen Doppelpunkte (siehe auch sbvf2/#125).

Suchen nach den folgenden DOIs (in der erweiterten Suche über ISBN/ISSN/ISMN/URN) funktionieren:
10.5169/seals-358091
10.5169/seals-358089
10.1016/j.biopsych.2014.05.003

Was nicht funktioniert ist z.B. die Abfrage der folgenden URN:
urn:nbn:ch:bel-bau-diss108444

Diese Abfrage generiert einen Fehler: http://devbabe.swissbib.ch/Search/Results?sort=relevance&advancedSearchFormRequest=advancedSearchFormRequest&join=AND&bool0[]=AND&lookfor0[]=urn%3Anbn%3Ach%3Abel-bau-diss108444&type0[]=ISN&lookfor0[]=&type0[]=AllFields&lookfor0[]=&type0[]=AllFields&daterange[]=publishDate&publishDatefrom=&publishDateto=&limit=20

VuFind sieht bei einer Fehlermeldung von Solr eine Prüfung und Korrektur des query strings vor (fixBadQuery, vgl. https://vufind.org/jira/browse/VUFIND-879), die u.a. Doppelpunkte auskommentieren würde.
In swissbib wird die Korrektur nicht aktiv, da die Fehlermeldungung von solr nicht den von VuFind erwarteten Tag "VuFind\Search\ParserError" erhält.

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [DOI-Suche funktioniert nicht #302 (05/2015-)](https://trello.com/c/Ki3pn98a/86-doi-suche-funktioniert-nicht-302-05-2015)

**Comment by guenterh** [comment]
see also: https://github.com/swissbib/sruServer/issues/26
@liowalter @basimar  @edelm  fyi
this topic "improve search quality" is one of the most important we have
next step before we are trying to tackle it: update to SOLR 6 - should be done until, hopefully, end of August

**Comment by witzigs** [comment]
Suche nach urn:nbn:ch:bel-bau-diss108444 über erweiterte Suche ISBN/ISSN/ISMN/URN gibt mit Solr 7 eine whoops-page.

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [302](https://trello.com/c/CKPzDhTv/133-302)

**Comment by liowalter** [comment]
see #686 for the fix
