### ISSUE TITLE
Kleine Übersetzungssachen (im Core)

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#305]
1. Fehlerseite IT (AErrore)
![screenshot-hbabkipwxmwd8jqf3huceqjx3brlqlnxal0gc3l89l7mhxwnyy1431090576449](https://cloud.githubusercontent.com/assets/2760220/7581033/563032d0-f87e-11e4-8802-cf5360a6cf89.png)

2. Suchhilfe FR (von Nicolas gemeldet, muss ich nochmal suchen

## Task
* Korrigieren
* PR für Core machen

**Comment by mschwendener** [comment]
Zu 1.: vorallem sollte die Emailadresse library@catalog.ch nicht so stehenbleiben (alle Sprachen). Hab's ausprobiert: geht ins Leere

**Comment by witzigs** [comment]
Das hier ist auch zum Korrigieren:
in der de.ini: On Reserve = "Vorgemerkt" statt On Reserve = "Vorgemerkt2"

**Comment by oschihin** [comment]
Erledigt mit https://github.com/vufind-org/vufind/pull/425
