### ISSUE TITLE
Sync mit libadmin in Produktion nicht mehr aktiv

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#315]
## Problem
Gemäss Meldung von Manu funktioniert der nächtliche Sync nicht mehr: "Ist mir aufgefallen, dass die libadmin-Änderungen nicht (mehr) über Nacht eingespielt werden: habe bei B404 ein Detail geändert vor ein paar Tagen (in Absprache mit Chantal), ist weder auf grün noch auf orange zu sehen, weder auf https://www.swissbib.ch/MyResearch/Favorites noch auf swissbib.ch/Search/Results/Swissbib?type=AllFields&filter[]=institution%3A"B404": heisst in libadmin (UB ZB) , nicht mehr (ZB)."

**Comment by mschwendener** [comment]
Inzwischen ist die Anzeige B404 aktualisiert (war heute am früheren Vormittag noch nicht so) - ich prüfe an anderem Bsp.

**Comment by guenterh** [comment]
@mschwendener
@oschihin 
@witzigs 

Liebe Manu,

Du musst nicht mehr prüfen. Ich habe den Update sowohl bei green als auch orange manuell gestartet.

Das Problem war: Der automatische Prozess, der den content aus libadmin  in ein Verzeichnis temporär ablegt, hatte für das Verzeichnis nicht die ausreichende Berechtigung.
Weiss im Moment nicht, was sich geändert hat. Früher klappte das immer.

Ich denke, wir können das Problem so lösen, dass Du jede Nacht um 24:00 Uhr aufstehst und die Prozesse per Hand startest! ....

Ich kümmere mich darum.

Viele Grüsse

Günter

**Comment by mschwendener** [comment]
> jede Nacht um 24:00 Uhr 
ok :)

**Comment by oschihin** [comment]
ok, wir tragen deinen Wecker in der crontab ein

Am 20.05.2015 um 11:47 schrieb mschwendener:
>     jede Nacht um 24:00 Uhr
>     ok :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swissbib/vufind/issues/315#issuecomment-103828939>.
>

-- 
UNIVERSITÄT BASEL
Universitätsbibliothek
Oliver Schihin
Projekt swissbib
Schönbeinstrasse 18-20
4056 Basel, Schweiz
Tel.: +41 61 267 13 07
Fax: +41 61 267 31 03
E-Mail oliver.schihin@unibas.ch
URL http://www.swissbib.org/

**Comment by mschwendener** [comment]
morgens um 7 wäre schwieriger als 24 h

**Comment by guenterh** [comment]
@oschihin @witzigs 
Hallo zusammen, 
bin gerade dabei, mit die VuFind Sachen wieder anzusehen. Deswegen auch ein Blick in diesen issue.
Aktuell war bei uns folgender Stand:
Die produktiven Systeme (green und orange) sind seit dem 11. Juni nicht mehr aktualisiert worden. Jusbib (sb-vf8) war ok. (Ich habe jetzt wieder 'per Hand' aktualisiert - vorher die Berechtigungen gesetzt.
Der Grund war überall der gleiche. Es fehlte eine Schreibberechtigung auf local/cache/language/cli

Kann es sein, dass Ihr am 11. Juni eine Aktualisierung auf die neue Version gemacht habt?
Ich hatte die Verteilscripte vor Berlin so angepasst, dass die Rechte stimmen (für das Verteilen) Meine Vermutung: dies ist beim regelmässigen Deployment noch nicht der Fall. Ich kümmere mich darum.
