### ISSUE TITLE
Irritierendes Verhalten der Sidebar / Anchor in /Libraries

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#321]
## Problem
(von @mschwendener gemeldet)
* Wenn ich auf http://baselbern.swissbib.ch/Libraries rechts auf "Freier Zugang - Online" klicke, springt der dunkle Balken auf "IDS Basel Bern".
* Auf https://www.swissbib.ch/Libraries ist es umgekehrt: wenn ich rechts auf den untersten Punkt "Schweizerische Nationalbibliothek > HelveticArchives" klicke, springt der markierte Balken auf "Schweizer Plakatsammlung".

**Comment by edelm** [comment]
Scheint gefixt (bei mir funktioniert der erste Link korrekt) oder nicht mehr relevant (der 2te Link existiert bei mir nicht [mehr]).

**Comment by mschwendener** [comment]
@edelm stimmt
