### ISSUE TITLE
Testbericht feature js-cleanup (#100)

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#323]
* Der Schlüssel eines Favoriten wird in der Box der angewählten Suchfilter nicht übersetzt.
![bildschirmfoto vom 2015-06-24 10 58 04](https://cloud.githubusercontent.com/assets/2760220/8326223/ec47ca28-1a5f-11e5-8466-b9eb4385b852.png)

**Comment by witzigs** [comment]
Gleiches gilt für Filter aus der Facette Online verfügbar.

**Comment by maechler** [comment]
Bei mir werden die Favoriten auch im aktuellen master Branch nicht übersetzt. Scheint also ein Problem unabhängig vom Issue #100 zu sein.

**Comment by maechler** [comment]
@oschihin @guenterh 

Der in diesem Issue beschriebene Fehler ist behoben und hing nicht mit dem feature/#100_javascript_cleanup zusammen.

Meines Wissens sind keine Fehler bekannt, die dieser Branch verursachen würde.
Ich denke es würde Sinn machen den Cleanup-Branch in den development Branch zu mergen, damit die Änderungen früher oder später auch im master landen.
Spricht aus eurer Sicht etwas dagegen?
