### ISSUE TITLE
jusbib : Notationsnummern fehlen in Baum

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#324]
## Problem
Im Klassifikationsbaum der View jusbib fehlen einige Nummern und ihre Untergruppen. So z.B. 18 (Rechtsphilosophie und allg. Rechtstheorie), 29  (Prozess- und Verfahrensrecht im IPR); 31 (Einzelne Gebiete des IPR), 38 (Grundrechte), 44 (Wirtschaftsrecht), 71 (Obligationenrecht und Vertragsrecht (allgemeine Literatur) .

## Erste Analyse
(Test mit Nr. 18 - Rechtsphilosophie)
* Im Index und den Daten korrekt
* Ein direkter Aufruf der Notationsnummer klappt:
https://jus.swissbib.ch/Search/Results?filter[]=navDrsys_Gen%3A%2218%22
* Die Übersetzung in languages/*ini ist vorhanden
* Im Klassifikationsbaum erscheint die Nummer nicht

Offenbar werden die Nummern beim Aufbau des Baums aus irgendwelchen Gründen nicht angezeigt. Das Problem bestand nicht in der bisherigen Oberfläche, dort wurden die jetzt fehlenden Nummern angezeigt.

**Comment by ToVie** [comment]
Da sind noch ganz andere Probleme - es fehlen auch Untergruppen, z.B. D 25.1 und D 25.2. Die Werte sind aber im Index, wie eine Suche zeigt:
- https://jus.swissbib.ch/Search/Results?filter[]=navDrsys_D%3A%22D+25.1%22
- https://jus.swissbib.ch/Search/Results?filter[]=navDrsys_D%3A%22D+25.2%22
Es ist davon auszugehen, dass aktuell ziemlich viel unterschlagen wird!

**Comment by maechler** [comment]
Der Fehler hängt mit den Änderungen zusammen, die ich gemacht habe um die PHP Notices zu entfernen. Ich kann mir im Moment nicht erklären warum das den Fehler verursacht / fixt, aber es funktioniert.

https://github.com/swissbib/vufind/commit/9bec48d6c7b2f0d7b6f0ba8a11d1744a39eef44a

Bitte schaut es euch an. Ich werde nächste Woche versuchen den Fehler zu verstehen.

**Comment by oschihin** [comment]
Der Fix ist auf http://sb-vf20.swissbib.unibas.ch/justestrd/ eingespielt. Einige Notationen werden jetzt angezeigt, aber nicht die Unterkategorien '25.1' und '25.2', die @ToVie  oben gemeldet hat. Habe Cache geleert. Ich spiele den Fix deshalb nicht auf die Produktion.

**Comment by ToVie** [comment]
@oschihin Die von mir gemeldeten Beispiele werden angezeigt. Es handelt sich bei meinen BSP. um __Eintragungen im D-Baum (Völkerrecht)__.

**Comment by oschihin** [comment]
@ToVie : Das hatte ich übersehen, die waren im D-Baum. Also, d.h. der Fix sollte das Problem lösen.

**Comment by oschihin** [comment]
@maechler :+1: danke für den Fix, er ist produktiv eingespielt. Ich schliesse hier.
