### ISSUE TITLE
Hierarchy Trees

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#325]
Die Darstellung der Hierarchy Trees soll im Zusammenhang mit der Einführung von hierarchischen Facetten (vgl. #69) überarbeitet werden.

* [x] Icons zum Aufklappen sollen klar erkennbar sein (und nicht doppelt angezeigt werden)
* [x] Muss auch auf kleinen Viewports verwendet werden können, vgl. dazu #290
* [x] Einheitliche Darstellung in allen Anwendungsbereichen (Tab Reihe / Bände, jusbib Klassifikationen, hierarchische Facetten in Side Facets)
* [x] Hierarchische Struktur muss erkennbar sein, auch bei mehreren Hierarchiestufen (z.B.: http://baselbern.swissbib.ch/Record/291101593). 
* [x] Braucht es dazu Linien und Dokument-Icons? vgl. https://www.finna.fi: hierarchische Facetten und Collections (z.B.: https://www.finna.fi/Record/sls.SLS%2B1849)
* [ ] Nicht direkt mit der Darstellung verbunden: In gewissen Einträgen werden html-Entitäten eingezeigt, siehe einige Titel in dieser Hierarchie: http://baselbern.swissbib.ch/Record/269967605
* [ ] Darstellung für hierarchische Facetten ist geklärt und schaut anständig aus (wie andere Hierarchien)

**Comment by maechler** [comment]
@oschihin @witzigs 
Ich habe den Merge mit den Hierarchischen Facetten zurückgesetzt und das ganze in einem neuen Branch veröffentlicht: https://github.com/swissbib/vufind/commits/feature/%23325_hierarchy_trees_release_08072015

Dort habe ich auch gleich den aktuellsten Stand vom master reingemerged. Dieser Branch kann jetzt zum Testen gebraucht werden.

Auf dem älteren Branch (https://github.com/swissbib/vufind/commits/feature/%23325_hierarchy_trees) werde ich jetzt mit dem Styling der hierarchischen Facetten fortfahren.

**Comment by oschihin** [comment]
@witzigs @maechler Der Branch ist auf test.swissbib.ch und http://sb-vf20.swissbib.unibas.ch/justestrd verteilt. Ich sehe aktuell keine Probleme.

**Comment by maechler** [comment]
Mir fällt auch nichts ungewöhnliches auf.

**Comment by witzigs** [comment]
Mir auch nicht, für orange habe ich lokal getestet.

**Comment by oschihin** [comment]
ist in Master gemergt und gepusht, der neue Branch wird gelöscht
