### ISSUE TITLE
Hierarchiebaum nach Merge mit letztem VF2 code nicht mehr funktional

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#326]
Nach dem Merge des letzten Standes VF2 (master) in unseren development branch wirft die Hierarchiebaum-Funktionalität  eine Exception

https://test.swissbib.ch/Record/020325118

[Fri Jul 03 11:08:00 2015] [error] [client 131.152.226.242] PHP Catchable fatal error:  Argument 1 passed to VuFind\\Hierarchy\\TreeDataSource\\Solr::__construct() must be
 an instance of VuFindSearch\\Backend\\Solr\\Connector, instance of VuFindSearch\\Service given, called in /usr/local/vufind/httpd/module/Swissbib/src/Swissbib/VuFind/Hier
archy/Factory.php on line 71 and defined in /usr/local/vufind/httpd/module/VuFind/src/VuFind/Hierarchy/TreeDataSource/Solr.php on line 83, referer: https://test.swissbib.c
h/Search/Results?lookfor=&type=AllFields&limit=20&sort=relevance

**Comment by guenterh** [comment]
@oschihin @witzigs @maechler 
Hallo zusammen,
ich habe einen patch eingestellt, mit dem der Hierarchiebaum wieder erstellt werden kann. 
https://github.com/swissbib/vufind/commit/03088e86d29082b20a39e9b99f3ed64a69931eab
Hintergrund:
VF2 core hat die die dependencies zur Erstellung des Baums geändert 
(vgl. https://github.com/swissbib/vufind/commit/2b1987c1ebc556f6bfdf646c6cfaa16f9c0f28ac
alles wird schneller..
)
Lokal wurde der Baum bei mir nun wieder angezeigt. 'Nicht' gekümmert habe ich mich um die Internas beim Hierarchiebaum. Damit habt Ihr Euch (und seid immer noch dabei) häufiger beschäftigt. Bitte ansehen - deswegen schliesse ich diesen issue jetzt noch nicht.


Der development branch auf GitHub ist nun wieder aktuell (enthält die sourcen von VF2 bis 1. Juli)
Auch die letzten Änderungen auf master sind enthalten.
Bitte für Weiterentwicklungen, die nicht master-relevant sind, development benutzen

Günter

**Comment by witzigs** [comment]
Zwei Punkte, die noch nicht funktionieren:
* Der Titel der obersten Hierarchiestufe wird nicht angezeigt
* Die Sortierung der Bände ist nicht korrekt (analog dem bei uns mal gelösten Issue #184)
