### ISSUE TITLE
Merklisten nach Merge mit letztem VF2 code

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#329]
Merklisten können nicht mehr angezeigt werden.
Merklisten erstellen oder Titel auf einer Merkliste speichern funktioniert.

**Comment by guenterh** [comment]
[Wed Jul 08 17:46:29.918592 2015] [:error] [pid 4865] [client ::1:46707] PHP Fatal error:  Call to undefined method Swissbib\\VuFind\\Search\\Favorites\\Params::set
AuthManager() in /usr/local/vufind/httpvfrd/module/Swissbib/src/Swissbib/Controller/MyResearchController.php on line 202, referer: http://localhost/vfrd/Record/3315
48437/Save



Ich schaue mir das an. Es sind, so wie ich das auf die Schnelle gesehen habe, auch sonst noch Sachen nicht in Ordnung

Günter

**Comment by guenterh** [comment]
@witzigs 
ist mit diesem commit behoben
@maechler 
Hallo Markus,
habe Deinen letzten commit auf test.swissbib.ch verteilt
Grüsse, Günter
