### ISSUE TITLE
Evaluation: Refactored Recommandation system in VF2

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#330]
@maechler @oschihin @witzigs 

# Hintergründe für die Evaluation

- Mit commit
https://github.com/swissbib/vufind/commit/d8e0011efb6e165131974fb9293db62bd4b00667
wurde durch VF2 das Recommendation System refaktorisiert (basiert neu auf dem Zend Event Manager) 
- dadurch wurden unter anderem folgende Typen neu eingeführt
-- VuFind/Search/SearchRunner
-- VuFind/Search/RecommendListener

Das Recommendation System ist für VuFind zentral. Darauf basieren verschiedenste Funktionalitäten wie:
-- Facetten
-- diverse Aneicherungen
-- Spelling System (https://github.com/vufind-org/vufind/pull/262)
-- browse indices (https://github.com/vufind-org/vufind/pull/225)
...

Durch die Einführung des SearchRunner Typs wurde der Ablauf der Initialisierung der Results/Params/Option Objekte geändert. Ebenfalls zentrale Elemente von VuFind, die von uns erweitert worden sind.

Wir planen, jetzt bestehende Recommendation Funktionen wie Facetten- und Spelling zu erweitern bzw. zu verbessern. 
Auch andere anstehende Anpassungen (multi domain translations) können von dem Refactoring betroffen sein.
Bevor wir bestehende (möglicherweise veraltete swissbib) Implementation erweitern, sollten wir die neue Implementierung kennen, verstehen und in ihren Konsequenzen einsetzen können.

Das Refactoring  hat im bestehenden code bereits Inkompatibilitaten ausgelöst (Funktionen waren nicht mehr lauffähig). Im swissbib code wurden deshalb bereits Anpassungen vorgenommen. vgl.:
https://github.com/swissbib/vufind/commit/6e98604849f50b63e26d859fd919765741b686da
oder
https://github.com/swissbib/vufind/commit/9ba19738710311c0b0147c04cc5fc0c9ac5d822d
(bezieht sich auf: https://github.com/swissbib/vufind/issues/246 und hat durch die Instantiierung von Results Objekten Bezug auf diesen task) - noch in eigenem branch und noch nicht mit development "gemerged"

Ein anderer bereits aufgenommener issue 
https://github.com/swissbib/vufind/issues/329
hat seine Ursache ebenfalls in der neuen Form des Einsatzes des SearchRunner Typs 
https://github.com/swissbib/vufind/blob/development/module/VuFind/src/VuFind/Controller/MyResearchController.php#L644
sowie Umstellung der Form der Authorisierung in diesem Bereich
https://github.com/swissbib/vufind/commit/e833afb064fcebb11017eef0d0701aa8e57a682d#diff-dbd84bab2ee8d1f228ecfb264e695533L647

# Ziel(e):
* Evaluation des neuen Event-basierten Recommendation Systems
** Beschreibung der neuen Abläufe
** wie können wir sie bei uns einsetzen (für die geplanten Erweiterungen und Anpassungen)
** welchen bestehenden swissbib code können / müssen wir wegen des Refactorings umstellen oder können wir evtl. ersatzlos streichen?
* Patchen der aktuellen Inkompatibilitäten beim merge mit VF2 auf Basis der neuen Implementierung
...

Beteiligte: 
Umsetzung/Evaluation: primär Markus / Günter
Diskussion im swissbib Team: alle

**Comment by guenterh** [comment]
vgl. auch pull request
https://github.com/vufind-org/vufind/pull/367

**Comment by maechler** [comment]
Hallo Günter

Ich habe folgende Konfiguration getestet und es scheint auch so zu funktionieren ohne, dass wir die VuFind Options-, Params- und ResultsPluginManager Konfiguration überschreiben.

```PHP
//'VuFind\SearchOptionsPluginManager' => 'Swissbib\Services\Factory::getSearchOptionsPluginManager',
//'VuFind\SearchParamsPluginManager' => 'Swissbib\Services\Factory::getSearchParamsPluginManager',
//'VuFind\SearchResultsPluginManager' => 'Swissbib\Services\Factory::getSearchResultsPluginManager',

'Swissbib\SearchOptionsPluginManager' => 'Swissbib\Services\Factory::getSearchOptionsPluginManager',
'Swissbib\SearchParamsPluginManager' => 'Swissbib\Services\Factory::getSearchParamsPluginManager',
'Swissbib\SearchResultsPluginManager' => 'Swissbib\Services\Factory::getSearchResultsPluginManager',

'VuFind\SearchRunner' => 'Swissbib\Services\Factory::getSearchRunner',
```

Ich denke es spricht aber eigentlich auch nichts dagegen folgenden Weg zu gehen:

```PHP
'VuFind\SearchOptionsPluginManager' => 'Swissbib\Services\Factory::getSearchOptionsPluginManager',
'VuFind\SearchParamsPluginManager' => 'Swissbib\Services\Factory::getSearchParamsPluginManager',
'VuFind\SearchResultsPluginManager' => 'Swissbib\Services\Factory::getSearchResultsPluginManager',
```

Hier müsste man einfach noch den Code refactoren, der z.B. die 'Swissbib\SearchOptionsPluginManager' aufruft, damit es einheitlich ist. Der Vorteil wäre wahrscheinlich, dass wir in Zukunft weniger Factory-Methoden selber implementieren müssen. (vgl. getSearchRunner)

**Comment by guenterh** [comment]
@maechler 
Hallo Markus, Danke!
Ich kann aus Deiner Zusammenstellung noch nicht ganz erkennen, dass man bei einer der beiden Varianten weniger Factory - Methoden erstellen muss. 
Beide haben Methoden getSearchResults..., getSearchParams... und getSearchOptions...
Nur sind sie unterschiedlich registriert.

Willst Du es nicht so machen, wie es Dir am besten erscheint? vielleicht zuerst auf einem eigenen branch?

Fände es schön, wenn wir immer dann, wenn Du in Basel bist, darüber kurz diskutieren könnten.

Viele Grüsse

Günter

**Comment by maechler** [comment]
Hallo Günter

Tut mir leid das mit dem eigenen Branch habe ich überlesen und erst jetzt gerade gesehen. Ich habe es jetzt im refactoring Branch gemacht, ich könnte aber diesen auch wieder zurücksetzen und die Änderungen in einem anderen Branch committen!

Ich habe jetzt alle Verwendungen von Swissbib\SearchOptionsPluginManager, Swissbib\SearchParamsPluginManager und Swissbib\SearchResultsPluginManager zu VuFind\* geändert. Vom Verhalten her ist es dasselbe wie wenn wir einen Alias definiert hätten.

An einigen Stellen haben wir die Factory Methoden nur selber implementiert, weil in der Methode 'VuFind\*' hart codiert war. Da aber neu hinter z.B. 'VuFind\SearchOptionsPluginManager' der Swissbib Manager steckt, können wir uns diese eigen Implementierung sparen. (Ich habe bei einem Beispiel einen Kommentar an dich hinterlassen)

Auch die getResultsPluginManager Methode im Search und SummonController konnte ich so entfernen. Mit deiner Implementierung war die Konfiguration ja so:
```PHP
'VuFind\SearchResultsPluginManager' => 'Swissbib\Services\Factory::getSearchResultsPluginManager',
'Swissbib\SearchResultsPluginManager' => 'Swissbib\Services\Factory::getSearchResultsPluginManager',
```

Unter VuFind\SearchResultsPluginManager und Swissbib\SearchResultsPluginManager kommt das gleiche Objekt. In der Methode getResultsManager hatten wir eine Fallunterscheidung für die beiden Services. Da aber hinter beiden Namen das gleiche Objekt steckt, können wir die Fallunterscheidung sein lassen.

Wir können das gerne nächste Woche zusammen ansehen.

Beste Grüsse
Markus

**Comment by guenterh** [comment]
@maechler Vielen Dank Markus - bis nächste Woche!
Günter

**Comment by guenterh** [comment]
Markus hat bereits die 'problematischen' Sachen für uns angepasst. Für eine weitergehende Analyse besteht im Moment kein Bedarf. Falls dieser wieder auftaucht, werden sich dei Umstände wieder geändert haben
