### ISSUE TITLE
lazy loading Marc Record

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#332]
@oschihin @witzigs 

mit dem commit vom 5. Mai 2015 
https://github.com/swissbib/vufind/blob/development/module/VuFind/src/VuFind/RecordDriver/SolrMarc.php
wurde das layz loading von Marc Records eingeführt.

Mit dieser neuen Funktionalität sollten Aufrufe wie diese 
https://github.com/swissbib/vufind/blob/master/module/Swissbib/src/Swissbib/RecordDriver/SolrMarc.php#L346
https://github.com/swissbib/vufind/blob/master/module/Swissbib/src/Swissbib/RecordDriver/SolrMarc.php#L424
https://github.com/swissbib/vufind/blob/master/module/Swissbib/src/Swissbib/RecordDriver/SolrMarc.php#L424

Neu gibt es eine magic Methode, die den Aufruf der property marcRecord als deprectated kennzeichnet
https://github.com/swissbib/vufind/blob/development/module/VuFind/src/VuFind/RecordDriver/SolrMarc.php#L1143
(erkennbar durch Aufruf von ini_set('display_errors', 1); in index.php)

Bei uns ist der Fall nochmals ein wenig speziell, da wir eine eigene property marcRecord verwenden.

Was man machen muss:
- genauere Analyse des Sachverhalts
- kann man unseren eigenen Mechanismus auf den des lazy loadings von VuFind 2 anpassen?

**Comment by maechler** [comment]
Der Aufruf der Property marcRecord habe ich bereits refactored zu getMarcRecord(). Damit sollte auch das Lazy-Loading von VuFind funktionieren.
