### ISSUE TITLE
Design / Usability improvements

### ISSUE THREAD

**Issue by maechler** [swissbib/vufind#335]
Nachfolgend einige Dinge, die auf der Oberfläche verbessert werden könnten:

- [x]  1) Grid: Das Gridsystem stimmt auf der Startseite nicht. Die Boxen sind nicht in einer Linie mit dem Logo und dem Text im Footer
- [x] 2) Die Flashmessages (Fehler beim Speichern, Erfolgreich gespeichert, etc.) haben immer die gleiche Farbe - die des Themes. Für den Benutzer hilfreicher wäre ein Ampelsystem (Grün, Orange, Rot), wahrscheinlich am Besten mit einem Grün und Orange, das nicht dem swissbib Grün und Orange entspricht.
- [x]  3) Beim Off-Canvas bei den Facetten fehlt ein Abstand beim Text "Suche verfeinern", ebenso in der erweiterten Suche bei den Überschriften.
- [x] 4) Wenn man im Konto bei den Merklisten Email, Export oder Delete drückt ohne eine Liste ausgewählt zu haben, erscheint eine Modalbox mit der Nachricht "undefined".
- [x] 5) Die Auswahl von Sprache, Format und Bibliothek in der erweiterten Suche ist sehr mühsam und unübersichtlich. Die Finnen (https://www.finna.fi/Search/Advanced) haben da eine sehr schöne Lösung mit einem einfachen jQuery Plugin. Das könnten wir bei uns auch relativ einfach einbauen und stylen.
- [x] 6) Der Suchtext wird nicht angezeigt. Bei einer einfachen Suche ist es nicht so störend wie bei einer erweiterten Suche, wo dem Benutzer jegliche Information fehlt.
- [x] 7) Bei der Auswahl der Favoriten stimmt die "Highlight"-Farbe nicht mit der Theme-Farbe überein.

**Comment by maechler** [comment]
@oschihin 

Wir haben heute über den Punkt "Der Suchtext wird nicht angezeigt." diskutiert und sind nicht zu einem Punkt gekommen. Weisst du aus welchem Grund das so ist? Absichtlich oder nicht?

**Comment by maechler** [comment]
@oschihin @witzigs @guenterh 

Zu Punkt 4)
Die Übersetzung fehlt da das Book Bag Feature nicht aktiviert ist. Bei diesem Feature kann man beliebig Bücher zur Book Bag hinzufügen um sich diese zu merken und dann entscheiden ob man sie z.B. speichern oder per E-Mail versenden möchte. Eigentlich ein schönes Feature bei dem ich glaub, dass wir das auch schon vermisst haben und nicht gewusst haben wieso es bei uns nicht läuft.
Die Konfiguration ist einfach:

```
[Site]
showBookBag = true
```

**Comment by guenterh** [comment]
@maechler 
aktivierst Du es? klingt gut und ich möchte es gerne mal sehen.
Grüsse! Günter

**Comment by maechler** [comment]
@guenterh 

https://github.com/swissbib/vufind/tree/feature/bookBag

Bei uns funktioniert das Hinzufügen im Moment nur über die Vollanzeige über das + Icon. Die BookBag selber findest du neben deinem Benutzernamen oder anmelden/abmelden im Header.

**Comment by guenterh** [comment]
@maechler 
nice!
Was mir als erstes durch den Kopf gegangen ist:
Die Anmeldung läuft bei uns, anders als VF, nicht über ein popup. Hängt vor allem mit den Mechanismen von Shibboelth zusammen (embedded Wayf)
Müssen mal schauen wie wir das machen können.

Grüsse! Günter

**Comment by oschihin** [comment]
@maechler : zum Suchtext (Punkt 6): Wenn ich mich richtig erinnere, hatten wir eine entsprechende Anzeige im letzten Design. Richtig? Wir haben das sicher nicht absichtlich ausgeschaltet. Möglichkeiten sehe ich entweder in einer Infobox (über der Liste oder rechts über den Facetten) oder mit den Breadcrumbs. Wie schaut das in VF core aus?

**Comment by maechler** [comment]
@oschihin 

Ja in VF core werden sie im Breadcrumb dargestellt (Suche: "Der Suchtext"). Mir ist als wäre das beim sbvfrd auch schon so gewesen und ging evtl. irgendwo verloren.

**Comment by maechler** [comment]
Punkt 5 wäre bereit zum Testen: 
https://github.com/swissbib/vufind/tree/feature/%23335_addsChosenMultiSelect

**Comment by oschihin** [comment]
siehe für Bookbag #359
