### ISSUE TITLE
Verhältnis VF2 core / swissbib Module (1)

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#337]
nach Diskussion mit Markus
VuFind\Search\Results\PluginiFactory:getSolr()

### Fragen:
- wie wird diese Funktion im core eingesetzt?
- sind wir damit konsistent

**Comment by edelm** [comment]
Verwendung im core mit swissbib verglichen:
- module/VuFind/src/VuFind/Controller/SearchController.php:449
- module/Swissbib/src/Swissbib/Controller/MyResearchController.php:433

Scheint konsistent zu sein.

**Comment by guenterh** [comment]
mit Matthias zusammen angesehen. Scheint nicht mehr relevant zu sein.
