### ISSUE TITLE
Verhältnis VF2 core / swissbib Module (2)

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#338]
Swissbib\Controller\MyResearchController::mylistAction

nach dem Fix eines issues bezogen auf die Authorisierung plus Aktualisierung unseres eigenen codes mit dem aus dem abgeleiteten VF Controller, hat @maechler  festgestellt, dass wir diese Methode nur noch wegen dieser Funktionalitt überschreiben:

      //GH: ermoegliche die Navigation zwischen Merkliste und Fullview
      $currentURL = $this->getRequest()->getRequestUri();
      $this->getSearchMemory()->rememberSearch($currentURL);

Frage an @witzigs:
brauchen wir das noch?

**Comment by edelm** [comment]
Im Moment wir Navigation zurück zur Merkliste über "Gespeichert in [Merkliste]" ermöglicht
![zurueckzurmerkliste](https://cloud.githubusercontent.com/assets/14071895/9957197/7adc64a6-5dfe-11e5-9cac-852f8ef55331.png)

Die alte Navigation (siehe: https://github.com/swissbib/sbvf2/issues/46) existiert nicht mehr. Die Funktion mylistAction() wird in unserem Controller nicht mehr benötigt.

**Comment by oschihin** [comment]
@guenterh @edelm : ist das noch offen oder gelöst? Soweit ich verstehe, kann man hier schliessen.

**Comment by guenterh** [comment]
@oschihin @edelm 
Hallo, wenn es so ist wie Matthias schreibt, dass die alte Navigation nicht mehr benötigt wird (und auch sonst kein für uns relevanter Unterschied besteht), dann sollte die Methode aus unserem Code raus. Machst Du das Matthias?

**Comment by edelm** [comment]
myListAction ist bereits entfernt worden mit 61e00a8 und a2ef7b6. Von dem her kann man schliessen.

**Comment by guenterh** [comment]
@edelm 
s. Kommentar Matthias -->  schliessen
