### ISSUE TITLE
Link auf FREE soll aus entsprechendem PARK-Feld stammen

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#339]
## Problem
Bei der Wahl der URL für den Button "Freier Zugang" wird der Wert aus dem Feld 856 genommen. Dies passiert in:
[APP_DIR]/themes/sbvfrd/templates/search/results/available.phtml
Dieser Link gehört nicht zwingend zur als "FREE" bezeichneten Zweigstelle, konkret, dem SWA-Zeitschriftenarchiv. Ein Beispiel ist diese Trefferliste bzw. Zeitschrift
http://baselbern.swissbib.ch/Search/Results?lookfor=265726840&type=AllFields&limit=20&sort=relevance

## Lösung
* Ev. eine präzisere Auswahl der URL im Template entwickeln.

**Comment by witzigs** [comment]
Analog zu den anderen Links auf der Trefferliste wird für den Button "Freier Zugang" das erste Feld 856 ausgewertet. Der Link wird dargestellt sofern eine Zweigstelle FREE vorkommt und es sich nicht um einen SFX-Link handelt.
Bei Auswahl des Links aus 950 des IDSBB würden wahrscheinlich weniger Links dargestellt, da auch bei freien Ressourcen ein SFX-Link gesetzt wird.

Ich schliesse hier, falls weitere Rückmeldungen kommen, öffne ich das Issue wieder.

**Comment by oschihin** [comment]
@witzigs : kannst du das an Nicolas melden?
