### ISSUE TITLE
Feedback-Link defekt

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#341]
## Problem
Der Feedback-Link auf https://www.swissbib.ch/ (unten rechts im Footer) linkt auf die Startseite. Hier sollte ein Popup des Dienstes uservoice erscheinen.

@maechler : Ging da beim JS-Cleanup was verloren?

**Comment by maechler** [comment]
@oschihin 
Die Funktion zur Initialisierung von UserVoice ist noch drin und wird auch ausgeführt. Ich weiss noch nicht was der Fehler ist, aber ich schaus mir an.

**Comment by maechler** [comment]
@oschihin 
Das Problem ist gelöst. Ich habe da einen Fehler gemacht beim Cleanup als ich 'use strict' für die Javascript Dateien eingeführt habe. 'use strict' setzt ein paar Regeln für die JavaScript Programmierung durch wie z.B. dass eine Variable immer zuerst deklariert werden muss bevor sie verwendet werden kann.
