### ISSUE TITLE
Anzeige der Adresse bei Semesterapparaten und Ausstellungen

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#343]
Übernahme von https://github.com/swissbib/sbvf2/issues/512
Sehr gewünscht, die Anzeige der Adresse bei Exemplaren in Semesterapparaten und Ausstellungen in der Spalte 'Verfügbarkeit'.

**Comment by witzigs** [comment]
Nur für Semesterapparate eingerichtet. Exemplare in Ausstellungen werden mit "Ausstellung" und der Leihfrist angezeigt, was sinnvoll ist, da Exemplare in Ausstellungen kaum für Benutzung vor Ort zugänglich sind.
