### ISSUE TITLE
Bestellverlauf: Bestandesanzeige sollte nach Anmeldung nicht wieder zugeklappt sein

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#345]
## Problem

(Übernahme von https://github.com/swissbib/sbvf2/issues/158)
soeben auf baselbern.swissbib.ch getestet. Bei mir funktioniert das korrekt

@chantalw : bitte schliessen, falls ok

**Comment by witzigs** [comment]
Verbesserungswunsch besteht weiterhin:

Problem
-----------
Wenn man nicht angemeldet ist und bestellen möchte, klickt man in der Vollanzeige bei einem bestimmten Exemplar auf "Anmelden". Nach der Anmeldung kommt man auf die Vollanzeige zurück. Das vorhin gewählte Exemplar ist jedoch wieder zugeklappt und muss neu aufgeklappt werden.

Ziel
-----
Der Bestellvorgang kann nahtlos beendet werden. Eine Wiederholung von Schritten ist nicht notwendig.

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bestellverlauf: Bestandesanzeige sollte nach Anmeldung nicht wieder zugeklappt sein #345 (08/2015-)](https://trello.com/c/8DUL6gL0/82-bestellverlauf-bestandesanzeige-sollte-nach-anmeldung-nicht-wieder-zugeklappt-sein-345-08-2015)
