### ISSUE TITLE
Integration Implementation translation MultiDomains in swissbib Module 

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#346]
Ziel: Integration des Pull Requests https://github.com/vufind-org/vufind/pull/419

* notwendige Anpassungen in https://github.com/swissbib/vufind/tree/development.mergedMultiDomains
* [x] Test des aktuellen Stands des branch
@witzigs : kannst Du das machen? Ziel: Herausfinden wo es noch hakt.
* [x] Fehler nach Anmeldung und Aufruf von http://localhost/vfrd/MyResearch/Home
Ich bekomme die exception:
Nachricht: Swissbib\VuFind\Search\Options\PluginManager::get was unable to fetch or create an instance for 
@maechler : ich meine, diese Fehlermeldung hast Du durch einen patch früher bereits behoben. Mittlerweile habe ich jedoch den Überblick verloren, was alles wo gemacht wurde und zurück in den development branch gemerged wurde. Kannst Du mir auf die Sprünge helfen? 
* [x] offen: Länge der Facettenlisten. Dies hat direkt nichts mit den Übersetzungen zu tun, wurde früher jedoch bei uns mit den Übersetzungen verwoben. Wo das neu am besten implementiert bzw wie zusätzlich konfiguriert werden kann jetzt offen. Muss ich mir Gedanken machen. Evtl. wird dies vom Core übernommen. Jedoch nicht sicher
* [x] Handling von location-idsbb (Importer Mechanismus lädt nach domain location und bildet Dateinamen nach dem Muster idsbb-[Sprachkürzel].ini
Mein aktueller Wissenstand: ExtendedIni SprachReader von VuFind unterstützt nur Dateinamen mit dem Muster [Sprachkürzel].ini innerhalb der domain. Testen! Abhänigig vom Ergebnis reagieren. Entweder Reader erweitern oder Importer ändern
* [x] in Solr/Results-getMyLibrariesFacets() gibt es noch den Aufruf der Methode getMyLibrariesFacets. Brauchen wir das noch? Wenn nein kann sowohl der Aufruf als auch die Methode entfernt werden

**Comment by maechler** [comment]
@guenterh @witzigs 

Der Fehler, den ich gefixt hatte war bei den Merklisten (https://github.com/swissbib/vufind/commit/e3a99151ef2f3e187d5c7ed3b04d166dfdb1eafd). Diese konnten nicht angezeigt werden. Die Merklisten funktionieren bei mir im aktuellen development Branch und der commit ist auch drin.
Den Fehler den du beschreibst beim Aufruf von MyReasearch/Home kann ich noch nicht nachvollziehen. Bei mir gibt es keinen Fehler.

**Comment by guenterh** [comment]
@maechler @witzigs 
Danke für die zusätzliche Information! Ich habe den Grund für die Exception gefunden.
Mit 
https://github.com/vufind-org/vufind/commit/3339efe9640bd74c52cb748f21b26099144b9b9a
eine Konfiguration entfernt, die wir z.B. in 
https://github.com/swissbib/vufind/blob/development.mergedMultiDomains/module/Swissbib/src/Swissbib/Controller/MyResearchController.php#L471
verwenden. Vermutlich noch an anderen Orten. Weiss im Moment noch nicht, wie wir die Information sonst erhalten

**Comment by guenterh** [comment]
ein anderer Kandidat für diesen Fehler:
https://github.com/swissbib/vufind/blob/development.mergedMultiDomains/themes/sbvfrd/templates/myresearch/settings.phtml#L43

**Comment by guenterh** [comment]
Arbeitsnotizen GH:
* Swissbib\VuFind\View\Helper\Root\Translate kann man wohl entfernen (nach besserem Testing)
* MyResearchController->getSortOptions() - Problem mit der Konfiguration s. oben nur vorübergehend gelöst. Jetzt statisch den Wert solr eingetragen
* themes\sbvfrd\templates\RecordDriver\SolrDefault\list-entry.phtml -> wo kommt die Methode openURLActive her?

**Comment by witzigs** [comment]
Hallo Günter

Das funktioniert korrekt so - die Standorte kommen nun auch bei den Holdings.

Liebe Grüsse
Silvia


________________________________
Von: Guenter Hipler [notifications@github.com]
Gesendet: Montag, 31. August 2015 18:09
An: swissbib/vufind
Cc: Silvia Witzig
Betreff: Re: [vufind] Integration Implementation translation MultiDomains in swissbib Module (#346)


@witzigs<https://github.com/witzigs>
Liebe Silvia
ich habe einen patch für die Übersetzung der locations eingestellt.
5f15dfa<https://github.com/swissbib/vufind/commit/5f15dfaf26274a3a0c8e9deb1109bc4add08e115>
Dies ist im Moment vorläufig. Der Importer muss noch angepasst werden.
Meine Bitte:
Kannst Du mal kurz ausprobieren, ob die Übersetzungen nun kommen? Ich hatte nur ein Beipiel:
/Record/076136957

Voraussetzung: Du musst die language files in local/language/location in die default Schreibweise umbenennen - also:
de.ini / fr.ini usw.

Vielen Dank, Günter

**Comment by guenterh** [comment]
@witzigs @edelm 
Liebe Silvia
ein bisschen habe ich dann heute doch noch machen können.  
https://github.com/swissbib/vufind/commit/e91b4f4e6c00597805cf1ed82961babab387d4b1
passt den Importmechanismus des tab40 Imports an. Neu wird in das Verzeichnis local/language/location-idsbb geschrieben. Den Holdingshelper habe ich entsprechend angepasst.
Ich habe es mal kurz getestet - aber nicht ausführlich (ich der immer von testcases spricht...)
Die Übersetzungen als Funktion sollten mehrheitlich abgeschlossen sein. Ich muss jedoch noch aufräumen (s. diesen issue) und bei den personal settings bin ich mir nicht sicher, ob alles läuft (haben wir mal besprochen)
Die Facettenlänge muss ich anpassen. Dieses 'feature' ist durch die neuen Übersetzungen nicht mehr vorhanden, die beiden Sachen haben aber inichts miteinander zu tun. Mache ich nach den Ferien.

Gute Zeit

**Comment by guenterh** [comment]
Ich habe nochmals einigen Code entfernt, der die neuen Anpassungen des Cores zur Integration von Multidomains überschrieben hat (zum Teil auch falsch war)

In den alten Implementierungen verwendeten wir ausserdem Strukturen, die zu den neuen Mechanismen nur noch zum Teil kompatibel gewesen sind. Jetzt noch sichtbar ist das an der Verwendung von Solr/Results->getResultQueryFacets() im Zusammenhang mit Solr/Results->getMyLibrariesFacets()
Ich habe im Moment aber zuwenig Zeit, dies alles im Detail zu bereinigen. Es sollte nun funktionieren.

Die Wegnahme von swissbib Code hatte auch zur Folge, dass die Implementierung von VuFind (getFacetList) nicht mehr die Information zur Lange der angezeigten Liste einer Facette liefert (s. dazu die Diskussion mit Demian im PullRequest, der diese Information in die SideFacet Recommendation ausgelagert haben wollte. Ich finde das nicht unbedingt notwendig. Dafür musste ich SwissBib/Recommend/SideFacets entsprechend erweitern und das template sbvfrd/templates/Recommend/SideFacets.phtml anpassen (Informationen zur Länge werden neu aus der Recommendation abgerufen)
s. dazu auch:
https://github.com/swissbib/vufind/issues/361


getMayLibraryFacets (s. Liste beim Eröffenen dieses issues) kann man nicht entfernen. Meines Wissens ist in VuFind immer noch nicht die Definition von QueryFacets möglich. Nur reine Termfacetten

@witzigs : Ich gehe davon aus, dass die Übersetzungen immer noch funktionieren. (Habe das für green und BaselBern getestet, noch nicht für Jus). Man sollte aber ein Auge darauf behalten.
