### ISSUE TITLE
Problem bei erweiterter Suche

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#347]
Bei der erweiterten Suche scheint etwas nicht ganz zu funktionieren, jedenfalls bei diesem Beispiel:
Ich setzte folgende Suchanfrage ab: 
![2015-08-17_erweiterte-suche_bsp](https://cloud.githubusercontent.com/assets/5259782/9306154/d075c86a-44f6-11e5-85d1-9ca6c163841c.jpg)
Die Abfrage erzielt keine Treffer:
![2015-08-17_keine treffer](https://cloud.githubusercontent.com/assets/5259782/9306206/131d0ab6-44f7-11e5-8b92-bc4e08f1b2a6.jpg)
Da ich das Bsp. schon verwendet habe für Demos, bin ich sicher, dass es Treffer gibt. Klicke ich nun auf "Erweiterte Suche bearbeiten", entspricht die Suchanfrage nicht mehr der zuvor eingegebenen:
![2015-08-17_erweiterte-suche-bearbeiten](https://cloud.githubusercontent.com/assets/5259782/9306305/bb549898-44f7-11e5-9f19-9b5ae8a1ced3.jpg)
Wenn ich bei "Format" nicht die Grobkategorien oben, sondern bei den spezifischen Kategorien weiter unten "Buch" bzw. "Artikel" anwähle, bekomme ich Treffer:
![2015-08-17_suche verfeinern format](https://cloud.githubusercontent.com/assets/5259782/9306497/fea927ac-44f8-11e5-9f40-c5884eeb8e1f.jpg)
Sieht so aus, als könnte man die Grobkategorien der Formate (auch der Sprachen?) nicht anwählen für die OR-Kombination. Wenn das so ist, wäre das einerseits sehr schade, andererseits dürften sie sicher nicht in der Auswahl erscheinen.

**Comment by witzigs** [comment]
Im Issue werden drei Probleme angesprochen:
* Doppelte Anzeige von gewählten Sprachen: Bei Deutsch, Englisch, Französisch, Italienisch wurde die Sprache, wenn als Filter gewählt, doppelt angezeigt. 
* OR-Kombination für Formatgrobkategorien nicht funktional
Beide Punkte behoben mit 15cf69a0202d91061c42c82949c7b1e0a16051ab

* Gewählte Formatgrobkategorien werden in erweiterter Suche nicht angezeigt: noch offen
