### ISSUE TITLE
Signaturen mit Doppelpunkt/Klammer werden nicht gefunden

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#348]
Analog zu swissbib/sbvf2#168:

Signaturen, die einen Doppelpunkt enthalten, werden weder über die einfache noch über die erweiterte Suche gefunden.
Der Doppelpunkt wird bei der Verarbeitung der Suche gelöscht, daher ergibt die Suche 0 Treffer.

Weiteres Beispiel:
MKB PP 305 : 27,2004

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Signaturen mit Doppelpunkt werden nicht gefunden #348 (08/2015-)](https://trello.com/c/9K7CpRZA/80-signaturen-mit-doppelpunkt-werden-nicht-gefunden-348-08-2015)

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [348](https://trello.com/c/N8netbrt/159-348)

**Comment by witzigs** [comment]
Gleiches gilt für Signaturen mit Klammern.

Beispiel: AEG F Spen (1979)

**Comment by FlorinneEgli** [comment]
Verhält sich nicht ganz gleich bei Paraphrasierung, in Erweiterter Suche unter _Signatur_:
**"**MKB PP 305 : 27,2004**"** wird gefunden
**"**AEG F Spen (1979)**"** wird nicht gefunden, Klammer muss trunkiert werden

**Comment by liowalter** [comment]
Recapitulation : 

|call number| link | found via simple search | found via call number search | found via simple search with "" enclosing the call number | found via call number search with "" enclosing the call number |
|---|---|---|---|---|---|
|  MKB PP 305 : 27,2004 |  https://www.swissbib.ch/Record/26427217X | [no](https://www.swissbib.ch/Search/Results?lookfor=MKB+PP+305+%3A+27%2C2004&type=AllFields&limit=20)   | [no](https://www.swissbib.ch/Search/Results?sort=relevance&advancedSearchFormRequest=advancedSearchFormRequest&join=AND&bool0%5B%5D=AND&lookfor0%5B%5D=MKB+PP+305+%3A+27%2C2004&type0%5B%5D=CallNumber&lookfor0%5B%5D=&type0%5B%5D=AllFields&lookfor0%5B%5D=&type0%5B%5D=AllFields&daterange%5B%5D=publishDate&publishDatefrom=&publishDateto=&limit=20)  | [yes](https://www.swissbib.ch/Search/Results?lookfor=%22MKB+PP+305+%3A+27%2C2004%22&type=AllFields&limit=20)  | [yes](https://www.swissbib.ch/Search/Results?sort=relevance&advancedSearchFormRequest=advancedSearchFormRequest&join=AND&bool0%5B%5D=AND&lookfor0%5B%5D=%22MKB+PP+305+%3A+27%2C2004%22&type0%5B%5D=CallNumber&daterange%5B%5D=publishDate&publishDatefrom=&publishDateto=&limit=20)  |
| AEG F Spen (1979)  | https://www.swissbib.ch/Record/277669472  | no  | no  | [yes](https://www.swissbib.ch/Search/Results?lookfor=%22AEG+F+Spen+%281979%29%22&type=AllFields&limit=20)  | [no](https://www.swissbib.ch/Search/Results?sort=relevance&advancedSearchFormRequest=advancedSearchFormRequest&join=AND&bool0%5B%5D=AND&lookfor0%5B%5D=%22AEG+F+Spen+%281979%29%22&type0%5B%5D=CallNumber&lookfor0%5B%5D=&type0%5B%5D=AllFields&lookfor0%5B%5D=&type0%5B%5D=AllFields&daterange%5B%5D=publishDate&publishDatefrom=&publishDateto=&limit=20)  |
| (02) 004.4 FRE  | https://www.swissbib.ch/Record/511915764  |  no | no  | yes  | no  |
| 18.01 MO WI 001  | https://www.swissbib.ch/Record/145659666  |  no | yes  | yes  | yes  |
| PER6170 | https://www.swissbib.ch/Record/315797290 | yes (10 results) | yes | yes (1 result) | yes | yes |
| UBH Kt 23420 | https://www.swissbib.ch/Record/490909868 | no | yes | yes | yes |

**Comment by liowalter** [comment]
Places to tune ? 

- https://github.com/swissbib/vufind/blob/master/local/config/vufind/searchspecs.yaml#L317
- https://github.com/swissbib/vufind/blob/master/module/Swissbib/src/Swissbib/VuFindSearch/Backend/Solr/QueryBuilder.php#L97

**Comment by guenterh** [comment]
@liowalter 
just a quick view: probably there is a combination of both but the second one might be the stronger culprit.

**Comment by liowalter** [comment]
Solr Queries : 

|call number| simple search | call number search | simple search with "" enclosing the call number | call number search with "" enclosing the call number | 
|---|---|---|---|---|
|MKB PP 305 : 27,2004|q:MKB PP 305 27,2004|q:(((callnumber:(MKBPP30527,2004)^1000 OR callnumber:(MKBPP30527,2004*))))|q:"MKB PP 305 : 27,2004"|q:(((callnumber:(MKBPP305\\:27,2004)^1000 OR callnumber:(MKBPP305\\:27,2004*))))

**Comment by liowalter** [comment]
Fixed with https://github.com/swissbib/vufind/commit/36a100f48583b4e2e8e3c29673d56f13e9e0fe85
