### ISSUE TITLE
SFX-Links / OpenURL in development

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#349]
Im core wurden diverse Anpassungen im Bereich OpenURL vorgenommen. Siehe Pull requests 397 und 398. 

Als Folge davon scheitert in Summon der Aufbau des SFX-Links und Trefferliste und Vollanzeige können nicht mehr angezeigt werden.
Von Summon wird die Verwendung der OpenURL nicht empfohlen. In Tab 2 sollen aber weiterhin SFX-Links und 360 Links von Summon parallel angeboten werden.

**Comment by guenterh** [comment]
@witzigs 
Liebe Silvia
ich habe mal einen patch eingestellt, mit dem man den summon tab nun zumindest wieder aufrufen kann.
Die beiden pullRequests habe ich mal quergelesen.
Frage: Kannst Du mir ein wenig die Hinetrgründe erläutern, was man sich dort gedacht hat (oder Du denkst was man sich gedacht haben könnte)? Wenn ich mich dort komplett einlesen muss, kostet mich das eine Menge Zeit - uff....

Schade, dass Andre Lahmann im Moment im Vaterschaftsurlaub ist (noch bis Ende September / oder in den Oktober hinein). Sonst würde ich ihn einfach mal anrufen und fragen, was sie sich dabei alles überlegt haben. 

Mit dem Patch wird noch keine OpenURL generiert. Man spricht von Regeln, es werden images generiert, scheint ja sehr kompley zu sein, die Generierung von URLs in der Bibliothek....
