### ISSUE TITLE
To Do HAN-records

### ISSUE THREAD

**Issue by annabellew** [swissbib/vufind#350]
- [x] Inhalt von 499 analog zu 490 in Tab 'Beschreibung' mit anderer Bezeichnung, z.B. 'Übergeordnete Stufe' anzeigen
- [x] Inhalt von Feld 779 im Tab 'Beschreibung' mit anderer Bezeichnung
- [x] Alle Relatoren anzeigen, welche in https://github.com/swissbib/HANTransformations/blob/master/xslt/HAN.Bestand.xslt definiert sind
- [x] Feld 340
- [x] Feld 351 anzeigen: Ev. im core-Template der Aufnahme?
- [x] Feld 541
- [x] Feld 545
- [x] Feld 561
- [x] Feld 581
- [x] Formatfacette 'Manuskript'
- [x] Default-Wert für Eingrenzung nach Erscheinungsjahr früher als 1450

**Comment by oschihin** [comment]
0d24fb8c5df546fdac702cba75fb8dd058668af5

**Comment by oschihin** [comment]
Siehe auch #352
Differenzen bei Codes rsp, pra, dis, opn, rsp klären, ebenso Trennung zwischen bkd, prt
