### ISSUE TITLE
check new feature healthCheck

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#351]
With https://github.com/vufind-org/vufind/pull/450 a new health check mechanism in LoadBalancer environments was introduced.

Analyze it!
Can we use it?

**Comment by maechler** [comment]
VuFind hat einen Health Check Mechanismus eingebaut, der dazu verwendet werden könnte zu prüfen, ob einzelne VuFind Instanzen noch funktionieren. Die URL für den Health Check sieht so aus:
http://swissbib.ch/Ajax/SystemStatus @oschihin 
--> funktioniert erst auf dem development Branch.

Wenn alles Ok ist, kommt einen Antwort mit Status-Code 200 und Response-Body OK.

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [check new feature healthCheck #351 (09/2015)](https://trello.com/c/I1AvOw8x/79-check-new-feature-healthcheck-351-09-2015)

**Comment by sonjakupfi** [comment]
Kann gemäss Diskussion vom 04.05.2016 geschlossen werden
