### ISSUE TITLE
Anzeige HAN-Relatoren

### ISSUE THREAD

**Issue by annabellew** [swissbib/vufind#352]
Indikator | Code (Beat) | CBS, wenn abweichend | Englisch | Deutsch | Französisch | Italienisch
----------- | --------------- | ------------------------------ | ----------- | ---------- | ---------------- | ------------
**Feld 901** | - | - | - | - | - | -
7 | pra | dis | Praeses | Praeses | Praeses | Praeses 
8 | rsp | opn | Respondent | Respondens | Respondens | Respondens
9 | rcp | - | Addressee | Adressat | Destinataire | Destinatario
A | ill | - | Illustrator | Illustrator | Illustrateur | Illustratore 
B | pat | - | Patron | Auftraggeber | Mécène | Mecenate
P | cre | - | Creator | Aktenbildner | Producteur de documents | Creator
**Feld 902** | - | - | - | - | - | -
1 | bnd | - | Binder | Buchbinder | Relieur | Rilegatore
2 | scr | bkd | Scriptorium | Scriptorium | Scriptorium | Scriptorium
9 | rcp | - | Addressee | Adressat | Destinataire | Destinatario
A | ill | - | Illustrator | Illustrator | Illustrateur | Illustratore 
B | pat | - | Patron | Auftraggeber | Mécène | Mecenate
P | cre | - | Creator | Aktenbildner | Producteur de documents | Creator

**Comment by witzigs** [comment]
Hier gibt es aus RDA-Perspektive bei cre ein Übersetzungsproblem. Mit RDA wird cre = geistiger Schöpfer = créateur = creator verwendet.

Von mir aus passender wäre hier com = Zusammenstellender = compilateur = compiler
Definition dafür gemäss RDA:
Zusammenstellender: Eine Person, eine Familie oder eine Körperschaft, die durch Selektieren, Gliedern, Zusammentragen und Editieren von Daten und Informationen usw. für die Schaffung eines neuen Werks (z. B. eine Bibliografie, ein Verzeichnis) verantwortlich ist.
