### ISSUE TITLE
Zugangsinformation Tab2 für Externe

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#353]
@witzigs @edelm 
## Beschreibung
In swissbib Basel Bern "Artikel & mehr" erscheint bei Benutzern ausserhalb der IP-Ranges der Unis Basel und Bern eine Textnachricht, die darauf aufmerksam macht, dass kein Zugang zu E-Ressourcen besteht. Diese Funktionalität ist als Teil der Datenbankempfehlungen von summon implementiert.
Konfiguration: https://github.com/swissbib/vufind/blob/development/local/config/vufind/TargetsProxy.ini
Klassen: https://github.com/swissbib/vufind/tree/development/module/Swissbib/src/Swissbib/TargetsProxy
View: https://github.com/swissbib/vufind/blob/development/themes/sbvfrdmulti/templates/Recommend/SummonDatabases.phtml
Die Datenbankvorschläge wurden unterdessen deaktiviert (siehe Template oben). Diese Implementierung ist unglücklich. Die Datenbankempfehlung könnte auch in der summon.ini deaktiviert werden. Das würde aber aktuelll auch unsere Benutzernachricht deaktivieren.

## Ziel
* [x] Beibehaltung der Funktionalität (Nachricht auf der Oberfläche, konfigurierbare IP-Ranges)
* [x] Eigener "Service" / Recommendation oder ähnliche Implementierung mit Standard-Mechanismen von VuFind

(hatte auf der Liste mal von einer Implementierung einer ähnlichen Funktionalität gelesen, finde es jetzt aber nicht mehr).

**Comment by edelm** [comment]
Neuer Recommend für IP-Range implementiert.
