### ISSUE TITLE
Pfeil statt Klickfinger

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#356]
## Problem
Auf den Facetteneinträgen von test.swissbib.ch erscheint kein "Klickfinger" mehr, sondern nur der normale Mauspfeil. Auf swissbib.ch ist nach wie vor das Händchen da. Ich bin auf Linux/Firefox

@edelm @maechler 
* Wie wird das gesteuert?
* Sollte wieder wie vorher funktionieren, bei Links soll der Mauszeiger konsistent  Klickfinger angezeigt werden.

**Comment by oschihin** [comment]
@edelm : das ging schnell, siehe https://github.com/vufind-org/vufind/pull/466
wahrscheinlich können wir zur Lösung den Commit https://github.com/vufind-org/vufind/commit/b019cf258d16a54d4492b10292f6f564e6f63b5e per cherry-pick reinziehen.

**Comment by edelm** [comment]
cherry-pick'ed mit cd8bcda75198257c184210b423c3633c3fe25f5f
