### ISSUE TITLE
Darstellung Hierarchien nicht korrekt

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#357]
(Fortsetzung von Issue #326, Punkte gemäss @witzigs )
## Problem
Folgende Punkte funktionieren bei der Darstellung des Hierarchiebaums in "Reihe / Bände" nach der Integration von VuFind 2.5 nicht mehr:
* [x] Der Titel der obersten Hierarchiestufe wird nicht angezeigt
* [x] Die Sortierung der Bände ist nicht korrekt (analog dem bei uns mal gelösten Issue #184)
* [x] Wenn man einen Band anklickt, springt man in der Vollanzeige des Bandes zwar auf den Tab Reihe/Bände, die Hierarchie bleibt jedoch zugeklappt.

**Comment by witzigs** [comment]
sieht für orange und grün gut aus - ich schliesse hier
