### ISSUE TITLE
Suchfunktion in Hierarchiebaum funktioniert nicht

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#360]
## Problem
Die Suchfunktion im Tab "Reihe / Bände", in der man nach "Titel" oder "Alle Felder" suchen kann, hat keinen sichtbaren Effekt. Weder springt man zum entsprechenden Eintrag in der Hierarchie, noch wird dieser markiert.

## Tasks
* [x] Analyse, wie diese Suche überhaupt funktioniert
* [x] Entscheid, entweder auskommentieren / deaktivieren oder fixen, so dass Benutzerinnen tatsächlich damit umgehen können (aktuell verwirrt das Suchfeld nur)

**Comment by edelm** [comment]
Suchfunktion gefixt mit https://github.com/swissbib/vufind/commit/5c5b8da42f23352624f859acd1780db8c775f4d5

**Comment by oschihin** [comment]
@edelm : Super. Aber wir haben dasselbe Problem wie letzthin mit dem CSS-Fix. Es handelt sich um ein JS des Core-Themes 'bootstrap3', das wir nicht selbst bearbeiten sollten. D.h., entweder müssen wir das überschreiben (wie das bei JS geht, weiss ich nicht, da kann sicher @maechler Auskunft geben). Oder, noch besser, deine Lösung ist generisch, dann sollten wir das mit einem Pull Request zum Core machen.
Grüsse aus Hamburg

**Comment by edelm** [comment]
Da es eine Anpassung für Änderungen in Swissbib\VuFind\Hierarchy\TreeRenderer\JSTree.php ist, denke ich es ist besser, wenn wir es lokal in das Theme "sbvfrd" legen. Ich recherchiere noch, ob wir das ganze File hierarchyTree.js überschreiben müssen, oder wir die Funktionen einzeln überschreiben und hinzufügen können.

**Comment by chantalw** [comment]
#190
