### ISSUE TITLE
Konfiguration Facet Display Limit nicht mehr wirksam

### ISSUE THREAD

**Issue by maechler** [swissbib/vufind#361]
Der "Show more" Button erscheint nicht mehr bei den Facetten.

**Comment by maechler** [comment]
Der Fehler trat auf da bei einem Merge (9769644bd8a8b1eecf36826e079238a06d646c98) zwei Funktionen gelöscht wurden. Ich hoffe das ist manuell passiert und nicht automatisch durch git, ansonsten könnten im Zuge mit dem CodeSniffer cleanup noch mehr Files betroffen sein.
@guenterh Kannst du dich noch an Details dieses Merges erinnern?

**Comment by guenterh** [comment]
@maechler @edelm  
Hallo Markus
Details kann ich auch nicht mehr nennen. Grundsätzlich habe ich Deine CodeCleanup Anpassungen mit den parallel von mir gemachten Anpassungen für die MultiDomains ge-merged. Ich hoffe nicht, dass dadurch weiterer Code 'verlorengegangen' ist. Dazu kann ich aber keine Aussage machen. Ich denke aber eher nicht, weil seit 11 Tagen wohl keine weiteren Fehler mehr auftraten. 

Dennoch öffne ich den issue nochmals. Vielleicht können wir noch ein Auge darauf werfen.

Bis bald

Günter

**Comment by guenterh** [comment]
vergleiche https://github.com/swissbib/vufind/commit/92a4a108561d1e51490c4693cddd6ab7925fd251
und comments zu issue https://github.com/swissbib/vufind/issues/346
