### ISSUE TITLE
Kein rekursiver Aufbau von Hierarchien mehr

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#363]
## Problem
Neu wird nur noch eine einstufige Hierarchie erstellt.

Vergleiche:
* https://test.swissbib.ch/Record/274836017
* https://www.swissbib.ch/Record/274836017

Arbeiten in VuFind Core
* https://github.com/vufind-org/vufind/commit/2b1987c1ebc556f6bfdf646c6cfaa16f9c0f28ac
* https://github.com/vufind-org/vufind/commit/e0dfeb8a9356580562b9098790e656dfd4c2b58f

siehe auch #357

**Comment by maechler** [comment]
Aus irgendeinem Grund scheint es nun lokal im development Branch sowie auf devbabe zu funktionieren:

http://devbabe.swissbib.ch/Record/274836017

Vielleicht haben wir einfach einen falschen Record angeschaut beim Testen.

**Comment by maechler** [comment]
Dank dieses Records (http://devbabe.swissbib.ch/Record/274835827/HierarchyTree?hierarchy=120474018) ist mir aber gerade noch ein Fehler aufgefallen. Es reicht nicht die HTML ID aus "Level_RecordID" zusammenzusetzen, da der gleiche Record auf dem gleichen Level mehrmals vorkommen kann. 

Ich habe das hier gleich korrigiert: https://github.com/swissbib/vufind/commit/4ca61bf2fd87708844bf7964209d6ec5025628ea

Die HTML ID wird jetzt als Pfad von Record IDs bis zum Root Element zusammengesetzt. So ist die Eindeutigkeit gegeben und es entstehen solche schöne HTML IDs: 0_282735267_279961146_284985902_090904443

@edelm Evtl. relevant für die Suche in den Hierarchien. Entstehen tut das ganze in der Funktion Swissbib\VuFind\Hierarchy\TreeRenderer\JSTree->buildNodeArray. Wird auf ein Record im Baum angeklickt, wird die HTML ID als GET Parameter mitgegeben um auf der nächsten Seite dann die automatische Auswahl mit der "Scroll-to" Funktion zu ermöglichen.
