### ISSUE TITLE
Character Entities in Series/Volumes werden auf dem produktiven Server nicht richtig dargestellt

### ISSUE THREAD

**Issue by edelm** [swissbib/vufind#366]
Siehe https://www.swissbib.ch/Record/029754895/HierarchyTree?recordID=029754895&htmlID=0_029754895&hierarchy=029754895#tree-029754895 -->Hierarchie-Baum aufklappen, Element "3 : [...]"

Im genannten Beispiel werden die Quotes als "&quot;" dargestellt, weil im HTML das "&" von "&quot;" bereits zu "&amp;" umgewandelt wurde (Ergebniss im HTML: "&amp;quot;").

Interessanterweise tritt dieses Verhalten nur im Hierarchiebaum (in der Vollansicht stimmt die Darstellung) und auf dem produktiven Server auf (auf test und lokal stimmt die Darstellung).

**Comment by edelm** [comment]
Gleiches Verhalten entdeckt auf der Login-Seite für AAI auf Englisch. Interessanterweise tritt der Effekt hier sowohl auf produktiv, auf test und auch lokal auf.

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Character Entities in Series/Volumes werden auf dem produktiven Server nicht richtig dargestellt #366 (09/2015-)](https://trello.com/c/fGJl5LCg/77-character-entities-in-series-volumes-werden-auf-dem-produktiven-server-nicht-richtig-dargestellt-366-09-2015)

**Comment by sonjakupfi** [comment]
Kann nicht mehr nachvollzogen werden. Deshalb geschlossen!
