### ISSUE TITLE
Verfügbarkeitsprüfung bei der Lageplananzeige

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#367]
(Übernahme von swissbib/sbvf2#526)
## Problem

In der aktuellen Umsetzung ist es nicht möglich, für die Anzeige eines Lageplanlinks die Verfügbarkeit (ausgeliehen, etc.) abzufragen. Eine entsprechende Variable ist im Code vorbereitet, jedoch unfunktional und stets auf true gesetzt. Einen Lageplan setzen aktuell A100, B500 und HSG ein, die Verfügbarkeitsprüfung soll primär für A100 und B500 umgesetzt werden.
## Orte
- Klasse bzw. Funktionen: 
  - `/module/Swissbib/src/Swissbib/RecordDriver/Helper/LocationMap.php::isItemValidForLocationMapB500() / ::isItemValidForLocationMapA100()`
  - darin die Variable `$isItemAvailable`
  - Konfiguration: `/local/config/vufind/config_base.ini > locationMap`
## Fragen

Sind bei der Umsetzung zu klären:
- Ist eine Konfiguration möglich und überhaupt sinnvoll?

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Verfügbarkeitsprüfung bei der Lageplananzeige #367 (09/2015-wishful)](https://trello.com/c/p1jK73xt/76-verfugbarkeitsprufung-bei-der-lageplananzeige-367-09-2015-wishful)
