### ISSUE TITLE
Bandanzeige bei mehrstufigen Aufnahmen aus Holding auslösen

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#368]
(Übernahme von swissbib/sbvf2#313)

**Vorschlag:**
Anstatt die "mittelmässig gute" Lösung aus Aleph mit "aussagekräftigen Hilfetexten" nachzubauen, sollen Holdings bei mehrstufigen Aufnahmen mit einem Button ergänzt werden, der die Anzeige aller untergeordneten verknüpften Titel ermöglicht.

Dies soll nicht die Baumanzeige und allfällige weitere Elemente ersetzen sondern ergänzen.

**Hintergrund:**
 NutzerInnen die sich das Werk ausleihen wollen, sollen mit einer nützlichen Funktion belohnt werden, anstatt sich (erneut) in der Exegese von bibliothekarischem Kauderwelsch zu üben.

**Schritte dazu:**
1. Auswertung des Feldes =897 --$a b  $b 7  => gibt Auskunft über verknüpfte untergeordnete Aufnahmen
2. Nachnutzung bestehender Mechanismen zur Suche oder evtl. eigener Index für die Abfrage dieser Werke
3. Falls das Holding aussagekräftig ist (i.e. einer Zweigstelle zugeordnet werden kann), Einschränkung der Treffermenge auf diese Zweigstelle.
4. Anzeige der gefilterten Liste (evtl. mit eigenem Sortierkriterium nach Bänden)

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bandanzeige bei mehrstufigen Aufnahmen aus Holding auslösen #368 (09/2015-useful)](https://trello.com/c/NGD7Ci99/75-bandanzeige-bei-mehrstufigen-aufnahmen-aus-holding-auslosen-368-09-2015-useful)
