### ISSUE TITLE
Manuelles Auf- und Zuklappen der Facetten

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#370]
Was von Hand zugeklappt wird, sollte zugeklappt bleiben, bis die Nutzerin es aktiv wieder aufklappt (wie vor der Umstellung auf responsive). Aktuell werden nach jeder Aktion der Nutzerin (auswählen eines Facettenkriteriums, neue Suche, etc.) die zugeklappten Facetten wieder aufgeklappt.

(In "my swissbib" funktioniert das besser: Wenn man das Menü "Konto IDS Basel Bern" zuklappt, bleibt es so, auch nachdem man zu Merklisten oder Einstellungen navigiert ist.)

**Comment by edelm** [comment]
Wurde im Core implementiert: https://github.com/vufind-org/vufind/pull/775

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Manuelles Auf- und Zuklappen der Facetten #370 (09/2015-wishful)](https://trello.com/c/FxASgLZF/74-manuelles-auf-und-zuklappen-der-facetten-370-09-2015-wishful)
