### ISSUE TITLE
Darstellung Titel arabische Transliteration

### ISSUE THREAD

**Issue by edelm** [swissbib/vufind#373]
siehe: https://www.swissbib.ch/Search/Results?type=AllFields&sort=title_sort+desc&filter[]=language%3A%22ara%22&filter[]=navAuthor_full%3A%22B%C3%BCrkli%2C+Friedrich+Paul+David%22

Font ist uneinheitlich bei font-weight 600. Mögliche Lösungen: font-weight auf '400' oder 'bold'

**Comment by maechler** [comment]
Ich würde font-weight: 400 bevorzugen und dann die Schriftgrösse noch 2px-4px (auf 22px oder 24px) grösser machen. Bei font-weight: bold ist die Schrift meistens weniger sauber / klar.

**Comment by edelm** [comment]
fontweight 400 sieht für mich (ubuntu firefox+chromium) gut aus. font-size 22px würde ich vor 24px bevorzugen. evtl können sich dazu noch @guenterh und @oschihin äussern.

**Comment by oschihin** [comment]
@edelm : font-weight 400 finde ich gut, font-size 22px auch (24 px finde ich zu gross).
Würde diese Stylekorrektur gerne noch in 2.5 drin haben. Kannst du das umsetzen und noch in development mergen?

**Comment by witzigs** [comment]
@edelm 
Kannst du das auch noch für die Vollanzeige ansehen?
z.B.: http://devbabe.swissbib.ch/Record/098276115
