### ISSUE TITLE
Hardcoded Text auslagern

### ISSUE THREAD

**Issue by edelm** [swissbib/vufind#374]
Text: "There are no holdings available in the system" o.ä.

Vorkommen:
- themes/sbvfrd/templates/search/results/available.phtml
- themes/sbvfrd/templates/RecordTab/holdingils-noholdings.phtml

**Comment by maechler** [comment]
Mit dem Commit 4a78149 habe ich die Labels eingeführt. Die Texte erscheinen zum einen auf der Trefferliste und zum andern in der Vollanzeige im Tab Exemplare wenn für ein Item keine Holdings vorhanden sind.

@witzigs Könntest du die Labels noch übersetzen? (Zeile 477 und 478 in den Sprachdateien)

**Comment by witzigs** [comment]
Übersetzung ist erledigt
