### ISSUE TITLE
falsche Umsetzung von Umlauten im ProtocolWrapper

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#375]
Hallo Günter

Hier das Beispiel für einen Link, der durch den ProtocolWrapper falsch verarbeitet wird:
Record: https://www.swissbib.ch/Record/266434347 , betroffen ist der Link "Zollikofen EHB: Volltext"

In Aleph eingegeben und auch in VuFind noch so vorhanden ist der folgende Link mit codierten Sonderzeichen und Umlauten:
https://content-select.com/?fq%5B0%5D=rel_title%3A%22Zeitschrift+f%C3%BCr+P%C3%A4dagogik%22&forceauth=1

Bei Anwählen auf der Oberfläche erhält man die folgende nicht funktionierende URL mit entcodiertem Doppelpunkt, die restlichen Zeichen und Umlaute bleiben codiert:
https://content-select.com/?fq[0]=rel_title:%22Zeitschrift%20f%FCr%20P%E4dagogik%22&forceauth=1

Liebe Grüsse
Silvia

**Comment by witzigs** [comment]
Ein weiteres Beispiel dafür, Autorenname Klöti in der URL:
http://baselbern.swissbib.ch/Record/33452329X

Die URL in den Daten funktioniert: http://boris.unibe.ch/59490/1/TRANS%20Kl%C3%B6ti%20%20Map%20Collecting%20in%20Switzerland_ENGSJT%20Rev%20061013_TK%20SJT-1.pdf 

Bei Anwählen der URL auf der Oberfläche erhält man die folgende URL, die nicht funktioniert: http://boris.unibe.ch/59490/1/TRANS%20Kl%F6ti%20%20Map%20Collecting%20in%20Switzerland_ENGSJT%20Rev%20061013_TK%20SJT-1.pdf

**Comment by guenterh** [comment]
@oschihin @witzigs 
Hallo zusammen
die beiden Geschichten mit den Umlauten und Availability HSG02 sollten gelöst sein. Hier
Umlaute ProtocolWrapper
https://testvf.swissbib.ch/Record/33452329X

Availability St. Gallen
https://testvf.swissbib.ch/Record/261149997

als zwei Testfälle. 
Der request geht auf sb-vf21

Es gibt nun auch ein Verteilverfahren für externalServices. Bisher nur für das Testsystem ausprobiert, scheint aber ganz gut zu funktionieren.
Wenn ihr mir ein feedback zu den beiden Fällen gebt, setze ich das auch noch für den produktiven server sb-vf17 auf.
Oliver, ich habe das auch auf sb-vf1 ausprobiert (Konfiguration dort per Hand auf sb-vf21 gesetzt). Die Konfiguration der Gruppen in der Vollansicht ist dort aber komplett anders als bei mir lokal und auf testvf (Zum Beispiel sind dort HSG01 und HSG02 noch getrennt). Und die availability für HSB02 
funktioniert nicht. Weiss nicht was die hosts für einen Stand haben.
Grüsse, Günter

**Comment by guenterh** [comment]
@witzigs @edelm @oschihin 
* Anpassungen auch auf produktiven Host sb-vf17 verteilt
* sowohl für Test als auch Produktion stehen nun Deploymentskripte zur Verfügung. Weitere Details siehe: http://www.swissbib.org/wiki/index.php?title=Members:SupportiveServices
