### ISSUE TITLE
"Delete search" for mobile devices

### ISSUE THREAD

**Issue by maechler** [swissbib/vufind#376]
Es kam der Input, dass es auf mobilen Geräten mühsam ist die Suche zu löschen. Es sollte für mobile Endgeräte eine "Eingabe löschen" Funktion geben. Die Finnen haben das bereits implementiert: https://www.finna.fi

Wird ein Suchtext eingegeben erscheint ein Pfeil mit einem x drin. Damit kann der ganze Suchtext gelöscht werden und der Pfeil verschwindet wieder. Eine gleiche Lösung sollte für swissbib implementiert werden.

**Comment by maechler** [comment]
Ist implementiert im Branch feature/#376_delete_search_text. Das könnte problemlos in den development Branch gemerged werden.
Vorher wäre es aber gut, wenn das noch auf einen Testserver gespielt werden könnte und die Implementierung auf einem echten Smartphone getestet würde.

**Comment by cansik** [comment]
:+1:

**Comment by guenterh** [comment]
@maechler 
Hi Markus,
Danke! Habe Deinen commit auf sb-vf20 für den jus Service verteilt. Dann sieht man auch, ob Jus mit den letzten sourcen noch in Ordnung ist.
http://sb-vf20.swissbib.unibas.ch/justestrd

Sieht gut aus. Da ich, wie erzählt, seit den Ferien kein Smartphone mehr habe, kann ich es nicht wirklich testen. 
@witzigs : Silvia, schaust Du auch mal? Vielleicht kannst Du ja auch noch einen Blick auf Jus werfen. Kenne die Details zu wenig

Viele Grüsse
Günter

**Comment by maechler** [comment]
@guenterh Das ging ja sehr schnell! Habe es eben auf dem iPhone getestet, scheint zu funktionieren.
Mir ist dabei noch etwas anderes aufgefallen: https://github.com/swissbib/vufind/issues/377

**Comment by maechler** [comment]
Mir ist noch ein Fehler aufgefallen, es hat nicht funktioniert, wenn das Suchfeld von Anfang an schon gefüllt war. Ist hier 1fb56e6 gefixt.

Mir ist nochmals was sehr kleines aufgefallen: #378

**Comment by guenterh** [comment]
merged into development
