### ISSUE TITLE
Deactivate iPhone zoom on text input 

### ISSUE THREAD

**Issue by maechler** [swissbib/vufind#377]
Wird auf dem iPhone in den Suchschlitz getippt zoomt das iPhone standardmässig etwas hinein. Das führt dazu, dass die Seite nicht mehr ganz Platz hat und seitlich gescrollt werden kann. Verlässt man das Textfeld wird nicht wieder herausgezoomed und man kann weiterhin seitlich scrollen, das ist sehr unschön. Habe kurz gegoogled und das könnte das Problem lösen: http://stackoverflow.com/questions/11064237/prevent-iphone-from-zooming-form

Man müsste **user-scalable=0** im meta Tag viewport hinzufügen.

**Comment by maechler** [comment]
Ist im letzten Commit implementiert. Müsste auf einen Server gespielt werden um auf dem Handy getestet werden zu können. Sollte aber funktionieren ;)

**Comment by oschihin** [comment]
@maechler funktioniert auf Android. Bitte mit iphone testen, und schliessen

**Comment by maechler** [comment]
@oschihin Läuft auch auf dem iPhone, schliesse hier.
