### ISSUE TITLE
ISBD-Darstellung für Beschreibung

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#379]
## Problem
Die Darstellung von "Beschreibung" in der bibliografischen Beschreibung ist nicht ISBD-konform. Dies sollte korrigiert werden. Betrifft MARC-Feld 300: Vor dem Illustrationsvermerk ($b) wäre der Doppelpunkt korrekt, vor dem Begleitmaterial das Pluszeichen (und kein zusätzlicher Strichpunkt)

## Hinweise
* https://www.swissbib.ch/Record/332614468
* siehe z.B. denselben Satz im OPAC, dort heisst das Label "Umfang": http://aleph.unibas.ch/F/?local_base=DSV01&con_lng=GER&func=find-b&find_code=SYS&request=006342979

**Comment by witzigs** [comment]
siehe auch #128

**Comment by edelm** [comment]
Mit https://github.com/swissbib/vufind/blob/master/module/Swissbib/src/Swissbib/View/Helper/PhysicalDescriptions.php#L70 werden alle einzelnen Elemente der physical description mit einem Semikolon aneinandergereiht.

Laut #128 ist es kein gangbarer Weg, hinter jedes Feld 300 $a oder $b einen Punkt (+Doppelpunkt) zu setzen.

Ein zu Prüfendes Vorgehen wäre es, das Semikolon bei der Abtrennung zu entfernen. Dann würde aus "64 S ; Ill + ; 1 CD-ROM" neu "64 S Ill + 1 CD-ROM" werden. Sieht dies schöner aus?

Für eine Lösung, welche alle/die meisten Fälle korrekt abbildet, müsste man mehr Informationen über den Inhalt des Feldes haben. Evtl ist die durch Mustererkennung im String möglich? Dies sollten wir mal intern mit Bibliothekars-Experten prüfen.
