### ISSUE TITLE
Suche mit Fragezeichen am Ende

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#380]
Beispiel:
Suche über alle Felder nach: mission possible?
Liefert Treffer mit mission und possibles (verwendet also ? als Wildcard für ein Zeichen)
Der Treffer mit genau diesem Titel http://baselbern.swissbib.ch/Record/338393447 wird nicht gefunden.

VuFind sieht eine Bereinigung des Suchstrings bei einer Query mit Fragezeichen am Ende vor, damit genau dieser Fall nicht auftritt. Vgl. https://github.com/swissbib/vufind/blob/master/module/VuFindSearch/src/VuFindSearch/Backend/Solr/QueryBuilder.php#L375
Diese Bereinigung wird bei uns jedoch nicht aktiv.

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Suche mit Fragezeichen am Ende #380 (10/2015-wishful)](https://trello.com/c/h6CaXprp/73-suche-mit-fragezeichen-am-ende-380-10-2015-wishful)

**Comment by witzigs** [comment]
Das oben beschriebene Verhalten tritt produktiv nicht mehr auf.

Produktiv ist die Treffermenge jedoch zu gross. Es gibt viele Treffer mit nur Mission und ohne possible.

Auf Solr 7 ist die Treffermenge korrekt und enthält nur Treffer mit beiden Worten. Das Fragezeichen hat keine Platzhalter-Funktion, gefunden wird possible? und possible.
