### ISSUE TITLE
Suchhistorie xs/sm: Speichern/Löschen

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#382]
Auf Viewports xs und sm wird in der Suchhistorie immer "Speichern" angezeigt. Unter "Gespeicherte Suchen" sollte jedoch "Löschen" angezeigt werden.

Siehe Template: https://github.com/swissbib/vufind/blob/master/themes/sbvfrd/templates/search/history-table-flipped.phtml
Wahrscheinlich schlägt die Prüfung nach showSaved fehl.

@edelm 
Falls du den Fehler gerade siehst, wärs super wenn das noch in den Release kommen würde.

**Comment by edelm** [comment]
$this->showSaved ist leer im history-table-flipped.phtml, obwohl die condition im history.phtml richtig gesetzt wird. Ich versteh die Zusammehänge noch nicht ganz, daher lass ich es erstmal so.

**Comment by edelm** [comment]
'showSaved' muss vom history.phtml zu history-table.phtml und von dort weiter zu history-table-flipped.phtml gereicht werden. Gemacht in e9f41ca.
