### ISSUE TITLE
PHP Speicherverbrauch

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#383]
Heute morgen ist mir im error.log (Apache) von sb-vf5 folgende Meldung ins Auge gesprungen:

PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to 
allocate 32 bytes) in /usr/local/vufind/httpd/vendor/pear-pear.php.net/File_MARC/File/MARC/List.php on line 211

Schaut man sich das log an, tritt die Meldung regelmässig (und relativ häufig) auf. Ursache ist mir im Moment nicht bekannt.

Der für PHP zur Verfügung gestellte Speicher liesse sich über /etc/php.ini u.a. mit dieser Direktive
memory_limit = 128M
erhöhen.

Grundsätzlich sind solche Meldungen für mich weitere Indikatoren, dass wir den Ressourcenbedarf von VuFind begrenzen müssen (Thema in VuFind 3)

@maechler @edelm : diskutieren wir bei unserem nächsten gemeinsamen Zusammentreffen, was wir konkret kurzfristig machen können/sollten?

Günter

**Comment by guenterh** [comment]
im Moment nicht mehr aktuell
@edelm fyi - bitte regelmässig logs monitoren
@sonjakupfi - bitte in Trello schliessen (falls vorhanden)

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [PHP Speicherverbrauch #383 (10/2015-urgent!)](https://trello.com/c/wIcck29i/71-php-speicherverbrauch-383-10-2015-urgent)
