### ISSUE TITLE
Design bei Versand/Export Merkliste

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#384]
Beim Versand und beim Export einer einzelnen Merkliste ist das Design auf dem iPhone (4S) nicht optimal, der Text befindet sich ganz am linken Rand: 

![iphone_2015-10_designexport](https://cloud.githubusercontent.com/assets/5259782/10571631/4b94059a-7641-11e5-9a19-62bfeb063981.PNG)
![iphone_2015-10_designversand](https://cloud.githubusercontent.com/assets/5259782/10571630/4b940c70-7641-11e5-989e-487c2173522f.PNG)

Beim Versand & Export ALLER Merklistentitel (Ansicht "alle Merklisten") ist das Design ok.

**Comment by edelm** [comment]
Konnte mit Chromium-DevTools und auf iphone4simulator.com nicht nachvollzogen werden. Sollte noch mit einem physischen 4S getestet werden.

**Comment by guenterh** [comment]
@chantalw 
Kannst du prüfen, ob das noch aktuell ist? Ansonsten bitte schliessen.

**Comment by chantalw** [comment]
@guenterh: iPhone 4S: in safari sieht das jetzt ok aus, in firefox besteht das darstellungsproblem aber noch. ist aus meiner sicht aber nicht weiter schlimm - man kann den issue von mir aus auch schliessen.

**Comment by guenterh** [comment]
geschlossen nach Test von Chantal
