### ISSUE TITLE
Passwort Uppercase X-Server Aufruf 

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#385]
Hallo zusammen,

hier der letze Satz eines Hinweises zum Umgang mit Passwörtern beim Aufruf der X-Server Schnittstelle:

**
Ich würde beim Aufruf des X-Servers das Passwort in Uppercase übergeben (Vorsicht Umlaute). Das sollte meiner Meinung nach keine Verschlechterung bringen.
**

@edelm @luchner @witzigs 
* [x]  Matthias, kannst Du das mal zusammen mit Bernd testen, ob mit dieser Änderung die Aufrufe für HSG laufen
* [x] wenn der HSG issue behoben ist, muss man noch testen, ob die logins gegenüber Basel / Bern noch funktionieren

**Comment by edelm** [comment]
Besprochen mit Silvia, getestet und läuft.
