### ISSUE TITLE
Verfügbarkeitsabfrage bei IDSSG

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#392]
## Problem
Nach dem Merger von IDSSG2>IDSSG1 funktioniert die Verfügbarkeitsabfrage nur noch bei dem Teilbestand der Uni St. Gallen.

## Hinweise
* Klären, wie die Abfrage im availability-Service ausschaut?
* Anpassen oder Erweitern des Services

## Beispiel
* https://www.swissbib.ch/Record/261149997

**Comment by ToVie** [comment]
Aus dem Off: könnte es etwas mit der ADM-Datenbank zu tun haben? Ich sehe in den Daten, dass sämtliche Zweigstellen auf die HSD50 verweisen. Wenn man in alephe/tab/tab_sub_library.ger des IDSSG nachsehen geht, dann sind die Zweigstellen weiterhin unterschiedlichen ADMs zugeordnet...
LG Tobias

**Comment by oschihin** [comment]
Tatsächlich sind die ADMs die Knacknuss. In den Daten (<holdings>) sind sie aber korrekt in $C:HSD52 Wo siehst du das in den Daten?
Muss man genauer mit circ_status vom X-Server anschauen.

**Comment by ToVie** [comment]
ich seh das natürlich nur mit meinen beschränkten Mitteln und muss entsprechend raten. Ich kann das nur im OPAC von CBS3i ansehen. Dort steht in allen $C-Werten "HSD50".

**Comment by oschihin** [comment]
Ist ja interessant. Da steht tatsächlich immer HSD50. Im exchange-level2 hab ich angepasst, in den solr-docs auch korrekt:
```
/* map libraries of PHSG to ADM HSD52, of FHS to HSD53 */
table SSG =
        "HPHS" "HSD52",
        "HPHG" "HSD52",
        "HPHRS" "HSD52",
        "HPHOL" "HSD52",
        "HRDZJ" "HSD52",
        "HRDZS" "HSD52",
        "HRDZW" "HSD52",
        "HRPMA" "HSD52",
        "HFHS" "HSD53",
        "HFHGE" "HSD53",
        "HFHSA" "HSD53",
        default "HSD50";
```

**Comment by ToVie** [comment]
Das kann daran liegen, dass hierfür ein anderes level-2 verwendet wird. Wenn ich mich richtig erinnere, dann wird in einem ersten Schritt der Verbundcode geprüft und dann erst anhand der Zweigstellen die ADM gesetzt. Was auf CBS3i verwendet wird, können die Götter in Leiden sicher genauer sagen.

**Comment by guenterh** [comment]
@oschihin @witzigs @edelm  
Die Verfügbarkeit für ehemals HSB02 steht nun wieder zur Verfügung.
Hintergrund: Die ex-HSB02 Institutionen haben andere loan-stati als HSB01 (deutsch - was ich bisher gesehen habe: 'ausleihbar' und 'ausleihbar Buch'. Ich werde Felix ein Mail schreiben ). Diese waren noch nicht für HSB01 konfiguriert, weswegen die Response immer die Angaben für den Fallback 'consult library' zurückgeliefert hat.

Ich habe die Ergänzung bisher nur 'per Hand' auf dem produktiven server gemacht.

Ich werde mir noch überlegen, wie ich das ganze Repository und die Implementierung als solche besser zugänglich machen kann. Dazu gehört auch ein sauberer Verteilmechanismus. Das braucht aber ein wenig Zeit.

Eine Vorabversion werde ich (in einem vereinafchten Verteilverfahren) zusammen mit einer Erweiterung für die falsch codierten URLs im ProtocolWrapper morgen zusammenstellen.
