### ISSUE TITLE
Loading Alexandria

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#393]
## Thema

Unter test.swissbib.ch sind die Bestände von Alexandria neu geladen. Die neuen Daten bringen auch einige Anpassungen auf der Oberfläche mit sich.
- [x] Backlinks in der Bestandsanzeige (31a46e88a0aed119816a1d6a8fe09c39d8cd2e65)
- [x] Backlink im Feld 035 der MARC-Anzeige (31a46e88a0aed119816a1d6a8fe09c39d8cd2e65)
- [ ] Anzeige des Standortcodes 949/852 $c : ev. in Absprache mit Verbund auch übersetzen
- [ ] EOD-Button: Abklären ob gewünscht, Kriterien (Bsp.: http://www.alexandria.ch/primo_library/libweb/uploaded_files/ALEX/marc.jsp?id=21303673470001791)

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Loading Alexandria #393 (11/2015)](https://trello.com/c/gO3hiUX2/69-loading-alexandria-393-11-2015)
