### ISSUE TITLE
Zugriff auf "Non Object" im apache error log

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#395]
Mir ist gerade im Apache log von sb-vf6 forlgender Fehler aufgefallen:
[Mon Nov 23 18:14:19 2015] [error] [client 131.152.226.242] PHP Notice:  Trying to get property of non-object in /usr/local/vufind/httpd/module/VuFind/src/VuFind/Controller/AbstractSearch.php on line 395

Mir scheint ein Zusammenhang mit dem Abspeichern von Suchen zu bestehen

**Comment by edelm** [comment]
Es scheint, dass entweder das User-Objekt oder das Search-Objekt leer ist. Wieso dies an der Stelle so ist, ist mir noch nicht klar. Evtl ein Session-Timeout?

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Zugriff auf "Non Object" im apache error log #395 (11/2015-on hold)](https://trello.com/c/bL4oW1NO/68-zugriff-auf-non-object-im-apache-error-log-395-11-2015-on-hold)
