### ISSUE TITLE
Zugriff auf geschützte images als icons in Listen- und Vollansicht

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#396]
@oschihin @witzigs @edelm 

Hallo zusammen,
ich bekam heute morgen einen Anruf von Frau Heidi Eisenhut, Kantonsbibliothek Trogen.
Wir verursachen Probleme durch die Darstellung von geschützten images "als icons" in der Listen- und Vollansicht. Beispiele - Suchen nach 
Beerdigung Giacometti
Krone Trogen (swissbib)
Albin Grau (swissbib)
Sabina Maeder (swissbib)

Setzt man swissbib wie in Klammern angegeben bei Google dazu, findet man die Beipiele auch dort. Weswegen ein Urheber darauf gestossen ist

Das Problem: Mit unserem netten icon Mechanismus, stellen wir die Bilder zwar verkleinert aber immer noch direkt zugänglich dar und umgehen damit einen einschränkenden Schutzmechanismus des Aleph-Adamsystems. Dieser verlangt vor der Ansicht eine Zustimmung zur eingeschränkten Benutzung von den NutzerInnen.

Beim Direktlink auf das Bild in der Vollansicht, wird der Tustmmungsmechanismus nicht umgangen - das ist ok.

Für SGBN habe ich den Mechanismus im Rahmen eines schnellen patch abgestellt. 
https://github.com/swissbib/vufind/commit/fcc8b4be9d61b588518a9280a3d32cfbffd8e334
Hinweis: Die Anpassung habe ich bisher nur 'per Hand' auf die Rechner von swissbib.ch verteilt - nicht per neuem Release (Grundlage ist der Masterbranch)

ToDo:
Wir müssen diskutieren, wie wir damit generell umgehen. Persönlich denke ich, wir müssen das abstellen - aber eben, open issue.

Günter

**Comment by oschihin** [comment]
@guenterh @witzigs 
Die aktuelle Lösung ist bekannermassen problematisch, aus optischen Gründen
https://www.swissbib.ch/Search/Results?type=AllFields&filter[]=union%3A%22HAN%22&filter[]=format%3A%22XK030000%22

**Comment by guenterh** [comment]
@oschihin @witzigs @edelm 

konfigurierbare Icongrösse für e-codices, e-manuskripta und e-rara erstellt
Beipiel: https://www.swissbib.ch/Search/Results?lookfor=IDSBB002219501&type=AllFields&limit=20&sort=relevance

Weitere Ressourcenquellen in 
https://github.com/swissbib/supportiveServices/blob/master/web/WEB-INF/classes/resources/services/whitelistScaleIcons.properties
einrichten

und mit deployscript verteilen
