### ISSUE TITLE
falscher Sprachcode En in table user

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#398]
In der Tabelle user colums language haben sich Sprachcodes eingeschlichen, die nicht erlaubt sind. 
So wie wir das in der produktiven Datenbank von BB gesehen haben, handelt es sich dabei ausschliesslich um Englisch. Deutsch, Französisch und Italienisch scheinen in Ordnung zu sein.

Der falsche Sprachcode: En
richtig wäre: en

Dies führt zu folgenden Fehlern:
- 2015-11-22T19:17:22+01:00 CRIT (2): Zend\View\Renderer\PhpRenderer::render: Unable to render template "search/homeElements/En/swissbib_content_1"; resolver could not resolve to a file
  Die meisten labels auf der Oberfläche sind nicht übersetzt (s. screenshot unten)

Unter anderem sind folgende Fragen zu beantworten
- [ ] warum haben ein Grossteil der Benutzer keinen Sprachcode? Von rund 44 Tausend haben rund 33 T einen leeren String in der Datenbank. Sollte nicht eine Defaultsprache von der Applikation gesetzt werden (Alternative wäre die Datenbank)
- [x] wie können wir die bestehenden user in der Datenbank, welche den falschen Sprachcode En haben auf en zurücksetzen (select language='en' ist nicht kontextsensitiv)

@witzigs fyi - bitte nachführen, wenn ich etwas vergessen habe

![screenshot - 04 12a](https://cloud.githubusercontent.com/assets/1825990/11688624/f5442d1c-9e8d-11e5-9e13-4bfaa29b31e8.jpg)

**Comment by guenterh** [comment]
@witzigs 
Hallo Silvia,

habe als Morgengymnastik zu Beginn ein wenig mit MySQL herumgespielt (lokal bei mir). Warum ich nicht kontextsensitiv suchen kann, ist mir immer noch nicht klar. Ich habe die verschiedensten collation ausprobiert. Aber: internationalization ist ein Thema für sich...

Was ich jedoch machen konnte:
Mit einem Update statement, scheint MySQL in der Lage zu sein, context sensitiv die richtigen rows 'herauszufischen'. Als Beipiele:

mysql> update user set language = 'en' where language = 'en';
Query OK, 65 rows affected (0.06 sec)
Rows matched: 1370  Changed: 65  Warnings: 0


mysql> update user set language = 'fr' where language = 'fr';
Query OK, 0 rows affected (0.05 sec)
Rows matched: 189  Changed: 0  Warnings: 0

mysql> update user set language = 'it' where language = 'it';
Query OK, 0 rows affected (0.05 sec)
Rows matched: 64  Changed: 0  Warnings: 0

mysql> update user set language = 'de' where language = 'de';
Query OK, 0 rows affected (0.05 sec)
Rows matched: 11228  Changed: 0  Warnings: 0

Es gibt 65 'falsche Engländer' diese werden gefunden und aktualisiert. Die anderen Sprachen sind ok. Ich denke man kann den Update auf der produktiven Datenbank machen. Dann würden die Fehler nicht mehr auftreten und Du hättest erstmal weniger Telefone ... Was hälst Du davon?

Günter

**Comment by witzigs** [comment]
Hallo Günter

Am daily vergssen - das ist von mir aus in Ordnung.

Liebe Grüsse
Silvia

--
UNIVERSITÄT BASEL
Universitätsbibliothek
Silvia Witzig
IT / Verbundkoordination
Schönbeinstrasse 18-20
4056 Basel, Schweiz
Tel. +41 (0)61 267 29 44
Tel. +41 (0)61 267 30 95
E-Mail silvia.witzig@unibas.ch
URL http://www.ub.unibas.ch/bibliotheksnetz
________________________________
Von: Guenter Hipler [notifications@github.com]
Gesendet: Donnerstag, 10. Dezember 2015 08:35
An: swissbib/vufind
Cc: Silvia Witzig
Betreff: Re: [vufind] falscher Sprachcode En in table user (#398)


@witzigs<https://github.com/witzigs>
Hallo Silvia,

habe als Morgengymnastik zu Beginn ein wenig mit MySQL herumgespielt (lokal bei mir). Warum ich nicht kontextsensitiv suchen kann, ist mir immer noch nicht klar. Ich habe die verschiedensten collation ausprobiert. Aber: internationalization ist ein Thema für sich...

Was ich jedoch machen konnte:
Mit einem Update statement, scheint MySQL in der Lage zu sein, context sensitiv die richtigen rows 'herauszufischen'. Als Beipiele:

mysql> update user set language = 'en' where language = 'en';
Query OK, 65 rows affected (0.06 sec)
Rows matched: 1370 Changed: 65 Warnings: 0

mysql> update user set language = 'fr' where language = 'fr';
Query OK, 0 rows affected (0.05 sec)
Rows matched: 189 Changed: 0 Warnings: 0

mysql> update user set language = 'it' where language = 'it';
Query OK, 0 rows affected (0.05 sec)
Rows matched: 64 Changed: 0 Warnings: 0

mysql> update user set language = 'de' where language = 'de';
Query OK, 0 rows affected (0.05 sec)
Rows matched: 11228 Changed: 0 Warnings: 0

Es gibt 65 'falsche Engländer' diese werden gefunden und aktualisiert. Die anderen Sprachen sind ok. Ich denke man kann den Update auf der produktiven Datenbank machen. Dann würden die Fehler nicht mehr auftreten und Du hättest erstmal weniger Telefone ... Was hälst Du davon?

Günter

**Comment by guenterh** [comment]
auf produktiver DB gemacht
mysql> update user set language = 'en' where language = 'en';
Query OK, 65 rows affected (0.10 sec)
Rows matched: 1370  Changed: 65  Warnings: 0

wenn der Fehler wieder auftritt, hat sich ein neues Em eingeschlichen.

Punkt 1 schaue ich mir noch an.

**Comment by witzigs** [comment]
@guenterh 
Kannst du dir das nochmals anschauen oder zumindest wieder die "En"-Einträge bereinigen?
Ich erhalte wieder Meldungen von NutzerInnen die sich darauf zurückführen lassen.
Danke!

**Comment by guenterh** [comment]
@witzigs mache ich morgen.

**Comment by guenterh** [comment]
@witzigs 
ich bin mir ziemlich sicher, dass ich die Beschreibung des Vorgehens, was ich gemacht habe, in einem Mail geschickt oder auf das Wiki gestellt habe
Hast Du das noch oder weisst Du den Ort, wo ich das hingestellt habe?
Sorry und Danke!
Günter

**Comment by guenterh** [comment]
@witzigs 
sorry, bin ziemlich blöde, ein paar Kästchen darüber steht es ja...
Günter

**Comment by guenterh** [comment]
@witzigs 
Habe es gerade in der Pause gemacht
Database changed
mysql> update user set language = 'en' where language = 'en';
Query OK, 30 rows affected (0.13 sec)
Rows matched: 1650  Changed: 30  Warnings: 0
(Basel / Bern)

mysql> update user set language = 'en' where language = 'en';
Query OK, 694 rows affected (0.08 sec)
Rows matched: 4134  Changed: 694  Warnings: 0
(green)

Database changed
mysql> update user set language = 'en' where language = 'en';
Query OK, 0 rows affected (0.00 sec)
Rows matched: 6  Changed: 0  Warnings: 0
(Jus)

Was mir durch den Kopf geht
- warum nur Englisch( da wird irgendwas fix geschrieben, der issue ist ja schon auf mich zugewiesen) 
- warum bei green keine Reklamationen (die Leute sind wohl geduldig)

Günter

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [falscher Sprachcode En in table user #398 (12/2015-bug)](https://trello.com/c/OwTtvUPd/67-falscher-sprachcode-en-in-table-user-398-12-2015-bug)

**Comment by sonjakupfi** [comment]
Die temporären Sessions werden neu per Script jede Nacht gelöscht.
Dies sollte dazu führen, dass die obenstehende Fehlermeldung nicht mehr auftritt.
Issue wird auf Grund von Günters Anpassung im Script geschlossen.

**Comment by guenterh** [comment]
@edelm 
hallo matthias,
können wir im nächsten scrum bitte diesen issue nochmals gemeinsam ansehen? Bei mir dauert es im Moment immer etwas länger, bis ich mir wieder eine komplette laufähige Umgebung aufgebaut habe.

Konkret bin ich jetzt wieder durch einen issue gestossen, den wir über den feedback - channel erhalten haben (s. swissbib-ub mail)  subject Fehlermeldung.

Ich schicke Dir die Einträge der Person in unserer Datenbank per Mail.
Die Person hat erstellt sich mit switchEduId einen neuen account (Browsersprache Englisch). Dadurch wird bei ihr als Sprache "En" eingetragen was falsch ist. (Richtig en).

Den Fehler erhielt sie dan bei der Anmeldung, weil ein Sprachtemplate nicht gefunden wurde. In Ihrem Fall habe ich das auf die Schnelle "gelöst", indem ich einen Pfad kopiert habe.

```text
vfsb@sb-uvf1:/usr/local/vufind/httpd/themes$ find . -name 'en' 
./sbvfrdsingle/templates/HelpPage/en
./sbvfrdsingle/templates/search/homeElements/en
./root/templates/HelpTranslations/en
./sbvfrdjus/templates/HelpPage/en
./sbvfrdjus/templates/search/homeElements/en
./sbvfrdmulti/images/HelpPage/en
./sbvfrdmulti/templates/HelpPage/en
./sbvfrdmulti/templates/search/homeElements/en
vfsb@sb-uvf1:/usr/local/vufind/httpd/themes$ find . -name 'En' 
./sbvfrdsingle/templates/search/homeElements/En
vfsb@sb-uvf1:/usr/local/vufind/httpd/themes$
```
Silvia sagt mir, dass der Fehler nicht nur hier sondern auch zum Beispiel bei der Exemplaranzeige auftritt. Hintergrund dort wohl: Bei der Übersetzung wird der Sprachcode En nicht gefunden.

Was wir tun sollten (gerne gemeinsam)
 * Anlegen eines neuen Benutzers in einer englischen session. das können wir aus Aleph oder shibboleth machen. bei beiden müsste ich jetzt bei mir wieder alles einrichten, ich denke Du hast bei Dir lokal eine Umgebung
 * Wo kommt der Sprachcode "En" her? Bei Shibboleth ist der Einsprungpunkt nach Rückkehr vom IdP  [hier](https://github.com/swissbib/vufind/blob/master/module/Swissbib/src/Swissbib/VuFind/Auth/Shibboleth.php). Ich gehe aber davon aus, dass das Userobjekt von VuFind bereits vor der Initilisierung der shibboleth session angelegt wird. Dort könnte dann möglicherweise der falsche Sprachcode gesetzt werden. Bei Basel/Bern (Aleph) sollte es eigentlich sehr ähnlich sein. Wenn wir das im Debuggingmode durchgehen, sollte es eiegntlich nicht sehr schwierig sein, den Ort zu finden, wo die falsche Spracheinstellung gesetzt wird.

@liowalter z.I.

**Comment by guenterh** [comment]
@liowalter @edelm @witzigs 
Hallo zusammen,
ich habe mich des Problems heute erneut angenommen, nachdem ich es geschafft hatte, ein VuFind fast fehlerfrei lokal zum Laufen zu bekommen. 
Um die login Vorgänge besser nachvollziehen zu können, habe ich von der produktiven green-prod Datenbank den dump des Datenbankschemas erstellt und bei mir lokal geladen. Dadurch kann ich meinen (Aleph)-Testuser sehr einfach immer wieder neu vom Bibliothekssystem abrufen und kann einfacher nachvollziehen, welche Werte in welchen Schritten in die Datenbank geschrieben werden.

Wen das Szenario interessiert: Das Schema ist eingecheckt. [db schema](https://github.com/swissbib/vufind/blob/development/sbDocumentation/v5.green.prod.full.schema.sql) @liowalter @edelm : ich würde die alten Sachen (vor allem VF4) an Eurer Stelle wegwerfen.


Zur Sache:
Ich konnte bisher nicht nachvollziehen, an welcher Stelle der language code falsch in die datenbank geschrieben wird. Was ich bisher gesehen habe: Bei der Neuanlage eine Benutzers ist das Feld language lange Zeit leer. Erst bei einem Sprachwechsel (Sprachauswahl an oberen Rand) wird der englische code "richtig" in die Datenbank geschrieben (en und nicht En)

Mit Silvia habe ich ein wenig über Ursachen/Möglichkeiten diskutiert:
- tritt der Fehler nur beim Erstellen einer BenutzerIn auf oder kann der falsche Sprachcode auch später noch geschrieben werden?
was man machen könnte:
- bereits beim Anlegen eines Benutzers schreiben wir immer einen Sprachcode abhängig von der Oberflächensprache (vorausgesetzt man hat die Sprache an dieser Stelle im Zugriff)
- An der Stelle, an der in die DB geschrieben wird, erzwingen wir vor dem safe, dass der Sprachcode korrekt formatiert ist. Diese code sollte eigentlich zentral sein, da  die Zend DB-Funktionen verwendet werden. 
- man versucht an der Stelle, an der in die Datenbank geschrieben wird, ein Logging zu aktivieren, in der Hoffnung, dass man erkennen kann, in welchem Kontext der falsche Sprachcode erscheint.
Mehr Logging fände ich sowieso eine gute Idee. Hatte heute mit Matthias, im Rahmen eines anderen Sachverhalts, eine ähnliche Diskussion.

Die Lösungen können den Nachteil haben, dass man evtl. VuFind Code nur für diesen Zweck überschreiben muss.  

Weitere Ideen?

**Comment by liowalter** [comment]
MySQL case sensitive searches can be done when cast to BINARY :

```
SELECT * FROM `user` WHERE BINARY `language` = BINARY "EN"
```

or

```
SELECT language, count(*)
FROM user
GROUP BY CAST(language as BINARY); 
```


As a result, we get for udb1 (at 16h33 on April 24) : 

language | count(*) 
-- | -- 
  | 47279
Du | 7
Ge | 3
da | 6
de | 5704
en | 9492
fr | 1277
ge | 228
it | 379

on udb2 : 


language | count(*) 
-- | -- 
  | 70363
Ge | 1
de | 32510
en | 3711
fr | 553
it | 149
{l | 1

**Comment by liowalter** [comment]
On orange, the Ge and {| are old entries. I have fixed them. I have the feeling the problem only happens on green.

All "Du" (which doesn't exist as a locale) and "da" (danish) entries are after a login with the unisg IdP.

The "Ge" entries are old entries.

"ge" (georgian, but probably rather a typo for german) is the worst problem. It seems to affect all IdP.

**Comment by liowalter** [comment]
I have the feeling that Swissbib Bootstrapper could be the reason of the error : 
https://github.com/swissbib/vufind/blob/master/module/Swissbib/src/Swissbib/Bootstrapper.php#L176

**Comment by guenterh** [comment]
Thanks for you work Lionel, that looks very likely!

**Comment by liowalter** [comment]
I could reproduce the error : 
- login
- go to https://test.swissbib.ch/MyResearch/Home?lng=Po
- it will store Po as a language in the user table

**Comment by liowalter** [comment]
On top of that, I removed all the wrong language codes from green and orange db. On jus, everything was fine. After deployment, we can remove the cronjobs on udb1 and udb2.
