### ISSUE TITLE
Seltsame Cover-Anzeige (Rückseite)

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#400]
## Problem
Bei einigen Suchanfragen werden offenbar aus externen Quellen (via ISBN) die Rückseiten der Bücher als Cover dargestellt. Dies sei seit 2-3 Monaten so ... Beispiele
* https://www.swissbib.ch/Search/Results?lookfor=politics+fear+wodak&type=AllFields
* https://www.swissbib.ch/Search/Results?lookfor=political+violence+context+bosi&type=AllFields&limit=20&sort=relevance
* https://www.swissbib.ch/Search/Results?lookfor=%22dynamics+of+political+violence%22+bosi&type=AllFields&limit=20&sort=relevance

## Fragen
* [ ] Bei welchem Provider liegt das Problem?
* [ ] Lässt sich ein Grund finden?

siehe auch Issue #293 (auch wenn's nicht direkt damit zu tun hat)

**Comment by edelm** [comment]
Auf der aktuellen Version der Resources-Komponente werden die obengenannten Covers richtig dargstellt. Das Issue sollte also mit dem nächsten Release der Resources-Komponente behoben sein.

**Comment by guenterh** [comment]
erledigt mit R.1.7.5
