### ISSUE TITLE
Piwik - Erweiterung

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#401]
Piwik ist eingerichtet, ich sammle hier Wünsche für Custom Variables, die durch die Standard-Implementierung von VuFind nicht erfüllt werden:
- [ ] Facetten-Typ: Bei der Standard-Implementierung (Variable FacetTypes) werden in Piwik gewählte Facettenkombinationen als ein Wert (z.B.: Union adv_search_year Language) aufgeführt. Ziel wäre, dass jeder gewählte Facettentyp einmal gezählt wird, unabhängig von der Kombination.
- [ ] Reiter in der Vollanzeige: Wie oft wird welcher Reiter in der Vollanzeige angewählt?
- [ ] Externe Links: Welche externen Links werden wie häufig gewählt? Welche Dienste interessieren die Benutzer? (gibt es eine Möglichkeit, den Wrapper "externalservices" wegzufiltern?)
- [ ] für jusbib: Nutzung des Typs "AdvancedClassification" (Hierarchiebaum der Rechtsklassifikation)

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Piwik - Erweiterung #401](https://trello.com/c/YMPdTtju/65-piwik-erweiterung-401)

**Comment by sonjakupfi** [comment]
Issue wird geschlossen! Eine Weiterentwicklung für Piwik ist nicht geplant, das Tool soll jedoch bis auf weiteres mit den bisherigen Funktionalitäten genutzt werden können. Zur Zeit wird geprüft, ob Statistiken direkt anhand von Logs erstellt werden können/sollen.
