### ISSUE TITLE
Summon Mailversand Einzeltreffer

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#402]
Aus Summon können keine Einzeltreffer verschickt werden. Es wird versucht ein solr-Record zu laden.

Fehlermeldung:
Record Solr:FETCH-oup_groveart_10_1093_benz_9780199773787_article_B001201253 does not exist.

**Comment by edelm** [comment]
Gefixt im Rahmen der core2swissbib-Integration 3.0.
