### ISSUE TITLE
Suchanfragen mit OR und or

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#403]
kommentar honsell OR: 23
Sucht nach kommentar AND honsell AND or.

kommentar honsell or: 216'504
Sucht nach kommentar OR honsell OR or. Enthält daher Treffer, die nur or enthalten, z.B.: http://baselbern.swissbib.ch/Record/072977302
Von mir aus sollte diese Abfrage die gleiche Treffermenge wie kommentar honsell OR ergeben. Dieser Unterschied lässt sich nicht vermitteln.

kommentar or honsell: 36'577 
kommentar OR honsell: 36'577
Identische Treffermenge ob mit or oder OR gesucht wird. or/OR werden als boolsches OR interpretiert. VuFind und swissbib Hilfeseiten kommunizieren im Moment, dass Boolsche Operatoren grossgeschrieben werden müssen. Das stimmt nicht mit dem momentanen Verhalten überein, wäre aber so gewünscht.

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Suchanfragen mit OR und or #403](https://trello.com/c/Dj90ak3i/64-suchanfragen-mit-or-und-or-403)

**Comment by witzigs** [comment]
Tritt mit Solr 7 nicht mehr so auf, Treffermengen sind aber immer noch unterschiedlich:
kommentar honsell OR: 29
kommentar honsell or: 17
kommentar OR honsell: 197
kommentar or honsell: 17 (gleiche Treffer wie bei kommentar honsell or)

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [403](https://trello.com/c/n4wC40ZW/160-403)

**Comment by liowalter** [comment]
As far as I can see, this has been solved by VuFind 5 / SOLR 7,
