### ISSUE TITLE
no image available in baselbern.swissbib.ch

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#405]
Mir ist gerade aufgefallen, dass in BB noch das "no image available" icon erscheint. 
http://baselbern.swissbib.ch/Summon/Search?type=AllFields

Warum ist das so?

**Comment by edelm** [comment]
Der GET-Parameter 'contenttype' sollte eigentlich einen formatcode enthalten, bei BB hat er aber seltsame Werte:
- "contenttype=Trade+Publication+Article"
- "contenttype=Book+Review".
- etc...

Das liegt entweder an den Records in der DB, oder VuFind durchläuft anderen Code für BB m Vergleich zu Classic.

**Comment by edelm** [comment]
Im Moment wird wieder der richtige formatcode mitgegeben, womit auch die Formaticons statt notavailable angezeigt wird. Evtl hat die DB temporär (wegen Neuindexierung?) falsche Daten zurückgeliefert?

**Comment by witzigs** [comment]
erledigt mit caecea3d5eb0344f2fc5e58d31ee57bab2b2b332
