### ISSUE TITLE
Sammelissue core2swissbib

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#407]
* [ ] Hierarchische Facetten in "Format" werden nicht mehr angezeigt
* [x] Fehler nach letztem Merge von VF2core
[Tue Mar 22 19:12:59.758486 2016] [:error] [pid 5179] [client ::1:56228] PHP Fatal error:  Call to undefined method Swissbib\\VuFind\\Search\\Solr\\Options::getLastSort() in /usr/local/vufind/httpd/themes/sbvfrd/templates/search/searchbox.phtml on line 17
* [x] Travis Build fails https://travis-ci.org/swissbib/vufind/builds/117763712
* [x] Suche gibt Fehlermeldung wegen neuer DB-Struktur

**Comment by edelm** [comment]
Punkt 2: mit dem commit 1d24cbe94912e438fe4add677667d670c25421ed hat sich die Suchpersistenz nach Seachr/Memory verlagert. Ich habe den Code entsprechend angepasst. Im Moment bricht die Suche noch an der neuen (in SB noch nicht implementierten) DB-Struktur.

Punkt 3: im build.xml hat der php-cs-fixer Aufruf eine neue fix-Regel (eof_ending). Ich habe die entsprechenden Aufrufe lokal für die Module "Swissbib", "Jusbib", "QRCode" und "Libadmin" gemacht, noch ein paar Fixes in den config-Verzeichnissen gemacht und dann die gefixten Dateien commited. Wir kriegen nun wieder grün von travis!

**Comment by guenterh** [comment]
s. https://github.com/swissbib/vufind/issues/411
