### ISSUE TITLE
Zugriff auf falschen Index bei Import der Daten von admin.swissbib.ch/libadmin

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#408]
Mit diesem commit https://github.com/swissbib/libadmin/commit/f83817af57f2feafba80aa6525868b3c25155120 wurde das Schema der Datenbank von libadmin geändert, Dies führt beim Import der Daten zu folgendem Fehler

Notice: Undefined index: position in /usr/local/vufind/httpd/module/Swissbib/src/Swissbib/Libadmin/Importer.php on line 382

**Comment by witzigs** [comment]
Seit der Anpassung in libadmin werden die Bibliotheken innerhalb der einzelnen Gruppen bei der Exemplaranzeige nicht mehr alphabetisch sortiert. 
@guenterh: Hängt das damit zusammen?

**Comment by guenterh** [comment]
fixed
https://github.com/swissbib/vufind/commit/84fdcc699ca6560d2659c927a2377b4520988d64
