### ISSUE TITLE
Suchanfragen mit Umlaut und Bindestrich

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#409]
Gemeldet von Monika Wechsler:

Sucht man nach Anthropozän-Küche: es kommt eine Fehlermeldung
Sucht man mit diesen Wörtern ohne Bindestriche (Anthropozän Küche): keine Fehlermeldung (einfach 0 Treffer)
Sucht man ohne Umlaute aber mit Bindestrichen (Anthropozan-Kuche): keine Fehlermeldung
Sucht man mit Platzhaltern statt Umlauten und mit Bindestrich (Anthropoz_n-K_che): keine Fehlermeldung

Ergo: die Kombination vor Umlaut mit Bindestrichen wird von swissbib nicht „vertragen“

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Suchanfragen mit Umlaut und Bindestrich #409](https://trello.com/c/yF8tQ1ic/62-suchanfragen-mit-umlaut-und-bindestrich-409)

**Comment by witzigs** [comment]
Tritt weder produktiv noch mit Solr 7 auf
