### ISSUE TITLE
integration V3: Hierarchische Facetten in "Format" werden nicht mehr angezeigt

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#411]
s. auch https://github.com/swissbib/vufind/issues/407

**Comment by edelm** [comment]
Gefixt mit 0075c38c40d47c84b47fe05b196ff93ee26d33af

Evtl noch offen: /usr/local/vufind/httpd/themes/sbvfrd/templates/RecordTab/holdingsils.phtml:99 (vufindString.favoriteReload). Muss hier noch eine Anpassunge gemacht werden?

**Comment by guenterh** [comment]
fixed with
https://github.com/swissbib/vufind/commit/0075c38c40d47c84b47fe05b196ff93ee26d33af
@witzigs : bitte nochmal anschauen - Danke!
