### ISSUE TITLE
integration V3: login Dialog wirft exception 

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#412]
Die login Dialoge aller drei Views (green: test.swissbib.ch / orange: devbabe.swissbib.ch / jus: http://sb-vf20.swissbib.unibas.ch/justestrd werfen eine Exception mit der Fehlermeldung:
Zend\Mvc\Controller\PluginManager::get was unable to fetch or create an instance for inLightbox

**Comment by witzigs** [comment]
Wenn man sich über einen anderen Weg als "Anmelden" im Header einloggt, erscheint der Login-Dialog (z.B. Mail-Versand auf Trefferliste oder Einstellungen im Footer). Danach funktioniert jedoch nichts mehr.
* Basel Bern: Weisse Seite
* grün: Die folgende Fehlermeldung erscheint:

> Fatal error: Uncaught exception 'Zend\Db\RowGateway\Exception\InvalidArgumentException' with message 'Not a valid column in this row: language' in /usr/local/vufind/httpd/vendor/zendframework/zendframework/library/Zend/Db/RowGateway/AbstractRowGateway.php:301 Stack trace: #0 /usr/local/vufind/httpd/module/Swissbib/src/Swissbib/Bootstrapper.php(213): Zend\Db\RowGateway\AbstractRowGateway->__get('language') #1 /usr/local/vufind/httpd/module/Swissbib/src/Swissbib/Bootstrapper.php(118): Swissbib\Bootstrapper->initUserLocale() #2 /usr/local/vufind/httpd/module/Swissbib/Module.php(70): Swissbib\Bootstrapper->bootstrap() #3 [internal function]: Swissbib\Module->onBootstrap(Object(Zend\Mvc\MvcEvent)) #4 /usr/local/vufind/httpd/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #5 /usr/local/vufind/httpd/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('bootstrap', Ob in /usr/local/vufind/httpd/vendor/zendframework/zendframework/library/Zend/Db/RowGateway/AbstractRowGateway.php on line 301

**Comment by guenterh** [comment]
fixed with
https://github.com/swissbib/vufind/commit/939087654079fb15de6ea12b36e08c3d668ec93c
and
https://github.com/swissbib/vufind/commit/525dee79f4baba4f4dfd480aade9a70cd940f650
