### ISSUE TITLE
integration V3: jusbib Klassifikationsbaum startet keine Suche mehr

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#413]
die auf core2swissbib basierende Jusbib View ruft keine Suche mehr auf.
Die einzelnen Blätter der Klassifikationsbäume werden für mich richtig angezeigt ( @witzigs : Bitte anschauen ob die Bäume korrekt aufgebaut werden, ich bin mit diesen zuwenig vertraut)

clickt man jedoch auf einen 'Zweig' des Baums, wird die Suche nicht mehr gestartet

**Comment by witzigs** [comment]
Die beiden Klassifikationsbäume werden ansonsten korrekt dargestellt.

**Comment by guenterh** [comment]
fixed with
https://github.com/swissbib/vufind/commit/0075c38c40d47c84b47fe05b196ff93ee26d33af
