### ISSUE TITLE
Integration VF3: Vollanzeige Link zu Autorensuche fehlts

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#417]
In der Vollanzeige werden in der Menüspalte Links für die Suche nach weiteren Medien der beteiligten Autoren angezeigt. Diese Links werden im Moment nicht aufgebaut. Zwei Fälle:
* Wenn in den Daten ein Feld 700 vorhanden ist, wird in der Menüspalte der Titel "Verfasser/Beitragende" angezeigt. Die Links zur Suche nach den einzelnen Autorennamen fehlen.
* Wenn nur ein Feld 100 vorhanden ist, wird auch der Titel "Verfasser/Beitragende" nicht angezeigt.

**Comment by guenterh** [comment]
fixed with
https://github.com/swissbib/vufind/commit/b377396b62d556abdf7a1b0eeec15c1b00fad6b9
cudos to @edelm

**Comment by edelm** [comment]
Punkt 1 ist gefixt, aber ich glaube Punkt 2 ist noch offen.

Hat evtl was mit 'themes/sbvfrd/templates/record/view.phtml:24' zu tun.
