### ISSUE TITLE
Integration VF3: Meine Bibliotheken

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#418]
Die Suche nach Bibliotheken auf /MyResearch/Favorites funktioniert nicht.

**Comment by guenterh** [comment]
@edelm Im Moment werden Bibliotheken vorgeschlagen, mit der return Taste werden sie aber nicht übernommen.
Dies ist in der produktiven Version ebenfalls nicht möglich, was, nach meiner Erinnerung, früher jedoch mal möglich war.
Finde ich nicht so sehr wichtig, vielleicht sieht man eine schnelle Lösung??
