### ISSUE TITLE
Integration VF3: Summon Vollanzeige

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#419]
Die Vollanzeige von Summon-Records funktioniert nicht bei allen Records. Es wird z.T. der folgende Fehler angezeigt:
> Array provided to Escape helper, but flags do not allow recursion 

Beispiele:
* http://devbabe.swissbib.ch/SummonRecord/FETCH-elsevier_sciencedirect_doi_10_1016_S0140_6736_11_61438_43
* http://devbabe.swissbib.ch/SummonRecord/FETCH-LOGICAL-p705-bc2796f4b98e6ba7672f234de1d8374a38e7bcc31e269a8d0b1c08e3fb99aa463
* http://devbabe.swissbib.ch/SummonRecord/FETCH-elsevier_sciencedirect_doi_10_1016_S0140_6736_11_61438_43

**Comment by edelm** [comment]
Fehler tritt lokal nicht mehr auf. Wahrscheinlich gefixt mit author-handling (#417).

**Comment by guenterh** [comment]
https://github.com/swissbib/vufind/commit/d8c5f8cd2f29f667a9db19ec725d500348b22f2e
auf devbabe.swissbib.ch verteilt
@edelm Fehler tritt nicht mehr auf
