### ISSUE TITLE
Integration VF3: Design Issues

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#420]
* [x] in den Facetten sollte das Dreieck zum Auf-/Zuklappen der Facette rechtsbündig sein und nicht neben dem Titel der Facette stehen (analog produktive Version)
* [x] Diverse Buttons u.a. "Weitere Ausgaben", "Merkliste" und "Bibliotheken" werden beim Anklicken dunkelblau statt in den Theme-Farben zu bleiben.

**Comment by FlorinneEgli** [comment]
- [ ] Orange Buttons "get it" etc. werden länglich, sobald nicht mehr im Vollbildmodus

VF3:
 ![image](https://cloud.githubusercontent.com/assets/17006552/14887173/e72ca5c0-0d54-11e6-8066-f4c5ca93d7e5.png)

Produktive Version:
![image](https://cloud.githubusercontent.com/assets/17006552/14887186/f71247d8-0d54-11e6-8bd4-0fda3e3fb2e0.png)
