### ISSUE TITLE
Integration VF3: Bei Buttons werden unschöne Rahmen angezeigt

### ISSUE THREAD

**Issue by FlorinneEgli** [swissbib/vufind#421]
Gewisse Buttons bekommen einen schwarzen Rahmen, wenn man mit der Maus drüberfährt, anstatt nur eine Farbänderung. 
Beobachtet bei: ie 11.0.960618282 / Chrome 49.0.2623.112 / Firefox 45.0.2 mit und ohne Citrix auf Windows-Laptop

Beispiele aus Firefox 45.0.2:

Zwei Reiter „Bücher & mehr“ bzw. „Artikel & mehr“
![bild](https://cloud.githubusercontent.com/assets/17006552/14851967/cdfde59a-0c83-11e6-9ac6-1a8515ecabd0.png)
 
Vier Tabs in Vollanzeige
![bild2](https://cloud.githubusercontent.com/assets/17006552/14851996/0c9b3302-0c84-11e6-927c-fffa67717712.png)

 „Anmelden“ bzw. „Abmelden“
![bild3](https://cloud.githubusercontent.com/assets/17006552/14852008/18bff2d0-0c84-11e6-9097-4cc03ebff298.png)

**Comment by edelm** [comment]
fixed with 0a40fd6cb7fcfd7619ba9937ac3aa428b9b683a5
