### ISSUE TITLE
Integration VF3: Zitierbutton im Tab „Artikel & mehr“ funktioniert nicht

### ISSUE THREAD

**Issue by FlorinneEgli** [swissbib/vufind#422]
Wenn man im Tab „Artikel & mehr“ den Zitiert-Bleistift drückt, wird eine Fehlermeldung generiert.

Beobachtet bei: ie 11.0.960618282 / Chrome 49.0.2623.112 / Firefox 45.0.2 mit und ohne Citrix auf Windows-Laptop sowie in Safari auf iPad Mini und iPhone SE

Beispiel aus ie 11.0.960618282
![zitier](https://cloud.githubusercontent.com/assets/17006552/14852079/86fe0f5c-0c84-11e6-86af-8198188362d8.png)
:

**Comment by witzigs** [comment]
Die gleiche Fehlermeldung gibt es auch beim Mailversand eines einzelnen Treffers in Artikel&mehr.
Es wird nach einem Solr-Record gesucht, der ja da nicht existieren kann.

**Comment by edelm** [comment]
Dieses Verhalten existiert auch auf dem aktuellen produktiven System. Es scheint schon vor VF3 aufgetreten zu sein.

**Comment by edelm** [comment]
gefixt mit 209adefda438ea91918fcc269f8e7cc4b46f3d0a
