### ISSUE TITLE
Integration VF3: Bestellen und reservieren im Tab „Bücher und mehr“ funktioniert nicht

### ISSUE THREAD

**Issue by FlorinneEgli** [swissbib/vufind#423]
Wenn man eine Bestellung/Reservation auslöst, passiert beim ersten Drücken des Buttons „Bestellen“ nichts. Beim zweiten Mal Drücken erscheint eine Fehlermeldung.

Beobachtet bei: ie 11.0.960618282 / Chrome 49.0.2623.112 / Firefox 45.0.2 mit und ohne Citrix auf Windows-Laptop sowie in Safari auf iPad Mini und iPhone SE

Beispiel aus Firefox 45.0.2
![bestellen](https://cloud.githubusercontent.com/assets/17006552/14852129/cdce8740-0c84-11e6-9b27-033d6404fdcd.png)

**Comment by witzigs** [comment]
Das scheint ein Lightbox-Darstellungsproblem zu sein.
Die Bestellung an sich funktioniert.

@FlorinneEgli : Kannst du das kurz verifizieren und bei dir im Konto kontrollieren, ob deine Bestellungen ebenfalls da sind?

**Comment by FlorinneEgli** [comment]
@witzigs Stimmt, die Bestellungen sind im Konto aufgelistet.
Ausserdem: Wenn ich von dieser Fehlerseite zurückgehe, erscheint dort auch die Meldung "Bestellung ausgeführt".

**Comment by edelm** [comment]
Anpassungen mit 4ede6d1cb22075cd819651925c66393658fca028
