### ISSUE TITLE
Integration VF3: Versenden von Titeln aus Merkliste funktioniert nicht

### ISSUE THREAD

**Issue by FlorinneEgli** [swissbib/vufind#425]
Wenn man einen Titel aus der Merkliste per Mail versenden möchte, erscheint ein weisser Screen.

Beobachtet bei: ie 11.0.960618282 / Chrome 49.0.2623.112 / Firefox 45.0.2 mit und ohne Citrix auf Windows-Laptop sowie in Safari auf iPad Mini und iPhone SE

**Comment by edelm** [comment]
Anpassungen für Lightbox mit 28e590dcc554df5b978d95165432deaaedb06c40
