### ISSUE TITLE
Integration VF3: eigene Seite für Zitate

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#426]
Für die Zitiervorlagen wird eine eigene Seite aufgerufen. Bis jetzt erschienen die in einer über der Seite liegenden Box.
Ist es zwingend, das auszuschalten?
Falls nicht, wäre ich an dieser Stelle eher für die Box als für die eigene Seite.

**Comment by edelm** [comment]
gefixt mit baf8d64a83ec75d820bdb1dc6e81a91de3dafeb3
