### ISSUE TITLE
Integration VF3: Datenbankupdate

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#428]
Der VF3 release vom core enthält Updates des Datenbankschemas von mysql, die so meines Wissens noch nicht in unserem Updatescript enthalten sein können.

* [ ] Anpassen des scripts
* [ ] Aufstellen eines konkreten Vorgehens (Kochbuch) für den Update unserer Datenbank bei Migration

**Comment by guenterh** [comment]
![mysql changes](https://cloud.githubusercontent.com/assets/1825990/14876825/555061b4-0d18-11e6-95b6-4b41ed5e1fd8.png)

**Comment by edelm** [comment]
done with 904beb6b7f09c7695c3d611b92f1ad4e7952b016
