### ISSUE TITLE
Integration VF3: Export-Option bei Merklisten fehlt

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#430]
Bei den Merklisten bieten wir bis jetzt E-Mail, Löschen und Export an. In VF3 fehlt Export. Wieso?

**Comment by witzigs** [comment]
@edelm 
Die Exportformate sind da, allerdings gibt es bei den Optionen RefWorks und EndNoteWeb eine Fehlermeldung. Da sollte eigentlich ein Redirect auf die entsprechende Seite stattfinden (vgl. export.ini). Kannst du das noch ansehen?

Und können wir die Reihenfolge der Exportoptionen wie gehabt behalten? Durch Anpassen der Reihenfolge im Abschnitt [Export] in config_base?

**Comment by guenterh** [comment]
unterschiedliches Verhalten bei HTTPs und http

test.swissbib.ch
8707:1 Mixed Content: The page at 'https://test.swissbib.ch/MyResearch/MyList/8707' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://www.refworks.com/express/expressimport.asp?vendor=VuFind&filter=RefW…orks%26i%255B%255D%3DSolr%257C057189579%26i%255B%255D%3DSolr%257C057189587'. This request has been blocked; the content must be served over HTTPS.


devbabe.swissbib.ch
XMLHttpRequest cannot load http://www.refworks.com/express/expressimport.asp?vendor=VuFind&filter=RefW…%26i%255B%255D%3DVuFind%257C278692052%26i%255B%255D%3DVuFind%257C08080943X. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://devbabe.swissbib.ch' is therefore not allowed access.

**Comment by edelm** [comment]
export funktioniert, allerdings öffnen download-exports auch in einem neuen window/tab.

momentan haben wir im export.phtml data-lightbox-onsubmit="exportFormHandler" (=aufruf einer nicht existierenden js-fuktion), damit der code im lightbox.js:_formSubmit() richtig aufgerufen wird. das sollte jedoch noch sauberer implementiert werden.

**Comment by edelm** [comment]
gefixt mit 5fdf2a7326634d3d0a335ba75c0df58b225369f0
