### ISSUE TITLE
Anmeldung auf baselbern.swissbib.ch nicht verschlüsselt

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#434]
Der von uns abgeänderte Login-Mechanismus verwendet nicht den salt, wie er von VuFind Standard in der Ajax-basierten Kommunikation verwendet wird (Popup-Dialoge)
Dadurch sind die Credentials nicht verschlüsselt!

Anders als www.swissbib.ch läuft baselbern nicht auf https.
Die Verschlüsselung vor Absenden des requests auf dem client (und Entschlüsselung mit dem entsprechenden key) ist (sollte) aber vertretbar (sein)

**Comment by edelm** [comment]
So wies aussieht, existiert dazu bereits ein Issue im VFCore:
https://vufind.org/jira/browse/VUFIND-736

Anscheinend geht die Verschlüsselung nur über den Popup-Dialog/Ajax. Wir müssten selber einen JS-Mechanismus für eine verschlüsselte Uebertragung bauen.

Wie würden wir mit Browsern ohne JS umgehen?

**Comment by guenterh** [comment]
@edelm @witzigs  
Hallo Matthias
ich habe gerade zufällig auf testbaselbern.swissbib.ch nachgesehen, ob das Passwort beim login verschlüsselt wird.
Das ist nicht der Fall, auch mit https.
Meine Vermutung: Die Verbindung ist noch nicht korrekt konfiguriert.
Kannst Du die apache conf auf sb-vf10 analog zu sb-vf3 einstellen?
/etc/httpd/conf.d/prod.swissbib.ch.conf
(auch mit Zertifikat und private key)
Diese solltest Du eigentlich von Stefan erhalten haben. Kannst Du Zertifikat und key anschliessend im Passwordsafe ablegen? Sie sollten nicht verloren gehen. Ich hoffe dann ist der login verschlüsselt.

Vielen Dank und Grüsse bis morgen

Günter

**Comment by edelm** [comment]
Tests mit einem FF-Addon (Live HTTP Headers) und mit einem Tool auf OS-Level (tcpflow) haben ergeben, dass das Passwort auf OS/Netzwerk-Ebene verschlüsselt ist. Das FF-Addon hat demnach Zugriff auf die bereits vom Browserentschlüsselten Daten. Die Sicherheit der Daten im Netzwerk ist gewährt.
