### ISSUE TITLE
Show detail Fenster bei Zeitschriften öffnet sich nicht mehr

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#435]
Ich bekam heute ein Anruf mit dem Hinweis. Hier ein screenshot des Mails. Das Problem liegt im Aufruf einer Methode der alten Lightbox

![zeitschriften details bug](https://cloud.githubusercontent.com/assets/1825990/15579408/c8214f5c-2364-11e6-8443-c6b854f8bf26.png)

**Comment by guenterh** [comment]
Javascript Fehlermeldung
Timestamp: 05/26/2016 05:11:41 PM
Error: ReferenceError: Lightbox is not defined
Source File: http://baselbern.swissbib.ch/themes/sbvfrd/js/swissbib/Holdings.js?_=1464183551
Line: 143

**Comment by witzigs** [comment]
@edelm 
Ich öffne dieses Issue nochmals, da noch ein weiteres Problem besteht:
Es wird nur die erste Seite angezeigt. Wenn man auf die nächste Seite umblättern will, erscheint eine Fehlermeldung "error_occured". Beispiel: http://baselbern.swissbib.ch/Record/278677339, Bestand UB Hauptbibliothek
