### ISSUE TITLE
Integration VF3: Zu grosse Treffermengen

### ISSUE THREAD

**Issue by FlorinneEgli** [swissbib/vufind#436]
Eine Suche in swissbib Basel Bern führt zu ungewohnt grossen Treffermengen mit auch nicht passenden Suchergebnissen. Wird eventuell eine OR-Suche anstatt eine AND-Suche abgesetzt?
Zum Beispiel eine einfache Suche mit "escher schweizerische interkantonale privatrecht civilrechtlichen" (Beispiel einer Rückmeldung)

**Comment by guenterh** [comment]
@FlorinneEgli @edelm @witzigs  : Florinne, ich schaue es mir gerade an

**Comment by guenterh** [comment]
@FlorinneEgli sollte gefixt sein (für orange und green indices, bitte mal anschauen) Weitere Kommentare, Hintergründe und was man davon mitnehmen könnte nach dem Mittagessen

**Comment by FlorinneEgli** [comment]
@guenterh das sieht gut aus, danke.

**Comment by guenterh** [comment]
@FlorinneEgli @witzigs @edelm 
Hallo zusammen,

der Grund für die hohe Treffermenge nach dem Wechsel auf die neue Version lag nur bedingt in der "and" oder "or" Verknüpfung. Es gibt auf Ebene der Suchmaschine die Möglichkeit anzugeben, wieviele der angegebenen Suchklauseln mindestens "matchen" müssen.  Dies merkt man natürlich besonders stark, wenn eine Abfrage viele Klauseln aufweist (im gegeben issue):
escher schweizerische interkantonale privatrecht civilrechtlichen
Die Option "minimum match" lässt sich bei der von uns verwendeten Suchmaschine mit dem Parameter mm angeben. Seit dem Versionswechsel gestern, wird folgende Abfrage an die Suchmaschine geschickt:

http://search.swissbib.ch/solr/sb-biblio/select?mm=0%25&facet.field=format_hierarchy_str_mv&qt=edismax&ps=2&hl=false&json.nl=arrarr&bf=recip%28abs%28ms%28NOW/DAY,freshness%29%29,3.16e-10,100,100%29&fl=*,score&start=0&q.op=AND&rows=10&facet.limit=-1&q=escher+schweizerische+interkantonale+privatrecht+civilrechtlichen&spellcheck=false&qf=title_short^1000+title_alt^200+title_sub^200+title_old^200+title_new^200+author^750+author_additional^100+author_additional_dsv11_txt_mv^100+title_additional_dsv11_txt_mv^100+author_additional_gnd_txt_mv^100+title_additional_gnd_txt_mv^100+publplace_additional_gnd_txt_mv^100+series^200+topic^500+addfields_txt_mv^50+publplace_txt_mv^25+publplace_dsv11_txt_mv^25+fulltext+callnumber^1000+ctrlnum^1000+publishDate+isbn+variant_isbn_isn_mv+issn+localcode+id&pf=title_short^1000&facet.mincount=1&facet=true&wt=xml&facet.sort=count
(Unsere Suchmaschinen API ist weltweit offen, Ihr könnt die Abfrage selber abschicken)

Wenn Ihr genau hinseht findet Ihr für mm den Wert 0.25. Das heisst, das mindestens 25% der Suchklauseln matchen müssen (und nicht nur ein einfaches and/or)
Als lediglich schnelle Lösung (wir werden das in den nächsten Tagen aber noch genauer ansehen) habe ich es nun so gelöst, dass ich auf Ebene der Suchmaschine angebe, immer und in jedem Fall für mm den Wert 100% zu verwenden. Egal was der client schickt, müssen nun also immer alle Klauseln matchen, faktisch läuft das auf eine 'and' Verknüpfung hinaus.

Mehr Hintergrund dazu findet Ihr zum Beispiel hier:
https://cwiki.apache.org/confluence/display/solr/The+DisMax+Query+Parser#TheDisMaxQueryParser-Themm%28MinimumShouldMatch%29Parameter

Warum schreibe ich das eigentlich:
Wir arbeiten mit einer offenen und für jedermann/frau zugänglichen Suchmaschine. Alle Optionen sind dokumentiert und nachvollziehbar. Wir sollten versuchen, die vielfältigen Möglichkeiten der Suchmaschine besser in den discovery service zu integrieren (nicht nur die bekannten einfachen booleschen Operationen) Dies können und versuchen wir natürlich von swissbib Team aus (nicht zuletzt müssen Zugriffe auf die Schnittstelle auch im code unserer Präsentationskomponente implementiert werden (worum sich vor allem Matthias kümmert). Die eigentlichen Mechanismen der Suche auf der Ebene des servers könnten/sollten nach meinem Verständnis auch von den InformationsspezialistenInnen der Bibliotheken verstanden und gestaltet werden. Dazu gehören zwei Seiten:
1) Analyse und Konfiguration des Suchverhaltens und Einsatz der verschiedensten Komponenten (oft kurz mit "Search" bezeichnet) 
2) Analyse und Mitteilhabe an der Aufbereitung der Texte, die anschliessend in der Maschine indexiert werden (oft mit Indexing bezeichnet)

Anders als bei kommerziellen Produkten können wir Euch mit einem offenen System diese Möglichkeiten anbieten. Wir sollten darüber im Gespräch bleiben.

Schönes WE
Günter

**Comment by guenterh** [comment]
@witzigs 
Ok, schaue es mir morgen an. Meine Vermutung: Es wird bei dieser Abfrage ein anderer Request Handler verwendet. s. oben qt=edismax fehlt bei Deinem Beispiel. Wenn ich es nicht übersehen habe.
Beim requestHandler edismax in solconfig.xml habe ich mm nicht überschreibbar auf 100 gesetzt (und damit faktisch and)

**Comment by guenterh** [comment]
@witzigs 
Silvia, das haben wir für Basel/Bern doch gelöst. Weiss aber nicht mehr genau was wir gemacht haben. Weisst Du es noch? 
@sonjakupfi Sollte mit jus nichts zu tun haben

**Comment by witzigs** [comment]
@guenterh 
gelöst mit 90637c9433e350eedbb9f64b302b20f56fffa9e1

siehe auch #437
