### ISSUE TITLE
Erweiterte Suche: zu grosse Treffermenge

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#437]
@guenterh 

Über die erweiterte Suche werden ebenfalls zu grosse Treffermengen ausgegeben, vgl. #436.

Beispiel: Suche in Verfasser nach Michael Armstrong ergibt 86'232 Treffer. Query kommt auf s17 so an:

[31/May/2016:14:59:35 +0200] "GET /solr/sb-biblio/select?fl=%2A%2Cscore&spellcheck=false&facet=true&facet.limit=100&facet.field=e_institution_str_mv&facet.field=navSub_orange&facet.f
ield=navAuthor_orange&facet.field=format_hierarchy_str_mv&facet.field=language&facet.field=navSubform&facet.field=institution&facet.field=publishDate&facet.sort=count&facet.mincount=1&sort=score+desc&q.
op=AND&hl=true&hl.fl=fulltext&hl.simple.pre=%7B%7B%7B%7BSTART_HILITE%7D%7D%7D%7D&hl.simple.post=%7B%7B%7B%7BEND_HILITE%7D%7D%7D%7D&hl.fragsize=250&wt=json&json.nl=arrarr&rows=20&start=0&q=%28%28%28_quer
y_%3A%22%7B%21edismax+qf%3D%5C%22author%5E100+author_additional%5E20+author_additional_dsv11_txt_mv%5E20%5C%22+mm%3D%5C%270%25%5C%27%7Dmichael+armstrong%22%29%29%29 HTTP/1.1" 200 296743

Das Verhalten ist bei allen über die Erweiterte Suche ausgeführten Anfragen identisch (egal ob in Alle Felder, Verfasser, ... gesucht wird).**

**Comment by guenterh** [comment]
patched with
https://github.com/swissbib/vufind/commit/965c5004cc63fc275440cddaa256635aca660386
https://github.com/swissbib/vufind/commit/90637c9433e350eedbb9f64b302b20f56fffa9e1
@witzigs 
bei SOLR 5.5. müssen wir noch schauen, ob wir dies rückgängig machen müssen oder sollen
