### ISSUE TITLE
Endnote/Citavi: bei Export werden Autoren nicht mitgeliefert

### ISSUE THREAD

**Issue by FlorinneEgli** [swissbib/vufind#439]
Eine Mitarbeiterin meldet, dass beim Exportieren in Endnote und citavi die Autoren nicht mitgeliefert werden. Dies betrifft sowohl die Merklisten wie auch einzelne Treffer.

Hier zwei Screenshots des Imports aus citavi:
![1](https://cloud.githubusercontent.com/assets/17006552/15926415/327542d2-2e3c-11e6-8fb5-17091af2c35b.png)

Statt Vor- und Nachname des Autors steht „Array“:
![2](https://cloud.githubusercontent.com/assets/17006552/15926434/49986ad4-2e3c-11e6-9b0d-5284fb82fe3a.png)

**Comment by witzigs** [comment]
@edelm 
Kannst du dir diesen Fall mal genauer anschauen? Ich komme nicht weiter...
Für den endnote-Export wird das Template export-endnote.phtml aufgerufen. Darin werden die Autoren geholt (getDeduplicatedAuthors in SolrDefault.php). Soweit ich sehe, entsteht der seltsame Export daraus, dass der Autorenname als Name eines Arrays statt als Inhalt eines Arrays ans Template zurückgegeben wird.
Da wir für die anderen Exportformate die Templates identisch aufgebaut haben, gilt das auch für BibTex, Refworks und EndnoteWeb.

Liebe Grüsse
Silvia

**Comment by FlorinneEgli** [comment]
Dieselbe Mitarbeiterin hat mir soeben gemeldet, dass wieder dasselbe Problem vorhanden ist.

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Endnote/Citavi: bei Export werden Autoren nicht mitgeliefert #439](https://trello.com/c/V9K0yhp4/55-endnote-citavi-bei-export-werden-autoren-nicht-mitgeliefert-439)
