### ISSUE TITLE
Upgrade Präsentationshosts -> ubuntu16.04 / PHP 7

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#440]
auf sb-vf16 fehlt noch 
php7.0-mbstring

führt zu folgendem Fehler

[Thu Jun 16 11:57:58.620561 2016] [:error] [pid 18829] [client 131.152.212.156:60918] PHP Fatal error:  Uncaught Error: Call to undefined function Swissbib\RecordDriver\mb_strtoupper() in /usr/local/vufind/httpd/module/Swissbib/src/Swissbib/RecordDriver/SolrMarc.php:746\nStack trace:\n#0 /usr/local/vufind/httpd/module/Swissbib/src/Swissbib/RecordDriver/SolrMarc.php(684): Swissbib\RecordDriver\SolrMarc->getThumbnail956()\n#1 [internal function]: Swissbib\RecordDriver\SolrMarc->getThumbnail('small')\n#2 /usr/local/vufind/httpd/module/VuFind/src/VuFind/RecordDriver/AbstractBase.php(506): call_user_func_array(Array, Array)\n#3 /usr/local/vufind/httpd/module/Swissbib/src/Swissbib/View/Helper/Record.php(502): VuFind\RecordDriver\AbstractBase->tryMethod('getThumbnail', Array)\n#4 /usr/local/vufind/httpd/themes/sbvfrd/templates/RecordDriver/SolrDefault/result-list.phtml(7): Swissbib\View\Helper\Record->getThumbnail('small')\n#5 /usr/local/vufind/httpd/vendor/zendframework/zendframework/library/Zend/View/Renderer/PhpRenderer.php(501): include('/usr/local/vufi...')\n#6 /usr/local/vufind/httpd/module/VuFind/src/VuFind/View/Helper in /usr/local/vufind/httpd/module/Swissbib/src/Swissbib/RecordDriver/SolrMarc.php on line 746, referer: http://sb-vf16.swissbib.unibas.ch/vfrd/Record/059559497/Holdings

bisher vorhandene packages:
libapache2-mod-php              install
libapache2-mod-php7.0               install
php                     install
php-common                  install
php-curl                    install
php-gd                      install
php-imagick                 install
php-intl                    install
php-ldap                    install
php-mcrypt                  install
php-memcache                    install
php-mysql                   install
php-odbc                    install
php-pear                    install
php-pgsql                   install
php-pspell                  install
php-readline                    install
php-xml                     install
php7.0                      install
php7.0-cli                  install
php7.0-common                   install
php7.0-curl                 install
php7.0-fpm                  install
php7.0-gd                   install
php7.0-intl                 install
php7.0-json                 install
php7.0-ldap                 install
php7.0-mcrypt                   install
php7.0-mysql                    install
php7.0-odbc                 install
php7.0-opcache                  install
php7.0-pgsql                    install
php7.0-pspell                   install
php7.0-readline                 install
php7.0-xml                  install
root@sb-vf16:/var/log/apache2#

**Comment by guenterh** [comment]
Das
http://sb-vf16.swissbib.unibas.ch/vfrd/Search/Results?lookfor=Schweizerische%20Krebsliga&type=Author
ist der link den ich aufgerufen habe

**Comment by pcoub** [comment]
Fixed:
php-mbstring wird mit Ansible auf allen Hosts der Klasse swissbib.presentation installiert. Siehe: https://git.its.unibas.ch/projects/ANSR/repos/swissbib.presentation/browse/tasks/php.yml

**Comment by guenterh** [comment]
@pcoub Super! - jetzt gehts (s. link oben)
Ja und danke nochmalas für den Hinweis auf Deinen account - hatte Dich nicht mehr gefunden. Jetzt kann ich Dir ja auch issues zuweisen....
Ich lasse diesen sammelissue mal noch offen. Da kann man transparenter austauschen.
@witzigs @edelm fyi

**Comment by pcoub** [comment]
Gute Idee mit dem Sammelissue - Sammelsurium ;-)

Noch zwei Fixes mit Ansible:

- mod_rewrite wird aktiviert
- Neue UFW Regel:

80/tcp                     ALLOW IN    Anywhere

**Comment by guenterh** [comment]
abgeschlossen
@sonjakupfi bitte in Trello schliessen
