### ISSUE TITLE
call to undefined method of VuFind core

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#442]
swissbib module is calling a method of VuFind Core which is no longer available

[Thu Jun 23 07:41:00 2016] [error] [client 131.152.212.156] PHP Fatal error:  Call to undefined method Swissbib\View\Helper\Record::getController() in /usr/local/vufind/c2sb_ci/themes/sbvfrd/templates/RecordDriver/SolrDefault/toolbar.phtml on line 9, referer: http://sb-vf20.swissbib.unibas.ch/c2sb_ci/Search/Results?lookfor=&type=AllFields

e.g.
http://sb-vf20.swissbib.unibas.ch/c2sb_ci/Record/044173229

@edelm I would like to create a new label something like coreIntegration
I do not see a possibility for this in the label dialog. Have I missed something?

**Comment by guenterh** [comment]
abgeschlossen - ich führe regelmässig manuellen merge durch. Fehler tritt nicht mehr auf
@edelm fyi

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [call to undefined method of VuFind core #442](https://trello.com/c/xTqla4k4/52-call-to-undefined-method-of-vufind-core-442)
