### ISSUE TITLE
Suchanfrage mit Ampersand

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#444]
Eine Suche mit Ampersand ergibt keine Treffer

Beispiel: allergy & clinical immunology sinai -> 0 Treffer
gleiche Abfrage ohne Ampersand: allergy clinical immunology sinai -> 2 korrekte Treffer

**Comment by FlorinneEgli** [comment]
Eine Kundenrückmeldung zu Ampersand und Apostroph, wo die verschiedenen Möglichkeiten durchgespielt wurden:
"Das E-Book Goodman & Gilman’s wird in der einfachen swissbib-Suche nicht gefunden, wenn das &-Zeichen eingetragen ist. Gefunden wird das Buch in der einfachen Suche nur mit „Goodman Gilman’s“. Auch ohne Apostroph gibt’s keinen Treffer.
In der erweiterten Titelstichwortsuche wird der Titel mit und ohne & gefunden, jedoch ist auch hier das Apostroph zwingend."

**Comment by witzigs** [comment]
Ein weiterer Fall:

Hotel&Gastro Union: 39 korrekte Treffer
Hotel & Gastro Union: keine Treffer

**Comment by sonjakupfi** [comment]
einfache Suche:
Scrum kurz & gut = Keine Resultate
![scrum_titelsuche_](https://cloud.githubusercontent.com/assets/22593821/23411324/41dec318-fdd2-11e6-9724-0278d8808e07.png)
Scrum kurz gut = Zwei Resultate
![scrum_titelsuche](https://cloud.githubusercontent.com/assets/22593821/23411283/23d1c28a-fdd2-11e6-9154-ae85c20e1f5d.png)
Scrum kurz UND gut = 1 Resultat
![scrum_titelsuche_ohneund](https://cloud.githubusercontent.com/assets/22593821/23411272/1c344584-fdd2-11e6-97f0-523a33698ca2.png)

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Suchanfrage mit Ampersand #444](https://trello.com/c/UMBoHSQF/51-suchanfrage-mit-ampersand-444)

**Comment by witzigs** [comment]
Tritt mit Solr 7 nicht mehr auf, daher geschlossen
