### ISSUE TITLE
Suchhistorie: vereinzelte Suchen können nicht entfernt werden

### ISSUE THREAD

**Issue by FlorinneEgli** [swissbib/vufind#446]
Einige Suchen erscheinen immer in der Suchhistorie:
![image](https://cloud.githubusercontent.com/assets/17006552/17403208/0d8457b4-5a57-11e6-81d5-06e21fe51926.png)
Die einzelnen Suchen lassen sich zwar unter "Gespeicherte Suchen" speichern, erscheinen aber nach dem Löschen wieder in der Suchhistorie, wo sie nicht zu entfernen sind:
![image](https://cloud.githubusercontent.com/assets/17006552/17403258/3e562f34-5a57-11e6-8a57-acc0662daa47.png)
Ich beobachte dies in meinem eigenen Konto, habe aber den Hinweis von einer Arbeitskollegin erhalten, die dasselbe Problem hat.

**Comment by guenterh** [comment]
@edelm Ich konnte das gleich beim ersten Versuch mit meinem eigenen account rekonstruieren

**Comment by guenterh** [comment]
@edelm 
haben wir irgendwo noch die aktuellsten sourcen vom vufind branch deployed um das Verhalten dort ansehen zu können?

**Comment by edelm** [comment]
Die "Suchhistorie" ist bei mir gelöscht, wenn ich mich das nächste mal einlogge. Diese Verhalten deckt sich auch mit dem aktuellen VFCore.

@guenterh: 2.0.2-core3.0.1 ist momentan nur produktiv deployed. Ich habe es mit dem Testaccount getestet. Lokal sollte das auch gehen (im Moment ist aber alephtest down...).

**Comment by sonjakupfi** [comment]
Nachfrage und weitere Klärung zum Issue (Mail Sonja/Florinne):
Bei Florinne bleibt die Suchhistorie bestehend, obwohl sie nicht sollte.
Trotz ausloggen und wieder einloggen hat es eine bestehende Suchhistorie. Obwohl bspw. beim aktuellen Zugriff noch gar keine Suche abgesetzt worden ist.
Löschen des Browserverlaufes, Cookies usw. bringt auch keine Verbesserung der Situation. 

Bei mir (Sonja) selber ist die Suchhistorie leer, wenn ich mich neu anmelde.

**Comment by FlorinneEgli** [comment]
Neue Erkenntnis: Bei den Treffern in meiner Suchhistorie, die ich nicht mehr entfernen kann, handelt es sich um **ehemalige gespeicherte Suchen**. Ich kann das reproduzieren, indem ich eine Suche speichere und sie dann wieder lösche. Anschliessend bleibt sie in der Suchhistorie und es gibt keine Möglichkeit (ausloggen, Cookies etc. löschen.), um sie wieder zu entfernen.

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Suchhistorie: vereinzelte Suchen können nicht entfernt werden #446](https://trello.com/c/YYjVjMB5/50-suchhistorie-vereinzelte-suchen-konnen-nicht-entfernt-werden-446)
