### ISSUE TITLE
Diskussion Vorgehen Migration Ubuntu 16_04 / PHP7

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#450]
@edelm 
Hallo Matthias
- sb-vf16 ist aktuell unser Testhost (Spielwiese) für das Testen von VuFind Applikationen unter Ubuntu 16.04 / PHP7
- wie abgemacht habe ich jusbib verteilt. Wir wollen ja jusbib, als die am wenigsten häufig benutzte Applikation als erstes verteilen.
- Bugs zu dem Thema Migration erfasse ich neu unter dem label php7_ubuntu16_04
- meine Vorschläge zum weiteren Vorgehen und einige Fragen zum Thema, die wir beide morgen besprechen sollten:
-   Ich würde einen zusätzlichen Branch (clone von development) erstellen und dort Fixes erledigen die speziell für die Migration gemacht werden müssen (sie auch die neu erstellten issues im milestone zum Thema)
-  Wie ist der stand im Branch Konfiguration? Wie möchtest Du hier weiter vorgehen? Willst Du das vor der Migration zu Ubuntu live stellen oder zusammen?
-  Für die Migration muss ich auch so Dinge anpassen wie das cli/sync.sh Script (dort wird noch httpd benutzt - unter Ubuntu geht das so nciht mehr. Ich meine im Kopf zu haben, dass Dein Konfigurationsbranch auch hier Anpassungen gemacht hat. Wie sollen wir hier abgestimmt vorgehen?

Günter

@witzigs, @pcoub zur Info

**Comment by guenterh** [comment]
@edelm @witzigs @pcoub
Hallo Matthias / Silvia
* mit Matthias habe ich letzte Woche abgemacht, dass ich einen neuen branch als clone von development für evtl. Anpassungen beim Wechsel zu php7 einrichte
* das ist gemacht: migration/php7
* auf dem branch habe ich angefangen, issues zu fixen. Diese sind unter dem milestone php7_ubuntu_16_04 zusammengefasst. Zur Zeit hat es keine mehr bzw. noch einen Sammelissue, den ich im Moment noch nicht schliessen möchte.
* sb-vf16 ist im Moment unter der domain develop.swissbib.ch ansprechbar (self signed certificate)
* dort habe ich jusbib verteilt. Mit Matthias habe ich ebenfalls abgemacht, dass wir als erstes mit jusbib wechslen werden. Dort gibt es den wenigsten traffic
* Die Applikation läuft, so wie ich das im Moment sehr, recht stabil. Fehler fallen mir keine mehr auf. Die Anmeldung mit Shibboleth klappt auch. @witzigs : kannst Du mal ein AP Personen fragen, ob sie sich die Applikation mal ansehen können? 

Wie weiter?
Hier
https://wiki.urz.unibas.ch/pages/viewpage.action?spaceKey=USC&title=Migration+Ubuntu
sieht man, welche Rechner der Staffel 1 bereits vorhanden und von Paul zum grösseren Teil Ansible bestückt worden sind 
Jusprod wird neu auf dem Rechner sb-uvf5.swissbib.unibas.ch laufen. Aktuell sollte man sich mit seinem persöhnlichen account (mit bereits verteiltem Schlüssel!!) anmelden können. Bitte ausprobieren und mir Feedback geben. Für vfsb wird das bald passieren.

Was ich als nächstes machen werde:
* sb-uvf5 für Jusbib fertig aufsetzen (wenn vfsb mit Schlüsselanmeldung aufgesetzt ist)
* sb-uvf8.swissbib.unibas.ch wird der Rechner für testbaselbern. Diesen möchte ich als nächstes verteilen. Ich werde Stefan Keller bitten, dass er die domain auf diesen Host leitet
@edelm : Macht Du im Moment etwas mit dem alten Host? Kann ich das wechseln

@witzigs : Matthias hat letzte Woche seinen Laptop auf ubuntu 16.04 aktualisiert. So langsam könntest Du auch daran denken. Wir können ja mal darüber reden, wie man es am besten machen kann.

Mal so viel
Günter

**Comment by edelm** [comment]
@guenterh 

>Wie ist der stand im Branch Konfiguration? Wie möchtest Du hier weiter vorgehen? Willst Du das vor der Migration zu Ubuntu live stellen oder zusammen?

Der Config-Branch ist noch nicht soweit. Planen wir erst die Migration auf Ubuntu und danach die Umstellung auf den Config-Branch.

> Für die Migration muss ich auch so Dinge anpassen wie das cli/sync.sh Script (dort wird noch httpd benutzt - unter Ubuntu geht das so nciht mehr. Ich meine im Kopf zu haben, dass Dein Konfigurationsbranch auch hier Anpassungen gemacht hat. Wie sollen wir hier abgestimmt vorgehen?

sync.sh und removeLocalCache.sh lesen beide neu eine Umgebungsvariable aus, um das LocalDir zu bestimmen. Der Code ist Rückwärtskompatibel. Am besten nimmst die Versionen vom config-Branch als Grundlage, um deine Anpassungen zu machen.

>sb-uvf8.swissbib.unibas.ch wird der Rechner für testbaselbern. Diesen möchte ich als nächstes verteilen. Ich werde Stefan Keller bitten, dass er die domain auf diesen Host leitet @edelm : Macht Du im Moment etwas mit dem alten Host? Kann ich das wechseln

testbaselbern.swissbib.ch ist im Moment aufgesetzt, damit die AG testen kann (ssl und config-branch). Ich würde mit dem Umsteller der Domain noch warten, bis der Test-Task durch ist. @witzigs ist da näher in Kontakt mit den Testern, vielleicht kann sie zum aktuellen Stand was sagen.

**Comment by guenterh** [comment]
@witzigs @edelm @pcoub
Hallo zusammen
* auf sb-uvf8.swissbib.unibas.ch ist nun eine erste Testinstallation für Basel/Bern unter php7
* die deploy-scripte zum Verteilen müssen für Ubuntu angepasst werden. Im repository gibt es dafür (nach und nach) neue mit dem Suffix php7.sh
* ich habe bis jetzt keine Zeit gehabt mir den ersten test genauer anzusehen. Könnt Ihr das zwischendurch mal machen und mir ein feedback geben.
* Es werden noch die Datenbanken auf den alten Hosts benutzt. Paul muss dafür erst noch eine Firewallregel auf den neuen hosts setzen

Morgen bin ich in Bern
Günter

**Comment by guenterh** [comment]
Migration Präsentationskomponente abgeschlossen
@sonjakupfi - bitte aus Trello nehemen falls vorhanden
