### ISSUE TITLE
Darstellung "Kosten und Lieferfristen" via Bandauflistung

### ISSUE THREAD

**Issue by FlorinneEgli** [swissbib/vufind#451]
Wenn man bei einer Vollanzeige unter "Standorte&bestellen", unter "Details anzeigen" die Funktion „Kopie bestellen“ nutzt und dort dann den Link „Kosten und Lieferfristen“ anklickt, erhält man diese  Darstellung:
![image](https://cloud.githubusercontent.com/assets/17006552/17777008/24f7b022-655f-11e6-9dd1-61f7b0c77be2.png)
![image](https://cloud.githubusercontent.com/assets/17006552/17777156/b93e33a0-655f-11e6-8760-c42e722bb4b6.png)

Wähle ich dann eine einzelne Bibliothek aus, kommt zudem eine Fehlermeldung:
![image](https://cloud.githubusercontent.com/assets/17006552/17777226/06e8386c-6560-11e6-8dfe-741423ae3898.png)

Ausprobiert habe ich es im IE, im Chrome und im Firefox in angemeldetem Zustand
http://baselbern.swissbib.ch/Record/266453538

**Comment by guenterh** [comment]
@edelm 
Hallo Matthias, ich vermute, dies hängt noch mit der Lightbox zusammen? Was denkst Du?

**Comment by witzigs** [comment]
Gleiches Problem: Wenn man im Zeitschriften-Fenster bei einem einzelnen Exemplar auf "Anmelden" klickt, erscheint nach der Anmeldung die Ausleihen-Seite in der Lightbox.

**Comment by witzigs** [comment]
Wenn man übers Zeitschriftenfenster eine Bestellung ausführt, wird statt der Bestellbestätigung nur ein schmaler weisser Balken angezeigt.

![bestellbestaetigung](https://cloud.githubusercontent.com/assets/9479686/17935684/8901acb4-6a1c-11e6-8fb8-1cc0e81911e4.png)

**Comment by FlorinneEgli** [comment]
Wenn man bei der Vollanzeige unter "Standorte&bestellen", unter "Details anzeigen" das "i" für die Bibliotheksinfo direkt anklickt, kommt ebenfalls eine Fehlermeldung.

**Comment by guenterh** [comment]
@witzigs Kannst Du mir mal zeigen, wie ich auf so ein Beispiel komme? Das hängt wohl mit der LightBox zusammen, die immer noch nicht richtig gefixt ist.

**Comment by guenterh** [comment]
@witzigs sorry, hab's gefunden - hätte im Thread nur bis oben scrollen müssen... Matthias hatte sich das mal angesehen. Das Problem scheint daran zu liegen, dass aus der neu implementierten lightbox heraus neue Links aufgerufen werden. Er hatte noch keine Lösung gesehen.  Schaue es mir an. Kann jedoch nicht sofort alles stehen und liegen lassen.
@FlorinneEgli sorry Florinne, bin mir bewusst es ist urgent. Versuche mich der Sache schnell zu widmen. Matthias ist im Moment leider bis zu Anfang des kommenden Monats in den Ferien

**Comment by FlorinneEgli** [comment]
@guenterh danke!

**Comment by sonjakupfi** [comment]
@edelm 
Wenn im Zeitschriftenfenster "bestellen" angewählt wird, und danach im Bestellfenster der Link "Kosten und Lieferfristen" öffnet sich der Text in einer Lightbox.
Die Änderungen welche für "Kopien bestellen" bereits gemacht worden ist, sollte nun auch noch für "bestellen" gemacht werden.

Wenn eine Bestellung abgeschickt worden ist, erscheint die Bestellbestätigung nicht sofort.
Bei "Kopien bestellen" ist diese Funktion in Ordnung.
