### ISSUE TITLE
Favoriten-Bibliotheken auswählen funktioniert nicht

### ISSUE THREAD

**Issue by FlorinneEgli** [swissbib/vufind#454]
Wenn man eine Favoritenbibliothek auswählen möchte, erscheint entweder eine Liste, in der man nicht nach unten scrollen kann oder es kommt bloss die Meldung "loading..."

![1](https://cloud.githubusercontent.com/assets/17006552/18310936/cb94b90a-7501-11e6-8189-ce8fcabdf7a4.jpg)

![2](https://cloud.githubusercontent.com/assets/17006552/18310939/cd5a40ca-7501-11e6-91d6-71b8032fb1a9.jpg)

**Comment by guenterh** [comment]
@FlorinneEgli @witzigs @edelm 
Hallo Florinne,
als Zwischenstand zu diesem Bug von meiner Seite:
Ich habe mir heute Nachmittag die Änderungen durch die letzten Updates von Matthias angesehen. Ich sehe was so gemacht wurde, habe aber das Problem, dass ich die Hintergründe der Änderungen nicht kenne. 
Es sind Sachen von früher, die noch von mir gemacht wurden, weggefallen, meist, so wie ich das verstehe, weil von VuFind Anpassungen gemacht wurden, die dann nicht mehr kompatibel mit unserer früheren Implementierung gewesen sind. So hatten wir ungefähr im Mai das Problem, dass durch Betätigen der Returntaste ein ausgewähltes item aus der Favoritenliste nicht übernommen worden ist (daran erinnere ich mich auch noch).
Nur, wenn ich mir jetzt so ansehe was gemacht wurde, habe ich grössere Zweifel, dass die Grundfunktionalität, wie sie mal bestand, noch funktionieren kann. (Deswegen geht es ja jetzt auch nicht mehr...) Aber: die Anpassungen wurden zum Teil bereits im Juni gemacht und ich kann mir eigentlich nicht vorstellen, dass dieser doch recht heftige und offensichtliche Bug (Favoriten werden, denke ich mal, noch häufig gebraucht) in der Zwischenzeit nicht bemerkt worden ist.

Deswegen möchte ich sehr ungerne jetzt einfach so etwas abändern ohne vorher mit Matthias darüber gesprochen zu haben. Ich habe die Favoriten mit dem alten Code bei mir lokal auch wieder laufbar bekommen, dann habe ich jedoch das Problem der Usabilty (Benutzung der Returntaste z.B.) Das wäre in meinen Augen zwar weniger schlimm als das jetzige Verhalten (bei dem gar nichts funktioniert) aber ich weiss auch nicht, ob durch die weiteren Anpassungend in der Zwischenzeit sonst Dinge nicht funktionieren würden, also die Möglichkeit einer Verschlimmbesserung nicht auszuschliesen ist.

Lange Rede, kurzer Sinn: Im Moment gehe ich davon aus, dass wir den Fehler nicht vor Matthias' Rückkehr werden beheben können. (Bzw. der Aufwand dafür sehr hoch wäre, weil ich mich noch sehr viel intensiver damit beschäftigen müsste, um die Hintergründe der Anpassungen zu erkunden. Dieser Aufwand würde sicherlich erheblich verkleinert, wenn mir Matthias die Überlegungen zu den Anpassungen direkt mitteilt)

Ich bitte vielmals um Entschuldigung und ich hoffe das ist für Dich akzeptabel.

Günter

**Comment by FlorinneEgli** [comment]
Nach Mail von Matthias, dass Favoriten wieder funktionieren, habe ich dies getestet:
Ich kann eine ausgewählte Bibliothek nicht als "Meine Bibliothek" speichern.
Ich kann eine bereits unter "Meine Bibliothek" gespeicherte Bibliothek nicht löschen.
Ich konnte nur bei den ersten Versuchen Bibliotheken wählen, bei weiteren Versuchen kommt eine ewiges "Loading...."

**Comment by FlorinneEgli** [comment]
Es gibt nun ein anderes Problem: Wenn ich z.B. "Uni Bern" eingebe, bekomme ich eine Liste von Bibliotheken, die so lange ist wie mein Bildschirm. In dieser Liste kann ich aber nicht scrollen. Ich kann so beispielsweise "Uni Bern - Bibliothek Münstergasse" nicht finden.
Diese Liste geht eigentlich von A-J, komischerweise steht die Bibliothek für Medizingeschichte aber als Ausnahme zuoberst.

**Comment by mschwendener** [comment]
Zur Ergänzung: ich hatte in Basel auch eine Fall, der fälschlicherweise zuoberst sortiert hat innerhalb von Uni Basel - dort lag es an einem doppelten Spatium im libadmin, sollte morgen behoben sein (Uni Basel - Kulturmanagement).

Uni Bern - Medizingeschichte sehe ich nicht innerhalb von Uni Bern - ...; weder in orange noch grün. 
 
 
Andere Ungereimtheit: E30 Uni Bern - Exakte Wissenschaften wird in orange unter Uni Bern - ... angezeigt, in grün nicht. Wenn ich weiterschreibe (Uni Bern - e) erscheint sie.

**Comment by edelm** [comment]
Bisher wurden nur jeweils 20 Treffer angezeigt. Ich habe die Anzahl anzuzeigenden Resultate erhöht. Jetzt sollte man also auch scrollen können.
