### ISSUE TITLE
Änderung der Einstellung "Sortieren nach"

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#455]
Wenn man im Konto unter "Einstellungen" die Sortierung ändert, wirkt sich das nicht aus. Die neu gewählte Einstellung wird zwar als abgespeichert angezeigt, bei der nächsten Suche ist jedoch noch immer die alte Einstellung wirksam.

Das Ändern der Sprache sowie der Maximalen Trefferanzahl funktionieren korrekt.

**Comment by edelm** [comment]
tritt nicht mehr auf bei release 2.0.6-core3.0.3
