### ISSUE TITLE
Zeitschriftenfenster bei Leitbibliotheken

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#457]
Bei Bibliotheken, die in CBS zu einer Leitbibliothek zusammengeführt werden, fehlt im Zeitschriftenfenster die Verfügbarkeitsanzeige und der Link zur Anmeldung (d.h. Bestellung, etc. ist nicht möglich).

Beispiele:
http://baselbern.swissbib.ch/Record/125912374/
Holding für Speicherbibliothek Büron 
institution_chb = CHSBK 
institution = BSSBK
Institution der Exemplare = BSSBK
-> in CBS wird BSSBK zur Leitbibliothek CHSBK hinzugefügt
Bei Aufbau des Zeitschriftenfenster werden zu den Exemplarinformationen, die über Aleph-Rest geholt werden, Informationen aus der Holding hinzugefügt. Dabei wird mit Institution BSSBK nach einer Holding von BSSBK gesucht. Diese wird nicht gefunden, da in der Holding als institution_chb CHSBK angegeben ist.

http://baselbern.swissbib.ch/Record/329137328
Holding für Schweizerisches Institut für Volkskunde / Uni Basel - Kulturwissenschaft, Europäische Ethnologie
institution_chb = A258
institution = A259
Institution der Exemplare = A259

**Comment by guenterh** [comment]
@witzigs 
Ist das ein Problem von swissbib DAIA?
so wie ich das sehe nicht.

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Zeitschriftenfenster bei Leitbibliotheken #457](https://trello.com/c/73LKK8gv/43-zeitschriftenfenster-bei-leitbibliotheken-457)

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Zeitschriftenfenster bei Leitbibliotheken #457](https://trello.com/c/73LKK8gv/43-zeitschriftenfenster-bei-leitbibliotheken-457)
