### ISSUE TITLE
Merkliste - Fehlermeldung fehlt

### ISSUE THREAD

**Issue by sonjakupfi** [swissbib/vufind#459]
Wenn eine Merkliste nach dem Erstellen per Mail versendet, oder Exportiert werden möchte, muss zwingend eine Auswahl getroffen werden.
Falls dies nicht gemacht wird, erscheint ein "leeres" Fenster, jedoch ohne entsprechende Fehlermeldung.
![meldung_merkliste-versenden](https://cloud.githubusercontent.com/assets/22593821/19680534/6181e360-9aa6-11e6-8a65-a80f8f689780.png)

In VuFind Demo erscheint für genannte Problematik die Fehlermeldung "es wurde nichts ausgewählt..."
![merkliste-versenden_beispiel_vufind](https://cloud.githubusercontent.com/assets/22593821/19680523/54ae8bde-9aa6-11e6-9a7a-85660ab53a13.png)

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Merkliste - Fehlermeldung fehlt #459](https://trello.com/c/1LnegwV8/41-merkliste-fehlermeldung-fehlt-459)

**Comment by witzigs** [comment]
neues Issue erfasst, deshalb hier geschlossen.
Siehe #520
