### ISSUE TITLE
Designanpassung / Layoutanpassung: Tabellen auf kleinen Viewports

### ISSUE THREAD

**Issue by ToVie** [swissbib/vufind#46]
Story
---
Wie im Dokument "rwd_problematische_inhaltselemente.pdf" festgehalten machen Tabellen auf kleinen Viewports Probleme. (Punkt 3.2)
Hier soll einerseits geprüft werden, wie die Umsetzung einer "vertikalen Lösung" auszusehen hätte und andererseits in Absprache mit dem Swissbib-Team eine Umsetzung vorgenommen werden.

**Comment by oschihin** [comment]
Sollte im Zug von #278 angegangen werden

**Comment by adchsnowflake** [comment]
@oschihin
Kann dieses Issue geschlossen werden? Dabei ging es ja um Abklärungen, welche wir getätigt haben.

**Comment by oschihin** [comment]
@adchsnowflake Abklärungen sind getroffen, Umsetzung offen als 3. Etappe der Arbeiten am Exemplartab. Schliesse hier, da inhaltlich andernorts erfasst (todoyu)
