### ISSUE TITLE
Sidebar Advanced Search

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#460]
Die sidebar für die Advanced Search sollte angepasst werden:
* In allen drei views: zusätzlich Links auf die Suchhistorie und die Einstellungen ergänzen. Vgl. https://github.com/swissbib/vufind/blob/master/themes/sbvfrdmulti/templates/search/advanced/sidebar.phtml#L26

* In swissbib Basel Bern: Zusätzlich vier Links auf andere Kataloge anzeigen. Vgl. https://github.com/swissbib/vufind/blob/master/themes/sbvfrdmulti/templates/search/advanced/sidebar.phtml#L33
Diese Links sind bei der Vereinheitlichung der Sidebars verloren gegangen (vgl. ce009c97614d4f3f137753c9a294ce5f48b05fda)

@edelm : Kannst du das mit @sonjakupfi anschauen?

**Comment by sonjakupfi** [comment]
Ist in Ordnung.

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sidebar Advanced Search #460](https://trello.com/c/F5NkEhAJ/40-sidebar-advanced-search-460)
