### ISSUE TITLE
add backlink at item level for national licenses

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#461]
Aktuell verweist der Holdings Backlink für Ressourcen aus Nationallizenzen auf die gleiche 'full view page' auf der sich BenutzerInnen bereits befinden.
Für mich macht dies nicht sehr viel Sinn. Wollen wir das so lassen? Gibt es eine bessere Alternative?
Beispiel: https://test.swissbib.ch/Record/35362117X
s. holdings tab

**Comment by liowalter** [comment]
I see two options : 

 * no backlink at all
 * use the same url as the one used above (with all the tests : IP address, ...)

I implemented the first option in commit 8b2796fa230f80b9993f6bf0c828bd511181dac2

The second option would be better. @edelm : can you take care of this when it is ready ?

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [holdings backlink for national licenses resources is recursive #461](https://trello.com/c/sm7iTDTo/39-holdings-backlink-for-national-licenses-resources-is-recursive-461)
