### ISSUE TITLE
national license menue item for users authenticated with shibboleth but not swissEduId

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#462]
@liowalter @edelm 
use case:
- user is logged in but 'not' with swissEduId
- then he/she clicked on the personal settings item
- now he/she can access the national license menu especially tailored for private users authenticated with swissEduId 
- I think this doesn't make any sense because now he/she can click on functionality which is stored in his/her user account but with the current shibboleth user Id he/she will never get an attribute common lib terms because this is, as far as a know, only available as swiss edu id user
question: is it necessary to hide the national license dialog if user is not authenticated with swiss edu id?

another question (discussion between Matthias and Günter)
- user authenticated with shibboleth (not swissEdu Id) but not within an IP range of an institution - does he/she get access to national license material?

**Comment by liowalter** [comment]
I suggest the following : 

For https://github.com/swissbib/vufind/blob/feature/Nationallizenzen/themes/sbvfrdsingle/templates/nationallicences/index.phtml, we add an if case at the beginning. If the person is logged in with something else than swiss edu-id (we use $_SERVER->entity-id or similar), we display something like this

>"You are logged in using your institutional credentials. Basically, you should have access to National Licences Content via your institution network and needs no special registration.
>
>If this is not the case and you live in Switzerland, you can access National Licences Content by creating a Swiss edu-ID or logging in with your Swiss edu-ID credentials if you already have a Swiss edu-ID account."
>
>Learn more about <a href="http://www.nationallicences.ch">Swiss National Licences</a>."

Indeed, you are completely right, it doesn't make sense to activate the flag if you are logged in with something else than swiss edu-id.

For the other question : 
> user authenticated with shibboleth (not swissEdu Id) but not within an IP range of an institution - does he/she get access to national license material?
It depends of the institution. For big universities, it is possible to login via shibboleth on the publisher's platform. For small or not "academic" (like the federal administration or hospitals), it only works with IP recognition on the publisher's platform. Therefore, I wouldn't tackle this case and keep it simple : either IP or Swiss edu-ID.

Is that ok for you ? If yes, I can take care of this.
