### ISSUE TITLE
Authentication with Swiss Edu-ID on Oxford Mobile Platform doesn't work

### ISSUE THREAD

**Issue by liowalter** [swissbib/vufind#465]
When Oxford detects a mobile phone, they redirect to their mobile platform. There, the authentication with swiss edu-id doesn't work.

One example : 
Kin Recognition in Ground Squirrels and Other Rodents
https://test.swissbib.ch/Search/Results?lookfor=Kin+Rodents&type=AllFields&filter%5B%5D=union%3A%22NATIONALLICENCE%22&limit=20&sort=relevance

The link is the following : 
https://shibboleth.highwire.org/session/init?entityID=https%3A%2F%2Feduid.ch%2Fidp%2Fshibboleth&hw-shib-return-uri=http%3A%2F%2Fjmammal.oxfordjournals.org%2Flookup%2Fdoi%2F10.1644/BLe-011&subcode=oupjournals&env=prod

At the end the user lands here : 
http://m.jmammal.oxfordjournals.org//lookup/doi/10.1644/BLe-011?hwshib2=authn%253A1480673492%253A20161201%25253A4d8008aa-9876-4242-876c-388918ae7379%253A0%253A0%253A0%253ANTwYsqKDc5r8iNye%252FjE7vg%253D%253D

Where a password is required : 

![screenshot_036](https://cloud.githubusercontent.com/assets/1135460/20790092/2a824c46-b7b7-11e6-8535-f3fa51204ec6.png)

It seems that Oxford Mobile Website doesn't support authentication via Shibboleth. Only IP address authentication is supported. Maybe the new platform (planned for January 2017) will be better with that.

**Comment by liowalter** [comment]
Fixed by Oxford new platform

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Authentication with Swiss Edu-ID on Oxford Mobile Platform doesn't work #465](https://trello.com/c/zNYqoIS3/38-authentication-with-swiss-edu-id-on-oxford-mobile-platform-doesn-t-work-465)
