### ISSUE TITLE
Links to Oxford platform sometimes fails

### ISSUE THREAD

**Issue by liowalter** [swissbib/vufind#466]
When the doi is not correctly registered the link to Oxford platform fails.

Example : 
 * https://test.swissbib.ch/Search/Results?lookfor=THE+BASIC+PRINCIPLES+AND+BRIEF+HISTORY+OF+COMPUTER+TECHNOLOGY+payne&type=AllFields&limit=20&sort=publishDateSort+desc

Maybe use
http://[WEBSITE CODE].oxfordjournals.org/content/[VOLUME]/[ISSUE]/[PAGE].long
http://nar.oxfordjournals.org/content/25/17/3389.long

as described here
http://www.oxfordjournals.org/en/help/tech-info/linking.html

**Comment by edelm** [comment]
Shall we just replace the DOI-URL-blueprint with the new blueprint? Or do we have to check if the DOI exists, and if not, use the new bluepint?

**Comment by liowalter** [comment]
Probably the new blueprint, but I need to check first in the data that we always have the volume-issue-page information.

**Comment by liowalter** [comment]
solved (probably by oxford new platform)

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Links to Oxford platform sometimes fails #466](https://trello.com/c/Ho0XU0JI/37-links-to-oxford-platform-sometimes-fails-466)
