### ISSUE TITLE
For some journals, links to De Gruyter fails

### ISSUE THREAD

**Issue by liowalter** [swissbib/vufind#467]
For the journal libri, the links to De Gruyter redirect to the newest article instead of the wanted article

https://test.swissbib.ch/Search/Results?lookfor=libri+nationallicence*&type=AllFields&limit=20&sort=publishDateSort+desc

**Comment by edelm** [comment]
Tritt bei mir lokal im Moment nicht mehr auf. Verschiedene DeGruyter Links verweisen auf verschiedene Dokumente.

**Comment by liowalter** [comment]
This is still the case in production : 
Libri's Golden Jubilee in a Bibliometric Mirror
https://www.swissbib.ch/Record/378600397
Link : https://www.degruyter.com/openurl?genre=article&issn=0024-2667&volume=50&issue=2&spage=75

We land on 
A Four Frames Analysis to Address the Information Challenges of Families of Children with ADHD: Actions for Public Libraries to Address Embedded Power Imbalances
https://www.degruyter.com/view/j/libr.2016.66.issue-1/libri-2015-0078/libri-2015-0078.xml

This is the most recent article of this journal, not the one we are looking for.

**Comment by liowalter** [comment]
This seems to be a problem on the side of De Gruyter. For some ISSN, De Gruyter cannot resolve to the correct issue although the openurl is correct.

But this will be solved by implementing the new url template for De Gruyter as described in #476
