### ISSUE TITLE
no backlik in full view for NL

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#470]
@liowalter @edelm 
is it by intention that we don't provide a link to the NL resource in the full view where resources were merged together?
Example:
https://www.swissbib.ch/Record/380185474 
Shouldn't we provide the link at least in the holdings tab?

**Comment by liowalter** [comment]
There is no link currently in the holdings tab due to issue #461. 

The fact that https://www.swissbib.ch/Record/380185474 has no backlink is the same problem as the issue #469.

Therefore I close this issue.
