### ISSUE TITLE
FRBR clustering of national licenses correct?

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#471]
@liowalter @witzigs 
is the clustering correct?
https://www.swissbib.ch/Search/Results?lookfor=049123017&type=FRBR&originalSort=relevance&limit=20&sort=publishDateSort+desc

**Comment by witzigs** [comment]
@guenterh  @liowalter 
Das Clustering ist schlecht, aber "korrekt". CBS prüft für das FRBR-Cluster vier Indices: Titel/Autor, ISBN, ISSN und Catalog Number (028).
In diesen Fällen ist nur der Index Titel/Autor vorhanden -> überall "Frontmatter". Daher wird ein Cluster gebildet.

**Comment by witzigs** [comment]
@liowalter 
Ich schliesse hier, wir lösen das über Ausschluss gewisser Aufnahmen. In Ordnung?

**Comment by liowalter** [comment]
yes, ok !
