### ISSUE TITLE
redirect to publisher's platform is sometimes slow

### ISSUE THREAD

**Issue by liowalter** [swissbib/vufind#472]
Sometimes the process to redirect to the publisher's platform with a wayfless url's with Swiss edu-ID embedded is slow. Especially for De Gruyter.

Some ideas : 

 * display something better than a blank screen (feedback from test "Ein Hinweis darauf, dass man weitergeleitet wird und sich ein paar Sekunden gedulden sollte, wäre hier sicher gut.")
 * only use wayfless links for the first link clicked. Then use normal direct links. This works as the user is already authenticated on the platform. But we need to know and record to which platform the user already authenticated himself.

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [redirect to publisher's platform is sometimes slow #472](https://trello.com/c/v1NThAUL/34-redirect-to-publisher-s-platform-is-sometimes-slow-472)

**Comment by liowalter** [comment]
This is now better after publisher's platform changes.
