### ISSUE TITLE
Backlink (Go to holdings) for serval is broken

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#474]
@sonjakupfi @edelm @witzigs 
the backlink to serval repository is broken. I made a test with two resources. Examples
https://www.swissbib.ch/Record/374370109
https://www.swissbib.ch/Search/Results?type=AllFields&filter%5B%5D=union%3A%22SERVAL%22

**Comment by witzigs** [comment]
Das ist kein generelles Problem mit Serval sondern mit einzelnen Datensätzen. Zum Teil funktioniert der Link korrekt (Beispiel: https://www.swissbib.ch/Record/26416380X).
Einen Zusammenhang mit den Nationallizenzen gibt es auf jeden Fall nicht.

@guenterh 
Kannst du prüfen, ob das Serval-Harvesting korrekt läuft? Wir haben seit dem 22.11. keine Daten erhalten. Auf Serval finde ich jedoch Datensätze mit Timestamp vom 30.11.
