### ISSUE TITLE
issn missing sometimes for De Gruyter

### ISSUE THREAD

**Issue by liowalter** [swissbib/vufind#476]
One example : https://www.swissbib.ch/Record/379726165

Then link to platform doesn't work.

**Comment by liowalter** [comment]
The source record has only an eissn and no pissn.
JATS : 
<issn pub-type="epub">1941-6008</issn>

In mods it gives 
<identifier type="eISSN">1941-6008</identifier>

This is the case for 17'000 articles.

Way to solve it : in mods2norm, take the eISSN, when there is no pISSN

At the end the link will be : https://www.degruyter.com/openurl?genre=article&issn=1941-6008&volume=4&issue=3&spage=

The other problem with journals that have no print issn is that they have no page numbers.

After searching a bit, we can use another syntax for linking : 
https://www.degruyter.com/doi/10.2202/1941-6008.1141

This seems to work even for doi which are not registered at crossref : 

 * https://doi.org/10.1515/9783110192377.21 doesn't work
 * https://www.degruyter.com/doi/10.1515/9783110192377.21 works

As a wayfless url's it becomes : 
https://www.degruyter.com/applib/openathens?entityID=https%3A%2F%2Feduid.ch%2Fidp%2Fshibboleth&openAthens2Redirect=https%3A%2F%2Fwww.degruyter.com%2Fdoi%2F10.2202%2F1941-6008.1141

which works fine.

We implement this solution.

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [issn missing sometimes for De Gruyter #476](https://trello.com/c/VLVn1lyN/31-issn-missing-sometimes-for-de-gruyter-476)
