### ISSUE TITLE
access to NL content within institution IP range not possible

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#477]
@liowalter @edelm 
I tried to access the resource
https://www.swissbib.ch/Record/379726165
while I was within the ip range of the University Basel. Therefor actually the application generates a direct link to the resource. https://www.degruyter.com/view/j/crelle.2016.2016.issue-719/crelle-2014-0029/crelle-2014-0029.xml
But, I guess because Basel hasn't licensed it, I have no access to it.
Using the swissEduId mechanisms I should have got access. 
How can we make these things smarter?

**Comment by liowalter** [comment]
The problem with https://www.swissbib.ch/Record/379726165 is that the ISSN is missing in the url. This is in the issue #476 .

Therefore I close this issue.
