### ISSUE TITLE
After successful registration, provide a way to search within national licences

### ISSUE THREAD

**Issue by liowalter** [swissbib/vufind#478]
After successful registration, on that screen : 

![image001](https://cloud.githubusercontent.com/assets/1135460/21011527/00f886ba-bd52-11e6-97bb-aaeed1a25db3.jpg)

Add on top a link to https://www.swissbib.ch/Search/Results?type=AllFields&filter%5B%5D=union%3A%22NATIONALLICENCE%22 

or a searchbox.

**Comment by liowalter** [comment]
tackled by https://github.com/swissbib/vufind/commit/e22070ddcac9e48a87fdc65c91cc009b662478a4

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [After successful registration, provide a way to search within national licences #478](https://trello.com/c/en8UTr1r/30-after-successful-registration-provide-a-way-to-search-within-national-licences-478)

**Comment by liowalter** [comment]
release 2.5.3-core3.1.2
