### ISSUE TITLE
Automatically activate temporary access ?

### ISSUE THREAD

**Issue by liowalter** [swissbib/vufind#479]
When the user adds his phone number, he is then sent back to 
https://www.swissbib.ch/NationalLicences

Then he needs to click "Activate Temporary Access".

Should this be automatic ?

Advantage : one less click for the user
Disadvantage : user can not choose when he wants to do the 14 days test

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Automatically activate temporary access ? #479](https://trello.com/c/V8205F6A/29-automatically-activate-temporary-access-479)

**Comment by liowalter** [comment]
automatic activation implemented in release 2.5.3-core3.1.2
