### ISSUE TITLE
Move intro text to the bottom of the registration screen ?

### ISSUE THREAD

**Issue by liowalter** [swissbib/vufind#483]
Would that be better ? Clearer ?

![screenshot_013](https://cloud.githubusercontent.com/assets/1135460/21095999/3cef87b8-c05e-11e6-9dd2-72a3cbfa3b10.png)

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Move intro text to the bottom of the registration screen ? #483](https://trello.com/c/kx4aDaZC/27-move-intro-text-to-the-bottom-of-the-registration-screen-483)

**Comment by liowalter** [comment]
release 2.5.3-core3.1.2
