### ISSUE TITLE
Impossible to uncheck the terms of use

### ISSUE THREAD

**Issue by liowalter** [swissbib/vufind#485]
Once the user has accepted the terms of use of swiss national licences, he cannot untick the box.

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Impossible to uncheck the terms of use #485](https://trello.com/c/7t7MXG8h/25-impossible-to-uncheck-the-terms-of-use-485)

**Comment by liowalter** [comment]
Not very important.
