### ISSUE TITLE
links to serval are broken

### ISSUE THREAD

**Issue by liowalter** [swissbib/vufind#486]
Example : https://www.swissbib.ch/Record/364846437/Holdings#tabnav

@witzigs : is that related to National Licences or to the fact that Serval has a new platform ?

Here is a url working for this record : https://serval.unil.ch/notice?pid=serval:BIB_4270B596AA2A
Or https://serval.unil.ch/notice/serval:BIB_4270B596AA2A ?

**Comment by witzigs** [comment]
hier geschlossen - doppeltes Issue, siehe #474
