### ISSUE TITLE
Improve availability text for National Licences

### ISSUE THREAD

**Issue by liowalter** [swissbib/vufind#487]
Currently we have : 

 * Verfügbar ? Keine Angabe

![screenshot_046](https://cloud.githubusercontent.com/assets/1135460/21097186/a929d474-c063-11e6-955d-5c0e6ee48184.png)

This is also the case for repositories like Zora and Boris or E-periodica.

For National Licences : I would suggest the text **Available online for Swiss Residents**.

For E-periodica : **Available online**.

For repositories, do we harvest only open access documents ? If yes, we could use **Available online** as well. If no, we might need to us **Access restricted** or something similar in some cases.

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve availability text for National Licences #487](https://trello.com/c/ZKyALTdj/24-improve-availability-text-for-national-licences-487)

**Comment by liowalter** [comment]
@witzigs : the "available online" text is now set for Boris, Serval, E-codices and E-periodica. Is that correct ?

**Comment by witzigs** [comment]
@liowalter : i've deleted SERVAL as not all content is OA

**Comment by liowalter** [comment]
closed with 48323b2a779281918f6e5e223a748a598303848d
