### ISSUE TITLE
Wrong url's for the intersection between E-periodica and Boris

### ISSUE THREAD

**Issue by liowalter** [swissbib/vufind#489]
For a record which is part of Boris and E-periodica, the url in the result list is wrong.
https://www.swissbib.ch/Search/Results?type=AllFields&filter%5B%5D=union%3A%22RETROS%22&filter%5B%5D=union%3A%22BORIS%22

First record : ""Es drängt sich eine Versetzung an einen sehr abgelegenen Ort auf ...". 

The link behind "E-periodica" is towards : 
https://www.swissbib.ch/Search/Results?type=AllFields&filter%5B%5D=union%3A%22RETROS%22&filter%5B%5D=union%3A%22BORIS%22

instead of the e-periodica links.

**Comment by edelm** [comment]
Trefferliste-Link "e-periodica" sollte analog Vollanzeige auf "retro.seals..." verweisen.

**Comment by edelm** [comment]
Record 334562880 stores the retro/eperiodica link in field 950. In the ResultsList, we show urls stored in 856 and 956. In Fullview, we show urls stored in 950 and 956. Therefore, the link doesn't get shown in the ResultList but in the Fullview.
