### ISSUE TITLE
date-slider in VuFind 3.1.1

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#491]
Nach dem Merge mit dem Release 3.1.1 (VuFind Core) ist der date-slider in der advanced search nicht mehr so wie er sein sollte.
@edelm : Matthias, können wir das zusammen ansehen, ich habe schon lange nicht mehr Java-Script / CSS bugs gefixt. Mir fehlt unterdessen ein wenig das passende Instrumentarium

 
![date slider defekt](https://cloud.githubusercontent.com/assets/1825990/21612966/87f0a82e-d1d3-11e6-832d-0e3d737169c8.png)

**Comment by guenterh** [comment]
der Bug tritt auf allen drei Instanzen auf:
test.swissbib.ch (sb-uvf4)
jus test (aktuell sb-uvf6)
test.baselbern.swissbib.ch
sb-uvf7 (wird devbabe werden, aktuell ist devbabe noch auf dem alten host)

**Comment by guenterh** [comment]
Problem besteht auch in Suchliste

![date-range-suchliste](https://cloud.githubusercontent.com/assets/1825990/21617417/557e8646-d1e6-11e6-86af-a6f62765ec4c.png)

**Comment by guenterh** [comment]
im letzten merge mit vufind - master (neuer branch https://github.com/swissbib/vufind/tree/core2swissbib_manually) tritt der Fehler ebenfalls auf

**Comment by edelm** [comment]
Include von bootstrap-slider.css auf entsprechenden Seiten eingefügt (analog 8c3bf7f3ba75f08ca9b51fec5413d9384b4a30ad).

**Comment by guenterh** [comment]
fixed with
https://github.com/swissbib/vufind/commit/35b53cd1b2350e25e65fe0368b52d303c7995ce7
deployed for:
test.swissbib.ch
justest
lastmaster

**Comment by liowalter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ajouter les oxford key url's pour les 65 nouveaux titres](https://trello.com/c/NZ7SDIGK/88-ajouter-les-oxford-key-url-s-pour-les-65-nouveaux-titres)
