### ISSUE TITLE
jusbib: Suche in Title und Series ergibt zu viele Treffer

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#492]
Bei einer Suche in jusbib über die folgenden types erhält man eine zu hohe Trefferzahl:
- Title
- Series

Die Suchbegriffe werden nicht mit AND oder mm 100% kombiniert.
In searchspecs_jusbib.yaml für Title ist der Parameter mm 100% jedoch vorhanden. Für Series fehlt er.

**Comment by sonjakupfi** [comment]
Hilft dieser Issue evtl. bei der Bearbeitung weiter?
https://github.com/swissbib/vufind/issues/436 
Oder dieser hier: 
https://github.com/swissbib/vufind/issues/437

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Titel-Suche in jusbib (#492)](https://trello.com/c/GVY7sqMu/267-titel-suche-in-jusbib-492)

**Comment by witzigs** [comment]
Korrigiert durch fb2fda1e7b3858576b095f7e67f5880469243a26
