### ISSUE TITLE
Verlinken auf faq3

### ISSUE THREAD

**Issue by sonjakupfi** [swissbib/vufind#493]
Innerhalb der Hilfeseite (FAQ) (https://baselbern.swissbib.ch/HelpPage/faq) kann auf den Bereich "Bestellen" gesprungen werden.

Mittels folgendem Link kommt man auf die #faq3
https://baselbern.swissbib.ch/HelpPage/faq#faq3

Der direkte Zugriff auf diesen Bereich der FAQ funktioniert jedoch nicht, wenn der Link direkt im Browser eingegeben wird. Somit kann auch nicht von einer anderen Webseite direkt auf die Funktion "Bestellen" verlinkt werden.

Gemäss Stand 16.01.2017 ist es ein bekanntes Firefox und IE-Problem.

Manuela Schwendener würde den Direktlink gerne auf der neuen Website der UB einbinden.
Die Website sollte erste Hälfte 2017 live geschaltet werden.

**Comment by mschwendener** [comment]
Ebenfalls für den neuen Webauftritt möchte ich direkt auf einzelne Fragen linken können, Antwort bereits aufgeklappt (Bsp. "Ich habe in swissbib Basel Bern das Gesuchte nicht gefunden, was kann ich tun?" und "Wie bestelle ich eine Kopie?").
 
Das betrifft nicht nur Firefox, geht in Chrome auch (noch) nicht.

**Comment by mschwendener** [comment]
Ergänzung zu post 1: was übrigens in Firefox problemlos funktioniert, ist ein direkter Link auf http://www.ub.unibas.ch/ub-hauptbibliothek/wir-ueber-uns/termine-veranstaltungen/themenabende/#c18831
= Themenabend April, verlinkt von http://www.ub.unibas.ch/ub-hauptbibliothek/wir-ueber-uns/termine-veranstaltungen

**Comment by mschwendener** [comment]
Weitere Frage in dem Zusammenhang: kann ich direkt auf die englische FAQ-Seite linken? 
https://baselbern.swissbib.ch/HelpPage/faq öffnet in der Sprache meines Browsers - wenn ich die Sprache durch Klick rechts oben umstelle, ändert sich nichts an der URL. 
'Geht nicht' ist ok als Antwort ;-)
