### ISSUE TITLE
jusbib: Erweiterte Suche Filter in searchspecs nicht aktiv

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#494]
Bei einer Suche in der erweiterten Suche in jusbib ist der jusbib-QueryFilter nicht aktiv bei folgenden Suchfeldern:
- Thema (Filter in searchspecs fehlt) -> erledigt
- Verfasser (Filter in searchspecs vorhanden) -> erledigt
- Zeitschriftentitel (Filter in searchspecs vorhanden)

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [jusbib: Erweiterte Suche Filter in searchspecs nicht aktiv #494](https://trello.com/c/B8RkTBrI/320-jusbib-erweiterte-suche-filter-in-searchspecs-nicht-aktiv-494)

**Comment by witzigs** [comment]
Thema korrigiert durch def2e818e250bfb2118c85b949d5dbbd915f3192
Verfasser korrigiert durch dc6ebae7e2e63c75d4b18efd4d82efa234e5e95f

Zeitschriftentitel: Die Kombination von Format-Filter und jusbib-Filter funktioniert nicht über VuFind. Auf solr gibt eine Abfrage mit der FilterQuery die korrekte Treffermenge.

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [494](https://trello.com/c/3OAYqonL/73-494)

**Comment by witzigs** [comment]
Ergänzung dazu: Wenn man in jusbib eine leere erweiterte Suche absetzt, wird der query filter nicht mit geschickt. Entsprechend erhält man die komplette Treffermenge von swissbib.
@liowalter : Siehst du eine Lösung dafür?

**Comment by edelm** [comment]
Suche nach JournalTitle gefixt mit 1d4ea1e08802fd39034e6d01b5f76f82e10fb5a1

**Comment by liowalter** [comment]
This is only for the empty search. We let it like this.
