### ISSUE TITLE
Information ("Little i") missing in the holdings of National Licences

### ISSUE THREAD

**Issue by liowalter** [swissbib/vufind#495]
In the holdings of National Licences, location is empty and there is no link to
http://www.nationallizenzen.ch/ : 
![screenshot_060](https://cloud.githubusercontent.com/assets/1135460/22419301/2550d152-e6dd-11e6-8688-68cde65af00b.png)

Is it a libadmin problem ?

**Comment by mschwendener** [comment]
Should be ok tomorrow.

**Comment by liowalter** [comment]
For the newly created springer, the little i is missing.
@mschwendener : can you fix it ?

Thanks a lot !

**Comment by liowalter** [comment]
done
