### ISSUE TITLE
Freihandbestände - Meldung zum Abholort

### ISSUE THREAD

**Issue by sonjakupfi** [swissbib/vufind#496]
Aus der Sitzung der AG Basel Bern vom 09.02.2017:
Bei Freihandbeständen wird momentan die besitzende Bibliothek nicht als Abholort gelistet, was in Basel zu vielen Kundenanfragen und Fehlbestellungen führt. Das Infoteam der UB Basel schlägt vor, die besitzende Bibliothek als Abholort aufzulisten und analog der HSG St. Gallen ein Popup-Fenster einzuführen. 
![grafik](https://cloud.githubusercontent.com/assets/22593821/22879246/5be02582-f1dd-11e6-81c3-2bb4ef0cd44b.png)

sks: m.E. auch Umsetzung einer ähnlichen Lösung möglich. Im Rahmen unserer Möglichkeiten.

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Freihandbestände - Meldung zum Abholort #496](https://trello.com/c/xc6UhzQS/323-freihandbestande-meldung-zum-abholort-496)

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [496](https://trello.com/c/YTrhkBRg/74-496)
