### ISSUE TITLE
Hint when NL terms of use have not been accepted

### ISSUE THREAD

**Issue by liowalter** [swissbib/vufind#498]
In the national licences registration, when user has a mobile phone number but hasn't accepted the terms of use, he cannot click on "Activate my temporary access". But he doesn't really know why. It would be good to add a mouseover there ("Please accept terms of use first").

![screenshot_089](https://cloud.githubusercontent.com/assets/1135460/23353125/29ee0604-fccb-11e6-95e4-75afc64cc519.png)

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Hint when NL terms of use have not been accepted #498](https://trello.com/c/mTRkh0dA/317-hint-when-nl-terms-of-use-have-not-been-accepted-498)

**Comment by liowalter** [comment]
release 2.5.3-core3.1.2
