### ISSUE TITLE
database updates vufind version 4

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#499]
Für version 4 werden Datenbankupdates notwendig werden.
Ein Hinweis ist dieser commit
module/VuFind/sql/migrations/pgsql/4.0/002-modify-user-columns.sql
(merge in core2swissbib_manually am 28.2.2017)

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [database updates vufind version 4 #499](https://trello.com/c/tjgpfx0i/322-database-updates-vufind-version-4-499)

**Comment by guenterh** [comment]
@edelm 
Hallo Matthias,
habe mir gestern mal die von Dir erstellte Testdatenbank (vforangetest) angesehen - und auch lokal installiert. Mir sind ein paar Dinge aufgefallen, die ich einfach mal hier hineinkopiere. Wir sollten darüber sprechen:
- wie diese Unterschiede entstanden sind?
- ich plädiere dafür, dass unsere Datenbank 1:1 der Grunddefinition von VuFind entspricht (https://github.com/vufind-org/vufind/blob/master/module/VuFind/sql/mysql.sql)
plus natürlich unsere eigenen Erweiterungen

* warum wird die neue Datenbank (v4orangetest) mit utf8mb4 erstellt (und nicht nur utf8 wie bisher)
CREATE DATABASE /*!32312 IF NOT EXISTS*/ `v4orangetest` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;

* vufind
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `external_session` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `session_id` varchar(128) NOT NULL,
  `external_session_id` varchar(255) NOT NULL,
  `created` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  PRIMARY KEY (`id`),
  UNIQUE KEY `session_id` (`session_id`),
  KEY `external_session_id` (`external_session_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_bin;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `tags`
—

* unsere Testdatenbank (auch hier wieder mb4 und andere Datentypen - warum)
DROP TABLE IF EXISTS `external_session`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `external_session` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `session_id` varchar(128) NOT NULL,
  `external_session_id` varchar(255) NOT NULL,
  `created` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`),
  UNIQUE KEY `session_id` (`session_id`),
  KEY `external_session_id` (`external_session_id`(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;

* müssen wir die autoincrement Werte nicht auf 0 setzen? (wir dumpen die Datenbank und importieren sie in die neue Struktur)
→ das Prozedere beim Wechsel auf version 3 (dump der Datenbank, neue Tabelle, ddl updates auf die bestehende Struktur)

* vufind (title und author felder sind bei VuFind länger)
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `resource` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `record_id` varchar(255) NOT NULL DEFAULT '',
  `title` varchar(255) NOT NULL DEFAULT '',
  `author` varchar(255) DEFAULT NULL,
  `year` mediumint(6) DEFAULT NULL,
  `source` varchar(50) NOT NULL DEFAULT 'Solr',
  PRIMARY KEY (`id`),
  KEY `record_id` (`record_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

* unsere Testdatenbank
CREATE TABLE `resource` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `record_id` varchar(255) NOT NULL DEFAULT '',
  `title` varchar(200) NOT NULL DEFAULT '',
  `author` varchar(200) DEFAULT NULL,
  `year` mediumint(6) DEFAULT NULL,
  `source` varchar(50) NOT NULL DEFAULT 'Solr',
  PRIMARY KEY (`id`),
  KEY `record_id` (`record_id`)
) ENGINE=InnoDB AUTO_INCREMENT=32150 DEFAULT CHARSET=utf8;

* vufind (wir haben noch ein expires Feld dass es bei VuFind nicht mehr gibt  warum bei VuFind weggefallen?)
CREATE TABLE `user_list` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `title` varchar(200) NOT NULL,
  `description` text,
  `created` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  `public` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `user_list_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

* unsere Testdatenbank
CREATE TABLE `user_list` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `title` varchar(200) NOT NULL,
  `description` text,
  `created` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `public` int(11) NOT NULL DEFAULT '0',
  `expires` datetime NOT NULL DEFAULT '2000-00-00 00:00:00',
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `user_list_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=8715 DEFAULT CHARSET=utf8;

* user_stats scheint es in VuFind gar nicht ehr zu geben??? warum?, wenn ja - können wir sie rausschmeissen
CREATE TABLE `user_stats` (
  `id` varchar(24) NOT NULL,
  `datestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `browser` varchar(32) NOT NULL,
  `browserVersion` varchar(8) NOT NULL,
  `ipaddress` varchar(15) NOT NULL,
  `referrer` varchar(512) NOT NULL,
  `url` varchar(512) NOT NULL,
  `session` varchar(64) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by edelm** [comment]
Das "utf8mb4" kommt wahrscheinlich vom Dump, unkorrekte Zeichensätze sind da ein oft auftauchendes Problem. Die unterschiedlichen Feldlängen habe ich angepasst. Die Tabellen "user_stats" und "user_stats_fields" waren für das (mittlerweile entfernte) interne Statistik-Tool. 

Das Feld "expires" in der Tabelle "user_list" kann ich nicht nachvollziehen. Es hat in unserer DB auch immer nur den Default-Wert.

Das Autoincrement würde ich belassen, da ein Dump/Import ja die bisher generierten IDs übernimmt.
