### ISSUE TITLE
Deduplizierung Links in Menü Vollanzeige

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#501]
Im Menü in der Vollanzeige werden Autoren und Themen hinterlegt mit Links zu einer Suche nach diesem Autor/Thema angezeigt. Auf Grund geringer Unterschiede in den Daten kann es vorkommen, dass die gleiche Person/Thema doppelt in den Daten vorhanden ist. 
In diesen Fällen wird die Person/Thema im Menü jetzt doppelt ohne sichtbaren Unterschied angezeigt.

Lösung: Texte vor der Anzeige prüfen und nur einfach ausgeben.

Beispiel: https://baselbern.swissbib.ch/Record/366659995

![themadoppelt](https://cloud.githubusercontent.com/assets/9479686/23546252/05e88ff4-ffff-11e6-840e-1a051cba3cae.png)

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Deduplizierung Links in Menü Vollanzeige #501](https://trello.com/c/uRB8cG6d/319-deduplizierung-links-in-menu-vollanzeige-501)
