### ISSUE TITLE
Add a library/location filter

### ISSUE THREAD

**Issue by gagarine** [swissbib/vufind#505]
You can filter by library network.
![screen shot 2017-04-11 at 16 56 29](https://cloud.githubusercontent.com/assets/164074/24915669/165bf09a-1ed8-11e7-9c3e-0fe29c31a8eb.png)
But sometimes you want to limit your search to a specific library. Specially if you are physically at this library.

**Comment by sonjakupfi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add a library/location filter #505](https://trello.com/c/TGI0K6Fq/325-add-a-library-location-filter-505)

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [505](https://trello.com/c/ghBjAdXw/77-505)

**Comment by liowalter** [comment]
This is now possible with the latest release : https://github.com/swissbib/vufind/releases/tag/5.1.1-core5.0.1
