### ISSUE TITLE
Change swissbib for a better name

### ISSUE THREAD

**Issue by gagarine** [swissbib/vufind#506]
swissbib is not a good name.  For the domain, the prefix "swiss" is useless because there is already the "ch" in the name and you can tell google this is a "swiss" (geographically) website.

Also "swiss" is in English and "bib" (for biblio, bibliothèque ...) is in French/German. It's not logic at all and hard to remember. Out of context "bib" doesn't  mean anything. Therefore, **swissbib is not understandable by himself**. There is a logic, but it's a broken logic.

For example, library.ch or library.swiss would be way better and easier to remember and works with the description: "Swissbib is the catalogue of all **Swiss** university **libraries**, the Swiss national library, several cantonal libraries and of other institutions."

Naming things is important.

**Comment by witzigs** [comment]
swissbib has been live with this name since 2010. By now it's a known name which we wont change out of the blue.

**Comment by gagarine** [comment]
> swissbib has been live with this name since 2010.
Yet it's still not known enough... even at the university library they don't know about it and only redirect you to RERO. The name is certainly part of the problem. But I agree, this need to be taught a bit.

**Comment by gagarine** [comment]
This is a swiss bib :

![Uploading swiss_flag_baby_bib-r7e4a5de983e84fdcb5aca04650eeeed0_zfe0o_324.jpeg…]()

**Comment by gagarine** [comment]
This is a "swiss bib":

![swiss_flag_baby_bib-r7e4a5de983e84fdcb5aca04650eeeed0_zfe0o_324](https://cloud.githubusercontent.com/assets/164074/25254792/b4db4918-2627-11e7-9a67-c54839004763.jpeg)

**Comment by ToVie** [comment]
Hey, in the end this is the only BIB that provides you with media you were looking for!
These coined words are not made to have an accurate English meaning. SWISSBIB works for Italian, French and German and Rumantsch additionally in Spanish and Portuguese - so it works for approx. 90% of the Swiss population...

**Comment by gagarine** [comment]
I speak English, French and a bit of German and Spanish... yet I didn't get it first. I asked around 10 peoples what they think "swissbib" was (out of context): almost nobody guesses it right yet. Wikipedia FR agrees: ![screen shot 2017-04-21 at 18 03 50](https://cloud.githubusercontent.com/assets/164074/25286129/ed2e834e-26bc-11e7-993a-5c9767418ec6.png)

But in DE it seems to be a more common abbreviation: https://de.wikipedia.org/wiki/BIB

It works when you know, not before. If you know what it is you think, "aaaah bib for bibliothèque!" and then "but why they choose to mix "swiss" in English and bib in french?".

I saw administration doing incredible effort not to use English and find names that "works" in the national language... yet everybody understands "library". I guess it's political and/or nationalist.

But as we don't agree, evidence is needed and I don't have time, neither the interest, to do a scientific research on that ;).
