### ISSUE TITLE
Bug when adding search engine to "one-click search engine" on Firefox

### ISSUE THREAD

**Issue by gagarine** [swissbib/vufind#508]
After adding the search engine on Firefox. Firefox steel propose to add it... On top of that, the icon is not the right one.

![screen shot 2017-04-17 at 13 57 14](https://cloud.githubusercontent.com/assets/164074/25088367/13da60de-2376-11e7-84fd-6e40070bbbc6.png)

**Comment by guenterh** [comment]
@edelm 
https://developer.mozilla.org/de/docs/OpenSearch_Plugin_f%C3%BCr_Firefox_erstellen
view-source:https://www.swissbib.ch/Search/OpenSearch?method=describe

**Comment by gagarine** [comment]
It's a duplicate? I'm not sure. This issue is about the auto detection and the installation of the search plugin that doesn't seem to work where #431 seem to be about the search plugin himself.

Perhaps is just I don't 100% understand the german on the other bug and that I can't access the trello card.

**Comment by gagarine** [comment]
Installing the test version from http://www.ub.unibas.ch/ibb/swissbib-searchplugin-test.html is working but swissbib is still proposing me to add the search engine on every page (the plus sign):

![screen shot 2017-04-25 at 16 29 28](https://cloud.githubusercontent.com/assets/164074/25390697/92d74136-29d4-11e7-94e4-922d0e423e15.png)
