### ISSUE TITLE
NOT-Filter - 2.Tab

### ISSUE THREAD

**Issue by sonjakupfi** [swissbib/vufind#512]
Der Ausschluss einzelner Facetten im 2. Tab funktioniert nicht.
Gemäss Anzeige und auch URL sollten die Facetten ausgeschlossen werden.
Gemäss Trefferliste funktioniert es aber nicht.
Die Trefferliste nach Ausschluss einer Facette beinhaltet genau die Menge an Treffern, die in der Facette angezeigt wird.

Einfache Suche: https://baselbern.swissbib.ch/Summon/Search?lookfor=recht&type=AllFields&limit=40
Ausschluss Themen-Facette https://baselbern.swissbib.ch/Summon/Search?lookfor=recht&type=AllFields&limit=40&filter%5B%5D=-SubjectTerms%3A%22medicine+%26+public+health%22

Im Hintergrund wird bei der Suchabfrage ein Parameter mit wiedersprüchlichen Informationen (Ausschluss / Einschliessen) gesetzt.

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 512](https://trello.com/c/W2wUA2xE/14-issue-512)

**Comment by witzigs** [comment]
Siehe auch Doku Summon Search API: https://developers.exlibrisgroup.com/summon/apis/SearchAPI

**Comment by guenterh** [comment]
@edelm hat's gelöst!!
