### ISSUE TITLE
eod-Bestellung: Hyperlink "Vorschau zum Bild und Bestellfunktion"

### ISSUE THREAD

**Issue by FlorinneEgli** [swissbib/vufind#513]
Link "Vorschau zum Bild und Bestellfunktion" lässt sich in ie, Chrome und FF nicht korrekt öffnen:
![1](https://user-images.githubusercontent.com/17006552/26965047-6e130af4-4cf4-11e7-93fe-05aaef15e7a5.jpg)

Bsp: https://baselbern.swissbib.ch/Record/364656735 oder https://baselbern.swissbib.ch/Record/364657928

Klick auf Link führt zu dieser Anzeige:
![2](https://user-images.githubusercontent.com/17006552/26965101-9e4b1568-4cf4-11e7-9f2c-718f8a800278.jpg)

Bestätigung führt zu dieser Anzeige oben links im Browser-Fenster:
![3](https://user-images.githubusercontent.com/17006552/26965107-a3872f6c-4cf4-11e7-8778-b5258df0e027.jpg)

**Comment by sonjakupfi** [comment]
Vorschau zum Bild:
idsbb001015948 - führt zu oben erwähntem Verhalten
idsbb005272711 - führt zu oben erwähntem Verhalten
idsbb005278762 - führt zu oben erwähntem Verhalten
idsbb000965034 - führt zu oben erwähntem Verhalten
idsbb004476115 - führt zu einem "Bad Request" (http / https)

**Juni2017: "Vorschau zum Bild" und "Vorschau zum Bild und Bestellfunktion" werden zur Zeit unterdrückt und somit nicht angezeigt, da die Verlinkung nicht zu einem erwünschten Resultat führt.**

idsbb004951419 - Portraits werden bereits unterdrückt
idsbb003493507 - Inhaltsverzeichnisse werden angezeigt und Links korrekt dargestellt

**Comment by witzigs** [comment]
Problem liegt bei Aleph: Die URL wird nicht korrekt expandiert. Ein case bei ExLibris ist eröffnet.

**Comment by witzigs** [comment]
Das Problem auf Aleph-Seite konnte gelöst werden, Links werden nun wieder verwendbar nach swissbib geliefert. Daher wurde die Unterdrückung der Links aufgehoben.
