### ISSUE TITLE
Start VF4 Migration

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#516]
# was mir aufgefallen ist und noch gemacht werden sollte

- classmap generator code wegnehmen
(neu wir hierfpr in ZF3 composer verwendet, s. auch https://docs.zendframework.com/tutorials/migration/to-v3/application/#scripts)
- verschiebe weitere Controller Invokables in Factories → Schritt für Schritt und Testen
- in einigen controllern wird noch die getServiceLocator Methode benutzt (funktionoert noch, erzeugt aber deprecated Warnung und wird in ZF3 wegfallen - ein gesehenes Beispiel HoldingsController

 
# Fragen
- warum ist diese Factory in unserer module.config.php??
'cart'   => 'VuFind\Controller\Factory::getCartController',
wenn schon dann muss swissbib namespace verwendet werden

- wir haben noch zwei invokable services im swissbib ServiceManager
		'invokables' => [
			'Swissbib\QRCode'                               => 'Swissbib\CRCode\QrCodeService',
			'MarcFormatter'                                 => 'Swissbib\XSLT\MARCFormatter',
		],
- ebenso invokable ViewHelpers im swissbib Modul → Umwandlung nach Factories?

- im Cover Typ verwendet VuFind nun direkt die property serviceLocator anstelle getServiceLocator der ZF Abstract class. https://github.com/swissbib/vufind/blob/fix/core2swissbib_manually/module/Swissbib/src/Swissbib/Controller/CoverController.php#L50 Im swissbib Modul nachgebaut damit die von ZF geworfene deprecated Warung nicht mehr erscheint. Ich denke hier wird sich etwas ändern. Variante wäre, bereits jetzt die benötigten dependencies durch eine Factory zu setzen. Dann ist man aber weniger kompatibel zum VF Code und die Loader Klasse verwendet den ServiceLocator immer noch. Dies ist nicht im Sinne des Erfinders. Sollte ebenfalls über Factory gelöst werden. Abwarten was VF macht? @edelm : was denkst Du?

# Probleme
- mit https://github.com/swissbib/vufind/commit/65ea0be78bff622c32baf49a450ed536b55d4daf musste ich einen Hack einführen, damit wir überhaupt noch die Autorensuche absetzen können (VF4)
Hintergründe:
--> wir haben uns vor einieger Zeit mal dazu entschieden, die Autorensuchen wie normale Suchen ablaufen zu lassen
--> Gründe wie ich sie im Kopf habe: 
wir benutzen keinen speziellen Autorenindex wie VuFind
die Wikidata - Abfragen, so wie sie VuFind für die Autoren macht, waren in unserem KOntext nicht kompatibel oder nicht gut genug (ich weiss es auch nicht mehr)
Jetzt haben wir aber u.a. das Problem, dass VuFind für die unterschiedlichen Suchtypen ein ziemlich ausgeklügeltes Recommendation System aufgebaut hat. Das ist nun zum Teil nicht mehr kompatibel mit der Art und Weise, wie wir Dinge angehen bzw, es entstehen ganz einfach Fehler
Actions
(Matthias und Günter): Ich wollte immer schon das VuFind Recommendation System besser verstehen, bin aber nie dazu gekommen, mir das besser anzusehen. Ein besseres Verständnis würde uns erheblich helfen, unseren Code wieder kompatibler zu strukturieren bzw. wir wären wohl auch in der Lage, neue Features einzuführen
(alle) wieder mal darüber sprechen, wie wir die Dinge gestalten könnten / sollten
@edelm @witzigs zur Info 
- was machen wir mit diesem Controllertypen
            //todo: I can't find console in the VuFind-module
            //what is the swissbib purpose of this Type??
            'console'              => 'Swissbib\Controller\ConsoleController',
ist in unserem Modul als invokable deklariert
- Verwendung der folgenden Controller bisher nicht getestet, einfach umgehängt
            'upgrade'   => 'Swissbib\Controller\Factory::getNoProductiveSupportController',
            'install'   => 'Swissbib\Controller\Factory::getNoProductiveSupportController',

- ebenso die folgende Neudefinition als Factory nicht getestet
            //nicht getestet
            'tab40import'   => 'Swissbib\Controller\Factory::getTab40ImportController',
            'institutionFavorites' => 'Swissbib\Controller\Factory::getFavoritesController',
            'hierarchycache'       => 'Swissbib\Controller\Factory::getHierarchyCacheController',
- auch nicht getestet
            //nicht getestet
            'helppage'    => 'Swissbib\Controller\Factory::HelpPageController',
            'libadminsync' => 'Swissbib\Controller\Factory::LibadminSyncController',
            'my-research'   => 'Swissbib\Controller\Factory::MyResearchController',

**Comment by guenterh** [comment]
# Layout-Dinge
- Variable $this->left    https://github.com/swissbib/vufind/blob/fix/core2swissbib_manually/module/Swissbib/src/Swissbib/View/Helper/LayoutClass.php#L55
gibt es nicht mehr. Damit funktioniert auch die Fallunterscheidung nicht mehr (mit Meldungen im Log)    @edelm Welche Auswirkungen hat dies auf Layout?

**Comment by guenterh** [comment]
# Deployment
- das composer json von VF4 verteilt Solr. 
https://github.com/swissbib/vufind/blob/fix/core2swissbib_manually/composer.json#L76
Dies ist ziemlich mühsam
Eine Möglichkeit dies auszuschalten wäre, dem Verteilscript diese Datei vorzugaukeln.
https://github.com/swissbib/vufind/blob/fix/core2swissbib_manually/build.xml#L148
@edelm : andere Ideen?

**Comment by guenterh** [comment]
# aktuelle Fehler
- für Basel/bern ist nun unter der domain feature.swissbib.ch der Merge mit VF4 verteilt
- ich bekomme dort einen Fehler beim Aufruf des Tabs Artikel, den ich lokal nicht erhalte (kann das mit einer fehlerhaften Konfiguration zu tun haben? @edelm zur Info, kannst Du das mal ansehen?
- die zum Testen zur Verfügung stehenden Views sind nun:
c2sbm.swissbib.ch
feature.swissbib.ch
jusdev.swissbib.ch

**Comment by liowalter** [comment]
@edelm : can you close this issue if relevant ?
