### ISSUE TITLE
Merklisten: privat oder öffentlich macht keinen Unterschied

### ISSUE THREAD

**Issue by FlorinneEgli** [swissbib/vufind#519]
Bei Tests (anlegen, versenden) sehe ich keinen Unterschied zwischen privaten und öffentlichen Merklisten. Diese Funktionalität müsste meiner Meinung nach nicht unbedingt ausgebaut werden, sie könnte aber entfernt werden, damit keine Optionen bestehen, wo man gar keine hat.

**Comment by witzigs** [comment]
Stimmt so nicht: Bei öffentlichen Merklisten kann der Link zur Merkliste an eine andere Person weitergegeben werden, diese kann die Liste dann einsehen aber nicht bearbeiten. Eine private Merkliste kann nur vom anlegenden Benutzer eingesehen werden.
