### ISSUE TITLE
Übersetzung Standortcodes aus location-idsbb funktioniert nicht

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#524]
Im Moment werden keine Standortcodes aus location-idsbb/*.ini übersetzt. 
Der Aufruf unter https://github.com/swissbib/vufind/blob/master/module/Swissbib/src/Swissbib/RecordDriver/Helper/Holdings.php#L873 gibt den Code und nicht die Übersetzung zurück.

Dies hat zur Folge, dass bei Holdings kein Standort angezeigt wird. Zum Beispiel: https://baselbern.swissbib.ch/Record/488402816
https://baselbern.swissbib.ch/Record/11878692X

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [524](https://trello.com/c/p3GIbFOG/89-524)

**Comment by witzigs** [comment]
mit release 5.5.0 erledigt
