### ISSUE TITLE
icons in search list (smart phone version, vf4 based) are cut-off

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#526]
@witzigs @liowalter @edelm 
icons (list, items, other editions) are cut-off in the smart phone version
Matthias and I discussed this yesterday shortly.
For me it's not a blocker to deploy the branch just at the beginning of the upcoming year. 
But we should discuss it in our group how to deal with it. As far as I noticed it there are additional shortcomings related to design in the new version

**Comment by witzigs** [comment]
tritt nicht mehr auf
