### ISSUE TITLE
type error in FlatArrayConverter

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#528]
@witzigs @liowalter @edelm 

I just deployed the https://github.com/swissbib/vufind/commit/619c32043cf36711f058eb540436886314786870 commit on devlinked.swissbib.ch
(thanks for your work @outermedia-cbo and @ema-om !)

I get an error and whoops tells me that FlatArrayConverter is getting Null for the Config-Type.
Could it be I'm missing the correct configs in 

VUFIND_LOCAL_DIR | /usr/local/vufind/linked/local/linked/develop   ?

**Comment by ema-om** [comment]
The FlatArrayConverter is a newly introduced utility component to handle the configuration for the drop-down list sections of the auto-suggest feature. I've added a new section to the `searches.ini` called `AutoSuggest`, but this has been added only to `local/classic/c2sbmanually/config/vufind/searches.ini` now. Presumably the same section has to be added to some or all of the other `searches.ini` files, too. Can someone tell me which of these ini-files have to be extended by the `AutoSuggest` section? Then I can do that.

However it might make sense to have some default configuration for that to never run into that null-pointer issue again. What do you think and where to add this default configuration in case it makes sense to you?

**Comment by guenterh** [comment]
We discussed it shortly this morning with @outermedia-cbo Because we are using the newly introduced 
local/linked/develop configuration directory the new section could be part of this searches.ini configuration.

searches.ini in this directory derives from 
path        = local/config/vufind/searches.ini

My proposal: because we want to use the linked/integration extensions in all the swissbib views it makes sense to put the new section into the parent searches.ini . Going this way it's part of all the various configurations

**Comment by guenterh** [comment]
I was able to deploy the configuration and the autosuggest functionality is now active :+1: 

compare http://devlinked.swissbib.ch/

By now the Elasticsearch-module is still de-activated because of  https://github.com/swissbib/vufind/issues/529

@witzigs fyi
