### ISSUE TITLE
missing configs for ElasticSearch module

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#529]
@outermedia-cbo As discussed this morning I added the missing 

module directive into the Apache config
       SetEnv VUFIND_LOCAL_MODULES Swissbib,ElasticSearch,Libadmin

Now I'm getting the Exception
e 21
[Wed Dec 13 10:39:48.168234 2017] [:error] [pid 25933] [client 131.152.212.156:54946] PHP Fatal error:  Uncaught Zend\\ModuleManager\\Listener\\Exception\\InvalidArgumentException: Config being merged must be an array, implement the Traversable interface, or be an instance of Zend\\Config\\Config. boolean given. in /usr/local/vufind/linked/vendor/zendframework/zend-modulemanager/src/Listener/ConfigListener.php:332\nStack trace:\n#0 /usr/local/vufind/linked/vendor/zendframework/zend-modulemanager/src/Listener/ConfigListener.php(125): Zend\\ModuleManager\\Listener\\ConfigListener->addConfig('ElasticSearch', false)\n#1 /usr/local/vufind/linked/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\\ModuleManager\\Listener\\ConfigListener->onLoadModule(Object(Zend\\ModuleManager\\ModuleEvent))\n#2 /usr/local/vufind/linked/vendor/zendframework/zend-eventmanager/src/EventManager.php(171): Zend\\EventManager\\EventManager->triggerListeners(Object(Zend\\ModuleManager\\ModuleEvent))\n#3 /usr/local/vufind/linked/vendor/zendframework/zend-modulemanager/src/ModuleManager.php(181): Zend\\EventManager\\EventManager->triggerEvent(Obje in /usr/local/vufind/linked/vendor/zendframework/zend-modulemanager/src/Listener/ConfigListener.php on line 332

As the exception says the configs for the Ealasticsearch module are not part of our repository
https://github.com/swissbib/vufind/tree/integration/linked/module/ElasticSearch
https://github.com/swissbib/vufind/blob/integration/linked/module/ElasticSearch/Module.php#L33

could you checkin the configs?

**Comment by outermedia-cbo** [comment]
@guenterh:
