### ISSUE TITLE
Nationallizenzen Message "Nutzungbedingung akzeptieren"

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#541]
Wenn man im Konto auf den Punkt "Nationallizenzen" klickt und dann auf eine weitere Seite geht, wird eine Flash-Message "Bitte akzeptieren Sie die Nutzungsbedingungen" angezeigt. 
Diese Message macht keinen Sinn, sie sollte nur angezeigt werden, wenn sie bei der Registrierung für die Nationallizenzen Sinn macht.

**Comment by liowalter** [comment]
I cannot reproduce the bug. Was that on production ? With which user account ? Can you give more details ?
