### ISSUE TITLE
nicht korrekt angezeigte Zeichen

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#546]
https://www.swissbib.ch/Record/033096058
Was sind das für Zeichen die nicht korrekt angezeigt werden?

![zeichen](https://user-images.githubusercontent.com/1825990/34761539-859fe6bc-f5e4-11e7-8a5d-6b243c39332f.png)

**Comment by ema-om** [comment]
Das sieht für mir verdächtig nach einem Encoding-Problem aus. Vermutlich ist irgendwo zwischen der Quelle des Textes und der Anzeige im Browser eine Encoding falsch eingestellt und es findet eine Umwandlung statt, die zu dieser fehlerhaften Anzeige führt.

**Comment by witzigs** [comment]
Die Aufnahmen stammen aus dem IDSSG und sehen dort gleich aus. Problem ist gemeldet.
