### ISSUE TITLE
Give page title some love

### ISSUE THREAD

**Issue by gagarine** [swissbib/vufind#569]
The front page title is not descriptive:
![screen shot 2018-01-24 at 16 39 12](https://user-images.githubusercontent.com/164074/35341094-2386b446-0125-11e8-923b-b5a32e0146f2.png)

It  impact how it appear on search engine
![screen shot 2018-01-24 at 16 38 30](https://user-images.githubusercontent.com/164074/35341117-335e8e7a-0125-11e8-9f5a-08d2d88a5c83.png)

Or sharing the website with Whatsapp or other social netwroks
![screen shot 2018-01-24 at 16 40 05](https://user-images.githubusercontent.com/164074/35341138-404d864a-0125-11e8-956a-0a20f99e937f.png)

Their is also problem in item page title, specially with language:
Page title in EN
![screen shot 2018-01-24 at 16 42 51](https://user-images.githubusercontent.com/164074/35341301-a84972e0-0125-11e8-878b-0bc844d98e26.png)
But when shared DE??
![screen shot 2018-01-24 at 16 42 02](https://user-images.githubusercontent.com/164074/35341282-982d1ca4-0125-11e8-905a-12e7a0808c56.png)

Generally page title should be descriptive and have a clear schema. For example for item: type - title - author - date would be cool

**Comment by liowalter** [comment]
Absolutely ! That's the kind of important things that you don't see when you are working on it every day...

For the home page it happens here : 
https://github.com/swissbib/vufind/blob/master/themes/sbvfrdmulti/templates/search/home.phtml

This should be a quick fix.

For the item page, this is a bit more complicated. We need to think a bit about what we want.

It happens here : 
https://github.com/swissbib/vufind/blob/master/themes/sbvfrd/templates/RecordTab/holdingsils.phtml#L11
and here
https://github.com/swissbib/vufind/blob/master/local/languages/de.ini#L126

Thanks for the feedback, and if you want to do a pull request, feel free !
