### ISSUE TITLE
strange subjects show up (very long)

### ISSUE THREAD

**Issue by liowalter** [swissbib/vufind#609]
![screenshot_198](https://user-images.githubusercontent.com/1135460/37598851-a78c8d82-2b83-11e8-8a88-8efcf4950b88.png)
Search "Kaleidoscope" and look at auto-suggest.

After a quick look, it seems to come from Liechtenstein.

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [609](https://trello.com/c/1FaFsGM0/93-609)

**Comment by liowalter** [comment]
Feld 648 soll im Autosuggest unter Thema nicht berücksichtigt werden.
