### ISSUE TITLE
Problems with Autosuggest on mobile

### ISSUE THREAD

**Issue by liowalter** [swissbib/vufind#610]
I tried various browsers on my Android 7.0 phone (Samsung Galaxy) with different results.

**Chrome**
Everything is working

**Firefox 59.0.1**

Autosuggest doesn't work. As I type, no suggestions are showing up. It's only when I tap the search field that I see the suggestions.

**Firefox & Samsung Internet 6.4.10.5 (default browser) & Iphone Safari**
When I scroll my screen to see the lower suggestions, the autosuggest box disappear. Therefore I cannot choose any suggestions.

**Comment by liowalter** [comment]
As a hint, the autosuggest on http://linked.swissbib.ch/ works fine on my Android Firefox.

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [610](https://trello.com/c/27RlfzUj/94-610)

**Comment by liowalter** [comment]
I still have the same problem

**Comment by edelm** [comment]
With vufind core it works

**Comment by liowalter** [comment]
Maybe related to blur event...

**Comment by liowalter** [comment]
there is a new version from vufind autocomplete js https://github.com/vufind-org/autocomplete.js/releases

**Comment by liowalter** [comment]
fixed with https://github.com/swissbib/vufind/commit/a66cece810a423eec62d1a818b391248922c3c7b and https://github.com/swissbib/vufind/commit/8e5157d2fdfe202726f578a69513fc209a7e2ca5

But it implied a change in autocomplete.js. Let's see if we wait the new autocomplete.js or make a copy for our own usage.
