### ISSUE TITLE
Page titles are missing

### ISSUE THREAD

**Issue by liowalter** [swissbib/vufind#611]
For person and subject pages, it would be better to have a page title.

http://devlinked.swissbib.ch/Page/Detail/Person/48710cd0-66d6-36f6-ad3c-dc51bdbd3875#

I would suggest (based on https://www.swissbib.ch/Record/368707636) : 
swissbib : Jane Austen (Person)

http://devlinked.swissbib.ch/Page/Detail/Subject/4073091-8
swissbib : Judenvernichtung (Subject)

**Comment by witzigs** [comment]
erledigt mit fff15e8b8b61cf3354a7aa494059a9bd91d051b8

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [399](https://trello.com/c/gmqwQ0hI/134-399)
