### ISSUE TITLE
Autosuggest without subheadings

### ISSUE THREAD

**Issue by liowalter** [swissbib/vufind#612]
In some cases, the subheadings (titles/authors/subjects) in autosuggest disappear. 

For example, if you type algeb, you have the screenshot below (on firefox). With one letter less or one more you have the three options (titles/authors/subjects).

![screenshot_199](https://user-images.githubusercontent.com/1135460/37607623-d0397bcc-2b98-11e8-897f-cc6391145048.png)

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [522](https://trello.com/c/H4SHCb1I/88-522)

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [612](https://trello.com/c/hIvgha7v/95-612)

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [279](https://trello.com/c/JOvxksGx/162-279)

**Comment by liowalter** [comment]
It was a result of the default vufind autosuggestions appearing when the outermedia autosuggest yields no results. I close it but see issue https://github.com/swissbib/vufind/issues/694 for the follow-up
