### ISSUE TITLE
deprecated Meldungen / unterdrückte Logmeldungen 

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#623]
In der VF5 Version werden deprecated Meldungen geworfen

![deprecatedmedlungen](https://user-images.githubusercontent.com/1825990/42315535-fdef5984-8047-11e8-9e39-768a1b0a4549.gif)

Schaltet man das logging ein, sieht man das Fehlermeldungen nicht geworfen werden weil dies in den PHP Einstellungen unterdrückt ist (Beispiel war im Bereich cover, habe es jetzt nicht mehr zur Hand)

**Comment by liowalter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[vufind] deprecated Meldungen / unterdrückte Logmeldungen](https://trello.com/c/MNLpzae8/215-vufind-deprecated-meldungen-unterdr%C3%BCckte-logmeldungen)
