### ISSUE TITLE
VF5 - missing hierarchy record driver

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#624]
see attachement
![missing_hirarchy_record_driver](https://user-images.githubusercontent.com/1825990/42372329-42781940-8112-11e8-9514-e39c4b1ff37c.png)

**Comment by edelm** [comment]
fixed with 2fbf7fe8d657f16044eca98b16122a7fe2123323 and 4cf947b25604da9605505b2e744186d1d138d2b5
