### ISSUE TITLE
Refactoring Backendregistry (MLT)

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#625]
Die MLT Funktionalität funktioniert mit Solr 7 nicht mehr.
Grund: für den Cloudmodus muss ein spzieller parser verwendet und mit entsprechender Syntax angesprochen werden.
VuFind unterstützt dies im core, durch unsere Überschreibungen des SOLR Backends (und dessen Refactoringin VF5) ist diese Fubktionalität für uns im Moment nicht mehr nutzbar.

Vergleiche auch
https://sourceforge.net/p/vufind/mailman/vufind-tech/?viewmonth=201807
https://sourceforge.net/p/vufind/mailman/message/36365318/
https://sourceforge.net/p/vufind/mailman/message/36365307/

Beispiel für eine Syntax mit eingebundenem MLT Parser:
https://solrgreendev.swissbib.ch/solr/green/select?q={!mlt%20fl=title,title_short,author,topic,publishDate,classif_rvk,classif_udc,classif_ddc%20qf=title,title_short%20%20%20mintf=1%20mindf=1}508192447

**Comment by guenterh** [comment]
notwendige Konfiguration in searches.ini (neu - als Vorschlag, weitere Möglichkeiten noch evaluieren)


[MoreLikeThis]
; Boolean value indicating whether the newer MoreLikeThis query handler should be
; used instead of the traditional MoreLikeThis component (default). Only the
; MoreLikeThis query handler supports sharded indexes, but as of this writing, the
; traditional component offers more nuanced relevance ranking. Results from these
; methods may differ.
useMoreLikeThisHandler = true
; If the MoreLikeThis handler is used, this setting can be used to adjust its
; behavior. See https://cwiki.apache.org/confluence/display/solr/Other+Parsers#OtherParsers-MoreLikeThisQueryParser
; for more information regarding the possible parameters.
;params = "qf=title,title_short,callnumber-label,topic,language,author,publishDate mintf=1 mindf=1";
; This setting can be used to limit the maximum number of suggestions. Default is 5.
;count = 5
params = "fl=title,title_short,author,topic,publishDate,classif_rvk,classif_udc,classif_ddc qf=title,title_short mintf=1 mindf=1";

**Comment by liowalter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[vufind] Refactoring Backendregistry (MLT)](https://trello.com/c/i0yRmS4k/221-vufind-refactoring-backendregistry-mlt)

**Comment by guenterh** [comment]
@liowalter @edelm 
Hallo zusammen,
das Problem war die falsche Indexdefinition in der config.ini. Eingestellt gewesen war sb-us6 (der alte BB Index), für SOLR7 was wir ja testen wollen ... gilt ausschliesslich diese Konfiguration (innerhalb der DMZ)
```text
für Basel/Bern
[Index]
engine                 = Solr
;for national licenses
url                    = http://sb-up2.swissbib.unibas.ch/solr
maxBooleanClauses      = 1024
default_core           = bb
timeout                = 30
;default_dismax_handler = edismax

für swissbib green
[Index]
engine                 = Solr
;for national licenses
url                    = http://sb-up1.swissbib.unibas.ch/solr
maxBooleanClauses      = 1024
default_core           = green
timeout                = 30
;default_dismax_handler = edismax

```

Bitte alle Konfigurationen, die wir für den Umstieg auf SOLR7 / VF5 benötigen, entsprechend anpassen, Danke!

Ich werde in den nächsten Tagen versuchen, die Diagramme, auf denen unsere Infrastruktur abgebildet ist, auf den letzten Stand zu stellen. Allerdings ist die dedizierte Übersicht für die neue Suchmaschinenumgebung bereits aktuell
