### ISSUE TITLE
Anpassung der Datenbank für VF5 / Aufräumen der alten Datenbanken auf den hosts

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#626]
* Unsere eigene Datenbankstruktur muss entsprechend der Weiterenentwicklung vom VF core angepasst werden
* spätestens bevor wir live gehen müssen die alten nicht mehr benutzten Datenbanken von den servern entfernt werden
* Achtung: die Backupscripte müssen beim Anpassen / Aufräumen angepasst werden

**Comment by edelm** [comment]
Ich habe mal auf sb-udb1 und sb-udb2 alle VuFind DBs ausser v4* und v5* gedropped. In der config zum python-maintenance-script stehen im Moment auch nur alle aktuellen (v4*) DBs.

**Comment by liowalter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[vufind] Anpassung der Datenbank für VF5 / Aufräumen der alten Datenbanken auf den hosts](https://trello.com/c/RU6WjseW/223-vufind-anpassung-der-datenbank-f%C3%BCr-vf5-aufr%C3%A4umen-der-alten-datenbanken-auf-den-hosts)
