### ISSUE TITLE
Umstellung aller services und links innerhalb der services auf https

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#627]
Chrome und bald auch Firefox erzwingen bald/jetzt schon  die Umstellung aller Webressourcen auf https. Nicht https Seiten werden als nicht sicher gekennzeichnet.
Dies gilt auch für Seiten mit "gemischtem Content"

Es kann auch passieren das Seiten mit nicht https Inhalt geblockt wird (z.B. bei iFrames jetzt schon mit Chrome)

Die Uni hat beschlossen, webservices, die nicht auf https laufen ab 1.11. ohne Rücksprache abzustellen.

Ich habe mit Stefan darüber Mitte Juli bereits gesprochen, für services wie sru.swissbib.ch oder data.swissbib.ch, die reine Datenservices sind, könnten wir diese evtl. noch nach dem 1.11.2018 auf http betreiben.

Wir haben jedoch ein Problem bei der Integration unserer linked Artefakte. Zum Beispiel: https://www.swissbib.ch/Page/Detail/Person/48710cd0-66d6-36f6-ad3c-dc51bdbd3875 

Hier haben wir gemischten content, der von DBPedia kommt. Bei Viaf habe ich das noch nicht gesehen.

Vor allem die Bilder werden als http Ressourcen gerendert (swissbib.imageSequence.register($('*[data-person-thumbnail-id="48710cd0-66d6-36f6-ad3c-dc51bdbd3875"]'), ["http:\/\/commons.wikimedia.org\/wiki\/Special:FilePath\/CassandraAusten-JaneAusten(c.1810)_hires.jpg?width=300","http:\/\/commons.wikimedia.org\/wiki\/Special:FilePath\/Jane_Austen,_from_A_Memoir_of_Jane_Austen_(1870).jpg?width=300","http:\/\/commons.wikimedia.org\/wiki\/Special:FilePath\/Jane_Austen_by_Cassandra_Austen,_gro\u00df.jpg?width=300","http:\/\/commons.wikimedia.org\/wiki\/Special:FilePath\/Jane_Austen_coloured_version.jpg?width=300","\/Cover\/Show?0=http%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FSpecial%3AFilePath%2FCassandraAusten-JaneAusten%28c.1810%29_hires.jpg%3Fwidth%3D300&1=http%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FSpecial%3AFilePath%2FJane_Austen%2C_from_A_Memoir_of_Jane_Austen_%281870%29.jpg%3Fwidth%3D300&2=http%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FSpecial%3AFilePath%2FJane_Austen_by_Cassandra_Austen%2C_gro%C3%9F.jpg%3Fwidth%3D300&3=http%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FSpecial%3AFilePath%2FJane_Austen_coloured_version.jpg%3Fwidth%3D300"]).process();)
Andere Ressourcen können aber auch noch zur Warnung "gemischter content" beitragen.

Im ES Index sieht das so aus: http://localhost:8080/lsb/person/48710cd0-66d6-36f6-ad3c-dc51bdbd3875

@sschuepbach Können, wir mal gemeinsam darüber nachdenken, ob wir alle http links im linked workflow auf https umsetzen können (macht das Sinn) oder sollten wir die links auf Präsentationsebene besser umsetzen? DBPedia bietet den Zugriff per https an, lenkt aber auf http um (curl -L 'https://dbpedia.org/page/Jane_Austen')

@edelm : Im Moment haben wir noch links die wir ganz sicher auf https umstellen können. Zum Beispiel der nach swissuniversities (http://www.swissuniversities.ch/isci) Gibt es noch weitere? Piwik? Spätestens mit dem Umstieg nach VF5 sollten wir das umstellen

**Comment by sschuepbach** [comment]
@guenterh, die Umstellung auf `https`-Links im linked-Workflow ist vermutlich am einfachsten direkt in der _"enrichedLine"_ zu implementieren. Wir verwenden hier bereits Morph-Definitionen für _[persons](https://github.com/linked-swissbib/mfWorkflows/blob/master/src/main/resources/transformation/indexWorkflows/enrichedPersonMorph.xml)_ und _[organisations](https://github.com/linked-swissbib/mfWorkflows/blob/master/src/main/resources/transformation/indexWorkflows/enrichedOrganisationMorph.xml)_, somit könnten diese mittels der Morph-Funktion [`replace`](https://github.com/metafacture/metafacture-core/wiki/Metamorph-functions#replace) ergänzt werden.

ToDo:
- [ ] Welche DBPedia-Felder enthalten `http`-Links, welche ersetzt werden müssen?
- [ ] Regeln in Dateien `enrichedPersonMorph.xml` und `enrichedOrganisationMorph.xml` implementieren

**Comment by liowalter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[vufind] Umstellung aller services und links innerhalb der services auf https](https://trello.com/c/lraSRUOZ/227-vufind-umstellung-aller-services-und-links-innerhalb-der-services-auf-https)

**Comment by liowalter** [comment]
Solved with https://github.com/linked-swissbib/mfWorkflows/commit/764583acb67313ab83a6887bf4acff0825fcbf29
