### ISSUE TITLE
Übernahme external-Info in VuFind (aus sbvf2)

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#63]
## Info
Mit Release sbvf2/v22 (https://github.com/swissbib/sbvf2/releases/tag/v22) wird im Tab "Artikel & mehr" ein Infotext eingeblendet, wenn Clients von ausserhalb der IP-Ranges der Universitäten Basel und Bern darauf zugreifen, bereits sichtbar auf http://testbaselbern.swissbib.ch. Dazu wird eine Variable $external = true|false dem Viewmodel mitgegeben. Falls true, wird der Text im entsprechenden Template eingeblendet. Die Umsetzung siehe in diesem Commit: https://github.com/swissbib/sbvf2/commit/900745ed8e62a2dcc1962fe2bb831b51400eb808)

## Ziel
Diese Funktionalität muss auch im neuen Repository und Themes zur Verfügung stehen, wobei die Umsetzung im Model im Vordergrund steht. Die saubere Umsetzung in der View erfolgt später

## Vorarbeiten
Methode isRestrictedTarget() und Aufruf übertragen: 4af94317

## Problem
Unklar, ob die Methode hier am richtigen Ort ist und wie der Aufruf aussehen muss. Die Umsetzung im Template erfolgt später durch mich selber.

**Comment by oschihin** [comment]
@chantalw 
Bitte Funktionalität testen:
* erscheint der Text ausserhalb der Unis
* wird in den Unis der jeweils richtige Content angezeigt, ohne Hinweistext

falls ja, hier bitte schliessen. Für das Design des Hinweises siehe dann #185

**Comment by witzigs** [comment]
Funktionalität ist in Ordnung: Unterschiedliche Trefferlisten in BS und BE, von ausserhalb des Uninetz erscheint der Hinweistext
