### ISSUE TITLE
backlink wissensportal / rechercheportal gebrochen

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#632]
ich nehme an, nach dem update auf eine neue Primo version geht der backlink zu ETH und zb auf die allgemeine nebis view und nicht mehr zu 
wissenspoartal
rechercheportal

Beispiel
https://www.swissbib.ch/Record/173556930
@witzigs @liowalter fyi

**Comment by witzigs** [comment]
@guenterh 
Das ist kein bug, alles funktioniert wie es sollte. Wir setzen pro Verbund einen Backlink, daher gehen alle Backlinks für NEBIS-Bibliotheken aufs NEBIS Primo.
