### ISSUE TITLE
VuFind5 : missing author box on the right

### ISSUE THREAD

**Issue by liowalter** [swissbib/vufind#633]
![screenshot_266](https://user-images.githubusercontent.com/1135460/45304041-782eac00-b517-11e8-8cba-b22379d4623f.png)

Compare with https://www.swissbib.ch/Record/277676746/Details#tabnav

**Comment by liowalter** [comment]
No connection to Elastic server

**Comment by edelm** [comment]
fixed by 
fa6101277a0c7945a6d0091f9b786e58e8d849c4
fc2f4aa52c295ff5f0fc8eb9643785135e65dfbe
1799418b695b34889f91c1035b32443e1d73c250
