### ISSUE TITLE
Die Darstellung der Format-Facetten ist noch nicht ganz korrekt.

### ISSUE THREAD

**Issue by liowalter** [swissbib/vufind#634]
![screenshot_268](https://user-images.githubusercontent.com/1135460/45621894-68b4e300-ba82-11e8-9ace-a2e681fd5a8a.png)

**Comment by witzigs** [comment]
Reopening, as facets with too long labels screw up the display. 

![screenshot_2018-10-19 swissbib resultats de la recherche](https://user-images.githubusercontent.com/9479686/47208028-102c7a80-d38d-11e8-8bcc-7d0abab066f8.png)

Currently too long labels are shortened with "...". Ideally we'd have a proper line break.

**Comment by liowalter** [comment]
Current fix : https://github.com/swissbib/vufind/commit/51bf98f54a2045dc846ca8dbfbd1f19401f6b528

**Comment by liowalter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[vufind] Die Darstellung der Format-Facetten ist noch nicht ganz korrekt.](https://trello.com/c/w2EAfTwO/342-vufind-die-darstellung-der-format-facetten-ist-noch-nicht-ganz-korrekt)

**Comment by liowalter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[vufind] Die Darstellung der Format-Facetten ist noch nicht ganz korrekt.](https://trello.com/c/w2EAfTwO/342-vufind-die-darstellung-der-format-facetten-ist-noch-nicht-ganz-korrekt)

**Comment by liowalter** [comment]
VuFind took the other way : https://github.com/vufind-org/vufind/pull/1287. They always have the x outside the badge.

Possibilities on our side : 
1. we adapt our phtml and css to do it the same way as vufind. This way we can use the facets.js from VuFind
2. we take the current javascript implemented in swissbib themes/bootstrap3/js/facets.js (https://github.com/swissbib/vufind/commit/8edc0e8fa7eb6cad90aeaa1bc9cda7f6eaf08e2f) in the sbvfrd theme instead of the bootstrap3 theme so that we have our own facets.js

Option 1 is better for the long term
Option 2 is much faster implemented

@edelm : anything to add ?

**Comment by witzigs** [comment]
@liowalter 
This needs to be fixed both for Fachbereichsfacette and the library facet. Is it still on your mind?

**Comment by liowalter** [comment]
Option 1 has been implemented
