### ISSUE TITLE
Problem to display items after login (BaselBern)

### ISSUE THREAD

**Issue by liowalter** [swissbib/vufind#635]
To reproduce : 

- http://devbabe.swissbib.ch/Record/304767867
- Uni Basel - UB Hauptbibliothek -> Verfügbar? -> Details anzeigen
- Anmelden
- Again : "Details anzeigen"
- It returns : "error_occurred. Internal Server Error"

![screenshot_270](https://user-images.githubusercontent.com/1135460/45628350-2c8a7e00-ba94-11e8-9a23-9af88b1eaf01.png)

**Comment by witzigs** [comment]
@liowalter  
Hier sollten die einzelnen Zeitschriftenexemplare der gewählten Bibliothek angezeigt werden, keine Verfügbarkeit - nur wegen möglicher Verwirrung...
