### ISSUE TITLE
Holdings information doesn't load for some libraries

### ISSUE THREAD

**Issue by liowalter** [swissbib/vufind#638]
Example : http://devbabe.swissbib.ch/Record/261652222 for PH Bern or Campus Muristalden

**Comment by liowalter** [comment]
Maybe a libadmin sync problem ?

**Comment by guenterh** [comment]
@FlorinneEgli @liowalter 
Hallo Florinne,
ich habe das gerade mal auf einer virtuellen Maschine ausprobiert, damit ich den Zugriff mit IE erhalte.
Bei mir funktionieren die beiden angegebenen links, aber nur dann, wenn ich den Kompatibilitätsmodus auf IE10 oder IE-Edge einstelle (Taste F12)
Alles darunter (vor allem IE im Modus Version 7) ist die Seite komplett zerrisssn und damit unbrauchbar, also nicht nur fehlende Holdings.
Welche Versionen verwendet denn ihr?

**Comment by FlorinneEgli** [comment]
@guenterh @liowalter 
Hallo Günter, wir verwenden hier an der Arbeit IE11. Jetzt funktionieren aber beide Links bei mir in allen drei erwähnten Browsern, also IE auch.
