### ISSUE TITLE
email address : @ is replaced by *

### ISSUE THREAD

**Issue by liowalter** [swissbib/vufind#641]
In "Adresse ändern" : 

![screenshot_271](https://user-images.githubusercontent.com/1135460/45631046-4dee6880-ba9a-11e8-90d2-2ee3236f8ac4.png)

**Comment by liowalter** [comment]
There was a green database associated with devbabe. Now it is correct (cf devbabe configuration in deploy rep)

**Comment by witzigs** [comment]
@liowalter @edelm 

Bei Florinne tritt das immer noch auf (22. und 23.10. auf IE und Chrome), bei meinem Konto ist hingegen alles in Ordnung.

**Comment by liowalter** [comment]
The address from Florinne was saved with an * in the database. I think that happened before 25.9, when the bug was still there.
@FlorinneEgli : could you test again on devbabe to make sure ?

**Comment by FlorinneEgli** [comment]
@liowalter : After changing the * to a @ it's okay, of course.
