### ISSUE TITLE
Umgang mit error / warning in PHP 7.2 / 18.04

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#647]
@liowalter @edelm 
beim Zusammenbau der Konfigurationen in meiner lokalen Umgebung bin ich wieder einmal auf Folgendes gestossen:

- meine PHP Version
PHP 7.2.10-0ubuntu0.18.04.1 (cli) (built: Sep 13 2018 13:45:02) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.6.1, Copyright (c) 2002-2018, by Derick Rethans
    with Zend OPcache v7.2.10-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies
- meine error-Einstellung im php.ini
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT

Wenn ich das so laufen lasse, bekomme ich eine whoops - Fehlermeldung 

![php error whoops](https://user-images.githubusercontent.com/1825990/45960884-84d5f880-c01d-11e8-90a5-bf710d35383d.png)

man kann das auf verschiedene Arten "übersteuern"
- ganz zu Anfang in index.php
error_reporting(0);
- laschere Einstellungen in php.ini

Persönlich finde ich es generell nicht gut, wenn wir solche Fehler einfach nicht beachten. Spätestens bei Ubuntu 18.04 / genereller Einsatz von PHP 7.2 werden wir damit wieder konfrontiert werden.

Meine Einschätzung / Fragen:
- nicht zwingend für den Umstieg nach VF5 zu beheben.
- auf welcher Umgebung / mit welchen Einstellungen  arbeitet ihr?
- was möchtet ihr machen?

**Comment by liowalter** [comment]
Hi Guenter !
I have : 

- PHP **7.1.20**-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jul 25 2018 10:06:40) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans
    with Zend OPcache v7.1.20-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
- error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT

Therefore I don't see the error you mention.

My Opinion : 
- I agree with you that we should fix such issues
- I wouldn't like to have a too big differences between the productive servers (which run on 7.0 right now) and our development environment

**Comment by guenterh** [comment]
@liowalter 
related to difference between production / development:
- is not easy
because: 
-- I'm running Ubuntu 18.04 where 7.2 is default
-- I have to use 7.2 for other projects e.g. data.swissbib.ch where the latest version I'm using in development requires 7.2 as minimum. This is similar to pura although there 7.1 is minimum (if I'm not wrong)
- possible solutions I see
-- containers
-- I guess switch to Ubuntu 18.04 for production is going to be done at the end of this or beginning of upcoming year
