### ISSUE TITLE
Testoberfläche für sbBB mit angepasstem Verhalten/Anzeige Autoren

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#649]
Für sbBB soll eine Testoberfläche mit folgenden Anpassungen aufgesetzt werden:
- Klick auf den Autor in der rechten Spalte löst eine Phrasen-Suche aus, statt wie bis jetzt eine Suche nach zwei zusammen vorkommenden Worten. Problem bei der jetzigen Lösung ist, dass es diverse Treffer gibt, wo eine Person den Nachnamen und eine andere Person der Vornamen des eigentlich gesuchten Autors hat. Beispiel bei Koch, Sebastian: https://baselbern.swissbib.ch/Record/438361768
- Auf der Personenseite sollte für den Abschnitt "Medien von und zu xxx" analog angepasst werden.
- Anzeige der Lebensdaten des Autors in der rechten Spalte, wenn vorhanden. Die Lebensdaten von Personen werden im Moment nur angezeigt, wenn die Person als Thema erfasst ist. Das ist etwas irritierend, Beispiel bei Jane Austen: https://baselbern.swissbib.ch/Record/309890268

**Comment by liowalter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[vufind] Testoberfläche für sbBB mit angepasstem Verhalten/Anzeige Autoren](https://trello.com/c/dkqimlgU/318-vufind-testoberfl%C3%A4che-f%C3%BCr-sbbb-mit-angepasstem-verhalten-anzeige-autoren)
