### ISSUE TITLE
Covers are smaller than before

### ISSUE THREAD

**Issue by liowalter** [swissbib/vufind#651]
Compare for example
http://devbabe.swissbib.ch/Search/Results?lookfor=algebra+grove+1983&type=AllFields&limit=20
and
https://baselbern.swissbib.ch/Search/Results?lookfor=algebra+grove+1983&type=AllFields&limit=20

**Comment by edelm** [comment]
fixed with 75a5e737e598dcb337f14bff8746aab7c05cecf2
