### ISSUE TITLE
Artikel&mehr: Anzeige Titellänge festlegen?

### ISSUE THREAD

**Issue by FlorinneEgli** [swissbib/vufind#655]
Sollte die angezeigte Titellänge in der Trefferliste beschränkt werden, damit solche fehlerhaften Aufnahmen (https://baselbern.swissbib.ch/SummonRecord/FETCH-crossref_primary_10_12944_CRNFSJ_6_2_183) nicht so auffällig angezeigt werden?

Reproduziere die Anzeige in der Trefferliste mit der Einfachen Suche nach  _Current Research in Nutrition and Food Science Journal_  in Artikel&mehr.

**Comment by witzigs** [comment]
@FlorinneEgli 
Ich kann das Problem nicht mehr nachvollziehen, da die Aufnahme nicht mehr existiert.
Ich schliesse hier, bitte mach das Issue mit einem neuen Beispiel auf, falls du wieder eines findest.
