### ISSUE TITLE
Coauthors of XXX doesn't work (linked)

### ISSUE THREAD

**Issue by liowalter** [swissbib/vufind#656]
See
http://devbabe.swissbib.ch/Page/Detail/Person/5b1b2f97-9e44-3c33-a7b4-9acc27d9af7d#detailpage-coauthors
Compare with
https://baselbern.swissbib.ch/Page/Detail/Person/5b1b2f97-9e44-3c33-a7b4-9acc27d9af7d#detailpage-coauthors

**Comment by liowalter** [comment]
Same is true for "authors of the same genre" : 
https://baselbern.swissbib.ch/Page/Detail/Person/d792881e-1e3e-36df-8489-a6c3ba957e24#detailpage-genres

**Comment by guenterh** [comment]
@liowalter @edelm 

Als Hinweis:

logik hinter co-authors
```bash
/AJAX/json?lookfor=[PPN]&method=getBibliographicResource&searcher=Elasticsearch&type=bibliographicResource
```
json-response 

```json
{
"persons": "hashvalue person", "hashvalue person" , "...."
}
```

so wie ich das im Kopf habe, ruft der client (Ajax) dann die Daten für die zurückgeliefeten Person ab

```bash
/AJAX/json?index=lsb&method=getAuthors&overrideFields[]=hash1,hash2,hash3,...
```

json response

```json
[
{
"id":"hash",
"type": "person",
"name: "Firth, Colin",
"firstName": "Colin",
"lastName": "Firth",
"hasSufficientData":"1"
},
{
"weitere Person":"...."
}
]

soabld das Attribut sufficientdata auf true gesetzt ist, generiert der JavaScript Client die entsprechenden Auszeichnungen.
Ich vermute, dass aufgrund des Refactorings in VF5 die Datenstrukturen wie beschrieben nicht mehr zurückgeliefert werden
```

so

**Comment by guenterh** [comment]
weitere Ajax - calls in diesem Zusammenhang

```bash
AJAX/json?method=GetCoAuthors&person=hashvalue&page=1&size=6
```

```json
[
{
"id=:"hash",
"name"="Kronheimer, Ann"
"displayName": "Ann Kronheimer"
},
{
}
]
```
```bash
AJAX/json?method=getSameGenreAuthors&genre="http://dbpedia.org/resource/Roman_novel&page=2&size=6
```
```json
[
{
"id":"hash",
"name":"McCullough, Collent",
"displayName":"....",
"hasSufficientdata":"true"
}
]
```

**Comment by guenterh** [comment]
wann wird das Attribut hasSufficientdata auf true gesetzt.

dbp:thumbnail
dbp:abstract
dbp:birthDate
lsb:dbpBirthPlaceLiteral
dbp:deathDate
lsb:dbpNationalityAsLiteral
lsb:dbpOccupationAsLiteral

**Comment by edelm** [comment]
fixed with
d3f4b188a0bf1a52e1988e52a73819102dac53e9
e222c2946370c25d23a8a2c3da017bbdaccc7149
05d6aff0900f28ef3afb694db46c88d6e95e721f
a409e63c1df057a463c46b5b587078141aeff2df
