### ISSUE TITLE
fehlerhafte Umsetzung von RD in IE8

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#66]
Vor meinen (GHI) Ferien ist Tobias und mir aufgefallen, dass IE8 unser aktuelles RD fehlerhaft umsetzt.

Das Thema wurde mit Nicolas in einem Skypegespräch kurz thematisiert.
IE8 wird noch in einem Ausmass benutzt, dass wir diesen Browser nicht negieren können.
**** mail Tobias****
Hallo Günter
die Stats für Juni 2014 zeigen immer noch eine sehr starke Durchdringung für IE8…
http://arstechnica.com/information-technology/2014/07/windows-8-x-internet-explorer-both-flatline-in-june/
Da müssen wir uns ernsthaft etwas überlegen...
Beste Grüsse
Tobias

******

@ToVie : ich habe die Beispiele nicht mehr. Diese müssen wir noch zusammenstellen.

**Comment by maechler** [comment]
@guenterh 
Hallo Günter

Das Dokument findest du im todoyu im swissbib Projekt Phase II. Wenn du auf den Projekt-Header klickst siehst du links eine Lasche "Anhänge". Dort findest du unter "AUFGABEN-ANHÄNGE" eine Datei swissbib_und_ie8_v1_1.pdf.

Die Änderungen im offCanvas.js sind nötig, da IE8 die "bind" Methode noch nicht unterstützt. Diese wird gebraucht um den Kontext (das "this" eines Objektes) zu setzen. Da das in IE8 nicht möglich ist, müssen wir alle Aufrufe absolut auf das OffCanvas Objekt beziehen. Es ist vom Code her etwas weniger schön, aber kein grosser Aufwand.

**Comment by maechler** [comment]
Ich habe die nötigen Änderungen gemacht, damit es im IE8 responsive läuft. Mit ein zwei zusätzlichen CSS Anpassungen haben wir es geschafft, dass die Seite praktische gleich aussieht wie in den neueren Browsern. Was nicht einfach möglich ist, sind die abgerundeten Ecken.

Ich hatte im development Branch bevor ich mit der Implementierung begonnen habe schon einen Javascript Fehler. Das Problem hängt mit dem Initialisieren des Sliders in den Facetten zusammen. Die Slider haben bereits vor heute nicht mehr funktioniert. Das ist ein Problem, das nicht mit diesem Issue zusammenhängt und noch gelöst werden sollte.
Ich habe im SideFacets.phtml Zeile 125 auskommentiert um den Fehler zu vermeiden, der Slider funktioniert aber noch nicht.
https://github.com/swissbib/vufind/commit/c2624aa195dee1a5619471a5050c00767228c5c7

**Comment by guenterh** [comment]
@maechler @oschihin 
Hallo Markus,
ich habe mir den aktuellen Stand (test.swissbib.ch) auf meinem IE8 angesehen (meine Version 8.0.6001.18702 auf WinXP)

Aktuell sind die Seiten noch sehr zerrissen. (s. screenshots) - wenn ich es noch recht in Erinnerung habe ein wenig besser als vor Deinen Arbeiten. In der für mich sichtbaren Form könnten wir es aber noch nicht anbieten. Nicht abgerundete Ecken wären mir egal.
 
Eine Reihe von JS - scripten liefern bei mir noch Fehler (evtl. die Ursache für die zerrissene Darstellung?)

Kannst Du es Dir mal auf test.swissbib.ch ansehen so dass wir vergleichen könnten?

Viele Grüsse

Günter

**Comment by guenterh** [comment]
![vollansicht](https://cloud.githubusercontent.com/assets/1825990/5661003/cc796920-9726-11e4-985d-945f6d0f2f7c.png)
![js_fehler_erweiterte_suche](https://cloud.githubusercontent.com/assets/1825990/5661002/cc794364-9726-11e4-9b77-3efb087af6e8.png)
![js_json_fehler](https://cloud.githubusercontent.com/assets/1825990/5661005/cc7dfeae-9726-11e4-86b9-842c752740c1.png)
![startseite](https://cloud.githubusercontent.com/assets/1825990/5661004/cc7a313e-9726-11e4-9ac0-a7acf1357d22.png)

**Comment by maechler** [comment]
Zu Dokumentationszwecken:
Die Fehler in den Screenshots wurden durch den Kompatibilitätsmodus des IE8 verursacht.

**Comment by guenterh** [comment]
- getestet mit IE8/WinXp (Einstiegsseite, Suche - einfach und erweitert, Vollansicht, Anmeldung mit Shibboleth). Das sieht ok aus.

einzelne Punkte:
- das icon Suche neben dem Suchfeld ist  nicht gut poistioniert
-> mit Markus thematisiert, evtl. liese sich hier etwas machen, muss jedoch von Markus analysiert werden.
Der IE8 ist für uns ein Auslaufmodell. Wir versuchen, soweit mach- und vertretbar, die Funktionen zu unterstützen, eine Darstellung wie in moderneren Browsern möglich wird nicht umgesetzt
