### ISSUE TITLE
Zeichenproblem Import Personendaten neuer linked workflow

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#665]
https://develop.swissbib.ch/Record/365729825
(Moln00E1r, Ferenc)
vgl.
https://www.swissbib.ch/Record/365729825/
(Molnár, Ferenc)

**Comment by sschuepbach** [comment]
@guenterh , sollte durch https://github.com/linked-swissbib/swissbib-metafacture-commands/commit/16e986fdb474edb8fe22fa01ff545650284ea2bc gefixt sein. Den enriched-Workflow habe ich mit dem aktualiserten plugins-Jar nochmals angestossen.

**Comment by sschuepbach** [comment]
Gerade überprüft: Der Ferenc Molnár wird nun korrekt angezeigt (https://develop.swissbib.ch/Record/365729825).

**Comment by guenterh** [comment]
Du bist so super Sebastian!!! Danke
