### ISSUE TITLE
DB Pedia / Viaf links auf Personenseite

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#667]
Auf der Personenseite (VuFind) wurde im Zusammenspiel mit dem neuen linked workflow nur noch ein Teil der externen links angezeigt. Dies hing mit der Umstellung von http nach https im workflow zusammen.

Für DBPedia habe ich das gefixt
https://github.com/swissbib/vufind/commit/918b1da5244bb688b1ddfd401df8b5333abf4b3f
@sschuepbach passt Du Viaf auch an? Hatte gerade kein Beispiel gefunden
Ich nehme es mal an (deswegen bereits die Umstellung auf https in der Konfiguration). Müsste dies wieder rückgängig machen falls nicht

**Comment by sschuepbach** [comment]
Die Links zu Viaf - meines Wissens nur in owl:sameAs-Statements vorkommend - wurden bisher noch nicht nach `https://` konvertiert. Dies hat sich mit dem Commit https://github.com/linked-swissbib/mfWorkflows/commit/1da08f44086f4560ebd0c7319b326003b592a63c geändert.

**Comment by guenterh** [comment]
getestet mit dem letzten Index (sb-us6). Dort sind die links auf Datenebene noch nicht auf https umgestellt, da der commit https://github.com/swissbib/vufind/commit/918b1da5244bb688b1ddfd401df8b5333abf4b3f erst nach dem Indexaufbau erfolgte. Deshalb wird der viaf link nicht korrekt angezeigt (https://develop.swissbib.ch/Page/Detail/Person/01818403-df74-3c3b-8f0c-3e4e65d871ee) Stelle ich die Konfiguration lokal zurück auf http erscheint der link. Ich gehe also davon aus, dass mit dem nächsten kompletten Indexaufbau, die VIAF-links korrekt generiert werden
