### ISSUE TITLE
Versendete Merkliste generiert Fehler

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#672]
Der Link, der beim Versenden einer öffentlichen Merkliste verschickt wird, führt zu einer Fehlermeldung.
Beispiel: https://baselbern.swissbib.ch/Records/Home?id%5B%5D=Solr%7C317680161&id%5B%5D=Solr%7C290587468

**Comment by liowalter** [comment]
When only one document is selected, it works : 
https://baselbern.swissbib.ch/Records/Home?id%5B%5D=Solr%7C36163465X

When more no :
https://baselbern.swissbib.ch/Records/Home?id%5B%5D=Solr%7C549179909&id%5B%5D=Solr%7C36163465X&id%5B%5D=Solr%7C511199856&id%5B%5D=Solr%7C363848711&id%5B%5D=Solr%7C368557049&id%5B%5D=Solr%7C341677299

**Comment by liowalter** [comment]
The error is Class 'Swissbib\VuFind\Search\Mixedlist\Results' not found. It is what we already saw in the logs. 

@edelm : can you have a look ? There is a card for this on the scrum board. Thanks !
