### ISSUE TITLE
npm run build fails with autosuggest.ts

### ISSUE THREAD

**Issue by liowalter** [swissbib/vufind#675]
Travis fails with npm run build : 

To reproduce locally : 
- remove node_modules
- npm install
- npm run build

The problem is with this line
https://github.com/swissbib/vufind/blob/master/themes/sbvfrd/ts/autosuggest/AutoSuggest.ts#L248

ERROR in ./themes/sbvfrd/ts/autosuggest/AutoSuggest.ts
[tsl] ERROR in /usr/local/vufind/httpd/themes/sbvfrd/ts/autosuggest/AutoSuggest.ts(248,40)
      TS2339: Property 'target' does not exist on type 'Event'.

Until December 7th it worked. Maybe it is related to this https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration.

As we don't use autosuggest right now, this shouldn't affect the users.

My PHPStorm also displays this error.

**Comment by edelm** [comment]
Looks like the @types/jquery npm-package changed: https://www.npmjs.com/package/@types/jquery/v/3.3.27

In https://github.com/swissbib/vufind/blob/master/tsconfig.json#L16 we include the file "node_modules/@types/jquery/index.d.ts" which contained the definition of the Event interface. When we remove the node_modules and reinstall them, the definition of the interface is in ''node_modules/@types/jquery/misc.d.ts".

So changing the include in tsconfig.json to the new file should fix it.

**Comment by edelm** [comment]
fixed by 867bc560cf52bd95383401d7205ba3c806681b7b
