### ISSUE TITLE
Spell Suggestions should include all terms in all cases

### ISSUE THREAD

**Issue by liowalter** [swissbib/vufind#676]
Compare 
* https://www.swissbib.ch/Search/Results?lookfor=eisenhozer+inside&type=AllFields&limit=20
*  https://vufind.org/demo/Search/Results?lookfor=eisenhozer+inside&type=AllFields&limit=20

In the latter the spell suggestions run a query for "eisenhower inside". In swissbib, only "eisenhower".

I have the feeling we can come closer to vufind core for this topic (using the renderSpellingSuggestions view helper and maybe get rid of some swissbib specialities like https://github.com/swissbib/vufind/blob/master/module/Swissbib/src/Swissbib/VuFind/Search/Solr/SpellingResults.php ?

**Comment by guenterh** [comment]
@liowalter Without looking into the details of the code I think it's definitely worth a try to use the VuFind implementation as first step
after this we can still decide if we need to / or can make it better

**Comment by liowalter** [comment]
see also https://github.com/vufind-org/vufind/pull/1391
