### ISSUE TITLE
Internet Explorer Erweiterte Suche und Vollanzeige Autoren

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#683]
Zwei Punkte, die im Internet Explorer (IE 11) nicht zu funktionieren scheinen:
* In der erweiterten Suche fehlen die Suchschlitze (siehe Screenshot)
* in der Vollanzeige werden die Autoren in der rechten Spalte nicht dargestellt (ES-Zugriff)

Problem dabei: wir haben in der UB keinen IE11 mehr zum Testen -> wie lösen wir das?

![grafik](https://user-images.githubusercontent.com/9479686/53807754-aafaaf80-3f50-11e9-9cee-d8dcf3fe672c.png)

**Comment by liowalter** [comment]
With vufind-core it works.

Vufind-core : https://github.com/swissbib/vufind/blob/master/themes/bootstrap3/js/advanced_search.js
Our js : https://github.com/swissbib/vufind/blob/master/themes/sbvfrd/js/swissbib/AdvancedSearch.js

I have a windows Virtual Machine with IE11. But for the moment, I can not test using the apache server running on my ubuntu machine.

Here is a way : http://blog.bruyere-freelance.fr/installer-internet-explorer-ie-9-10-11-edge-sur-linux-ubuntu-16-04/

I already tried step 5, but it didn't work.

**Comment by liowalter** [comment]
Finally, I could make it work by adding 
10.0.2.2 localhost
on windows in C:\Windows\System32\drivers\etc\hosts and entering localhost in internet explorer.

@edelm : could you have a look at the issue and let me know if you solve it or if I should ?

**Comment by liowalter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[vufind] Internet Explorer Erweiterte Suche und Vollanzeige Autoren](https://trello.com/c/lNkEsAfA/401-vufind-internet-explorer-erweiterte-suche-und-vollanzeige-autoren)

**Comment by guenterh** [comment]
..
Seit Freitag hatten wir intern Probleme, Swissbib auf IE zu betreiben. Nun erreichen uns auch Anrufe von Benutzenden, dass mit IE und Edge die Bibliotheksauwahl (das Ausklappmenü zum Reservieren etc.) nicht mehr lädt (es dreht ewig ein Kreis). Mit Firefox und Chrome geht es aber, ich habe jetzt intern unsere Webstationen auf Chrome umgestellt. Hat evtl. Swissbib oder Microsoft etwas gepatcht?

**Comment by liowalter** [comment]
5.3.0-core5.0.1 : advanced search, little i and holdings work on internet explorer

**Comment by liowalter** [comment]
5.3.1-core5.0.1 : the three features don't work any more (deployed right now on test.swissbib.ch)

**Comment by liowalter** [comment]
fixed with https://github.com/swissbib/vufind/commit/7c13cecbf897187e2da37cfc4da75b70895cf43f

**Comment by edelm** [comment]
In 23055e1ca679a02c207d59a65f3c015a0991bdb8 I changed to code that even IE understands. I still get sometimes a strange behaviour (on completely other parts of the code) in IE. Please test with your IE environments as well.

**Comment by witzigs** [comment]
@edelm  @liowalter 
Claudia und ich haben am Freitag getestet. Bei Claudia ging die Suche nach der nächsten Bibliothek in der Karte nicht.
Ansonsten haben wir nichts festgestellt.
