### ISSUE TITLE
Searches with : don't work as expected

### ISSUE THREAD

**Issue by liowalter** [swissbib/vufind#686]
There are several cases where a searches with ":" in the middle is expected to work. But this is not always the case.

  | description | simple search | simple search with “” | advanced search | advanced search with “”
-- | -- | -- | -- | -- | --
Linear : algebra | simple search | [**not ok**](https://www.swissbib.ch/Search/Results?lookfor=linear+%3A+algebra&type=AllFields&limit=20) | [?](https://www.swissbib.ch/Search/Results?lookfor=%22linear+%3A+algebra%22&type=AllFields&limit=20) <br>less results than "linear algebra" |  | 
MKB PP 305 : 27,2004 | call number | [not ok](https://www.swissbib.ch/Search/Results?lookfor=MKB+PP+305+%3A+27%2C2004&type=AllFields&limit=20) but this is fine | [ok](https://www.swissbib.ch/Search/Results?lookfor=%22MKB+PP+305+%3A+27%2C2004%22&type=AllFields&limit=20) | [ok](https://www.swissbib.ch/Search/Results?sort=relevance&advancedSearchFormRequest=advancedSearchFormRequest&join=AND&bool0%5B%5D=AND&lookfor0%5B%5D=MKB+PP+305+%3A+27%2C2004&type0%5B%5D=CallNumber&lookfor0%5B%5D=&type0%5B%5D=AllFields&lookfor0%5B%5D=&type0%5B%5D=AllFields&daterange%5B%5D=publishDate&publishDatefrom=&publishDateto=&limit=20) | [ok](https://www.swissbib.ch/Search/Results?sort=relevance&advancedSearchFormRequest=advancedSearchFormRequest&join=AND&bool0%5B%5D=AND&lookfor0%5B%5D=%22MKB+PP+305+%3A+27%2C2004%22&type0%5B%5D=CallNumber&daterange%5B%5D=publishDate&publishDatefrom=&publishDateto=&limit=20)
10.1023/A:1008433817832 | doi | [not ok](https://www.swissbib.ch/Search/Results?lookfor=10.1023%2FA%3A1008433817832&type=AllFields&limit=20) but this is fine  | [not ok](https://www.swissbib.ch/Search/Results?lookfor=%2210.1023%2FA%3A1008433817832%22&type=AllFields&limit=20)  | [not ok](https://www.swissbib.ch/Search/Results?sort=relevance&advancedSearchFormRequest=advancedSearchFormRequest&join=AND&bool0%5B%5D=AND&lookfor0%5B%5D=10.1023%2FA%3A1008433817832&type0%5B%5D=ISN&daterange%5B%5D=publishDate&publishDatefrom=&publishDateto=&limit=20)  | [ok](https://www.swissbib.ch/Search/Results?sort=relevance&advancedSearchFormRequest=advancedSearchFormRequest&join=AND&bool0%5B%5D=AND&lookfor0%5B%5D=%2210.1023%2FA%3A1008433817832%22&type0%5B%5D=ISN&lookfor0%5B%5D=&type0%5B%5D=AllFields&lookfor0%5B%5D=&type0%5B%5D=AllFields&daterange%5B%5D=publishDate&publishDatefrom=&publishDateto=&limit=20)  
urn:nbn:ch:bel-bau-diss108444 | urn | [not ok](https://www.swissbib.ch/Search/Results?lookfor=urn%3Anbn%3Ach%3Abel-bau-diss108444&type=AllFields&limit=20) but this is fine | [not ok](https://www.swissbib.ch/Search/Results?lookfor=%22urn%3Anbn%3Ach%3Abel-bau-diss108444%22&type=AllFields&limit=20)   | [not ok](https://www.swissbib.ch/Search/Results?sort=relevance&advancedSearchFormRequest=advancedSearchFormRequest&join=AND&bool0%5B%5D=AND&lookfor0%5B%5D=urn%3Anbn%3Ach%3Abel-bau-diss108444&type0%5B%5D=ISN&lookfor0%5B%5D=&type0%5B%5D=AllFields&lookfor0%5B%5D=&type0%5B%5D=AllFields&daterange%5B%5D=publishDate&publishDatefrom=&publishDateto=&limit=20) error  |   [ok](https://www.swissbib.ch/Search/Results?sort=relevance&advancedSearchFormRequest=advancedSearchFormRequest&join=AND&bool0%5B%5D=AND&lookfor0%5B%5D=%22urn%3Anbn%3Ach%3Abel-bau-diss108444%22&type0%5B%5D=ISN&lookfor0%5B%5D=&type0%5B%5D=AllFields&lookfor0%5B%5D=&type0%5B%5D=AllFields&daterange%5B%5D=publishDate&publishDatefrom=&publishDateto=&limit=20)
RETROSoai:agora.ch:hnu-001:1917:23::141 | id | [not ok](https://www.swissbib.ch/Search/Results?lookfor=RETROSoai%3Aagora.ch%3Ahnu-001%3A1917%3A23%3A%3A141&type=AllFields&limit=20) but this is fine | [ok](https://www.swissbib.ch/Search/Results?lookfor=%22RETROSoai%3Aagora.ch%3Ahnu-001%3A1917%3A23%3A%3A141%22&type=AllFields&limit=20)  |   |  
author:dicker | "expert" search | [ok](https://www.swissbib.ch/Search/Results?lookfor=author%3Adicker&type=AllFields&limit=20)| [ok](https://www.swissbib.ch/Search/Results?lookfor=%22author%3Adicker%22&type=AllFields&limit=20) | |

Involved in this process are these parts : 
- https://github.com/swissbib/vufind/blob/master/module/Swissbib/src/Swissbib/VuFind/Search/Backend/Solr/LuceneSyntaxHelper.php#L78
- https://github.com/swissbib/vufind/blob/master/module/VuFindSearch/src/VuFindSearch/Backend/Solr/LuceneSyntaxHelper.php#L526
- https://github.com/swissbib/vufind/blob/master/local/config/vufind/searchspecs.yaml#L326
- https://github.com/swissbib/vufind/blob/master/local/config/vufind/searchspecs.yaml#L131
- https://github.com/swissbib/searchconf/blob/master/solr/bib/solr.home/conf/managed-schema#L219
- https://github.com/swissbib/searchconf/blob/master/solr/bib/solr.home/conf/managed-schema#L239

**Comment by liowalter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[vufind] Searches with : don't work as exepected](https://trello.com/c/pPY5fcPc/413-vufind-searches-with-dont-work-as-exepected)

**Comment by liowalter** [comment]
Astonishingly the parser for the ISSN/ISMN/DOI/URN advanced search was not set to edismax. Changing this yield the following improvements


|   | description | simple search | simple search with “” | advanced search | advanced search with “” |
| -- | -- | -- | -- | -- | -- |
Linear : algebra | simple search | [**not ok**](https://test.swissbib.ch/Search/Results?lookfor=linear+%3A+algebra&type=AllFields&limit=20) | [?](https://test.swissbib.ch/Search/Results?lookfor=%22linear+%3A+algebra%22&type=AllFields&limit=20) less results than "linear algebra" |  | 
MKB PP 305 : 27,2004 | call number | [not ok](https://test.swissbib.ch/Search/Results?lookfor=MKB+PP+305+%3A+27%2C2004&type=AllFields&limit=20) but this is fine | [ok](https://test.swissbib.ch/Search/Results?lookfor=%22MKB+PP+305+%3A+27%2C2004%22&type=AllFields&limit=20) | [ok](https://test.swissbib.ch/Search/Results?sort=relevance&advancedSearchFormRequest=advancedSearchFormRequest&join=AND&bool0%5B%5D=AND&lookfor0%5B%5D=MKB+PP+305+%3A+27%2C2004&type0%5B%5D=CallNumber&lookfor0%5B%5D=&type0%5B%5D=AllFields&lookfor0%5B%5D=&type0%5B%5D=AllFields&daterange%5B%5D=publishDate&publishDatefrom=&publishDateto=&limit=20) | [ok](https://test.swissbib.ch/Search/Results?sort=relevance&advancedSearchFormRequest=advancedSearchFormRequest&join=AND&bool0%5B%5D=AND&lookfor0%5B%5D=%22MKB+PP+305+%3A+27%2C2004%22&type0%5B%5D=CallNumber&daterange%5B%5D=publishDate&publishDatefrom=&publishDateto=&limit=20)
10.1023/A:1008433817832 | doi | [not ok](https://test.swissbib.ch/Search/Results?lookfor=10.1023%2FA%3A1008433817832&type=AllFields&limit=20) but this is fine  | [not ok](https://test.swissbib.ch/Search/Results?lookfor=%2210.1023%2FA%3A1008433817832%22&type=AllFields&limit=20)  | [**OK**](https://test.swissbib.ch/Search/Results?sort=relevance&advancedSearchFormRequest=advancedSearchFormRequest&join=AND&bool0%5B%5D=AND&lookfor0%5B%5D=10.1023%2FA%3A1008433817832&type0%5B%5D=ISN&daterange%5B%5D=publishDate&publishDatefrom=&publishDateto=&limit=20)  | [ok](https://test.swissbib.ch/Search/Results?sort=relevance&advancedSearchFormRequest=advancedSearchFormRequest&join=AND&bool0%5B%5D=AND&lookfor0%5B%5D=%2210.1023%2FA%3A1008433817832%22&type0%5B%5D=ISN&lookfor0%5B%5D=&type0%5B%5D=AllFields&lookfor0%5B%5D=&type0%5B%5D=AllFields&daterange%5B%5D=publishDate&publishDatefrom=&publishDateto=&limit=20)  
urn:nbn:ch:bel-bau-diss108444 | urn | [not ok](https://test.swissbib.ch/Search/Results?lookfor=urn%3Anbn%3Ach%3Abel-bau-diss108444&type=AllFields&limit=20) but this is fine | [not ok](https://test.swissbib.ch/Search/Results?lookfor=%22urn%3Anbn%3Ach%3Abel-bau-diss108444%22&type=AllFields&limit=20)   | [not ok](https://test.swissbib.ch/Search/Results?sort=relevance&advancedSearchFormRequest=advancedSearchFormRequest&join=AND&bool0%5B%5D=AND&lookfor0%5B%5D=urn%3Anbn%3Ach%3Abel-bau-diss108444&type0%5B%5D=ISN&lookfor0%5B%5D=&type0%5B%5D=AllFields&lookfor0%5B%5D=&type0%5B%5D=AllFields&daterange%5B%5D=publishDate&publishDatefrom=&publishDateto=&limit=20) **no more error**  |   [ok](https://test.swissbib.ch/Search/Results?sort=relevance&advancedSearchFormRequest=advancedSearchFormRequest&join=AND&bool0%5B%5D=AND&lookfor0%5B%5D=%22urn%3Anbn%3Ach%3Abel-bau-diss108444%22&type0%5B%5D=ISN&lookfor0%5B%5D=&type0%5B%5D=AllFields&lookfor0%5B%5D=&type0%5B%5D=AllFields&daterange%5B%5D=publishDate&publishDatefrom=&publishDateto=&limit=20)
RETROSoai:agora.ch:hnu-001:1917:23::141 | id | [not ok](https://test.swissbib.ch/Search/Results?lookfor=RETROSoai%3Aagora.ch%3Ahnu-001%3A1917%3A23%3A%3A141&type=AllFields&limit=20) but this is fine | [ok](https://test.swissbib.ch/Search/Results?lookfor=%22RETROSoai%3Aagora.ch%3Ahnu-001%3A1917%3A23%3A%3A141%22&type=AllFields&limit=20)  |   |  
author:dicker | "expert" search | [ok](https://test.swissbib.ch/Search/Results?lookfor=author%3Adicker&type=AllFields&limit=20)| [ok](https://test.swissbib.ch/Search/Results?lookfor=%22author%3Adicker%22&type=AllFields&limit=20) | |

**Comment by liowalter** [comment]
Solved via https://github.com/swissbib/searchconf/commit/ac015d40d05adb19da617f015fd388e6a038feee

**Comment by guenterh** [comment]
@liowalter @witzigs  
Hi Lionel,
thanks a lot for fixing it. As you already mentioned: It might happen that an Index error caused by wrong spelled field-names leads to a bunch of documents not index which are part of a whole batch request sent to SOLR by the indexer client. But we can test it especially before the next Gesamtexport.

Another idea came to my mind: Now you are using a field type text_untreated valid for indexing and query use cases. What if you would define a new field type which is only valid for for indexing puposes and not for the query execution?

Not sure if this works but a fast test might be helpful

**Comment by liowalter** [comment]
after release the status should be : 

|   | description | simple search | simple search with “” | advanced search | advanced search with “” |
| -- | -- | -- | -- | -- | -- |
Linear : algebra | simple search | [ok](https://test.swissbib.ch/Search/Results?lookfor=linear+%3A+algebra&type=AllFields&limit=20) | [?](https://test.swissbib.ch/Search/Results?lookfor=%22linear+%3A+algebra%22&type=AllFields&limit=20) less results than "linear algebra" |  | 
Linear:algebra | simple search | [ok](https://test.swissbib.ch/Search/Results?lookfor=linear%3Aalgebra&type=AllFields&limit=20) | [ok](https://test.swissbib.ch/Search/Results?lookfor=%22linear%3Aalgebra%22&type=AllFields&limit=20) |  | 
MKB PP 305 : 27,2004 | call number | [ok](https://test.swissbib.ch/Search/Results?lookfor=MKB+PP+305+%3A+27%2C2004&type=AllFields&limit=20) | [ok](https://test.swissbib.ch/Search/Results?lookfor=%22MKB+PP+305+%3A+27%2C2004%22&type=AllFields&limit=20) | [ok](https://test.swissbib.ch/Search/Results?sort=relevance&advancedSearchFormRequest=advancedSearchFormRequest&join=AND&bool0%5B%5D=AND&lookfor0%5B%5D=MKB+PP+305+%3A+27%2C2004&type0%5B%5D=CallNumber&lookfor0%5B%5D=&type0%5B%5D=AllFields&lookfor0%5B%5D=&type0%5B%5D=AllFields&daterange%5B%5D=publishDate&publishDatefrom=&publishDateto=&limit=20) | [ok](https://test.swissbib.ch/Search/Results?sort=relevance&advancedSearchFormRequest=advancedSearchFormRequest&join=AND&bool0%5B%5D=AND&lookfor0%5B%5D=%22MKB+PP+305+%3A+27%2C2004%22&type0%5B%5D=CallNumber&daterange%5B%5D=publishDate&publishDatefrom=&publishDateto=&limit=20)
10.1023/A:1008433817832 | doi | [ok](https://test.swissbib.ch/Search/Results?lookfor=10.1023%2FA%3A1008433817832&type=AllFields&limit=20) | [ok](https://test.swissbib.ch/Search/Results?lookfor=%2210.1023%2FA%3A1008433817832%22&type=AllFields&limit=20)  | [ok](https://test.swissbib.ch/Search/Results?sort=relevance&advancedSearchFormRequest=advancedSearchFormRequest&join=AND&bool0%5B%5D=AND&lookfor0%5B%5D=10.1023%2FA%3A1008433817832&type0%5B%5D=ISN&daterange%5B%5D=publishDate&publishDatefrom=&publishDateto=&limit=20)  | [ok](https://test.swissbib.ch/Search/Results?sort=relevance&advancedSearchFormRequest=advancedSearchFormRequest&join=AND&bool0%5B%5D=AND&lookfor0%5B%5D=%2210.1023%2FA%3A1008433817832%22&type0%5B%5D=ISN&lookfor0%5B%5D=&type0%5B%5D=AllFields&lookfor0%5B%5D=&type0%5B%5D=AllFields&daterange%5B%5D=publishDate&publishDatefrom=&publishDateto=&limit=20)  
urn:nbn:ch:bel-bau-diss108444 | urn | [ok](https://test.swissbib.ch/Search/Results?lookfor=urn%3Anbn%3Ach%3Abel-bau-diss108444&type=AllFields&limit=20) | [ok](https://test.swissbib.ch/Search/Results?lookfor=%22urn%3Anbn%3Ach%3Abel-bau-diss108444%22&type=AllFields&limit=20)   | [ok](https://test.swissbib.ch/Search/Results?sort=relevance&advancedSearchFormRequest=advancedSearchFormRequest&join=AND&bool0%5B%5D=AND&lookfor0%5B%5D=urn%3Anbn%3Ach%3Abel-bau-diss108444&type0%5B%5D=ISN&lookfor0%5B%5D=&type0%5B%5D=AllFields&lookfor0%5B%5D=&type0%5B%5D=AllFields&daterange%5B%5D=publishDate&publishDatefrom=&publishDateto=&limit=20) |  [ok](https://test.swissbib.ch/Search/Results?sort=relevance&advancedSearchFormRequest=advancedSearchFormRequest&join=AND&bool0%5B%5D=AND&lookfor0%5B%5D=%22urn%3Anbn%3Ach%3Abel-bau-diss108444%22&type0%5B%5D=ISN&lookfor0%5B%5D=&type0%5B%5D=AllFields&lookfor0%5B%5D=&type0%5B%5D=AllFields&daterange%5B%5D=publishDate&publishDatefrom=&publishDateto=&limit=20)
RETROSoai:agora.ch:hnu-001:1917:23::141 | id | [ok](https://test.swissbib.ch/Search/Results?lookfor=RETROSoai%3Aagora.ch%3Ahnu-001%3A1917%3A23%3A%3A141&type=AllFields&limit=20) | [ok](https://test.swissbib.ch/Search/Results?lookfor=%22RETROSoai%3Aagora.ch%3Ahnu-001%3A1917%3A23%3A%3A141%22&type=AllFields&limit=20)  |   |  
author:dicker | "expert" search | [ok](https://test.swissbib.ch/Search/Results?lookfor=author%3Adicker&type=AllFields&limit=20)| [ok](https://test.swissbib.ch/Search/Results?lookfor=%22author%3Adicker%22&type=AllFields&limit=20) | |
