### ISSUE TITLE
kein access auf free online

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#688]
Fällt mir gerade durch Zufall auf:
Bei https://www.swissbib.ch/Record/HAN000085847?expandlib=IDSBB-FREE 
verbleibe ich beim Exemplar "free access - online" auf der Vollanzeige
(s. auch screenshot)

@witzigs @liowalter - ist das so gewollt?

![no-free-online-access](https://user-images.githubusercontent.com/1825990/55951733-39510800-5c58-11e9-932e-2e57e534ff12.png)

**Comment by witzigs** [comment]
Man muss nur auf den Link oben klicken, falls man denn überhaupt je auf das Exemplar geklickt hat.
