### ISSUE TITLE
Suche mit 3 Punkten geht nicht

### ISSUE THREAD

**Issue by Kordishal** [swissbib/vufind#689]
Der Titel `De astrologia: Rabbi Mosis filii Meimon epistola elegans ... Hebraea` enthält drei Punkte. Wenn man so komplett sucht, ergibt das keinen Treffer. Wenn man die drei Punkte weglässt erhält man jedoch Treffer.

@liowalter

**Comment by liowalter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[vufind] Suche mit 3 Punkten geht nicht](https://trello.com/c/wPIzt0tN/419-vufind-suche-mit-3-punkten-geht-nicht)

**Comment by liowalter** [comment]
[SOLR query](http://localhost:8984/solr/green/select?fl=%2A%2Cscore&spellcheck=false&facet=true&facet.limit=100&facet.field=%7B%21ex%3Dunion_filter%7Dunion&facet.field=%7B%21ex%3Dlibrary_hierarchy_str_mv_filter%7Dlibrary_hierarchy_str_mv&facet.field=%7B%21ex%3DnavAuthor_full_filter%7DnavAuthor_full&facet.field=%7B%21ex%3Dformat_hierarchy_str_mv_filter%7Dformat_hierarchy_str_mv&facet.field=%7B%21ex%3Dlanguage_filter%7Dlanguage&facet.field=navSub_green&facet.field=%7B%21ex%3DnavSubform_filter%7DnavSubform&facet.field=publishDate&facet.sort=count&facet.mincount=1&sort=score+desc&q.op=AND&hl=true&hl.simple.pre=%7B%7B%7B%7BSTART_HILITE%7D%7D%7D%7D&hl.simple.post=%7B%7B%7B%7BEND_HILITE%7D%7D%7D%7D&hl.fl=fulltext&hl.fl=0%2Cauthor%2Cauthor_additional%2Cauthor_additional_dsv11_txt_mv%2Cauthor_additional_gnd_txt_mv%2Cseries%2Ctopic%2Crelated_gnd_txt_mv%2Caddfields_txt_mv%2Cpublplace_txt_mv%2Cpublplace_dsv11_txt_mv%2Cpublplace_gnd_txt_mv%2Cfulltext%2Clocalcode%2Ctitle_short%2Ctitle_alt%2Ctitle%2Ctitle_sub%2Ctitle_old%2Ctitle_new%2Ctitle_additional_dsv11_txt_mv%2Ctitle_additional_gnd_txt_mv%2Cpublplace_additional_gnd_txt_mv%2Ccallnumber_txt_mv%2Cctrlnum%2CpublishDate%2Cisbn%2Ccancisbn_isn_mv%2Cvariant_isbn_isn_mv%2Cissn%2Cincoissn_isn_mv%2Cid_txt&hl.fragsize=250&wt=json&json.nl=arrarr&rows=20&start=0&qf=title_short%5E1000+title_alt%5E200+title%5E200+title_sub%5E200+title_old%5E200+title_new%5E200+author%5E750+author_additional%5E100+author_additional_dsv11_txt_mv%5E100+title_additional_dsv11_txt_mv%5E100+author_additional_gnd_txt_mv%5E100+title_additional_gnd_txt_mv%5E100+publplace_additional_gnd_txt_mv%5E100+series%5E200+topic%5E500+related_gnd_txt_mv%5E500+addfields_txt_mv%5E50+publplace_txt_mv%5E25+publplace_dsv11_txt_mv%5E25+fulltext+callnumber_txt_mv%5E50+ctrlnum%5E1000+publishDate+isbn+cancisbn_isn_mv+variant_isbn_isn_mv+issn+incoissn_isn_mv+localcode+id_txt&qt=edismax&pf=title_short%5E1000+callnumber_txt_mv%5E100&ps=2&bf=recip%28abs%28ms%28NOW%2FDAY%2Cfreshness%29%29%2C3.16e-10%2C100%2C100%29&mm=0%25&q=De+astrologia++Rabbi+Mosis+filii+Meimon+epistola+elegans+...+Hebraea)

q : `De astrologia  Rabbi Mosis filii Meimon epistola elegans ... Hebraea`

Enclosed in `"`, it [works](https://test.swissbib.ch/Search/Results?lookfor=%22De+astrologia++Rabbi+Mosis+filii+Meimon+epistola+elegans+...+Hebraea%22&type=AllFields&limit=20)

**Comment by liowalter** [comment]
Advanced search with title [works](https://test.swissbib.ch/Search/Results?sort=relevance&advancedSearchFormRequest=advancedSearchFormRequest&join=AND&bool0%5B%5D=AND&lookfor0%5B%5D=De+astrologia++Rabbi+Mosis+filii+Meimon+epistola+elegans+...+Hebraea&type0%5B%5D=Title&lookfor0%5B%5D=&type0%5B%5D=AllFields&lookfor0%5B%5D=&type0%5B%5D=AllFields&daterange%5B%5D=publishDate&publishDatefrom=&publishDateto=&limit=20) as well.

**Comment by liowalter** [comment]
Without spaces around the ..., it [works](https://test.swissbib.ch/Search/Results?lookfor=De+astrologia%3A+Rabbi+Mosis+filii+Meimon+epistola+elegans...Hebraea&type=AllFields&limit=20) as well.

**Comment by liowalter** [comment]
The problem is the following. Local codes are [included] in the simple search.
Or the field localcode is a [stringlike](https://github.com/swissbib/searchconf/blob/master/solr/bib/solr.home/conf/managed-schema#L283) field in solr. For this field the punctuation is not removed. 

Several solutions : 
- take localcode away from simple search
- change the analysis on localcode (use text_untreated). But could it be that spaces or special characters have some significance in local codes ?
- ...

**Comment by liowalter** [comment]
Will be fully solved after the next reindex
