### ISSUE TITLE
Analyse und ev. Konfiguration von Facettenfunktionen

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#69]
In der facets.ini existieren einige interessante Konfigurationsmöglichkeiten, die man sich mal genauer anschauen müsste:
* exclude
* orFacets
* collapsedFacets
* ev. weitere
 * Hierarchische Facetten sind in Arbeit: https://github.com/vufind-org/vufind/pull/185

Ziel ist es herauszufinden, wie wir "out of the box" die Facetten funktional verbessern können und wo wir ev. Entwicklerkapazitäten reinstecken können und sollen.

**Comment by witzigs** [comment]
Kommentare zu Konfiguarationsmöglichkeiten und -wünschen

exclude (NOT):
* pro Facette kann konfiguriert werden, ob exclude-Links angeboten werden sollen
* funktioniert, Treffermengen sind korrekt
* geringe Design-Anpassungen sind notwendig (out of the box werden die Facetten-Einträge als Links dargestellt und das x zum aussschliessen eines Werts ist nicht sichtbar)
* Konfiguration wird bei Favoriten-Facette nicht wirksam

orFacets (OR):
* pro Facette kann konfiguriert werden, ob gewählte Einträge mit OR statt mit AND kombiniert werden sollen
* Facetten-Einträge aus verschiedenen Facetten werden immer mit AND kombiniert
* Konfiguration erfolgt separat für Facetten auf Trefferliste und Facetten in der erweiterten Suche (momentaner Stand: AND auf der Trefferliste, OR in der erweiterten Suche)
* funktioniert, Treffermengen sind korrekt
* Konfiguration wird bei Favoriten-Facette nicht wirksam

collapsedFacets:
* pro Facette kann konfiguriert werden, ob sie standardmässig zugeklappt sein soll

hierarchical:
* pro Facette kann konfiguriert werden, ob sie hierarchisch dargestellt werden soll
* für Facetten-Einträge sind verschiedene Sortierungsmöglichkeiten möglich: Alle Levels nach Menge, Top-Level alphabetisch und weitere Levels nach Menge, alle Levels alphabetisch
* in der Vollanzeige kann die ganze Hierarchie oder nur das tiefste Level angezeigt werden
* Anpassungen am Index sind notwendig

Alphabetische Sortierung von Facetten (Thema aus Entwicklungsplan sbBB):
* Eine alphabetische Sortierung von Facetten-Einträgen wird von VuFind nicht vorgesehen. Grund dafür: Für Facetten in der Trefferliste wird eine Maximal-Anzahl von Einträgen (konfigurierbar) angezeigt. Bei alphabetischer Sortierung fallen relevante Einträge (mit hoher Trefferanzahl) am Ende des Alphabets weg, was sinnlos ist.
