### ISSUE TITLE
Update linked für ES7 

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#711]
Hallo zusammen
@liowalter @witzigs @Kordishal @sschuepbach @edelm 
wie gestern im scrum abgemacht, heir meine ersten Ergebnisse Analyse Machbarkeit möglicht schneller und einfacher Update des Vufind-clients für den Zugriff auf einen ES7 Index mit altem Datenmodell (bzw. integriert mit neuem)

- ich habe den Adapter und das Vufind repository ein wenig angepasst. Vielleicht nicht de eleganteste Lösung, dafür aber nicht sehr invasiv und hoffentlich das Ziel erreichend

u.a.
https://github.com/swissbib/vufind/commit/7f24f0f92aac4a4094eb31894847da32a325bb60
https://github.com/linked-swissbib/adapterElasticsearch/commit/275195f8580fb7726414cbfe79bd43efacd4957c

Es sollte weniger Probleme geben, den code für den Zugriff anzupassen, mehr achten müssen wir auf die requirements für PHP
mit unserer VuFid Version benutzten wir fix php 7.0.8. Der neueste php ES 7 client benötigt jedoch mindesten php 7.1 (Wasser auf meine Mühlen, mit VuFind Updates nicht zu lange zu warten...). Das grössere Risiko betsht für mich darin, einfach VuFind auf 7.1 hochzusetzen. Obwohl ich das zuerst gemacht habe und ich auf meinem Laptop 7.2 (Ubuntu 18) verwende. Jetzt verwende ich den php client für ES6 
https://github.com/linked-swissbib/adapterElasticsearch/commit/275195f8580fb7726414cbfe79bd43efacd4957c
und den DSL wrapper für ES in der aktuellsten version
https://github.com/swissbib/vufind/blob/migration_linked_es7/composer.json#L118
Ich denke das sollte gehen, weil die Zugriffe mit einem php-client ausschliesslich über HTTP verlaufen und wir keine speziellen features der DSL verwenden, die in den Versionen unterschiedlich sind.
Bisher hat das geklappt, allerdings konnte ich bisher auch nur sehr eingeshränkt testen.
Grund: Ich benötige auf dem ES7 cluster noch unsere alte Version des GND Index. Diese muss ich noch erstellen.

Dinge die ich etwas seltsam fand (mich dann aber nicht mehr darum weiter gekümmert habe). Wenn ich eine Komponente esAdapter verwende, die im composer json dependencies angegen hat, ich diese im parent Projket nochmals angeben muss. Dies machen wir bisher auch schon so (war mir nicht bewusst) sollte aber wohl nicht sein

**Comment by liowalter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[vufind] Update linked für ES7](https://trello.com/c/wIy07TSP/437-vufind-update-linked-f%C3%BCr-es7)
