### ISSUE TITLE
Funktion show all authors auf person page zeigt nur eine Person

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#715]
@liowalter 
Die URL
http://c2sbm.local.ch/Search/Persons/Subject?lookfor=4138544-5
zeigt nur eine Person aus einem grösseren set in einer Liste an.

Richtig wäre dies:
https://www.swissbib.ch/Search/Persons/Subject?lookfor=4138544-5

**Comment by liowalter** [comment]
Now that all persons (even the non-enriched) are in the persons index, this is fine.
