### ISSUE TITLE
Display of Birth/death dates

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#718]
Dates on Person pages and cards should be displayed in a readable form. 
Currently they are displayed as: 1929-12-06T00:00:00Z
I'd prefer: 6.12.1929

**Comment by liowalter** [comment]
See also https://gitlab.com/swissbib/linked/workflows/issues/11

**Comment by Kordishal** [comment]
solve on the vufind side : 
* wikidata style : 1775-12-16T00:00:00Z (wikidata style) or start with a minus
* gnd : free string
