### ISSUE TITLE
fehlende Id bei angereicherter Person 

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#719]
Greife ich auf eine als "angereichert" gekennzeichnete Person zu, erhalte ich eine Fehlermeldung.
https://shibdev.swissbib.ch/Record/259283649
Der ES Suche wird keine (Hash) Id mitgegeben, was die Exception verursacht.
Problem im vufind client

**Comment by liowalter** [comment]
It not always an error. This is fine for example : https://shibdev.swissbib.ch/Page/Detail/Person/358c5368-3aa3-34b2-9b74-5c3965b87a8e#

Here is another person that leads to an error : https://shibdev.swissbib.ch/Page/Detail/Person/76cac2df-9706-3251-a879-25b6c11c3946

**Comment by guenterh** [comment]
fixed with https://github.com/swissbib/vufind/commit/0781af1e6f2462ca2ff100801269cc42681343e3
