### ISSUE TITLE
encoding problems (dbpedia?)

### ISSUE THREAD

**Issue by liowalter** [swissbib/vufind#721]
![screenshot_383](https://user-images.githubusercontent.com/1135460/70431274-fa8c7f80-1a7c-11ea-8cb9-c5192067144c.png)

This is already so in elastic.

Something for you @Kordishal ?

**Comment by Kordishal** [comment]
I don't know. You will have to be more specific.

**Comment by liowalter** [comment]
Sorry that was the wrong screenshot...

**Comment by liowalter** [comment]
For wikidata : fixed by @Kordishal 
For dbpedia : we will use the old dump from ls1 which doesn't have the encoding problems and has the same content
