### ISSUE TITLE
sbBB: Verlängerung wirft exception

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#731]
In sbBB wird bei einer Verlängerung eine exception "array to string conversion" geworfen.

**Comment by liowalter** [comment]
This is also present on produtive hosts. The book is extended but we get an error message.

**Comment by liowalter** [comment]
on test : 

![screenshot_390](https://user-images.githubusercontent.com/1135460/72533971-57e2d000-3876-11ea-825f-958b27d88754.png)
