### ISSUE TITLE
Merklisten werfen tlw. eine exception

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#732]
Bei gewissen Merklisten wird eine exception "Route name with vufindrecord not found" geworfen. 
Meine Vermutung: es handelt sich um Merklisten wo nicht mehr existierende Aufnahmen drauf sind. Daher nicht bei allen Merklisten der Fall.

**Comment by edelm** [comment]
Da waren noch alte sourceIds in der DB, ich habe die angepasst.
