### ISSUE TITLE
jusbib: Anpassung Verhalten gewählte Facetten

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#734]
Die folgenden Punkte sind ausschliesslich auf jusbib noch nicht in Ordnung und sollten analog zu BB/grün angepasst werden:
* Bei gewähltem Filter wird noch der Button "Filter zurücksetzen" angezeigt. 
* Das Häkchen bei "Filter behalten" wird automatisch gesetzt.

**Comment by edelm** [comment]
gefixt mit 566822c35b6c474d238c4616fd7894b2fc56279e
