### ISSUE TITLE
Fehler Aufruf person knowledgecard

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#735]
Fehler bei Aufruf einer Person knowledgecard
https://www.swissbib.ch/Page/Detail/Person/7ed9c841-780c-3e46-9fa5-fd139eba9edc

020-01-16T18:48:58+01:00 CRIT (2): TypeError : Argument 1 passed to ElasticSearch\VuFind\RecordDriver\ESPerson::getValueByLanguagePriority() must be of the type array or null, string given, called in /usr/local/vufind/httpd/module/ElasticSearch/src/ElasticSearch/VuFind/RecordDriver/ESPerson.php on line 176
2020-01-16T18:49:33+01:00 ALERT (1): AvailabilityService has thrown an Exception while called with idls=EBI01 and sysNr=004962204: Exception: Availability request failed: Internal Server Error in /usr/local/vufind/httpd/module/Swissbib/src/Swissbib/RecordDriver/Helper/Availability.php:228
Stack trace:
#0 /usr/local/vufind/httpd/module/Swissbib/src/Swissbib/RecordDriver/Helper/Availability.php(131): Swissbib\RecordDriver\Helper\Availability->fetch('https://externa...')
#1 /usr/local/vufind/httpd/module/Swissbib/src/Swissbib/RecordDriver/SolrMarc.php(2920): Swissbib\RecordDriver\Helper\Availability->getAvailabilityByLibraryNetwork('004962204', 'EBI01', 'de')
#2 /usr/local/vufind/httpd/module/Swissbib/src/Swissbib/Controller/SearchController.php(217): Swissbib\RecordDriver\SolrMarc->getAvailabilityIconFromServer('EBI01', '004962204')
#3 /usr/local/vufind/httpd/module/Swissbib/src/Swissbib/Controller/SearchController.php(176): Swissbib\Controller\SearchController->doAlephAvailabilityRequest(Object(Swissbib\RecordDriver\SolrMarc))

**Comment by guenterh** [comment]
andere Personen werfen keine exception
https://www.swissbib.ch/Page/Detail/Person/79b10ac9-e794-3cd7-a6b7-cd06c135aa84

**Comment by guenterh** [comment]
![issue_735](https://user-images.githubusercontent.com/1825990/72550682-87540580-3893-11ea-8a17-44bfda2108ba.png)

**Comment by guenterh** [comment]
@liowalter @Kordishal @witzigs 
Hallo, getValueByLanguagePriority akzeptiert nur array typen, was mich auf den ersten Blick erstaunt. Deswegen der Fehler.
Lionel: Hast du in diesen Bereich der Daten schon mal hineingesehen?
Ich mache auf die Schnelle erstmal nichts. Möchte es morgen noch kurz diskutieren

**Comment by liowalter** [comment]
I take care of this. The problem is for labels which are available in multiple languages.

**Comment by liowalter** [comment]
I published a small fix (and copied it on all hosts). I was expecting Pseudonym to be an array (as Occupation) but it was only a string in some cases. @Kordishal : is that normal that it is only a string sometime : https://data.swissbib.ch/person/b488581a-84f9-3955-9749-3ff219ae3f69

**Comment by guenterh** [comment]
@liowalter thanks!
