### ISSUE TITLE
redirect error auf www.swissbib.ch

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#742]
Ich habe bei einigen Usern das komische Phänomen, dass diese bei swissbib.ch folgenden Fehler erhalten, aber bei test.swissbib.ch sich einloggen können.

Error_1: Ich rufe swissbib.ch auf und klicke auf Einloggen, "error_1" erscheint.
Error_2: Ich wähle zuerst ein Buch und logge mich dann erst ein, "error_2" erscheint.

Aber bei der Seite test.swissbib.ch funktioniert alles.

Können Sie mir hier evtl. weiterhelfen?

@liowalter @edelm 
Hallo, Wir hatten, wenn ich mich recht erinnere, das Problem schon mal gehabt. Durch eine zusätzliche 000_default Apache Config Datei, deren Direktive zuerst ausgeführt wurden, konnten wir das Problem lösen.
Kann es sein, dass auf den neuen servern die Konfiguration nicht so eingestellt ist wie auf den alten Rechnern?

test.swissbib.ch läuft wohl deswegen, weil hier www nicht verwendet wird.

**Comment by liowalter** [comment]
The only thing missing I think : redirect https://swissbib.ch and http://swissbib.ch to https://www.swissbib.ch. 

@edelm : this might be related with the DB errors we saw in the errror log.
