### ISSUE TITLE
Passwort ändern

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#76]
Unterissue zu #67 
Dokumentation: https://developers.exlibrisgroup.com/aleph/apis/Aleph-RESTful-APIs/Password

Ziel
-----
* Erweiterung des (Core)-Aleph-Drivers zur Integration der neuen Funktion
* Erstellung der notwendigen Templates, falls möglich im bootstrap3-theme
* Rückgabe an die Community via PR

**Comment by guenterh** [comment]
@witzigs, @oschihin 
Hallo Silvia
habe mir Deine Probleme mit password change auf sb-vf10 angesehen, bzw. bei mir lokal funktionierte es auch nicht, so dass ich wohl die Ursache finden konnte.

In dem screenshot siehst Du, dass nach einer driver source MULTI_IDSBB gesucht wird, jedoch zwei driver in anderer Schreibweise registriert sind. Dadurch wird kein passender driver gefunden. Die Fehlermeldung ist irreführend.

Ich habe mich mit den Konfigurationen in diesem Bereich bisher nicht beschäftigt, ich denke Du oder Oliver wisst wo man da etwas einstellen muss.

Viele Grüsse
Günter


![password problem](https://cloud.githubusercontent.com/assets/1825990/7315595/39751e84-ea6f-11e4-911c-299acb5b4417.png)

**Comment by oschihin** [comment]
@witzigs ich schliesse hier. Super! Kannst du noch den Feature-Branch löschen?
