### ISSUE TITLE
Fotokopien anlegen / Kopienbestellung

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#78]
Unterissue zu #67 
Dokumentation: https://developers.exlibrisgroup.com/aleph/apis/Aleph-RESTful-APIs/Photo-per-Item

Ziel
-----
Den Benutzern steht eine in die Oberfläche von swissbib integrierte Möglichkeit zur Verfügung, Fotokopien zu bestellen. Aleph v22 bietet diese Möglichkeit via RestFul API an.
* Umsetzung im Alephdriver
* Erstellen der für den Workflow notwendigen Templates (in bootstrap3)
* Rückgabe an den Core via PR (wenn möglich)

Beispiele
-----------
[folgen]

**Comment by witzigs** [comment]
Beispiel: http://devbabe.swissbib.ch/Record/276827465
Muster-URL für REST: ````<Base URL>:patron/<patron ID>/record/<record ID>/items/<Item ID>/photo````
record ID für Beispiel: DSV01006100755
Item ID für Beispiel: DSV51006100755000010

* REST-Abfrage für Aufbau des Formulars (GET)

* Formular mit folgenden Feldern (vgl. Bestell-Formular hold.phtml):
 * Pickup-Locations als Dropdown
 * AutorIn des Artikels ````<sub-author>````
 * Titel des Artikels ````<sub-title>````
 * Seiten ````<pages>```` -> Pflichtfeld
 * Jahrgang/Bandnummer ````<note1>````
 * Kommentar ````<note2>````

* REST-Abfrage für Setzen der Kopienbestellung (PUT):
Mit Body:
 ````post_xml=<?xml version="1.0"?>
<photo-request-parameters>
  <pickup-location>WEB</pickup-location>
  <sub-author>Anna Test</sub-author>
  <sub-title>Die Bestellung</sub-title>
  <pages>12-24</pages>
  <note1>Jg. 7 (2005)</note1>
  <note2>Kommentar</note2>
</photo-request-parameters>````

**Comment by adchsnowflake** [comment]
@oschihin 
Wie soll dem Benutzer die Funktion angeboten werden? Was sind eure Vorstellungen? Wird die Funktion auf dem Detail eines Treffers [1] anhand eines Drucker-Icons [2] angeboten?
[1] zB. http://devbabe.swissbib.ch/Record/276827465
[2] https://www.google.ch/search?q=Printer+icon&espv=2&biw=1280&bih=638&source=lnms&tbm=isch&sa=X&ei=UKQ3VcX7D4rgaLvPgIAO&ved=0CAYQ_AUoAQ#tbm=isch&q=printer+symbol&revid=4175971

**Comment by witzigs** [comment]
@adchsnowflake 
Die Funktion soll analog zur Funktion "Bestellen" aufgebaut und angeboten werden.

Die Kopienbestellung wird auf Ebene eines Exemplars einer Bibliothek angeboten (siehe Beispiel oben, nach Anmeldung). Im Moment wird unter "Kopie bestellen" auf den ALEPH WebOPAC verlinkt. Dies soll durch die Kopienbestellung in VuFind ersetzt werden. Ein Icon ist nicht notwendig.
