### ISSUE TITLE
Checkboxen auf Trefferliste / Ausgewähltes Exportieren

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#81]
[in Arbeit]
Beschreibung
-----------------
Auf der Trefferliste sollen per Checkbox mehrere Titel ausgewählt und die Auswahl exportiert werden können.
Beispiel: https://catalog.lib.uchicago.edu

Frage
-------
* Bringt VuFind diese Funktionalität mit? In blueprint war sie enthalten.
* Lässt sich das einfach in bootstrap integrieren?

**Comment by chantalw** [comment]
Das wäre in der Tat eine praktische und gewünschte Funktionalität. Prüft ihr das noch?

**Comment by witzigs** [comment]
Die Funktion ist als bookbag in VuFind vorhanden. 
Wir haben bookbag nicht eingeführt (Design, Verwirrung zwischen Merklisten und Bookbag). Siehe dazu: #359
