### ISSUE TITLE
Bessere Steuerung der URL-Anzeige in swissbib

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#82]
[in Arbeit]
Übernahme eines Issue aus sbvf2: https://github.com/swissbib/sbvf2/issues/507

Genauere Analyse und Beschreibung notwendig

**Comment by ToVie** [comment]
@oschihin: Wäre es mit Blick auf Euren baldigen Livegang nicht ein sehr guter Zeitpunkt, dieses Thema wieder auf die Agenda zu nehmen? Und zwar möglichst bevor die ersten Kommentare dazu kommen wie "das haben sie nach 3 Jahren immer noch nicht im Griff" oder "das lief doch schon mal"...
Ist übrigens auch der Grund warum ich mich dazu melde - habe von Kollegen aus den Archivsammlungen der NB eine entsprechende Anfrage bekommen.

**Comment by guenterh** [comment]
Die links zu HA sollten entfernt werden. Beispiel:
https://test.swissbib.ch/Record/cha83861
Der link geht direkt auf die Image - Rohdaten, welche ein Browser, wenn überhaupt, nur durch entspechendes content negotiation darstellen könnte, Dies einzubauen ist fr den Einzelfall HA im Moment aber zu aufwendig.
Wir benutzten hier früher eine spezielle Lightbox für die Darstellung. Das war möglich.
Aktuell benutzen wir die links noch für die icons. In HTML img-tags ist die Anzeige möglich

Die Implementierung für die links auf der Vollanzeige ist, wenn ich mich recht erinnere, für einzelne Repositories (darunter HA) im RecordDriver hard-coded

Günter

**Comment by guenterh** [comment]
Bezogen auf die Bildlinks von Helvetic Archive (aktuell werden Daten in einer Form geliefert, die wir im Browser so nicht darstellen können) hier noch ein Kommentar von Tobias

Lieber Günter

Bezüglich des Links hinter dem Bild: Bevor man den komplett entfernt, könnte man ihn auch ganz leicht anpassen:

Anstatt: https://www.helveticarchives.ch/getimage.aspx?VEID=162581&DEID=10&SQNZNR=1&SIZE=30 

Könnte man folgenden verwenden: https://www.helveticarchives.ch/bild.aspx?VEID=162581&DEID=10&SQNZNR=1&SIZE=30

Quintessenz: man ersetze das Element "getimage.aspx" durch "bild.aspx", damit spricht man die Vorschau von helveticarchives an und kriegt was lesbares zurück...

Beste Grüsse
Tobias


todo: Anpassen des links

**Comment by oschihin** [comment]
@ToVie sehe ich das richtig, dass die Anpassung des Links in den Daten bzw. via die EAD-Skripte passieren soll, und nicht in der Oberfläche? Wenn doch, eröffne ich dafür einen kleinen Issue und packe es an

**Comment by ToVie** [comment]
@oschihin Ich kann das aktuell nicht machen und wäre froh, wenn Du es machen könntest.

**Comment by oschihin** [comment]
@ToVie kein Problem. Was empfiehlt der Experte: Skripte oder Oberfläche? Skripte ist wohl einfacher

**Comment by ToVie** [comment]
@oschihin Ich würde Oberfläche empfehlen, da die bei HelveticArchives aktuell in den Daten gelieferten Links für die Anzeige der Thumbnails benötigt werden (mit dem "getimage" liefert HelveticArchives Daten für ein img-Element). Der Backlink für eine grösere Vorschau benötigt dann ein "bild". Du kannst das also nicht per Skript einfach generell anpassen.

Meine Anregung war allerdings genereller gedacht - durch die Komentare von Günter wurde es dann sehr HelveticArchves-lastig.
irgendwie solltet Ihr Euch um die Vielzahl an Inhaltsverzeichnissen in den Datensätzen kümmern, die aktuell noch angezeigt werden...

**Comment by oschihin** [comment]
Genau das werde ich tun. Ich werde einen neuen Issue für die generelle 
Link-Problematik erstellen (mit deiner Analyse als Teil). Die 
Helvetic-Archives lös ich jetzt

Am 23.04.2015 um 06:29 schrieb ToVie:
> @oschihin <https://github.com/oschihin> Ich würde Oberfläche empfehlen,
> da die bei HelveticArchives aktuell in den Daten gelieferten Links für
> die Anzeige der Thumbnails benötigt werden (mit dem "getimage" liefert
> HelveticArchives Daten für ein img-Element). Der Backlink für eine
> grösere Vorschau benötigt dann ein "bild". Du kannst das also nicht per
> Skript einfach generell anpassen.
>
> Meine Anregung war allerdings genereller gedacht - durch die Komentare
> von Günter wurde es dann sehr HelveticArchves-lastig.
> irgendwie solltet Ihr Euch um die Vielzahl an Inhaltsverzeichnissen in
> den Datensätzen kümmern, die aktuell noch angezeigt werden...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swissbib/vufind/issues/82#issuecomment-95427373>.
>

-- 
UNIVERSITÄT BASEL
Universitätsbibliothek
Oliver Schihin
Projekt swissbib
Schönbeinstrasse 18-20
4056 Basel, Schweiz
Tel.: +41 61 267 13 07
Fax: +41 61 267 31 03
E-Mail oliver.schihin@unibas.ch
URL http://www.swissbib.org/

**Comment by ToVie** [comment]
Cool - merci!
