### ISSUE TITLE
Verlinkung auf FL und AV-Formulare UB Basel/Bern

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#88]
Wünsche seitens Benutzung gemäss Protokoll AG swissbib Basel Bern 24.6.2014:

1. Link auf FL- und AV-Formulare analog zu ALEPH-OPAC (Brief-Icon unten rechts) 

2. Die Seite http://baselbern.swissbib.ch/HelpPage/Faq soll wie folgt ergänzt werden (als zweitletzten Punkt): 

De:
Das Richtige nicht gefunden? 
- Erweitern Sie Ihre Suche auf swissbib.ch (ganze Schweiz) [Link] und bestellen Sie bequem aus IDS-Kurierbibliotheken [Link] oder 
- Schicken Sie uns Ihren Fernleihauftrag: Bestellformular UB Basel [Link] / UB Bern [Link] oder 
- Schicken Sie uns Ihren Anschaffungsvorschlag: Anschaffungsvorschlag UB Basel [Link] / UB Bern [Link] 

En:
Didn't like what you found?
- You can extend your search to swissbib.ch (all of Switzerland) and order via pickup libraries [Link] or
- send us requests for interlibrary loan: order form UB Basel [Link] / UB Bern [Link] or
- send us an acquisition suggestion: Acquisition UB Basel [Link] / UB Bern [Link]

Fz:
Vous n'avez pas trouvé ce qu'il vous faut?
- Elargissez votre recherche en consultant swissbib.ch (valable pour toute la Suisse) [Lien] et effectuez à votre aise une commande auprès de l'une des bibliothèques participant au réseau de livraison IDS [lien] ou 
- envoyez nous votre demande de prêt entre bibliothèques : formulaire BU Bâle 
[lien] / BU Berne [lien] ou
- envoyez nous votre proposition d'acquisition: formulaire BU Bâle 
[lien] / BU Berne [lien]

It: 
Non hai trovato quello che stavi cercando?
- espandi la tua ricerca scegliendo swissbib.ch [Link]  e
approfitta della possibilità di ordinare direttamente da altre
biblioteche IDS tramite corriere [Link], oppure
- inviaci la tua richiesta di prestito interbibliotecario (di un
libro o di un articolo) [beide Links UB Basel] [Links? UB Bern], oppure
- aiutaci a completare il fondo della nostra biblioteca inviandoci la
tua proposta d'acquisto [Link UB Basel] [Link UB Bern]

**Comment by witzigs** [comment]
@chantalw 
zu 2. der deutsche Text ist (schon länger) in allen vier Hilfeseiten ergänzt. 
zu 1. haben wir ja mal per Mail diskutiert. Mein Stand: es ist nicht geklärt, wo genau diese Links hin sollten, gehört aber irgendwo auf die Hilfeseiten.
Ich verzichte im Moment mal auf eine weitere Bearbeitung, da ich davon ausgehe, dass ihr diese Punkte bei der Überarbeitung der Hilfeseiten einfliessen lässt. Ok?

**Comment by chantalw** [comment]
@witzigs: Ja das ist natürlich ok, wir werden diese Links auf den Hilfeseiten platzieren.
