### ISSUE TITLE
Warnhinweis vor definitiver Bestellung

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#89]
Wunsch seitens Benutzung gemäss Protokoll AG swissbib Basel Bern 24.6.2014:
Warnhinweis vor definitiver Bestellung, sofern techn. ansprechend machbar. Hintergrund: Verringerung von Bestellungen mit falschem Abholort. 

Aktuell wird im OPAC der folgende Text angezeigt: 
Deutsch:
Ihre Vormerkung wird erst wirksam, wenn Sie 'OK' geklickt haben. Ort der Abholung/Lieferung: XY.
Das Fälligkeitsdatum ist dd/mm/yyyy.

Französisch:
Votre demande ne sera enregistrée q'avant vous clickez 'OK'. Lieu de reprise/livraison: XY. 
La date de retour prévu est dd/mm/yyyy.

Englisch:
Your request will not be active unless the 'Go' button is clicked. Pickup/delivery location: XY.
The due date is dd/mm/yyyy.

Italienisch:
Text folgt

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Warnhinweis vor definitiver Bestellung #89 (09/2014-useful)](https://trello.com/c/0VgVTHWv/104-warnhinweis-vor-definitiver-bestellung-89-09-2014-useful)

**Comment by witzigs** [comment]
Geschlossen, gemäss AG swissbib BB vom 18.7.2017
