### ISSUE TITLE
Language change on Settings page not working correctly

### ISSUE THREAD

**Issue by maechler** [swissbib/vufind#91]
Auf der Einstellungsseite im Benutzerkonto (/MyResearch/Settings) führt ein Sprachwechsel über das Sprachmenü im Header in jedem Fall zur Spracheinstellung "Deutsch". Der Sprachwechsel im Header funktioniert auf jeder anderen Seite als der MyResearch/Settings Seite korrekt. Die Einstellung im Inhaltsbereich über das Dropdown-Menü funktioniert ebenfalls korrekt.

**Comment by guenterh** [comment]
Erweiterung:

Die Auswahl einer Sprache im Header führt nicht in jedem Fall zu Deutsch sondern zu der Defaultlanguage. Diese ist bei mir Englisch. Folge: Ich bekomme in jedem Fall Englisch

**Comment by guenterh** [comment]
s. https://github.com/swissbib/vufind/commit/5f2da734a5631986b8dd5c8b4b434e38dd8e4b93
