### ISSUE TITLE
Backlinks in MARC-Anzeige wieder aktivieren

### ISSUE THREAD

**Issue by ToVie** [swissbib/vufind#92]
Analog zur Lösung von issue swissbib/sbvf2/issues/50 sollen die Backlinks in MARC-Sätzen verlinkt werden.

**Comment by maechler** [comment]
Das Problem trat meines Erachtens nur bei den Ajax-Requests auf. Wenn man direkt den "Details" Tab  (vufind/Record/227383443/Details) aufruft tritt der Fehler nicht auf.
Ich habe das Problem mit dem selben Hack gelöst, wie das bereits Günter gemacht hat. (https://github.com/swissbib/sbvf2/commit/f44f348cd262f4488a2dc28fc1e146c868f2031b --> RecordController)

Das Problem ist, dass im XSLT-Template die Funktionsaufrufe statisch sein müssen. Bei einem statischen Aufruf wird aber der Instanzierungsprozess vom ZF2 umgangen, deshalb fehlte der ServiceManager im MarcFormatter.

Eine andere Möglichkeit das Problem zu lösen wäre, im Bootstraper den ServiceManager als statische Variable zu setzen. Dann könnte man im MarcFormatter darauf zugreifen: Bootstrapper::$serviceManager
Hier hat es ein Beispiel dafür: http://devblog.x2k.co.uk/getting-the-servicemanager-into-the-test-environment-and-dependency-injection/
Das untergräbt aber auch das ServiceManagement vom ZF2. Im Moment sehe ich keine Möglichkeit das sauber zu machen, da der Aufruf im XSLT statisch sein muss, statische Aufrufe aber nicht in das Service-Konzept passen.

**Comment by guenterh** [comment]
@maechler 
Hallo Markus
erstmal noch, sehr nachträglich: ich wünsche Dir ein gutes Neues Jahr 2015 und ich hoffe Du bist gut gestartet!

Danke für Deine gute Analyse! Ist es so, dass Ajax - requests den bootstrap - Prozess umgehen / verkürzen / anders durchlaufen? Wenn ja war ich mir dessen nicht bewusst. Das werde ich mir mal anschauen.

Was man alles für Hacks in seinem Leben produziert...
Die Lösung mit dem globalen service manager würde mir auch gar nicht gefallen.

Schön dass es wieder läuft!

Günter

**Comment by maechler** [comment]
Hallo Günter

Der Bootstrap-Prozess wird bei Ajax-Requests nicht umgangen, wir landen aber in einer anderen Action.

Ohne Ajax gehen wir über RecordController->homeAction, dort hast du den Hack eingebaut.
Mit Ajax gehen wir über RecordController->ajaxtabAction, dort habe ich den selben Hack eingebaut.

**Comment by guenterh** [comment]
@maechler 
Hallo Markus,
danke für die Rückmeldung! Hatte heute morgen einen kleinen Knoten im Kopf. Mein erster Gedanke war, im Bootstrap Prozess sollte doch der Grossteil der notwendigen Referenzen bereitgestellt werden und warum passiert das nicht bei Ajax. Später habe ich dann gesehen, dass in diesem Kontext  unterschiedliche Actions aufgerufen werden und ich seinerzeit ja sogar noch einen richtig schönen Kommentar geschrieben habe....
Mehr Austausch mit PartnerInnen über solche Sachen würde ich schätzen.

Einen schönen Abend!

Günter
