### ISSUE TITLE
Warnhinweis zur längeren Lieferfrist bei der Bestellung eines Exemplars in Bearbeitung

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#95]
Anliegen der AG BEN: 
Nach der Bestellung eines Exemplars mit Geschäftsgangstatus "in Bearbeitung" (IP) sollte ein Warnhinweis zur längeren Lieferfrist angezeigt werden.

Deutsch: 
Dieses Exemplar ist noch im internen Bearbeitungsprozess und hat deshalb eine längere Lieferfrist. Sobald das Exemplar zur Abholung bereitsteht, werden Sie benachrichtigt.

Englisch:
This item is still being processed and will be on loan shortly. You will be notified when it is available.

Französisch: 
Cet exemplaire est encore en processus de traitement interne et fait ainsi l'objet d'un plus long délai de livraison. Dès que l'exemplaire sera mis à disposition, vous en serez averti.

Italienisch: 
Esemplare in processo d'acquisizione cioè non ancora disponibile. Il lettore sarà avvisato quando può ritirarlo.

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Warnhinweis zur längeren Lieferfrist bei der Bestellung eines Exemplars in Bearbeitung #95 (11/2014-)](https://trello.com/c/Ka9zQNzz/103-warnhinweis-zur-langeren-lieferfrist-bei-der-bestellung-eines-exemplars-in-bearbeitung-95-11-2014)
